version: "3.9"

services:
  django:
    container_name: django
    build:
      context: .
      dockerfile: Dockerfile
      target: main
    volumes:
      - ./:/app/
    command: >
      sh -c "poetry run python manage.py migrate && poetry run python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - postgres
    stdin_open: true
    tty: true

  postgres:
    container_name: postgres
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: registration
      POSTGRES_USER: bc_obps
      POSTGRES_PASSWORD: postgres

volumes:
  postgres_data:
