# Generated by Django 4.2.4 on 2023-09-22 21:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='operator_id',
            new_name='operator',
        ),
    ]
