# Generated by Django 4.2.4 on 2023-09-16 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='operator',
            name='compliance_obligee_idx',
        ),
        migrations.AlterField(
            model_name='operator',
            name='compliance_obligee',
            field=models.ForeignKey(
                blank=True,
                db_comment='',
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='obligee',
                to='registration.operator',
            ),
        ),
    ]
