# Generated by Django 5.2.16 on 2026-08-07 16:23

import django.db.models.deletion
from django.db import migrations, models

from registration.migrations._0002_squashed_data_functions import (
    set_regulated_name,
    update_activity_name,
    add_product_and_pwaei,
    reverse_add_product_and_pwaei,
    update_lng_product_units,
    populate_valid_dates,
)


class Migration(migrations.Migration):

    replaces = [
        ('registration', '0155_V5_0_1'),
        ('registration', '0156_activity_display_and_regulated_name'),
        ('registration', '0157_V5_1_0'),
        ('registration', '0158_add_pulp_and_paper_product'),
        ('registration', '0159_optedinoperationdetail_final_reporting_year'),
        ('registration', '0160_V5_2_0'),
        ('registration', '0161_V5_3_0'),
        ('registration', '0162_V5_3_1'),
        ('registration', '0163_V5_4_0'),
        ('registration', '0164_V5_4_1'),
        ('registration', '0165_V5_4_2'),
        ('registration', '0166_V5_4_3'),
        ('registration', '0167_V5_5_0'),
        ('registration', '0168_V5_6_0'),
        ('registration', '0169_V5_7_0'),
        ('registration', '0170_V5_8_0'),
        ('registration', '0171_add_units_to_lng_product'),
        ('registration', '0172_V5_9_0'),
        ('registration', '0173_alter_regulatedproduct_options'),
        ('registration', '0174_activity_immutable_slug'),
        ('registration', '0175_V5_10_0'),
        ('registration', '0176_V5_11_0'),
        ('registration', '0177_V5_12_0'),
        ('registration', '0178_alter_document_file_alter_historicaldocument_file'),
        ('registration', '0179_V5_13_0'),
        ('registration', '0180_V5_13_1'),
        ('registration', '0181_regulatedproduct_valid_dates'),
        ('registration', '0182_update_document_metadata'),
        ('registration', '0183_V5_14_0'),
        ('registration', '0184_update_registration_metadata'),
        ('registration', '0185_V5_15_0'),
        ('registration', '0186_V5_15_1'),
        ('registration', '0187_V5_16_0'),
        ('registration', '0188_V5_17_0'),
        ('registration', '0189_V5_18_0'),
    ]

    dependencies = [
        ('registration', '0001_initial_squashed_0154_V5_0_0'),
        ('reporting', '0001_initial_squashed_0148_V5_0_0'),
    ]

    operations = [
        migrations.RunPython(code=set_regulated_name),
        migrations.RunPython(code=update_activity_name),
        migrations.RunPython(code=add_product_and_pwaei, reverse_code=reverse_add_product_and_pwaei),
        migrations.AddField(
            model_name='historicaloptedinoperationdetail',
            name='final_reporting_year',
            field=models.ForeignKey(
                blank=True,
                db_comment='The final reporting year that this opted-in operation is expected to report for, if applicable. Foreign key to reporting.reporting_year',
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='reporting.reportingyear',
            ),
        ),
        migrations.AddField(
            model_name='optedinoperationdetail',
            name='final_reporting_year',
            field=models.ForeignKey(
                blank=True,
                db_comment='The final reporting year that this opted-in operation is expected to report for, if applicable. Foreign key to reporting.reporting_year',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='reporting.reportingyear',
            ),
        ),
        migrations.RunPython(code=update_lng_product_units),
        migrations.RunPython(code=populate_valid_dates),
    ]
