# Generated by Django 4.2.8 on 2024-02-27 20:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('registration', '0002_prod_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloperator',
            name='swrs_organisation_id',
            field=models.IntegerField(
                blank=True,
                db_comment='An identifier used in the CIIP/SWRS dataset (in swrs: organisation = operator). This identifier will only be populated for operators that were imported from that dataset.',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='operator',
            name='swrs_organisation_id',
            field=models.IntegerField(
                blank=True,
                db_comment='An identifier used in the CIIP/SWRS dataset (in swrs: organisation = operator). This identifier will only be populated for operators that were imported from that dataset.',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='historicaloperation',
            name='status',
            field=models.CharField(
                choices=[
                    ('Not Started', 'Not Started'),
                    ('Draft', 'Draft'),
                    ('Pending', 'Pending'),
                    ('Approved', 'Approved'),
                    ('Declined', 'Declined'),
                    ('Changes Requested', 'Changes Requested'),
                ],
                db_comment='The status of an operation in the app (e.g. pending review)',
                default='Not Started',
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name='historicaloperator',
            name='cra_business_number',
            field=models.IntegerField(
                db_comment='The CRA business number of an operator',
                validators=[
                    django.core.validators.MaxValueValidator(
                        999999999, message='CRA Business Number should be 9 digits.'
                    ),
                    django.core.validators.MinValueValidator(
                        100000000, message='CRA Business Number should be 9 digits.'
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name='operation',
            name='status',
            field=models.CharField(
                choices=[
                    ('Not Started', 'Not Started'),
                    ('Draft', 'Draft'),
                    ('Pending', 'Pending'),
                    ('Approved', 'Approved'),
                    ('Declined', 'Declined'),
                    ('Changes Requested', 'Changes Requested'),
                ],
                db_comment='The status of an operation in the app (e.g. pending review)',
                default='Not Started',
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name='operator',
            name='cra_business_number',
            field=models.IntegerField(
                db_comment='The CRA business number of an operator',
                validators=[
                    django.core.validators.MaxValueValidator(
                        999999999, message='CRA Business Number should be 9 digits.'
                    ),
                    django.core.validators.MinValueValidator(
                        100000000, message='CRA Business Number should be 9 digits.'
                    ),
                ],
            ),
        ),
    ]
