# Generated by Django 4.2.6 on 2023-11-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('registration', '0002_alter_operation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='status',
            field=models.CharField(
                choices=[
                    ('not_registered', 'Not Registered'),
                    ('pending', 'Pending'),
                    ('approved', 'Approved'),
                    ('rejected', 'Rejected'),
                ],
                db_comment='The status of an operation in the app (e.g. pending review)',
                default='pending',
                max_length=1000,
            ),
        ),
    ]
