# Generated by Django 4.2.8 on 2023-12-12 19:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('registration', '0002_alter_historicaloperation_previous_year_attributable_emissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloperator',
            name='bc_corporate_registry_number',
            field=models.CharField(
                db_comment='The BC corporate registry number of an operator',
                validators=[
                    django.core.validators.RegexValidator(
                        message='"BC Corporate Registry Number should be 1-3 letters followed by 7 digits".',
                        regex='^[A-Za-z]{1,3}\\d{7}$',
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name='multipleoperator',
            name='bc_corporate_registry_number',
            field=models.CharField(
                db_comment='The BC corporate registry number of an operator',
                validators=[
                    django.core.validators.RegexValidator(
                        message='"BC Corporate Registry Number should be 1-3 letters followed by 7 digits".',
                        regex='^[A-Za-z]{1,3}\\d{7}$',
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name='operator',
            name='bc_corporate_registry_number',
            field=models.CharField(
                db_comment='The BC corporate registry number of an operator',
                validators=[
                    django.core.validators.RegexValidator(
                        message='"BC Corporate Registry Number should be 1-3 letters followed by 7 digits".',
                        regex='^[A-Za-z]{1,3}\\d{7}$',
                    )
                ],
            ),
        ),
    ]
