# Generated by Django 4.2.8 on 2024-01-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('registration', '0002_prod_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloperation',
            name='submission_date',
            field=models.DateTimeField(
                blank=True, db_comment='The time the user submitted the operation registration request', null=True
            ),
        ),
        migrations.AddField(
            model_name='operation',
            name='submission_date',
            field=models.DateTimeField(
                blank=True, db_comment='The time the user submitted the operation registration request', null=True
            ),
        ),
    ]
