# Generated by Django 4.2.8 on 2024-02-21 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('registration', '0002_prod_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloperator',
            name='swrs_organisation_id',
            field=models.IntegerField(
                blank=True,
                db_comment='An identifier used in the CIIP/SWRS dataset (in swrs: organisation = operator). This identifier will only be populated for operators that were imported from that dataset.',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='operator',
            name='swrs_organisation_id',
            field=models.IntegerField(
                blank=True,
                db_comment='An identifier used in the CIIP/SWRS dataset (in swrs: organisation = operator). This identifier will only be populated for operators that were imported from that dataset.',
                null=True,
            ),
        ),
    ]
