# Generated by Django 4.2.5 on 2023-09-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('registration', '0002_rename_operator_id_operation_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='estimated_emissions',
            field=models.DecimalField(db_comment='', decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='operation',
            name='latitude',
            field=models.DecimalField(db_comment='', decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='operation',
            name='longitude',
            field=models.DecimalField(db_comment='', decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='operation',
            name='operator_percent_of_ownership',
            field=models.DecimalField(db_comment='', decimal_places=5, max_digits=10),
        ),
    ]
