# Generated by Django 4.2.8 on 2023-12-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('registration', '0002_historicalcontact_historicaloperation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloperation',
            name='previous_year_attributable_emissions',
            field=models.IntegerField(
                blank=True,
                db_comment="An operation or facility's attributable emissions from the previous year. Only needed if the operation/facility submitted a report the previous year.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='operation',
            name='previous_year_attributable_emissions',
            field=models.IntegerField(
                blank=True,
                db_comment="An operation or facility's attributable emissions from the previous year. Only needed if the operation/facility submitted a report the previous year.",
                null=True,
            ),
        ),
    ]
