# Generated by Django 4.2.8 on 2024-01-27 00:29

from django.db import migrations, models
import django.db.models.deletion
import localflavor.ca.models


class Migration(migrations.Migration):
    dependencies = [
        ('registration', '0003_remove_historicaloperation_application_lead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='municipality',
            field=models.CharField(
                blank=True, db_comment='Municipality of relevant location', max_length=1000, null=True
            ),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=localflavor.ca.models.CAPostalCodeField(
                blank=True,
                db_comment='Postal code of relevant location, limited to valid Canadian postal codes',
                max_length=7,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=localflavor.ca.models.CAProvinceField(
                blank=True,
                db_comment='Province of the relevant location, restricted to two-letter province postal abbreviations',
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_address',
            field=models.CharField(
                blank=True, db_comment='Street address of relevant location)', max_length=1000, null=True
            ),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.CharField(blank=True, db_comment='Description of the document', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='municipality',
            field=models.CharField(
                blank=True, db_comment='Municipality of relevant location', max_length=1000, null=True
            ),
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='postal_code',
            field=localflavor.ca.models.CAPostalCodeField(
                blank=True,
                db_comment='Postal code of relevant location, limited to valid Canadian postal codes',
                max_length=7,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='province',
            field=localflavor.ca.models.CAProvinceField(
                blank=True,
                db_comment='Province of the relevant location, restricted to two-letter province postal abbreviations',
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='street_address',
            field=models.CharField(
                blank=True, db_comment='Street address of relevant location)', max_length=1000, null=True
            ),
        ),
        migrations.AlterField(
            model_name='historicaldocument',
            name='description',
            field=models.CharField(blank=True, db_comment='Description of the document', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmultipleoperator',
            name='website',
            field=models.URLField(blank=True, db_comment='The website address of an operator', null=True),
        ),
        migrations.AlterField(
            model_name='historicalparentoperator',
            name='website',
            field=models.URLField(blank=True, db_comment='The website address of an operator', null=True),
        ),
        migrations.AlterField(
            model_name='multipleoperator',
            name='website',
            field=models.URLField(blank=True, db_comment='The website address of an operator', null=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='business_structure',
            field=models.ForeignKey(
                blank=True,
                db_comment='The business structure of an operator',
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='operators',
                to='registration.businessstructure',
            ),
        ),
        migrations.AlterField(
            model_name='parentoperator',
            name='website',
            field=models.URLField(blank=True, db_comment='The website address of an operator', null=True),
        ),
    ]
