# Generated by Django 4.2.8 on 2024-02-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('registration', '0003_alter_businessstructure_table_comment_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['type'], name='document_type_idx'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['created_at'], name='operation_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['status'], name='operation_status_idx'),
        ),
        migrations.AddIndex(
            model_name='parentoperator',
            index=models.Index(fields=['child_operator'], name='po_child_operator_idx'),
        ),
        migrations.AddIndex(
            model_name='parentoperator',
            index=models.Index(fields=['business_structure'], name='po_business_structure_idx'),
        ),
        migrations.AddIndex(
            model_name='parentoperator',
            index=models.Index(fields=['physical_address'], name='po_physical_address_idx'),
        ),
        migrations.AddIndex(
            model_name='parentoperator',
            index=models.Index(fields=['mailing_address'], name='po_mailing_address_idx'),
        ),
    ]
