# Generated by Django 4.2.8 on 2024-03-20 22:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('registration', '0004_historicaluseroperator_user_friendly_id_and_more'),
    ]

    operations = []
