# Generated by Django 4.2.8 on 2024-04-02 21:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('registration', '0005_V1_2_0'),
    ]

    def add_325190_naics_code_data(apps, schema_monitor):
        '''
        Add initial data to erc.naics_code
        '''
        NaicsCode = apps.get_model('registration', 'NaicsCode')
        NaicsCode.objects.create(naics_code='325190', naics_description='Other basic organic chemical manufacturing')

    def reverse_add_325190_naics_code_data(apps, schema_monitor):
        '''
        Remove initial data from erc.naics_code
        '''
        NaicsCode = apps.get_model('registration', 'NaicsCode')
        NaicsCode.objects.filter(
            naics_code__in=[
                '325190',
            ]
        ).delete()

    operations = [migrations.RunPython(add_325190_naics_code_data, reverse_add_325190_naics_code_data)]
