# Generated by Django 4.2.8 on 2024-04-03 15:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('registration', '0006_update_naics_codes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaloperation',
            name='previous_year_attributable_emissions',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='previous_year_attributable_emissions',
        ),
    ]
