# Generated by Django 4.2.8 on 2024-04-03 20:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('registration', '0006_update_naics_codes'),
    ]

    operations = []
