# Generated by Django 4.2.8 on 2024-04-08 17:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('registration', '0007_V1_2_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaloperation',
            name='previous_year_attributable_emissions',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='previous_year_attributable_emissions',
        ),
    ]
