# Generated by Django 4.2.8 on 2024-04-10 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_remove_historicaloperation_previous_year_attributable_emissions_and_more'),
    ]

    operations = []
