# Generated by Django 4.2.8 on 2024-04-11 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_V1_2_3'),
    ]

    operations = []
