# Generated by Django 4.2.8 on 2024-04-23 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_V1_3_0'),
    ]

    operations = []
