# Generated by Django 4.2.8 on 2024-04-16 14:18

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_V1_3_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='approle',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(
                default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name='historicalapprole',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(
                default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, srid=4326
            ),
        ),
    ]
