# Generated by Django 4.2.8 on 2024-04-16 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_facility_alter_operation_table_comment_and_more'),
    ]
    # this migration makes the address field required. Previously (before migration 011), we didn't collect any address data so we had to set the field to blank=True for existing records.
    operations = [
        migrations.AlterField(
            model_name='facility',
            name='address',
            field=models.ForeignKey(
                db_comment='The address of the operation or facility',
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='registration.address',
            ),
        ),
        migrations.AlterField(
            model_name='operation',
            name='address',
            field=models.ForeignKey(
                db_comment='The address of the operation or facility',
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='registration.address',
            ),
        ),
    ]
