# Generated by Django 4.2.8 on 2024-05-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_V1_4_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='approle',
            name='brianna',
            field=models.CharField(db_comment='Description of the app role', default='fff', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalapprole',
            name='brianna',
            field=models.CharField(db_comment='Description of the app role', default='ddd', max_length=1000),
            preserve_default=False,
        ),
    ]
