# Generated by Django 4.2.8 on 2024-04-30 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_V1_4_1'),
    ]

    operations = []
