# Generated by Django 4.2.8 on 2024-05-02 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_V1_5_0'),
    ]

    operations = []
