# Generated by Django 4.2.8 on 2024-05-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_V1_5_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='bcghg_id',
            field=models.CharField(blank=True, db_comment="A facility's BCGHG identifier.", max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='swrs_facility_id',
            field=models.IntegerField(blank=True, db_comment="A facility's SWRS facility ID.", null=True),
        ),
        migrations.AddField(
            model_name='historicalfacility',
            name='bcghg_id',
            field=models.CharField(blank=True, db_comment="A facility's BCGHG identifier.", max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='historicalfacility',
            name='swrs_facility_id',
            field=models.IntegerField(blank=True, db_comment="A facility's SWRS facility ID.", null=True),
        ),
        migrations.AlterField(
            model_name='historicaloperation',
            name='bcghg_id',
            field=models.CharField(
                blank=True,
                db_comment="An operation's BCGHG identifier. Only needed if the operation submitted a report the previous year.",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='historicaloperation',
            name='swrs_facility_id',
            field=models.IntegerField(
                blank=True,
                db_comment="An operation's SWRS facility ID. Only needed if the operation submitted a report the previous year.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='operation',
            name='bcghg_id',
            field=models.CharField(
                blank=True,
                db_comment="An operation's BCGHG identifier. Only needed if the operation submitted a report the previous year.",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='operation',
            name='swrs_facility_id',
            field=models.IntegerField(
                blank=True,
                db_comment="An operation's SWRS facility ID. Only needed if the operation submitted a report the previous year.",
                null=True,
            ),
        ),
    ]
