# Generated by Django 4.2.8 on 2024-05-28 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_V1_5_2'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='address',
            table_comment='Table containing address data. Only Canadian addresses are supported.',
        ),
        migrations.AlterModelTableComment(
            name='approle',
            table_comment='This table contains the definitions for roles within the BCIERs apps. These roles are used to define the permissions a user has within BCIERs apps.',
        ),
        migrations.AlterModelTableComment(
            name='bcobpsregulatedoperation',
            table_comment='Table to store BC OBPS Regulated Operation metadata. Once an operation has been approved as a BC OBPS Regulated Operations (IRC has determined the operation meets certain criteria and should be included in the program), then it is issued an ID.',
        ),
        migrations.AlterModelTableComment(
            name='businessrole',
            table_comment='This table contains the definitions for roles within the operator/operation. These roles are used to define the permissions a user has within the operator/operation.',
        ),
        migrations.AlterModelTableComment(
            name='businessstructure',
            table_comment='Table containing operator business structures. Business structure refers to the legal and organizational framework under which a business operates (e.g., partnership, sole proprietorship, corporation, limited liability company).',
        ),
        migrations.AlterModelTableComment(
            name='contact',
            table_comment="Table containing information about contacts. Contacts are people that IRC may need to get in touch with to confirmation information about industry. Contacts can be BCIERs app users (in which case they will also have a record in the Users table), but they don't have to be.",
        ),
        migrations.AlterModelTableComment(
            name='document',
            table_comment='Table that contains information about documents such as file metadata, type, and description.',
        ),
        migrations.AlterModelTableComment(
            name='documenttype',
            table_comment='Table that contains types of documents.',
        ),
        migrations.AlterModelTableComment(
            name='facility',
            table_comment='Contains data on facilities that emit carbon emissions and must report them to Clean Growth. A linear facility operation is made up of several different facilities whereas a single facility operation has only one facility. In the case of a single facility operation, much of the data in this table will overlap with the parent record in the operation table.',
        ),
        migrations.AlterModelTableComment(
            name='multipleoperator',
            table_comment="Table containing data about operations' operators. An operation's designated (primary) operator has a record in the Operator table (this information has been submitted by someone who works for that operator). Any additional operators are stored in this table (additional operator information has been submitted by a user who works for a different operator, so this user should not have access to the Operator table record).",
        ),
        migrations.AlterModelTableComment(
            name='naicscode',
            table_comment='Table contains NAICS codes & their descriptions. NAICS code means the 6-digit code applicable to one or more producing units within a reporting operation under the North American Industrial Classification System (NAICS) Canada, 2007, published by Statistics Canada. Operations can have more than one NAICS code. More information, including version history for NAICS codes can be found at https://www.statcan.gc.ca/en/concepts/industry.',
        ),
        migrations.AlterModelTableComment(
            name='operation',
            table_comment="Table containing information about operations. 'Industrial operation' means one or more facilities, or a prescribed activity, to which greenhouse gas emissions are attributable, subject to subsection (3)of the Greenhouse Gas Industrial Reporting and Control Act: https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/14029_01#section1.",
        ),
        migrations.AlterModelTableComment(
            name='operator',
            table_comment='Table containing operator information. An operator is the person who owns and/or controls and directs industrial operations. An operator can own multiple operations. For more information see definitions in the Greenhouse Gas Industrial Reporting and Control Act: https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/14029_01#section1: https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/14029_01#section1',
        ),
        migrations.AlterModelTableComment(
            name='parentoperator',
            table_comment="Table containing data about operators' parent operators. Parent operators may have a record in the Operator table. If so, that record is controlled by someone who works for that parent operator. The information in this table is controlled by child operators who should not have access to other operator's records.",
        ),
        migrations.AlterModelTableComment(
            name='regulatedproduct',
            table_comment='Table containing the names of regulated products. Regulated product means a product listed in column 2 of Table 2 of Schedule A.1 of the Greenhouse Gas Industrial Reporting and Control Act: https://www.bclaws.gov.bc.ca/civix/document/id/lc/statreg/249_2015.',
        ),
        migrations.AlterModelTableComment(
            name='reportingactivity',
            table_comment='Table containing names activities. If facilities carry out these activities, in many cases they are required to report. Some activities can only be carried out by certain types of facilities. Reporting activities are listed in column 2 of Table 1 of Schedule A of the Greenhouse Gas Industrial Reporting and Control Act: https://www.bclaws.gov.bc.ca/civix/document/id/lc/statreg/249_2015.',
        ),
        migrations.AlterModelTableComment(
            name='user',
            table_comment='Table containing information about app users. Industry users are all associated with a business and are identified via their Business BCEID.',
        ),
        migrations.AlterModelTableComment(
            name='wellauthorizationnumber',
            table_comment='A table containing well authorization numbers. Authorization numbers are assigned by the British Columbia Energy Regulator: https://www.bc-er.ca/what-we-regulate/oil-gas/wells/. Facilities can have multiple well authorization numbers.',
        ),
    ]
