# Generated by Django 5.0.6 on 2024-06-05 23:13

import django.db.models.deletion
import simple_history.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_alter_address_table_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name_plural': 'Facilities'},
        ),
        migrations.AlterModelOptions(
            name='historicalfacility',
            options={
                'get_latest_by': ('history_date', 'history_id'),
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical facility',
                'verbose_name_plural': 'historical Facilities',
            },
        ),
        migrations.RemoveField(
            model_name='facility',
            name='new_entrant',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='historicalfacility',
            name='new_entrant',
        ),
        migrations.RemoveField(
            model_name='historicalfacility',
            name='operation',
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(db_comment='The name of the facility when the operation owned it', max_length=1000),
        ),
        migrations.AlterField(
            model_name='facility',
            name='type',
            field=models.CharField(
                choices=[
                    ('Single Facility', 'Single Facility'),
                    ('Large', 'Large'),
                    ('Medium', 'Medium'),
                    ('Small Aggregate', 'Small Aggregate'),
                ],
                db_comment='The type of the facility',
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name='historicalfacility',
            name='name',
            field=models.CharField(db_comment='The name of the facility when the operation owned it', max_length=1000),
        ),
        migrations.AlterField(
            model_name='historicalfacility',
            name='type',
            field=models.CharField(
                choices=[
                    ('Single Facility', 'Single Facility'),
                    ('Large', 'Large'),
                    ('Medium', 'Medium'),
                    ('Small Aggregate', 'Small Aggregate'),
                ],
                db_comment='The type of the facility',
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                (
                    'id',
                    models.UUIDField(
                        db_comment='Primary key to identify the event',
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('effective_date', models.DateTimeField(db_comment='The effective date of the event')),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('Closing or Temporary Shutdown', 'Closing Or Temporary Shutdown'),
                            ('Acquisition', 'Acquisition'),
                            ('Transfer of Control', 'Transfer Of Control'),
                            ('Divestment', 'Divestment'),
                            ('Startup', 'Startup'),
                        ],
                        db_comment='The type of the event',
                        max_length=100,
                    ),
                ),
                (
                    'additional_data',
                    models.JSONField(blank=True, db_comment='Additional data about the event', null=True),
                ),
                (
                    'archived_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_archived',
                        to='registration.user',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_created',
                        to='registration.user',
                    ),
                ),
                (
                    'facility',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='events',
                        to='registration.facility',
                    ),
                ),
                (
                    'operation',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='events',
                        to='registration.operation',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_updated',
                        to='registration.user',
                    ),
                ),
            ],
            options={
                'db_table': 'erc"."event',
                'db_table_comment': 'Table containing information about events that occur in the lifecycle of an operation or facility.',
            },
        ),
        migrations.CreateModel(
            name='FacilityOwnershipTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                (
                    'start_date',
                    models.DateTimeField(
                        blank=True, db_comment='The start date of the ownership of the facility', null=True
                    ),
                ),
                (
                    'end_date',
                    models.DateTimeField(
                        blank=True, db_comment='The end date of the ownership of the facility', null=True
                    ),
                ),
                (
                    'archived_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_archived',
                        to='registration.user',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_created',
                        to='registration.user',
                    ),
                ),
                (
                    'facility',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='ownerships',
                        to='registration.facility',
                    ),
                ),
                (
                    'operation',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='facility_ownerships',
                        to='registration.operation',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_updated',
                        to='registration.user',
                    ),
                ),
            ],
            options={
                'db_table': 'erc"."facility_ownership_timeline',
                'db_table_comment': 'A table to connect facilities and operations',
            },
        ),
        migrations.CreateModel(
            name='HistoricalEvent',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                (
                    'id',
                    models.UUIDField(db_comment='Primary key to identify the event', db_index=True, default=uuid.uuid4),
                ),
                ('effective_date', models.DateTimeField(db_comment='The effective date of the event')),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('Closing or Temporary Shutdown', 'Closing Or Temporary Shutdown'),
                            ('Acquisition', 'Acquisition'),
                            ('Transfer of Control', 'Transfer Of Control'),
                            ('Divestment', 'Divestment'),
                            ('Startup', 'Startup'),
                        ],
                        db_comment='The type of the event',
                        max_length=100,
                    ),
                ),
                (
                    'additional_data',
                    models.JSONField(blank=True, db_comment='Additional data about the event', null=True),
                ),
                ('history_user_id', models.UUIDField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                (
                    'history_type',
                    models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
                ),
                (
                    'archived_by',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.user',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.user',
                    ),
                ),
                (
                    'facility',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.facility',
                    ),
                ),
                (
                    'operation',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.operation',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.user',
                    ),
                ),
            ],
            options={
                'verbose_name': 'historical event',
                'verbose_name_plural': 'historical events',
                'db_table': 'erc_history"."event_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFacilityOwnershipTimeline',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                (
                    'start_date',
                    models.DateTimeField(
                        blank=True, db_comment='The start date of the ownership of the facility', null=True
                    ),
                ),
                (
                    'end_date',
                    models.DateTimeField(
                        blank=True, db_comment='The end date of the ownership of the facility', null=True
                    ),
                ),
                ('history_user_id', models.UUIDField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                (
                    'history_type',
                    models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
                ),
                (
                    'archived_by',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.user',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.user',
                    ),
                ),
                (
                    'facility',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.facility',
                    ),
                ),
                (
                    'operation',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.operation',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.user',
                    ),
                ),
            ],
            options={
                'verbose_name': 'historical facility ownership timeline',
                'verbose_name_plural': 'historical facility ownership timelines',
                'db_table': 'erc_history"."facility_ownership_timeline_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalOperationOwnershipTimeline',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                (
                    'start_date',
                    models.DateTimeField(
                        blank=True, db_comment='The start date of the ownership of the operation', null=True
                    ),
                ),
                (
                    'end_date',
                    models.DateTimeField(
                        blank=True, db_comment='The end date of the ownership of the operation', null=True
                    ),
                ),
                ('history_user_id', models.UUIDField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                (
                    'history_type',
                    models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
                ),
                (
                    'archived_by',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.user',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.user',
                    ),
                ),
                (
                    'operation',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.operation',
                    ),
                ),
                (
                    'operator',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.operator',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.user',
                    ),
                ),
            ],
            options={
                'verbose_name': 'historical operation ownership timeline',
                'verbose_name_plural': 'historical operation ownership timelines',
                'db_table': 'erc_history"."operation_ownership_timeline_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='OperationOwnershipTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                (
                    'start_date',
                    models.DateTimeField(
                        blank=True, db_comment='The start date of the ownership of the operation', null=True
                    ),
                ),
                (
                    'end_date',
                    models.DateTimeField(
                        blank=True, db_comment='The end date of the ownership of the operation', null=True
                    ),
                ),
                (
                    'archived_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_archived',
                        to='registration.user',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_created',
                        to='registration.user',
                    ),
                ),
                (
                    'operation',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='ownerships',
                        to='registration.operation',
                    ),
                ),
                (
                    'operator',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='operation_ownerships',
                        to='registration.operator',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_updated',
                        to='registration.user',
                    ),
                ),
            ],
            options={
                'db_table': 'erc"."operation_ownership_timeline',
                'db_table_comment': 'A table to connect operations and operators',
            },
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(('operation_id__isnull', True), ('facility_id__isnull', False)),
                    models.Q(('operation_id__isnull', False), ('facility_id__isnull', True)),
                    _connector='OR',
                ),
                name='event_not_both_operation_and_facility',
            ),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(
                check=models.Q(('operation_id__isnull', False), ('facility_id__isnull', False), _negated=True),
                name='event_cannot_have_both_operation_and_facility',
            ),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(
                check=models.Q(('facility_id__isnull', True), ('operation_id__isnull', True), _negated=True),
                name='event_has_operation_or_facility',
            ),
        ),
        migrations.AddConstraint(
            model_name='facilityownershiptimeline',
            constraint=models.UniqueConstraint(
                condition=models.Q(('end_date__isnull', True)),
                fields=('facility',),
                name='unique_active_ownership_per_facility',
            ),
        ),
        migrations.AddConstraint(
            model_name='operationownershiptimeline',
            constraint=models.UniqueConstraint(
                condition=models.Q(('end_date__isnull', True)),
                fields=('operation',),
                name='unique_active_ownership_per_operation',
            ),
        ),
    ]
