# Generated by Django 5.0.6 on 2024-06-10 17:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('registration', '0019_alter_facility_options_and_more'),
    ]

    operations = []

    def add_418990_naics_code_data(apps, schema_monitor):
        '''
        Add initial data to erc.naics_code
        '''
        NaicsCode = apps.get_model('registration', 'NaicsCode')
        NaicsCode.objects.create(naics_code='418990', naics_description='All other merchant wholesalers')

    def reverse_add_418990_naics_code_data(apps, schema_monitor):
        '''
        Remove initial data from erc.naics_code
        '''
        NaicsCode = apps.get_model('registration', 'NaicsCode')
        NaicsCode.objects.filter(
            naics_code__in=[
                '418990',
            ]
        ).delete()

    operations = [migrations.RunPython(add_418990_naics_code_data, reverse_add_418990_naics_code_data)]
