# Generated by Django 5.0.7 on 2024-07-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0023_historicalparentoperator_foreign_address_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contact',
            name='contact_role_idx',
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='document_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='operation',
            name='operator_idx',
        ),
        migrations.RemoveIndex(
            model_name='operation',
            name='naics_code_idx',
        ),
        migrations.RemoveIndex(
            model_name='operation',
            name='operation_verified_by_idx',
        ),
        migrations.RemoveIndex(
            model_name='operation',
            name='operation_created_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='parentoperator',
            name='po_child_operator_idx',
        ),
        migrations.RemoveIndex(
            model_name='parentoperator',
            name='po_business_structure_idx',
        ),
        migrations.RemoveIndex(
            model_name='parentoperator',
            name='po_physical_address_idx',
        ),
        migrations.RemoveIndex(
            model_name='parentoperator',
            name='po_mailing_address_idx',
        ),
        migrations.RemoveIndex(
            model_name='partneroperator',
            name='partner_bc_obps_operator_idx',
        ),
        migrations.RemoveIndex(
            model_name='partneroperator',
            name='partner_business_structure_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_app_role_idx',
        ),
        migrations.RemoveIndex(
            model_name='useroperator',
            name='user_operator_user_idx',
        ),
        migrations.RemoveIndex(
            model_name='useroperator',
            name='user_operator_operator_idx',
        ),
        migrations.AlterField(
            model_name='historicalparentoperator',
            name='trade_name',
            field=models.CharField(
                blank=True, db_comment='The trade name of a parent operator', max_length=1000, null=True
            ),
        ),
        migrations.AlterField(
            model_name='parentoperator',
            name='trade_name',
            field=models.CharField(
                blank=True, db_comment='The trade name of a parent operator', max_length=1000, null=True
            ),
        ),
    ]
