# Generated by Django 5.0.7 on 2024-08-01 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0024_remove_contact_contact_role_idx_and_more'),
    ]

    operations = []
