# Generated by Django 5.0.7 on 2024-08-07 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0026_facility_is_current_year_facility_starting_date_and_more'),
    ]

    operations = []
