# Generated by Django 5.0.7 on 2024-08-07 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0027_V1_8_0'),
    ]

    operations = []
