# Generated by Django 5.0.8 on 2024-08-16 21:00

import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0033_alter_historicaloperation_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOptedInOperationDetail',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                (
                    'meets_section_3_emissions_requirements',
                    models.BooleanField(
                        blank=True,
                        db_comment='Does this operation have emissions that are attributable for the purposes of section 3 of the Act?',
                        null=True,
                    ),
                ),
                (
                    'meets_electricity_import_operation_criteria',
                    models.BooleanField(
                        blank=True, db_comment='Is this operation an electricity import operation?', null=True
                    ),
                ),
                (
                    'meets_entire_operation_requirements',
                    models.BooleanField(
                        blank=True,
                        db_comment='Designation as an opt-in can only be granted to an entire operation (i.e. not a part or certain segment of an operation). Do you confirm that the operation applying for this designation is an entire operation?',
                        null=True,
                    ),
                ),
                (
                    'meets_section_6_emissions_requirements',
                    models.BooleanField(
                        blank=True,
                        db_comment='Does this operation have emissions that are attributable for the purposes of section 6 of the Act?',
                        null=True,
                    ),
                ),
                (
                    'meets_naics_code_11_22_562_classification_requirements',
                    models.BooleanField(
                        blank=True,
                        db_comment="Is this operation's primary economic activity classified by the following NAICS Code - 11, 22, or 562?",
                        null=True,
                    ),
                ),
                (
                    'meets_producing_gger_schedule_a1_regulated_product',
                    models.BooleanField(
                        blank=True,
                        db_comment='Does this operation produce a regulated product listed in Table 1 of Schedule A.1 of the GGERR?',
                        null=True,
                    ),
                ),
                (
                    'meets_reporting_and_regulated_obligations',
                    models.BooleanField(
                        blank=True,
                        db_comment='Is this operation capable of fulfilling the obligations of a reporting operation and a regulated operation under the Act and the regulations?',
                        null=True,
                    ),
                ),
                (
                    'meets_notification_to_director_on_criteria_change',
                    models.BooleanField(
                        blank=True,
                        db_comment='Will the operator notify the Director as soon as possible if this operation ceases to meet any of the criteria for the designation of the operation as a reporting operation and a regulated operation?',
                        null=True,
                    ),
                ),
                ('history_user_id', models.UUIDField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                (
                    'history_type',
                    models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
                ),
                (
                    'archived_by',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.user',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.user',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.user',
                    ),
                ),
            ],
            options={
                'verbose_name': 'historical opted in operation detail',
                'verbose_name_plural': 'historical opted in operation details',
                'db_table': 'erc_history"."opted_in_operation_detail_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='OptedInOperationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                (
                    'meets_section_3_emissions_requirements',
                    models.BooleanField(
                        blank=True,
                        db_comment='Does this operation have emissions that are attributable for the purposes of section 3 of the Act?',
                        null=True,
                    ),
                ),
                (
                    'meets_electricity_import_operation_criteria',
                    models.BooleanField(
                        blank=True, db_comment='Is this operation an electricity import operation?', null=True
                    ),
                ),
                (
                    'meets_entire_operation_requirements',
                    models.BooleanField(
                        blank=True,
                        db_comment='Designation as an opt-in can only be granted to an entire operation (i.e. not a part or certain segment of an operation). Do you confirm that the operation applying for this designation is an entire operation?',
                        null=True,
                    ),
                ),
                (
                    'meets_section_6_emissions_requirements',
                    models.BooleanField(
                        blank=True,
                        db_comment='Does this operation have emissions that are attributable for the purposes of section 6 of the Act?',
                        null=True,
                    ),
                ),
                (
                    'meets_naics_code_11_22_562_classification_requirements',
                    models.BooleanField(
                        blank=True,
                        db_comment="Is this operation's primary economic activity classified by the following NAICS Code - 11, 22, or 562?",
                        null=True,
                    ),
                ),
                (
                    'meets_producing_gger_schedule_a1_regulated_product',
                    models.BooleanField(
                        blank=True,
                        db_comment='Does this operation produce a regulated product listed in Table 1 of Schedule A.1 of the GGERR?',
                        null=True,
                    ),
                ),
                (
                    'meets_reporting_and_regulated_obligations',
                    models.BooleanField(
                        blank=True,
                        db_comment='Is this operation capable of fulfilling the obligations of a reporting operation and a regulated operation under the Act and the regulations?',
                        null=True,
                    ),
                ),
                (
                    'meets_notification_to_director_on_criteria_change',
                    models.BooleanField(
                        blank=True,
                        db_comment='Will the operator notify the Director as soon as possible if this operation ceases to meet any of the criteria for the designation of the operation as a reporting operation and a regulated operation?',
                        null=True,
                    ),
                ),
                (
                    'archived_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_archived',
                        to='registration.user',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_created',
                        to='registration.user',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_updated',
                        to='registration.user',
                    ),
                ),
            ],
            options={
                'db_table': 'erc"."opted_in_operation_detail',
                'db_table_comment': 'Table containing details about operations that have opted in',
            },
        ),
        migrations.AddField(
            model_name='historicaloperation',
            name='opted_in_operation',
            field=models.ForeignKey(
                blank=True,
                db_comment='Details about the operation if it is opted in',
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='registration.optedinoperationdetail',
            ),
        ),
        migrations.AddField(
            model_name='operation',
            name='opted_in_operation',
            field=models.OneToOneField(
                blank=True,
                db_comment='Details about the operation if it is opted in',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='operation',
                to='registration.optedinoperationdetail',
            ),
        ),
    ]
