# Generated by Django 5.0.7 on 2024-09-04 18:34

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0036_remove_historicalevent_archived_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalfacilityownershiptimeline',
            name='archived_by',
        ),
        migrations.RemoveField(
            model_name='historicalfacilityownershiptimeline',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalfacilityownershiptimeline',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='historicalfacilityownershiptimeline',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='historicalfacilityownershiptimeline',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='historicaloperationownershiptimeline',
            name='archived_by',
        ),
        migrations.RemoveField(
            model_name='historicaloperationownershiptimeline',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicaloperationownershiptimeline',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='historicaloperationownershiptimeline',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='historicaloperationownershiptimeline',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='operationownershiptimeline',
            name='archived_by',
        ),
        migrations.RemoveField(
            model_name='operationownershiptimeline',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='operationownershiptimeline',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='operationownershiptimeline',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='operationownershiptimeline',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='historicalmultipleoperator',
            name='mailing_address',
        ),
        migrations.RemoveField(
            model_name='historicalmultipleoperator',
            name='mailing_address_same_as_physical',
        ),
        migrations.RemoveField(
            model_name='historicalmultipleoperator',
            name='operator_index',
        ),
        migrations.RemoveField(
            model_name='historicalmultipleoperator',
            name='percentage_ownership',
        ),
        migrations.RemoveField(
            model_name='historicalmultipleoperator',
            name='physical_address',
        ),
        migrations.RemoveField(
            model_name='historicalmultipleoperator',
            name='website',
        ),
        migrations.RemoveField(
            model_name='multipleoperator',
            name='mailing_address',
        ),
        migrations.RemoveField(
            model_name='multipleoperator',
            name='mailing_address_same_as_physical',
        ),
        migrations.RemoveField(
            model_name='multipleoperator',
            name='operator_index',
        ),
        migrations.RemoveField(
            model_name='multipleoperator',
            name='percentage_ownership',
        ),
        migrations.RemoveField(
            model_name='multipleoperator',
            name='physical_address',
        ),
        migrations.RemoveField(
            model_name='multipleoperator',
            name='website',
        ),
        migrations.AddField(
            model_name='bcobpsregulatedoperation',
            name='status',
            field=models.CharField(
                choices=[('Active', 'Active'), ('Inactive', 'Inactive')],
                db_comment='The status of an operation.',
                default='Active',
                max_length=1000,
            ),
        ),
        migrations.AddField(
            model_name='historicalbcobpsregulatedoperation',
            name='status',
            field=models.CharField(
                choices=[('Active', 'Active'), ('Inactive', 'Inactive')],
                db_comment='The status of an operation.',
                default='Active',
                max_length=1000,
            ),
        ),
        migrations.AddField(
            model_name='historicalmultipleoperator',
            name='attorney_address',
            field=models.ForeignKey(
                blank=True,
                db_comment="The address of the operator's attorney",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='registration.address',
            ),
        ),
        migrations.AddField(
            model_name='historicaloperation',
            name='secondary_naics_code',
            field=models.ForeignKey(
                blank=True,
                db_comment="This column refers to an operation's secondary NAICS code.",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='registration.naicscode',
            ),
        ),
        migrations.AddField(
            model_name='historicaloperation',
            name='tertiary_naics_code',
            field=models.ForeignKey(
                blank=True,
                db_comment="This column refers to an operation's tertiary NAICS code.",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='registration.naicscode',
            ),
        ),
        migrations.AddField(
            model_name='multipleoperator',
            name='attorney_address',
            field=models.ForeignKey(
                blank=True,
                db_comment="The address of the operator's attorney",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='multiple_operators',
                to='registration.address',
            ),
        ),
        migrations.AddField(
            model_name='operation',
            name='secondary_naics_code',
            field=models.ForeignKey(
                blank=True,
                db_comment="This column refers to an operation's secondary NAICS code.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='operations_naics_secondary',
                to='registration.naicscode',
            ),
        ),
        migrations.AddField(
            model_name='operation',
            name='tertiary_naics_code',
            field=models.ForeignKey(
                blank=True,
                db_comment="This column refers to an operation's tertiary NAICS code.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='operations_naics_tertiary',
                to='registration.naicscode',
            ),
        ),
        migrations.AlterField(
            model_name='historicalmultipleoperator',
            name='bc_corporate_registry_number',
            field=models.CharField(
                blank=True,
                db_comment='The BC corporate registry number of an operator',
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message='BC Corporate Registry Number should be 1-3 letters followed by 7 digits.',
                        regex='^[A-Za-z]{1,3}[0-9]{7}$',
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name='historicaloperation',
            name='naics_code',
            field=models.ForeignKey(
                blank=True,
                db_comment="This column refers to an operation's primary NAICS code.",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='registration.naicscode',
            ),
        ),
        migrations.AlterField(
            model_name='multipleoperator',
            name='bc_corporate_registry_number',
            field=models.CharField(
                blank=True,
                db_comment='The BC corporate registry number of an operator',
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message='BC Corporate Registry Number should be 1-3 letters followed by 7 digits.',
                        regex='^[A-Za-z]{1,3}[0-9]{7}$',
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name='multipleoperator',
            name='business_structure',
            field=models.ForeignKey(
                db_comment='The business structure of an operator',
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='multiple_operators',
                to='registration.businessstructure',
            ),
        ),
        migrations.AlterField(
            model_name='multipleoperator',
            name='operation',
            field=models.ForeignKey(
                db_comment='The operation that this multiple operator is associated with',
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='multiple_operators',
                to='registration.operation',
            ),
        ),
        migrations.AlterField(
            model_name='operation',
            name='naics_code',
            field=models.ForeignKey(
                db_comment="This column refers to an operation's primary NAICS code.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='operations',
                to='registration.naicscode',
            ),
        ),
        migrations.CreateModel(
            name='FacilityDesignatedOperationTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                (
                    'start_date',
                    models.DateTimeField(
                        blank=True,
                        db_comment='The date an operation became the designated operation of a facility. This data captures the relationship between the facility and operation it falls under.',
                        null=True,
                    ),
                ),
                (
                    'end_date',
                    models.DateTimeField(
                        blank=True,
                        db_comment='The date an operation stopped being the designated operation of a facility',
                        null=True,
                    ),
                ),
                (
                    'archived_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_archived',
                        to='registration.user',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_created',
                        to='registration.user',
                    ),
                ),
                (
                    'facility',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='designated_operations',
                        to='registration.facility',
                    ),
                ),
                (
                    'operation',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='facility_designated_operations',
                        to='registration.operation',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_updated',
                        to='registration.user',
                    ),
                ),
            ],
            options={
                'db_table': 'erc"."facility_designated_operation_timeline',
                'db_table_comment': 'A table to connect facilities and operations',
            },
        ),
        migrations.CreateModel(
            name='HistoricalFacilityDesignatedOperationTimeline',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                (
                    'start_date',
                    models.DateTimeField(
                        blank=True,
                        db_comment='The date an operation became the designated operation of a facility. This data captures the relationship between the facility and operation it falls under.',
                        null=True,
                    ),
                ),
                (
                    'end_date',
                    models.DateTimeField(
                        blank=True,
                        db_comment='The date an operation stopped being the designated operation of a facility',
                        null=True,
                    ),
                ),
                ('history_user_id', models.UUIDField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                (
                    'history_type',
                    models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
                ),
                (
                    'archived_by',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.user',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.user',
                    ),
                ),
                (
                    'facility',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.facility',
                    ),
                ),
                (
                    'operation',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.operation',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.user',
                    ),
                ),
            ],
            options={
                'verbose_name': 'historical facility designated operation timeline',
                'verbose_name_plural': 'historical facility designated operation timelines',
                'db_table': 'erc_history"."facility_designated_operation_timeline_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalOperationDesignatedOperatorTimeline',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                (
                    'start_date',
                    models.DateTimeField(
                        blank=True,
                        db_comment="The date the operator started being the designated operator of the operation. The 'designated'/controlling operator isn't necessarily the operation's owner.",
                        null=True,
                    ),
                ),
                (
                    'end_date',
                    models.DateTimeField(
                        blank=True,
                        db_comment='The date the operator ended being the designated operator of the operation',
                        null=True,
                    ),
                ),
                ('history_user_id', models.UUIDField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                (
                    'history_type',
                    models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
                ),
                (
                    'archived_by',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.user',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.user',
                    ),
                ),
                (
                    'operation',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.operation',
                    ),
                ),
                (
                    'operator',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.operator',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.user',
                    ),
                ),
            ],
            options={
                'verbose_name': 'historical operation designated operator timeline',
                'verbose_name_plural': 'historical operation designated operator timelines',
                'db_table': 'erc_history"."operation_designated_operator_timeline_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='OperationDesignatedOperatorTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                (
                    'start_date',
                    models.DateTimeField(
                        blank=True,
                        db_comment="The date the operator started being the designated operator of the operation. The 'designated'/controlling operator isn't necessarily the operation's owner.",
                        null=True,
                    ),
                ),
                (
                    'end_date',
                    models.DateTimeField(
                        blank=True,
                        db_comment='The date the operator ended being the designated operator of the operation',
                        null=True,
                    ),
                ),
                (
                    'archived_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_archived',
                        to='registration.user',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_created',
                        to='registration.user',
                    ),
                ),
                (
                    'operation',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='designated_operators',
                        to='registration.operation',
                    ),
                ),
                (
                    'operator',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='operation_designated_operators',
                        to='registration.operator',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_updated',
                        to='registration.user',
                    ),
                ),
            ],
            options={
                'db_table': 'erc"."operation_designated_operator_timeline',
                'db_table_comment': 'A table to connect operations and their designated operators throughout their lifetimes',
            },
        ),
        migrations.DeleteModel(
            name='FacilityOwnershipTimeline',
        ),
        migrations.DeleteModel(
            name='HistoricalFacilityOwnershipTimeline',
        ),
        migrations.DeleteModel(
            name='HistoricalOperationOwnershipTimeline',
        ),
        migrations.DeleteModel(
            name='OperationOwnershipTimeline',
        ),
        migrations.AddConstraint(
            model_name='facilitydesignatedoperationtimeline',
            constraint=models.UniqueConstraint(
                condition=models.Q(('end_date__isnull', True)),
                fields=('facility',),
                name='unique_active_designated_operation_per_facility',
            ),
        ),
        migrations.AddConstraint(
            model_name='operationdesignatedoperatortimeline',
            constraint=models.UniqueConstraint(
                condition=models.Q(('end_date__isnull', True)),
                fields=('operation',),
                name='unique_active_designated_operator_per_operation',
            ),
        ),
    ]
