# Generated by Django 5.0.7 on 2024-09-05 21:09

import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0038_V1_10_0'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalfacilityownershiptimeline',
            name='archived_by',
        ),
        migrations.RemoveField(
            model_name='historicalfacilityownershiptimeline',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalfacilityownershiptimeline',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='historicalfacilityownershiptimeline',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='historicalfacilityownershiptimeline',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='historicaloperationownershiptimeline',
            name='archived_by',
        ),
        migrations.RemoveField(
            model_name='historicaloperationownershiptimeline',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicaloperationownershiptimeline',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='historicaloperationownershiptimeline',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='historicaloperationownershiptimeline',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='operationownershiptimeline',
            name='archived_by',
        ),
        migrations.RemoveField(
            model_name='operationownershiptimeline',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='operationownershiptimeline',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='operationownershiptimeline',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='operationownershiptimeline',
            name='updated_by',
        ),
        migrations.CreateModel(
            name='FacilityDesignatedOperationTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                (
                    'start_date',
                    models.DateTimeField(
                        blank=True,
                        db_comment='The date an operation became the designated operation of a facility. This data captures the relationship between the facility and operation it falls under.',
                        null=True,
                    ),
                ),
                (
                    'end_date',
                    models.DateTimeField(
                        blank=True,
                        db_comment='The date an operation stopped being the designated operation of a facility',
                        null=True,
                    ),
                ),
                (
                    'archived_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_archived',
                        to='registration.user',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_created',
                        to='registration.user',
                    ),
                ),
                (
                    'facility',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='designated_operations',
                        to='registration.facility',
                    ),
                ),
                (
                    'operation',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='facility_designated_operations',
                        to='registration.operation',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_updated',
                        to='registration.user',
                    ),
                ),
            ],
            options={
                'db_table': 'erc"."facility_designated_operation_timeline',
                'db_table_comment': 'A table to connect facilities and operations',
            },
        ),
        migrations.CreateModel(
            name='HistoricalFacilityDesignatedOperationTimeline',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                (
                    'start_date',
                    models.DateTimeField(
                        blank=True,
                        db_comment='The date an operation became the designated operation of a facility. This data captures the relationship between the facility and operation it falls under.',
                        null=True,
                    ),
                ),
                (
                    'end_date',
                    models.DateTimeField(
                        blank=True,
                        db_comment='The date an operation stopped being the designated operation of a facility',
                        null=True,
                    ),
                ),
                ('history_user_id', models.UUIDField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                (
                    'history_type',
                    models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
                ),
                (
                    'archived_by',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.user',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.user',
                    ),
                ),
                (
                    'facility',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.facility',
                    ),
                ),
                (
                    'operation',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.operation',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.user',
                    ),
                ),
            ],
            options={
                'verbose_name': 'historical facility designated operation timeline',
                'verbose_name_plural': 'historical facility designated operation timelines',
                'db_table': 'erc_history"."facility_designated_operation_timeline_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalOperationDesignatedOperatorTimeline',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                (
                    'start_date',
                    models.DateTimeField(
                        blank=True,
                        db_comment="The date the operator started being the designated operator of the operation. The 'designated'/controlling operator isn't necessarily the operation's owner.",
                        null=True,
                    ),
                ),
                (
                    'end_date',
                    models.DateTimeField(
                        blank=True,
                        db_comment='The date the operator ended being the designated operator of the operation',
                        null=True,
                    ),
                ),
                ('history_user_id', models.UUIDField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                (
                    'history_type',
                    models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
                ),
                (
                    'archived_by',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.user',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.user',
                    ),
                ),
                (
                    'operation',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.operation',
                    ),
                ),
                (
                    'operator',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.operator',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.user',
                    ),
                ),
            ],
            options={
                'verbose_name': 'historical operation designated operator timeline',
                'verbose_name_plural': 'historical operation designated operator timelines',
                'db_table': 'erc_history"."operation_designated_operator_timeline_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='OperationDesignatedOperatorTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                (
                    'start_date',
                    models.DateTimeField(
                        blank=True,
                        db_comment="The date the operator started being the designated operator of the operation. The 'designated'/controlling operator isn't necessarily the operation's owner.",
                        null=True,
                    ),
                ),
                (
                    'end_date',
                    models.DateTimeField(
                        blank=True,
                        db_comment='The date the operator ended being the designated operator of the operation',
                        null=True,
                    ),
                ),
                (
                    'archived_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_archived',
                        to='registration.user',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_created',
                        to='registration.user',
                    ),
                ),
                (
                    'operation',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='designated_operators',
                        to='registration.operation',
                    ),
                ),
                (
                    'operator',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='operation_designated_operators',
                        to='registration.operator',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_updated',
                        to='registration.user',
                    ),
                ),
            ],
            options={
                'db_table': 'erc"."operation_designated_operator_timeline',
                'db_table_comment': 'A table to connect operations and their designated operators throughout their lifetimes',
            },
        ),
        migrations.DeleteModel(
            name='FacilityOwnershipTimeline',
        ),
        migrations.DeleteModel(
            name='HistoricalFacilityOwnershipTimeline',
        ),
        migrations.DeleteModel(
            name='HistoricalOperationOwnershipTimeline',
        ),
        migrations.DeleteModel(
            name='OperationOwnershipTimeline',
        ),
        migrations.AddConstraint(
            model_name='facilitydesignatedoperationtimeline',
            constraint=models.UniqueConstraint(
                condition=models.Q(('end_date__isnull', True)),
                fields=('facility',),
                name='unique_active_designated_operation_per_facility',
            ),
        ),
        migrations.AddConstraint(
            model_name='operationdesignatedoperatortimeline',
            constraint=models.UniqueConstraint(
                condition=models.Q(('end_date__isnull', True)),
                fields=('operation',),
                name='unique_active_designated_operator_per_operation',
            ),
        ),
    ]
