# Generated by Django 5.0.7 on 2024-09-05 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0039_remove_historicalfacilityownershiptimeline_archived_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='address',
            field=models.ForeignKey(
                blank=True,
                db_comment='The address of the facility',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_address',
                to='registration.address',
            ),
        ),
        migrations.AlterField(
            model_name='facilitydesignatedoperationtimeline',
            name='facility',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='designated_operations',
                to='registration.facility',
            ),
        ),
        migrations.AlterField(
            model_name='facilitydesignatedoperationtimeline',
            name='operation',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='facility_designated_operations',
                to='registration.operation',
            ),
        ),
        migrations.AlterField(
            model_name='operation',
            name='bc_obps_regulated_operation',
            field=models.OneToOneField(
                blank=True,
                db_comment='The BC OBPS regulated operation ID of an operation when operation is approved',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='registration.bcobpsregulatedoperation',
            ),
        ),
        migrations.AlterField(
            model_name='operation',
            name='naics_code',
            field=models.ForeignKey(
                db_comment="An operation's NAICS code",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='operations',
                to='registration.naicscode',
            ),
        ),
        migrations.AlterField(
            model_name='operation',
            name='operator',
            field=models.ForeignKey(
                db_comment='The operator who owns the operation',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='operations',
                to='registration.operator',
            ),
        ),
        migrations.AlterField(
            model_name='operation',
            name='point_of_contact',
            field=models.ForeignKey(
                blank=True,
                db_comment='Foreign key to the contact that is the point of contact (point of contact is only used in registration 1)',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='operations',
                to='registration.contact',
            ),
        ),
        migrations.AlterField(
            model_name='operation',
            name='verified_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='The IRC user who verified the operator',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='operation_verified_by',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='operationdesignatedoperatortimeline',
            name='operation',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='designated_operators',
                to='registration.operation',
            ),
        ),
        migrations.AlterField(
            model_name='operationdesignatedoperatortimeline',
            name='operator',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='operation_designated_operators',
                to='registration.operator',
            ),
        ),
    ]
