# Generated by Django 5.0.8 on 2024-09-19 22:07

from django.db import migrations


def update_activity_weights(apps, schema_monitor):
    '''
    Update weights to reflect how IRC would like activities ordered
    '''

    Activity = apps.get_model('registration', 'Activity')
    Activity.objects.all().update(weight=9999)
    Activity.objects.filter(name='General stationary combustion excluding line tracing').update(weight=100)
    Activity.objects.filter(name='General stationary combustion solely for the purpose of line tracing').update(
        weight=200
    )
    Activity.objects.filter(
        name='General stationary combustion, other than non-compression and non-processing combustion'
    ).update(weight=300)
    Activity.objects.filter(name='General stationary non-compression and non-processing combustion').update(weight=400)
    Activity.objects.filter(name='Fuel combustion by mobile equipment').update(weight=500)


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0042_prod_data'),
    ]

    operations = [
        # No reverse function needed here
        migrations.RunPython(update_activity_weights),
    ]
