# Generated by Django 5.0.8 on 2024-10-08 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0044_facilitydesignatedoperationtimeline_status_and_more'),
    ]

    operations = []
