# Generated by Django 5.0.9 on 2024-10-23 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0045_V1_11_0'),
    ]

    operations = []
