# Generated by Django 5.0.9 on 2024-10-22 17:38

from django.db import migrations


def add_document_type_data(apps, schema_monitor):
    '''
    Add new_entrant_application_and_statutory_declaration to erc.document_type
    '''
    DocumentType = apps.get_model('registration', 'DocumentType')
    DocumentType.objects.bulk_create(
        [
            DocumentType(name='new_entrant_application_and_statutory_declaration'),
        ]
    )


def reverse_add_document_type_data(apps, schema_monitor):
    '''
    Remove new_entrant_application_and_statutory_declaration from erc.document_type
    '''
    DocumentType = apps.get_model('registration', 'DocumentType')
    DocumentType.objects.filter(
        name='new_entrant_application_and_statutory_declaration',
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('registration', '0047_historicalnewentrantoperationdetail_and_more'),
    ]

    operations = [
        migrations.RunPython(add_document_type_data, reverse_add_document_type_data),
    ]
