# Generated by Django 5.0.7 on 2024-10-31 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0049_bcghgoperationorfacility_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalbcgreenhousegasid',
            options={
                'get_latest_by': ('history_date', 'history_id'),
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical bc greenhouse gas id',
                'verbose_name_plural': 'historical bc greenhouse gas ids',
            },
        ),
    ]
