# Generated by Django 5.0.9 on 2024-10-30 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0049_auto_20241030_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloperation',
            name='date_of_first_shipment',
            field=models.CharField(
                blank=True,
                choices=[
                    ('On or before March 31, 2024', 'On Or Before March 31 2024'),
                    ('On or after April 1, 2024', 'On Or After April 1 2024'),
                ],
                db_comment="The date of the operation's first shipment (determines which application and statutory declaration template should be used)",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='operation',
            name='date_of_first_shipment',
            field=models.CharField(
                blank=True,
                choices=[
                    ('On or before March 31, 2024', 'On Or Before March 31 2024'),
                    ('On or after April 1, 2024', 'On Or After April 1 2024'),
                ],
                db_comment="The date of the operation's first shipment (determines which application and statutory declaration template should be used)",
                max_length=1000,
                null=True,
            ),
        ),
    ]
