# Generated by Django 5.0.7 on 2024-11-01 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0052_auto_20241101_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='bcghg_id',
            field=models.OneToOneField(
                blank=True,
                db_comment="A facility's BCGHG identifier.",
                max_length=1000,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='registration.bcgreenhousegasid',
            ),
        ),
        migrations.AlterField(
            model_name='historicalfacility',
            name='bcghg_id',
            field=models.ForeignKey(
                blank=True,
                db_comment="A facility's BCGHG identifier.",
                db_constraint=False,
                max_length=1000,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='registration.bcgreenhousegasid',
            ),
        ),
        migrations.AlterField(
            model_name='historicaloperation',
            name='bcghg_id',
            field=models.ForeignKey(
                blank=True,
                db_comment="An operation's BCGHG identifier.",
                db_constraint=False,
                max_length=1000,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='registration.bcgreenhousegasid',
            ),
        ),
        migrations.AlterField(
            model_name='operation',
            name='bcghg_id',
            field=models.OneToOneField(
                blank=True,
                db_comment="An operation's BCGHG identifier.",
                max_length=1000,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='registration.bcgreenhousegasid',
            ),
        ),
    ]
