# Generated by Django 5.0.7 on 2024-11-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0054_V1_13_0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltransferevent',
            name='status',
            field=models.CharField(
                choices=[
                    ('Complete', 'Complete'),
                    ('To be transferred', 'To Be Transferred'),
                    ('Transferred', 'Transferred'),
                ],
                default='To be transferred',
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name='transferevent',
            name='status',
            field=models.CharField(
                choices=[
                    ('Complete', 'Complete'),
                    ('To be transferred', 'To Be Transferred'),
                    ('Transferred', 'Transferred'),
                ],
                default='To be transferred',
                max_length=100,
            ),
        ),
    ]
