# Generated by Django 5.0.9 on 2024-11-15 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0055_V1_14_0'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltransferevent',
            name='future_designated_operator',
        ),
        migrations.RemoveField(
            model_name='transferevent',
            name='future_designated_operator',
        ),
        migrations.AlterField(
            model_name='historicaltransferevent',
            name='status',
            field=models.CharField(
                choices=[
                    ('Complete', 'Complete'),
                    ('To be transferred', 'To Be Transferred'),
                    ('Transferred', 'Transferred'),
                ],
                default='To be transferred',
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name='transferevent',
            name='status',
            field=models.CharField(
                choices=[
                    ('Complete', 'Complete'),
                    ('To be transferred', 'To Be Transferred'),
                    ('Transferred', 'Transferred'),
                ],
                default='To be transferred',
                max_length=100,
            ),
        ),
    ]
