# Generated by Django 5.0.9 on 2024-11-27 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0058_regulatedproduct_add_isregulated_and_unit'),
    ]

    operations = []
