# Generated by Django 5.0.9 on 2024-12-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0060_auto_20241128_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloperationdesignatedoperatortimeline',
            name='status',
            field=models.CharField(
                choices=[
                    ('Active', 'Active'),
                    ('Transferred', 'Transferred'),
                    ('Closed', 'Closed'),
                    ('Temporarily Shutdown', 'Temporarily Shutdown'),
                ],
                db_comment='The status of an operation in relation to a specific operator (e.g. if an operation has transferred ownership, it may have a status of Transferred with its old operator and Active with its new one)',
                default='Active',
                max_length=1000,
            ),
        ),
        migrations.AddField(
            model_name='operationdesignatedoperatortimeline',
            name='status',
            field=models.CharField(
                choices=[
                    ('Active', 'Active'),
                    ('Transferred', 'Transferred'),
                    ('Closed', 'Closed'),
                    ('Temporarily Shutdown', 'Temporarily Shutdown'),
                ],
                db_comment='The status of an operation in relation to a specific operator (e.g. if an operation has transferred ownership, it may have a status of Transferred with its old operator and Active with its new one)',
                default='Active',
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name='historicaloperation',
            name='status',
            field=models.CharField(
                choices=[
                    ('Not Started', 'Not Started'),
                    ('Draft', 'Draft'),
                    ('Registered', 'Registered'),
                    ('Approved', 'Approved'),
                    ('Declined', 'Declined'),
                    ('Changes Requested', 'Changes Requested'),
                    ('Pending', 'Pending'),
                ],
                db_comment='The status of an operation in the app (e.g. pending review)',
                default='Not Started',
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name='operation',
            name='status',
            field=models.CharField(
                choices=[
                    ('Not Started', 'Not Started'),
                    ('Draft', 'Draft'),
                    ('Registered', 'Registered'),
                    ('Approved', 'Approved'),
                    ('Declined', 'Declined'),
                    ('Changes Requested', 'Changes Requested'),
                    ('Pending', 'Pending'),
                ],
                db_comment='The status of an operation in the app (e.g. pending review)',
                default='Not Started',
                max_length=1000,
            ),
        ),
    ]
