# Generated by Django 5.0.8 on 2024-12-12 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0061_remove_naics_code'),
    ]

    operations = []
