# Generated by Django 5.0.9 on 2024-12-13 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0062_V1_16_0'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltransferevent',
            name='description',
        ),
        migrations.RemoveField(
            model_name='historicaltransferevent',
            name='other_operator',
        ),
        migrations.RemoveField(
            model_name='historicaltransferevent',
            name='other_operator_contact',
        ),
        migrations.RemoveField(
            model_name='transferevent',
            name='description',
        ),
        migrations.RemoveField(
            model_name='transferevent',
            name='other_operator',
        ),
        migrations.RemoveField(
            model_name='transferevent',
            name='other_operator_contact',
        ),
        migrations.AddField(
            model_name='historicaloperationdesignatedoperatortimeline',
            name='status',
            field=models.CharField(
                choices=[
                    ('Active', 'Active'),
                    ('Transferred', 'Transferred'),
                    ('Closed', 'Closed'),
                    ('Temporarily Shutdown', 'Temporarily Shutdown'),
                ],
                db_comment='The status of an operation in relation to a specific operator (e.g. if an operation has transferred ownership, it may have a status of Transferred with its old operator and Active with its new one)',
                default='Active',
                max_length=1000,
            ),
        ),
        migrations.AddField(
            model_name='historicaltransferevent',
            name='from_operation',
            field=models.ForeignKey(
                blank=True,
                db_comment='The operation that facilities are being transferred from.',
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='registration.operation',
            ),
        ),
        migrations.AddField(
            model_name='historicaltransferevent',
            name='from_operator',
            field=models.ForeignKey(
                blank=True,
                db_comment='The operator who is transferring the operation or facility.',
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='registration.operator',
            ),
        ),
        migrations.AddField(
            model_name='historicaltransferevent',
            name='to_operation',
            field=models.ForeignKey(
                blank=True,
                db_comment='The operation that facilities are being transferred to.',
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='registration.operation',
            ),
        ),
        migrations.AddField(
            model_name='historicaltransferevent',
            name='to_operator',
            field=models.ForeignKey(
                blank=True,
                db_comment='The operator who is receiving the operation or facility.',
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='registration.operator',
            ),
        ),
        migrations.AddField(
            model_name='operationdesignatedoperatortimeline',
            name='status',
            field=models.CharField(
                choices=[
                    ('Active', 'Active'),
                    ('Transferred', 'Transferred'),
                    ('Closed', 'Closed'),
                    ('Temporarily Shutdown', 'Temporarily Shutdown'),
                ],
                db_comment='The status of an operation in relation to a specific operator (e.g. if an operation has transferred ownership, it may have a status of Transferred with its old operator and Active with its new one)',
                default='Active',
                max_length=1000,
            ),
        ),
        migrations.AddField(
            model_name='transferevent',
            name='from_operation',
            field=models.ForeignKey(
                blank=True,
                db_comment='The operation that facilities are being transferred from.',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='transfer_events_from',
                to='registration.operation',
            ),
        ),
        migrations.AddField(
            model_name='transferevent',
            name='from_operator',
            field=models.ForeignKey(
                db_comment='The operator who is transferring the operation or facility.',
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='transfer_events_from',
                to='registration.operator',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferevent',
            name='to_operation',
            field=models.ForeignKey(
                blank=True,
                db_comment='The operation that facilities are being transferred to.',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='transfer_events_to',
                to='registration.operation',
            ),
        ),
        migrations.AddField(
            model_name='transferevent',
            name='to_operator',
            field=models.ForeignKey(
                db_comment='The operator who is receiving the operation or facility.',
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='transfer_events_to',
                to='registration.operator',
            ),
            preserve_default=False,
        ),
    ]
