# Generated by Django 5.0.9 on 2024-12-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0063_remove_historicaltransferevent_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloperation',
            name='status',
            field=models.CharField(
                choices=[
                    ('Not Started', 'Not Started'),
                    ('Draft', 'Draft'),
                    ('Registered', 'Registered'),
                    ('Approved', 'Approved'),
                    ('Declined', 'Declined'),
                    ('Changes Requested', 'Changes Requested'),
                    ('Pending', 'Pending'),
                ],
                db_comment='The status of an operation in the app (e.g. pending review)',
                default='Not Started',
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name='operation',
            name='status',
            field=models.CharField(
                choices=[
                    ('Not Started', 'Not Started'),
                    ('Draft', 'Draft'),
                    ('Registered', 'Registered'),
                    ('Approved', 'Approved'),
                    ('Declined', 'Declined'),
                    ('Changes Requested', 'Changes Requested'),
                    ('Pending', 'Pending'),
                ],
                db_comment='The status of an operation in the app (e.g. pending review)',
                default='Not Started',
                max_length=1000,
            ),
        ),
    ]
