# Generated by Django 5.0.9 on 2024-12-18 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0063_remove_historicaltransferevent_description_and_more'),
    ]

    operations = []
