# Generated by Django 5.0.10 on 2025-01-02 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0065_alter_historicaloperation_status_and_more'),
    ]

    operations = []
