# Generated by Django 5.0.11 on 2025-01-27 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0070_alter_facility_type_alter_historicalfacility_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='naics_code',
            field=models.ForeignKey(
                blank=True,
                db_comment="This column refers to an operation's primary NAICS code.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='operations',
                to='registration.naicscode',
            ),
        ),
    ]
