# Generated by Django 5.0.11 on 2025-02-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0071_remove_historicaloperation_documents_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloptedinoperationdetail',
            name='meets_producing_gger_schedule_a1_regulated_product',
            field=models.BooleanField(
                blank=True,
                db_comment='Does this operation produce a regulated product listed in Table 2 of Schedule A.1 of the GGERR?',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='optedinoperationdetail',
            name='meets_producing_gger_schedule_a1_regulated_product',
            field=models.BooleanField(
                blank=True,
                db_comment='Does this operation produce a regulated product listed in Table 2 of Schedule A.1 of the GGERR?',
                null=True,
            ),
        ),
    ]
