# Generated by Django 5.0.11 on 2025-02-12 21:48

import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0076_alter_facility_type_alter_historicalfacility_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalFacility_well_authorization_numbers',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                (
                    'facility',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace='',
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.facility',
                    ),
                ),
                (
                    'history',
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='registration.historicalfacility',
                    ),
                ),
                (
                    'wellauthorizationnumber',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace='',
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.wellauthorizationnumber',
                    ),
                ),
            ],
            options={
                'verbose_name': 'HistoricalFacility_well_authorization_numbers',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalOperation_contacts',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                (
                    'contact',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace='',
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.contact',
                    ),
                ),
                (
                    'history',
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='registration.historicaloperation',
                    ),
                ),
                (
                    'operation',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace='',
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.operation',
                    ),
                ),
            ],
            options={
                'verbose_name': 'HistoricalOperation_contacts',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
