# Generated by Django 5.0.13 on 2025-03-11 22:08

from django.db import migrations

"""
One-time forward-only migration to be applied to prod data.
Purpose: create a contact record for each approved industry_user who doesn't already appear in the contact table.
"""


def create_contacts_from_prod_industry_users(apps, schema_editor):
    """Creates Contact records for approved industry users not already in the Contact table."""
    # Import the required Django models
    User = apps.get_model('registration', 'User')
    Contact = apps.get_model('registration', 'Contact')
    UserOperator = apps.get_model('registration', 'UserOperator')
    BusinessRole = apps.get_model('registration', 'BusinessRole')

    # Fetch only approved UserOperator user IDs
    approved_user_operators = UserOperator.objects.filter(status="Approved").values_list("user_id", flat=True)

    # Fetch approved industry users who are not already in Contact
    approved_industry_users = User.objects.filter(
        user_guid__in=approved_user_operators, app_role__role_name="industry_user"
    ).exclude(email__in=Contact.objects.values_list("email", flat=True))

    operation_representative_role = BusinessRole.objects.get(role_name="Operation Representative")

    for user in approved_industry_users:
        users_user_operator = user.user_operators.filter(status="Approved").first()
        operator = users_user_operator.operator if users_user_operator else None
        if operator:
            _ = Contact.objects.get_or_create(
                email=user.email,
                defaults={
                    "first_name": user.first_name,
                    "last_name": user.last_name,
                    "phone_number": user.phone_number,
                    "position_title": user.position_title,
                    "business_role": operation_representative_role,
                    "address": None,
                    "operator": operator,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0084_remove_historicaloperation_point_of_contact_and_more'),
    ]

    operations = [
        migrations.RunPython(create_contacts_from_prod_industry_users, migrations.RunPython.noop, elidable=True),
    ]
