# Generated by Django 5.0.13 on 2025-03-11 22:09

from django.db import migrations

"""
One-time forward-only migration to be applied to prod data.
Purpose: Replace Operation Registration Lead with Operation Representative business fole for contacts. Delete Operation Registration Lead from BusinessRole model.
"""


def migrate_business_roles(apps, schema_monitor):

    Contact = apps.get_model('registration', 'Contact')
    BusinessRole = apps.get_model('registration', 'BusinessRole')

    Contact.objects.filter(business_role='Operation Registration Lead').update(business_role='Operation Representative')

    BusinessRole.objects.get(role_name='Operation Registration Lead').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0085_make_contacts_from_industry_users'),
    ]

    operations = [
        migrations.RunPython(migrate_business_roles, migrations.RunPython.noop, elidable=True),
    ]
