# Generated by Django 5.0.13 on 2025-03-11 22:09

from django.db import migrations
from collections import defaultdict

"""
One-time forward-only migration to be applied to prod data.
Purpose: First, check that contacts records are duplicated in full. Then,remove duplicate contacts.  Where operation.point_of_contact was one of the duplicates, replace with the unique contact.
"""


def migrate_remove_duplicate_contacts(apps, schema_monitor):

    Contact = apps.get_model('registration', 'Contact')

    email_groups = defaultdict(list)
    # group contacts by email
    for contact in Contact.objects.all():
        email = contact.email
        if Contact.objects.filter(email=email).count() > 1:
            email_groups[email].append(contact)

    for email, contacts in email_groups.items():
        duplicate_contacts = contacts[1:]

        # delete duplicate contacts
        Contact.objects.filter(id__in=[contact.id for contact in duplicate_contacts]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0086_update_contact_business_roles'),
    ]

    operations = [
        migrations.RunPython(migrate_remove_duplicate_contacts, migrations.RunPython.noop, elidable=True),
    ]
