# Generated by Django 5.0.13 on 2025-03-12 17:12

from django.db import migrations
import datetime

"""
One-time forward-only migration to be applied to prod data.
Purpose: set the `status` field of Operations (created in Reg1) to match the statuses used in Administration/Registration2 modules.
Also archives operations with a "Declined" status (only 1 as of Feb 19, 2025)
Reg1 Status        | Reg2 Status
-------------------+-------------------
PENDING            | DRAFT
APPROVED           | DRAFT
CHANGES_REQUESTED  | DRAFT
NOT_STARTED        | NOT_STARTED
DRAFT              | DRAFT
DECLINED           | Archive the operation
"""


def migrate_reg1_operation_statuses(apps, schema_monitor):
    # import the required Django model
    Operation = apps.get_model('registration', 'Operation')
    User = apps.get_model('registration', 'User')
    breakpoint()
    Operation.objects.filter(status="Pending").update(status="Draft")
    Operation.objects.filter(status="Approved").update(status="Draft")
    Operation.objects.filter(status="Changes Requested").update(status="Draft")

    po_user = User.objects.filter(first_name="Patricia", last_name="Russell").first()
    # we won't have a po_user in every environment
    if po_user:
        Operation.objects.filter(status="Declined").update(
            archived_by_id=po_user.user_guid, archived_at=datetime.datetime.now(datetime.timezone.utc)
        )  # declined operations will be archived, per PR's instruction and using her user GUID


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0089_set_purpose_for_existing_operations'),
    ]

    operations = [migrations.RunPython(migrate_reg1_operation_statuses, migrations.RunPython.noop, elidable=True)]
