# Generated by Django 5.0.11 on 2025-03-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0094_V2_0_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(
                choices=[('Unscanned', 'Unscanned'), ('Clean', 'Clean'), ('Quarantined', 'Quarantined')],
                default='Unscanned',
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='status',
            field=models.CharField(
                choices=[('Unscanned', 'Unscanned'), ('Clean', 'Clean'), ('Quarantined', 'Quarantined')],
                default='Unscanned',
                max_length=100,
            ),
        ),
    ]
