# Generated by Django 5.0.13 on 2025-03-26 18:21

from django.db import migrations
from datetime import datetime
from zoneinfo import ZoneInfo


"""
One-time forward-only migration to be applied to prod data.
Purpose: Update the start_date of each FacilityDesignatedOperationTimeline record in the database.
"""


def update_facility_designated_operation_timeline_start_date(apps, schema_editor):
    FacilityDesignatedOperationTimeline = apps.get_model("registration", "FacilityDesignatedOperationTimeline")
    FacilityDesignatedOperationTimeline.objects.update(start_date = datetime(2024, 1, 1, tzinfo=ZoneInfo("UTC")))  # January 1, 2024

class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0096_populate_operation_timeline_with_prod_data'),
    ]

    operations = [
        migrations.RunPython(code=update_facility_designated_operation_timeline_start_date, reverse_code=migrations.RunPython.noop, elidable=True),
    ]
