# Generated by Django 5.0.13 on 2025-03-27 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0097_document_status_historicaldocument_status'),
    ]

    operations = []
