# Generated by Django 5.0.13 on 2025-04-02 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0100_address_protect_fields_empty_update_and_more'),
    ]

    operations = []
