# Generated by Django 5.0.14 on 2025-04-11 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0104_product_non_nullable_units_remove_unused_products'),
    ]

    operations = []
