# Generated by Django 5.0.14 on 2025-04-16 18:12

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0105_V2_3_0'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='operation',
            name='restrict_bcghg_id_unless_registered',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='operation',
            name='restrict_boro_id_unless_registered',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='operation',
            trigger=pgtrigger.compiler.Trigger(
                name='restrict_bcghg_id_unless_registered',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (NEW."bcghg_id_id" IS NOT NULL)',
                    func="\n                    IF NEW.status != 'Registered' AND\n                       (TG_OP = 'INSERT' OR NEW.bcghg_id_id IS DISTINCT FROM OLD.bcghg_id_id) THEN\n                        RAISE EXCEPTION 'Cannot assign bcghg_id to Operation unless status is Registered';\n                    END IF;\n                    RETURN NEW;\n                ",
                    hash='50a014796cd08bfa6cee329f046d612dc96df631',
                    operation='INSERT OR UPDATE',
                    pgid='pgtrigger_restrict_bcghg_id_unless_registered_48253',
                    table='erc"."operation',
                    when='BEFORE',
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='operation',
            trigger=pgtrigger.compiler.Trigger(
                name='restrict_boro_id_unless_registered',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (NEW."bc_obps_regulated_operation_id" IS NOT NULL)',
                    func="\n                    IF NEW.status != 'Registered' AND\n                        OLD.bc_obps_regulated_operation_id IS NULL AND\n                        NEW.bc_obps_regulated_operation_id IS NOT NULL THEN\n                            RAISE EXCEPTION 'Cannot assign bc_obps_regulated_operation to Operation unless status is Registered';\n                    END IF;\n                    RETURN NEW;\n                ",
                    hash='0873d9592282f59dad4a3f9bb0f0f9e3079e0ca7',
                    operation='INSERT OR UPDATE',
                    pgid='pgtrigger_restrict_boro_id_unless_registered_ba9a4',
                    table='erc"."operation',
                    when='BEFORE',
                ),
            ),
        ),
    ]
