# Generated by Django 5.0.14 on 2025-04-22 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0106_remove_facility_restrict_bcghg_id_unless_operation_registered_and_more'),
    ]

    operations = []
