# Generated by Django 5.0.14 on 2025-05-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0109_remove_closureevent_set_created_audit_columns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnaicscode',
            name='is_regulated',
            field=models.BooleanField(
                db_comment='Whether the NAICS code applies to regulated operations', default=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='naicscode',
            name='is_regulated',
            field=models.BooleanField(
                db_comment='Whether the NAICS code applies to regulated operations', default=True
            ),
            preserve_default=False,
        ),
    ]
