# Generated by Django 5.0.14 on 2025-05-12 20:10

from django.db import migrations

"""
Forward-only prod data migration to remove the contacts associated with an operation that has been transferred, if the contact is associated with the from_operator (not the to_operator) of the transfer.
"""


def remove_contacts_from_transferred_operations(apps, schema_editor):
    TransferEvent = apps.get_model("registration", "TransferEvent")

    # fetch all transfer events
    transfer_events = TransferEvent.objects.all()

    # iterate over each transfer event, and for each operation in the event, check the operation's contacts
    for transfer_event in transfer_events:
        operation = transfer_event.operation
        from_operator = transfer_event.from_operator
        operation_contacts = operation.contacts.all()

        # for each contact in operation_contacts, check if the contact is associated with the from_operator. If so, delete it.
        for contact in operation_contacts:
            if contact.operator == from_operator:
                # remove the contact from the operation (without deleting the contact - it might be used elsewhere)
                operation.contacts.remove(contact)


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0111_add_non_regulated_naics_codes'),
    ]

    operations = [
        migrations.RunPython(
            code=remove_contacts_from_transferred_operations,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
    ]
