# Generated by Django 5.0.14 on 2025-05-14 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0112_prod_fix_contacts_post_transfer'),
    ]

    operations = []
