# Generated by Django 5.0.14 on 2025-05-29 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0116_V3_3_0'),
    ]

    operations = []
