# Generated by Django 5.0.14 on 2025-06-05 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0119_bcghg_ids_to_sfo_facilities'),
    ]

    operations = []
