# Generated by Django 5.0.14 on 2025-06-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0121_V3_7_0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalwellauthorizationnumber',
            name='well_authorization_number',
            field=models.CharField(
                db_comment='A well authorization number from the BC Energy Regulator', db_index=True
            ),
        ),
        migrations.AlterField(
            model_name='wellauthorizationnumber',
            name='well_authorization_number',
            field=models.CharField(
                db_comment='A well authorization number from the BC Energy Regulator', primary_key=True, serialize=False
            ),
        ),
    ]
