# Generated by Django 5.1.10 on 2025-06-19 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0122_V3_8_0'),
    ]

    operations = []
