# Generated by Django 5.1.10 on 2025-06-23 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0123_V3_8_1'),
    ]

    operations = [
        # had to write this SQL script manually because Django migrations don't automatically alter the
        # through table's column type when the primary key type of a model changes
        migrations.RunSQL(
            sql=[
                # Drop existing FK constraint
                """
                alter table erc.facility_well_authorization_numbers
                drop constraint if exists facility_well_author_wellauthorizationnum_2fc21025_fk_well_auth;
                """,
            ]
        ),
        migrations.AlterField(
            model_name='historicalwellauthorizationnumber',
            name='well_authorization_number',
            field=models.CharField(
                db_comment='A well authorization number from the BC Energy Regulator',
                db_index=True,
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message='Well authorization number must only contain digits', regex='^\\d+$'
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name='wellauthorizationnumber',
            name='well_authorization_number',
            field=models.CharField(
                db_comment='A well authorization number from the BC Energy Regulator',
                max_length=10,
                primary_key=True,
                serialize=False,
                validators=[
                    django.core.validators.RegexValidator(
                        message='Well authorization number must only contain digits', regex='^\\d+$'
                    )
                ],
            ),
        ),
        migrations.RunSQL(
            sql=[
                # see comment above - this is necessary because the through table's column type does not automatically change
                # when the primary key type of a model changes
                #
                # alter column type
                """
                alter table erc.facility_well_authorization_numbers
                alter column wellauthorizationnumber_id type varchar(10)
                using wellauthorizationnumber_id::varchar(10);
                """,
                # Re-introduce FK constraint
                """
                alter table erc.facility_well_authorization_numbers
                add constraint facility_well_authorization_numbers_wellauthorizationnumber_id_fkey
                foreign key (wellauthorizationnumber_id)
                references erc.well_authorization_number(well_authorization_number)
                """,
            ]
        ),
    ]
