# Generated by Django 5.1.10 on 2025-07-22 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0127_V3_11_0'),
    ]

    operations = []
