# Generated by Django 5.1.10 on 2025-08-15 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0131_alter_bcgreenhousegasid_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bcgreenhousegasid',
            name='id',
            field=models.CharField(
                db_comment='The BCGHG ID of an operation or facility',
                max_length=255,
                primary_key=True,
                serialize=False,
                validators=[
                    django.core.validators.RegexValidator(
                        message='BCGHG ID should be 11 digits, starting with 1 or 2.', regex='^[1-2]\\d{10}$'
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name='historicalbcgreenhousegasid',
            name='id',
            field=models.CharField(
                db_comment='The BCGHG ID of an operation or facility',
                db_index=True,
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        message='BCGHG ID should be 11 digits, starting with 1 or 2.', regex='^[1-2]\\d{10}$'
                    )
                ],
            ),
        ),
    ]
