# Generated by Django 5.1.10 on 2025-08-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0132_V3_15_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloperation',
            name='test_field',
            field=models.CharField(
                blank=True,
                db_comment='This is a test field to ensure that the operation model can be migrated without issues.',
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='operation',
            name='test_field',
            field=models.CharField(
                blank=True,
                db_comment='This is a test field to ensure that the operation model can be migrated without issues.',
                max_length=1000,
                null=True,
            ),
        ),
    ]
