# Generated by Django 5.1.12 on 2025-10-28 22:08

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0144_V4_3_0'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOptedOutOperationDetail',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                (
                    'effective_date',
                    models.CharField(
                        blank=True,
                        choices=[('Start of 2026', 'Start 2026'), ('End of 2026', 'End 2026')],
                        db_comment='Operation is opted out as of this date',
                        max_length=1000,
                        null=True,
                    ),
                ),
                ('history_user_id', models.UUIDField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                (
                    'history_type',
                    models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
                ),
                (
                    'archived_by',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.user',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.user',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.user',
                    ),
                ),
            ],
            options={
                'verbose_name': 'historical opted out operation detail',
                'verbose_name_plural': 'historical opted out operation details',
                'db_table': 'erc_history"."opted_out_operation_detail_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='OptedOutOperationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                (
                    'effective_date',
                    models.CharField(
                        blank=True,
                        choices=[('Start of 2026', 'Start 2026'), ('End of 2026', 'End 2026')],
                        db_comment='Operation is opted out as of this date',
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    'archived_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_archived',
                        to='registration.user',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_created',
                        to='registration.user',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_updated',
                        to='registration.user',
                    ),
                ),
            ],
            options={
                'db_table': 'erc"."opted_out_operation_detail',
                'db_table_comment': 'Table containing details about operations that have opted out',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='historicaloptedinoperationdetail',
            name='opted_out_operation',
            field=models.ForeignKey(
                blank=True,
                db_comment='Details if the operation has subsequently opted out',
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='registration.optedoutoperationdetail',
            ),
        ),
        migrations.AddField(
            model_name='optedinoperationdetail',
            name='opted_out_operation',
            field=models.OneToOneField(
                blank=True,
                db_comment='Details if the operation has subsequently opted out',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='opted_out',
                to='registration.optedoutoperationdetail',
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='optedoutoperationdetail',
            trigger=pgtrigger.compiler.Trigger(
                name='set_created_audit_columns',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="new.created_by_id = (select nullif(current_setting('my.guid', true), '')); new.created_at = now(); return new;",
                    hash='017dc1c6f7ba296f3b973e76116cdffea4a8aa70',
                    operation='INSERT',
                    pgid='pgtrigger_set_created_audit_columns_77268',
                    table='erc"."opted_out_operation_detail',
                    when='BEFORE',
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='optedoutoperationdetail',
            trigger=pgtrigger.compiler.Trigger(
                name='set_updated_audit_columns',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="new.updated_by_id = (select current_setting('my.guid', true)); new.updated_at = now(); return new;",
                    hash='9a34ed94671ca4d2fc196172e39d0ef95b50057e',
                    operation='UPDATE',
                    pgid='pgtrigger_set_updated_audit_columns_3e147',
                    table='erc"."opted_out_operation_detail',
                    when='BEFORE',
                ),
            ),
        ),
    ]
