# Generated by Django 5.1.14 on 2025-11-26 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0145_V4_4_0'),
    ]

    operations = []
