# Generated by Django 5.1.15 on 2025-12-15 10:23

from django.db import migrations


def update_activity_applicable_to_field(apps, schema_editor):
    """
    Forward-only migration to update the activit applicable_to field values
    to match the latest business requirements.
    """
    Activity = apps.get_model("registration", "activity")

    # SFO only activities
    Activity.objects.filter(slug="fuel_combustion_by_mobile").update(applicable_to="Single Facility Operation")

    # LFO only activities
    Activity.objects.filter(slug="gsc_other_than_non_compression").update(applicable_to="Linear Facilities Operation")
    Activity.objects.filter(slug="gsc_non_compression").update(applicable_to="Linear Facilities Operation")
    Activity.objects.filter(slug="og_activities_other_than_non_compression").update(
        applicable_to="Linear Facilities Operation"
    )
    Activity.objects.filter(slug="og_activities_non_compression").update(applicable_to="Linear Facilities Operation")
    Activity.objects.filter(slug="electricity_transmission").update(applicable_to="Linear Facilities Operation")
    Activity.objects.filter(slug="natural_gas_activities_other_than_non_compression").update(
        applicable_to="Linear Facilities Operation"
    )
    Activity.objects.filter(slug="natural_gas_activities_non_compression").update(
        applicable_to="Linear Facilities Operation"
    )
    Activity.objects.filter(slug="lng_activities").update(applicable_to="Linear Facilities Operation")

    # activities applicable to all facility types
    Activity.objects.filter(slug="gsc_solely_for_line_tracing").update(applicable_to="all")
    Activity.objects.filter(slug="gsc_excluding_line_tracing").update(applicable_to="all")
    Activity.objects.filter(slug="aluminum_production").update(applicable_to="all")
    Activity.objects.filter(slug="ammonia_production").update(applicable_to="all")
    Activity.objects.filter(slug="cement_production").update(applicable_to="all")
    Activity.objects.filter(slug="underground_coal_mining").update(applicable_to="all")
    Activity.objects.filter(slug="coal_storage").update(applicable_to="all")
    Activity.objects.filter(slug="copper_nickel_refining").update(applicable_to="all")
    Activity.objects.filter(slug="electricity_generation").update(applicable_to="all")
    Activity.objects.filter(slug="electronics_manufacturing").update(applicable_to="all")
    Activity.objects.filter(slug="ferroalloy_production").update(applicable_to="all")
    Activity.objects.filter(slug="glass_manufacturing").update(applicable_to="all")
    Activity.objects.filter(slug="hydrogen_production").update(applicable_to="all")
    Activity.objects.filter(slug="ind_wastewater_processing").update(applicable_to="all")
    Activity.objects.filter(slug="lead_production").update(applicable_to="all")
    Activity.objects.filter(slug="lime_manufacturing").update(applicable_to="all")
    Activity.objects.filter(slug="magnesium_production").update(applicable_to="all")
    Activity.objects.filter(slug="nitric_acid_manufacturing").update(applicable_to="all")
    Activity.objects.filter(slug="petrochemical_production").update(applicable_to="all")
    Activity.objects.filter(slug="petroleum_refining").update(applicable_to="all")
    Activity.objects.filter(slug="phos_acid_production").update(applicable_to="all")
    Activity.objects.filter(slug="pulp_and_paper").update(applicable_to="all")
    Activity.objects.filter(slug="refinery_fuel_gas").update(applicable_to="all")
    Activity.objects.filter(slug="zinc_production").update(applicable_to="all")
    Activity.objects.filter(slug="open_pit_coal_mining").update(applicable_to="all")
    Activity.objects.filter(slug="storage_petro_products").update(applicable_to="all")
    Activity.objects.filter(slug="carbonate_use").update(applicable_to="all")


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0148_V4_6_1'),
    ]

    operations = [
        migrations.RunPython(update_activity_applicable_to_field, migrations.RunPython.noop, elidable=True),
    ]
