# Generated by Django 5.1.15 on 2026-01-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0148_V4_6_1'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contact',
            name='unique_email_per_operator',
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(
                condition=models.Q(('archived_at__isnull', True), ('operator__isnull', False)),
                fields=('email', 'operator'),
                name='unique_active_email_per_operator',
            ),
        ),
    ]
