# Generated by Django 5.1.15 on 2026-01-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0149_update_activity_applicable_to'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contact',
            name='unique_email_per_operator',
        ),
        migrations.RunSQL(
            sql="""
                DROP INDEX IF EXISTS "erc"."unique_email_per_operator";
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(
                condition=models.Q(('archived_at__isnull', True), ('operator__isnull', False)),
                fields=('email', 'operator'),
                name='unique_active_email_per_operator',
            ),
        ),
    ]
