# Generated by Django 5.1.15 on 2026-01-06 23:29

import django.core.validators
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
import simple_history.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0151_V4_7_0'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalFacilitySnapshot',
            fields=[
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                (
                    'id',
                    models.UUIDField(
                        db_comment='Primary key to identify the facility snapshot',
                        db_index=True,
                        default=uuid.uuid4,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        db_comment='The name of the facility at the time of the snapshot', max_length=1000
                    ),
                ),
                (
                    'is_current_year',
                    models.BooleanField(
                        blank=True,
                        db_comment="The facility's starting date is within the current year or preceding year at snapshot time",
                        null=True,
                    ),
                ),
                (
                    'starting_date',
                    models.DateTimeField(
                        blank=True,
                        db_comment='The date of the facility starting operations at snapshot time',
                        null=True,
                    ),
                ),
                ('type', models.CharField(db_comment='The type of the facility at snapshot time', max_length=100)),
                (
                    'street_address',
                    models.CharField(
                        blank=True,
                        db_comment='Street address of the facility at snapshot time',
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    'municipality',
                    models.CharField(
                        blank=True,
                        db_comment='Municipality of the facility at snapshot time',
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    'province',
                    models.CharField(
                        blank=True, db_comment='Province of the facility at snapshot time', max_length=1000, null=True
                    ),
                ),
                (
                    'postal_code',
                    models.CharField(
                        blank=True, db_comment='Postal code of the facility at snapshot time', max_length=10, null=True
                    ),
                ),
                (
                    'swrs_facility_id',
                    models.IntegerField(
                        blank=True, db_comment="The facility's SWRS facility ID at snapshot time", null=True
                    ),
                ),
                (
                    'bcghg_id',
                    models.CharField(
                        blank=True,
                        db_comment="The facility's BCGHG identifier at snapshot time",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    'latitude_of_largest_emissions',
                    models.DecimalField(
                        blank=True,
                        db_comment='The latitude of the largest point of emissions at snapshot time',
                        decimal_places=6,
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    'longitude_of_largest_emissions',
                    models.DecimalField(
                        blank=True,
                        db_comment='The longitude of the largest point of emissions at snapshot time',
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    'well_authorization_numbers',
                    models.JSONField(
                        blank=True,
                        db_comment='List of well authorization numbers at snapshot time',
                        default=list,
                        null=True,
                    ),
                ),
                (
                    'snapshot_timestamp',
                    models.DateTimeField(
                        blank=True, db_comment='The timestamp at which this snapshot was taken', editable=False
                    ),
                ),
                ('history_user_id', models.UUIDField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                (
                    'history_type',
                    models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
                ),
                (
                    'archived_by',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.user',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.user',
                    ),
                ),
                (
                    'facility',
                    models.ForeignKey(
                        blank=True,
                        db_comment='The facility that this snapshot represents',
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.facility',
                    ),
                ),
                (
                    'operation',
                    models.ForeignKey(
                        blank=True,
                        db_comment='The operation that owned the facility at the time of the snapshot',
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.operation',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.user',
                    ),
                ),
            ],
            options={
                'verbose_name': 'historical facility snapshot',
                'verbose_name_plural': 'historical Facility Snapshots',
                'db_table': 'erc_history"."facility_snapshot_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='FacilitySnapshot',
            fields=[
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                (
                    'id',
                    models.UUIDField(
                        db_comment='Primary key to identify the facility snapshot',
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        db_comment='The name of the facility at the time of the snapshot', max_length=1000
                    ),
                ),
                (
                    'is_current_year',
                    models.BooleanField(
                        blank=True,
                        db_comment="The facility's starting date is within the current year or preceding year at snapshot time",
                        null=True,
                    ),
                ),
                (
                    'starting_date',
                    models.DateTimeField(
                        blank=True,
                        db_comment='The date of the facility starting operations at snapshot time',
                        null=True,
                    ),
                ),
                ('type', models.CharField(db_comment='The type of the facility at snapshot time', max_length=100)),
                (
                    'street_address',
                    models.CharField(
                        blank=True,
                        db_comment='Street address of the facility at snapshot time',
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    'municipality',
                    models.CharField(
                        blank=True,
                        db_comment='Municipality of the facility at snapshot time',
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    'province',
                    models.CharField(
                        blank=True, db_comment='Province of the facility at snapshot time', max_length=1000, null=True
                    ),
                ),
                (
                    'postal_code',
                    models.CharField(
                        blank=True, db_comment='Postal code of the facility at snapshot time', max_length=10, null=True
                    ),
                ),
                (
                    'swrs_facility_id',
                    models.IntegerField(
                        blank=True, db_comment="The facility's SWRS facility ID at snapshot time", null=True
                    ),
                ),
                (
                    'bcghg_id',
                    models.CharField(
                        blank=True,
                        db_comment="The facility's BCGHG identifier at snapshot time",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    'latitude_of_largest_emissions',
                    models.DecimalField(
                        blank=True,
                        db_comment='The latitude of the largest point of emissions at snapshot time',
                        decimal_places=6,
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    'longitude_of_largest_emissions',
                    models.DecimalField(
                        blank=True,
                        db_comment='The longitude of the largest point of emissions at snapshot time',
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    'well_authorization_numbers',
                    models.JSONField(
                        blank=True,
                        db_comment='List of well authorization numbers at snapshot time',
                        default=list,
                        null=True,
                    ),
                ),
                (
                    'snapshot_timestamp',
                    models.DateTimeField(
                        auto_now_add=True, db_comment='The timestamp at which this snapshot was taken'
                    ),
                ),
                (
                    'archived_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_archived',
                        to='registration.user',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_created',
                        to='registration.user',
                    ),
                ),
                (
                    'facility',
                    models.ForeignKey(
                        db_comment='The facility that this snapshot represents',
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='snapshots',
                        to='registration.facility',
                    ),
                ),
                (
                    'operation',
                    models.ForeignKey(
                        db_comment='The operation that owned the facility at the time of the snapshot',
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='facility_snapshots',
                        to='registration.operation',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_updated',
                        to='registration.user',
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'Facility Snapshots',
                'db_table': 'erc"."facility_snapshot',
                'db_table_comment': 'Snapshots of facility data at the time of transfer. This allows old operators to view facility information as it existed when they owned the facility, even after changes are made by new operators.',
                'abstract': False,
                'indexes': [
                    models.Index(fields=['facility', 'operation'], name='facility_sn_facilit_462ca1_idx'),
                    models.Index(fields=['operation'], name='facility_sn_operati_3806bb_idx'),
                    models.Index(fields=['snapshot_timestamp'], name='facility_sn_snapsho_785eef_idx'),
                ],
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='facilitysnapshot',
            trigger=pgtrigger.compiler.Trigger(
                name='set_created_audit_columns',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="new.created_by_id = (select nullif(current_setting('my.guid', true), '')); new.created_at = now(); return new;",
                    hash='5266783ec3333621311f17d042f8d85c816e54d4',
                    operation='INSERT',
                    pgid='pgtrigger_set_created_audit_columns_80665',
                    table='erc"."facility_snapshot',
                    when='BEFORE',
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='facilitysnapshot',
            trigger=pgtrigger.compiler.Trigger(
                name='set_updated_audit_columns',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="new.updated_by_id = (select nullif(current_setting('my.guid', true), '')); new.updated_at = now(); return new;",
                    hash='20129c3a449227930792f361a0d3edf239953552',
                    operation='UPDATE',
                    pgid='pgtrigger_set_updated_audit_columns_6a831',
                    table='erc"."facility_snapshot',
                    when='BEFORE',
                ),
            ),
        ),
    ]
