# Generated by Django 5.1.15 on 2026-01-27 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0155_V5_0_1'),
        ('reporting', '0150_report_operation_final_reporting_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloptedinoperationdetail',
            name='final_reporting_year',
            field=models.ForeignKey(
                blank=True,
                db_comment='The final reporting year an opted-out operation is expected to report for, if applicable.',
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='reporting.reportingyear',
            ),
        ),
        migrations.AddField(
            model_name='optedinoperationdetail',
            name='final_reporting_year',
            field=models.ForeignKey(
                blank=True,
                db_comment='The final reporting year an opted-out operation is expected to report for, if applicable.',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='reporting.reportingyear',
            ),
        ),
    ]
