# Generated by Django 5.1.15 on 2026-02-04 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0156_activity_display_and_regulated_name'),
    ]

    operations = []
