# Generated by Django 5.1.15 on 2026-02-03 21:41

from django.db import migrations


def add_product(apps, schema_monitor):
    '''
    Add the new Pulp & Paper: Lime Revovery Kiln
    '''
    RegulatedProduct = apps.get_model('registration', 'RegulatedProduct')
    RegulatedProduct.objects.create(
        name="Pulp and paper: lime revovery kiln",
        unit="Tonnes dry recovered lime (calcium oxide)",
        is_regulated=True,
    )


def reverse_add_product(apps, schema_monitor):
    RegulatedProduct = apps.get_model('registration', 'RegulatedProduct')
    RegulatedProduct.objects.filter(name="Pulp and paper: lime revovery kiln").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0156_activity_display_and_regulated_name'),
    ]

    operations = [
        migrations.RunPython(add_product, reverse_add_product),
    ]
