# Generated by Django 5.1.15 on 2026-02-03 21:41

from decimal import Decimal
from django.db import migrations


def add_product_and_pwaei(apps, schema_monitor):
    '''
    Add the new Pulp & Paper: Lime Revovery Kiln
    '''
    RegulatedProduct = apps.get_model('registration', 'RegulatedProduct')
    ProductEmissionIntensity = apps.get_model('reporting', 'ProductEmissionIntensity')

    RegulatedProduct.objects.create(
        name="Pulp and paper: lime recovered by kiln",
        unit="Tonnes dry recovered lime (calcium oxide)",
        is_regulated=True,
    )
    ProductEmissionIntensity.objects.create(
        product_id=RegulatedProduct.objects.get(name="Pulp and paper: lime recovered by kiln").id,
        product_weighted_average_emission_intensity=Decimal("0.3822"),
        valid_from='2023-01-01',
        valid_to='9999-12-31',
    )


def reverse_add_product_and_pwaei(apps, schema_monitor):
    RegulatedProduct = apps.get_model('registration', 'RegulatedProduct')
    ProductEmissionIntensity = apps.get_model('reporting', 'ProductEmissionIntensity')

    ProductEmissionIntensity.objects.filter(product__name="Pulp and paper: lime recovered by kiln").delete()
    RegulatedProduct.objects.filter(name="Pulp and paper: lime recovered by kiln").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0157_V5_1_0'),
    ]

    operations = [
        migrations.RunPython(add_product_and_pwaei, reverse_add_product_and_pwaei),
    ]
