# Generated by Django 5.1.15 on 2026-03-10 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0164_V5_4_1'),
    ]

    operations = []
