# Generated by Django 5.1.15 on 2026-04-28 17:55

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0172_V5_9_0'),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name='activity',
            trigger=pgtrigger.compiler.Trigger(
                name='immutable_slug',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            begin\n\n                if new.slug != old.slug then\n                    raise exception 'slug field is immutable';\n                end if;\n                return new;\n\n            end;\n            ",
                    hash='00355fcacd44013744cb105fa7ca064836b94b86',
                    operation='UPDATE',
                    pgid='pgtrigger_immutable_slug_a2fb4',
                    table='erc"."activity',
                    when='BEFORE',
                ),
            ),
        ),
    ]
