# Generated by Django 5.1.15 on 2026-05-07 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0174_activity_immutable_slug'),
    ]

    operations = []
