# Generated by Django 5.1.15 on 2026-06-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0177_V5_12_0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(
                db_comment='The file format, metadata, etc.', max_length=1000, upload_to='documents'
            ),
        ),
        migrations.AlterField(
            model_name='historicaldocument',
            name='file',
            field=models.TextField(db_comment='The file format, metadata, etc.', max_length=1000),
        ),
    ]
