# Generated by Django 5.1.15 on 2026-06-08 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0178_alter_document_file_alter_historicaldocument_file'),
    ]

    operations = []
