# Generated by Django 5.1.15 on 2026-06-11 15:36

from datetime import date
from django.db import migrations, models


def populate_valid_dates(apps, schema_editor):
    RegulatedProduct = apps.get_model('registration', 'RegulatedProduct')
    RegulatedProduct.objects.all().update(
        valid_from=date(2023, 1, 1),
        valid_to=date(2099, 12, 31),
    )
    RegulatedProduct.objects.filter(name='Pulp and paper: chemical pulp').update(
        valid_from=date(2025, 1, 1),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0180_V5_13_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalregulatedproduct',
            name='valid_from',
            field=models.DateField(
                blank=True, db_comment='Date from which this regulated product is valid for reporting', null=True
            ),
        ),
        migrations.AddField(
            model_name='historicalregulatedproduct',
            name='valid_to',
            field=models.DateField(
                blank=True, db_comment='Date until which this regulated product is valid for reporting', null=True
            ),
        ),
        migrations.AddField(
            model_name='regulatedproduct',
            name='valid_from',
            field=models.DateField(
                blank=True, db_comment='Date from which this regulated product is valid for reporting', null=True
            ),
        ),
        migrations.AddField(
            model_name='regulatedproduct',
            name='valid_to',
            field=models.DateField(
                blank=True, db_comment='Date until which this regulated product is valid for reporting', null=True
            ),
        ),
        # Populate all existing rows before enforcing NOT NULL
        migrations.RunPython(populate_valid_dates, migrations.RunPython.noop),
        # Now enforce non-nullable
        migrations.AlterField(
            model_name='historicalregulatedproduct',
            name='valid_from',
            field=models.DateField(db_comment='Date from which this regulated product is valid for reporting'),
        ),
        migrations.AlterField(
            model_name='historicalregulatedproduct',
            name='valid_to',
            field=models.DateField(db_comment='Date until which this regulated product is valid for reporting'),
        ),
        migrations.AlterField(
            model_name='regulatedproduct',
            name='valid_from',
            field=models.DateField(db_comment='Date from which this regulated product is valid for reporting'),
        ),
        migrations.AlterField(
            model_name='regulatedproduct',
            name='valid_to',
            field=models.DateField(db_comment='Date until which this regulated product is valid for reporting'),
        ),
    ]
