# Generated by Django 5.1.15 on 2026-06-18 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0182_update_document_metadata'),
    ]

    operations = []
