# Generated by Django 5.1.15 on 2026-07-07 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0185_V5_15_0'),
    ]

    operations = []
