# Generated by Django 5.2.16 on 2026-07-28 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0188_V5_17_0'),
    ]

    operations = []
