# Generated by Django 5.2.16 on 2026-07-30 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_V5_0_1_squashed_0189_V5_18_0'),
    ]

    operations = []
