# Generated by Django 6.0.8 on 2026-09-01 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0194_V5_20_0'),
    ]

    operations = []
