nodeLinker: node-modules
npmMinimalAgeGate: 7d
npmPreapprovedPackages:
    [
        "@astrojs/starlight@0.41.0",
        "astro@7.0.2",
        "@astrojs/markdown-satteri@0.3.2",
        "@astrojs/*@7",
        "satteri@0.9.1",
        "@bruits/*@0.9.1",
    ]
