version: '3.8'

services:
  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_USER: slava
      POSTGRES_PASSWORD: slava
      POSTGRES_DB: cas_registration
      DB_NAME: cas_registration
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 