version: '3.8'

services:
  bc-bciers-nx-app:
    build:
      context: .
      dockerfile: ./bciers/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - HOST_ADMINISTRATION=http://localhost:3000
      - HOST_COMPLIANCE=http://localhost:3001
      - HOST_REGISTRATION=http://localhost:3002
      - HOST_REPORTING=http://localhost:3003
    networks:
      - bciers-network

  bc-obps-app:
    build:
      context: .
      dockerfile: ./bc_obps/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=bc_obps.settings.production
    networks:
      - bciers-network

  zap-scan:
    image: owasp/zap2docker-stable
    container_name: zap-scanner
    ports:
      - "8080:8080"  # ZAP UI
    volumes:
      - ./zap-scan:/zap/wrk
    command: ["zap.sh", "-daemon", "-host", "0.0.0.0", "-port", "8080", "-config", "api.disablekey=true"]
    networks:
      - bciers-network

networks:
  bciers-network:
    driver: bridge
