version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: registration
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db:/var/lib/postgresql/data
    network_mode: host

  backend:
    image: ghcr.io/bcgov/cas-reg-backend:${GITHUB_SHA}
    environment:
      DB_USER: postgres
      DB_NAME: registration
      DB_PASSWORD: postgres
      DB_PORT: 5432
      DB_HOST: localhost
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      ALLOWED_HOSTS: localhost,0.0.0.0,127.0.0.1
      ENVIRONMENT: dev
      CI: "true"
    depends_on:
      - db
    network_mode: host

  dashboard:
    image: ghcr.io/bcgov/cas-dash-e2e-frontend:${GITHUB_SHA}
    environment:
      CI: "true"
      PORT: 3000
      API_URL: http://127.0.0.1:8000/api/
    depends_on:
      - backend
    network_mode: host

  administration:
    image: ghcr.io/bcgov/cas-admin-frontend:${GITHUB_SHA}
    environment:
      PORT: 4001
      API_URL: http://127.0.0.1:8000/api/
    depends_on:
      - backend
    network_mode: host

  compliance:
    image: ghcr.io/bcgov/cas-compliance-frontend:${GITHUB_SHA}
    environment:
      PORT: 7000
      API_URL: http://127.0.0.1:8000/api/
    depends_on:
      - backend
    network_mode: host

  registration:
    image: ghcr.io/bcgov/cas-reg-frontend:${GITHUB_SHA}
    environment:
      PORT: 4000
      API_URL: http://127.0.0.1:8000/api/
    depends_on:
      - backend
    network_mode: host

volumes:
  db:
    driver: local
