apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cas-bciers.fullname" . }}-backend
  labels:
    component: backend
{{- include "cas-bciers.labels" . | nindent 4 }}
spec:
{{- if not .Values.backend.autoscaling.enabled }}
  replicas: {{ .Values.backend.replicaCount }}
{{- end }}
  selector:
    matchLabels:
{{- include "cas-bciers.selectorLabels" . | nindent 6 }}
      component: backend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
{{- include "cas-bciers.selectorLabels" . | nindent 8 }}
        component: backend
    spec:
      containers:
        - name: {{ .Release.Name }}-backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.defaultImageTag | default .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          env:
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: django-secret-key
                  name: {{ include "cas-bciers.fullname" . }}-backend
            - name: CHES_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: clientSecret
                  name: ches-integration
            - name: CHES_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: clientId
                  name: ches-integration
            - name: CHES_TOKEN_ENDPOINT
              valueFrom:
                secretKeyRef:
                  key: tokenEndpoint
                  name: ches-integration
            - name: CHES_API_URL
              valueFrom:
                secretKeyRef:
                  key: apiUrl
                  name: ches-integration
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: cas-obps-postgres-pguser-registration
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: cas-obps-postgres-pguser-registration
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  key: dbname
                  name: cas-obps-postgres-pguser-registration
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  key: pgbouncer-port
                  name: cas-obps-postgres-pguser-registration
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  key: pgbouncer-host
                  name: cas-obps-postgres-pguser-registration
            - name: ALLOWED_HOSTS
              value: '*'
            - name: BACKEND_HOST
              value: {{ .Values.backend.route.host }}
            - name: GS_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  key: bucket_name
                  name: gcp-{{ .Release.Namespace }}-bciers-attach-service-account-key
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/attachment-credentials/attachment-credentials.json"
            - name: ENVIRONMENT
              value: {{ .Values.backend.environment }}
            {{- if hasSuffix "-prod" .Release.Namespace }}
            - name: SENTRY_ENVIRONMENT
              value: {{ include "cas-bciers.namespaceSuffix" . }}
            - name: SENTRY_RELEASE
              value: {{ .Values.backend.image.tag }}
            - name: SENTRY_TRACE_SAMPLE_RATE
              value: {{ .Values.backend.sentry.traceSampleRate | quote }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.backend.service.port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8000
            # we want the readiness threshold to fail fast,
            # to prevent any request from going to a pod that is not ready
            failureThreshold: 1
            successThreshold: 1
            periodSeconds: 30
            timeoutSeconds: 5
            initialDelaySeconds: 120
          livenessProbe:
            # the liveness probe is here to ensure that a pod does not get
            # stuck in a shutdown state. It needs to allow enough time for
            # the registered shutdown handler to run to completion.
            httpGet:
              path: /liveness
              port: 8000
            initialDelaySeconds: 150
            periodSeconds: 30
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 5
          resources: {{ toYaml .Values.backend.resources | nindent 12 }}
          volumeMounts:
            - mountPath: "/attachment-credentials"
              name: gcs-attachment-credentials
              readOnly: true
      volumes:
        - name: gcs-attachment-credentials
          secret:
            secretName: gcp-{{ .Release.Namespace }}-bciers-attach-service-account-key
            items:
            - key: credentials.json
              path: attachment-credentials.json
      restartPolicy: Always
