version: "3"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: registration
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db:/var/lib/postgresql/data
    network_mode: host

  backend:
    image: ghcr.io/bcgov/cas-reg-backend:${GITHUB_SHA}
    environment:
      DB_USER: postgres
      DB_NAME: registration
      DB_PASSWORD: postgres
      DB_PORT: 5432
      DB_HOST: localhost # This points to the PostgreSQL service
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      ALLOWED_HOSTS: localhost,0.0.0.0,127.0.0.1
      ENVIRONMENT: dev
      CI: true
    depends_on:
      - db # Ensures the database is up before the backend starts
    network_mode: host

  dashboard:
    # Use the dashboard-e2e image which has nextjs rewrite hosts built in
    image: ghcr.io/bcgov/cas-dash-e2e-frontend:${GITHUB_SHA}
    environment:
      CI: true # This is used to disable secureCookie in the dashboard route.ts file
      PORT: 3000
      HOSTNAME: localhost
      NEXTAUTH_URL_INTERNAL: http://localhost:3000
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      API_URL: http://127.0.0.1:8000/api/
      KEYCLOAK_LOGIN_URL: ${KEYCLOAK_LOGIN_URL}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
    depends_on:
      - backend
    network_mode: host

  nx-app:
    image: ghcr.io/bcgov/cas-admin-frontend:${GITHUB_SHA}
    environment:
      PORT: ${NX_APP_PORT}
      HOSTNAME: localhost
      NEXTAUTH_URL_INTERNAL: http://localhost:3000
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      API_URL: http://127.0.0.1:8000/api/
      KEYCLOAK_LOGIN_URL: ${KEYCLOAK_LOGIN_URL}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
    depends_on:
      - backend
    network_mode: host

volumes:
  db:
    driver: local
