services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: registration
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db:/var/lib/postgresql/data
    network_mode: host

  backend:
    image: ghcr.io/bcgov/cas-reg-backend:${GITHUB_SHA}
    environment:
      DB_USER: postgres
      DB_NAME: registration
      DB_PASSWORD: postgres
      DB_PORT: 5432
      DB_HOST: localhost
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      ALLOWED_HOSTS: localhost,0.0.0.0,127.0.0.1
      ENVIRONMENT: dev
      CI: "true"
    depends_on:
      - db
    network_mode: host
    healthcheck:
      test: curl --fail http://127.0.0.1:8000/api || exit 1
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 60s

  dashboard:
    image: ghcr.io/bcgov/cas-dash-e2e-frontend:${GITHUB_SHA}
    environment:
      CI: "true"
      PORT: 3000
      HOSTNAME: localhost
      NEXTAUTH_URL_INTERNAL: http://localhost:3000
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      API_URL: http://127.0.0.1:8000/api/
      KEYCLOAK_LOGIN_URL: ${KEYCLOAK_LOGIN_URL}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
    depends_on:
      backend:
        condition: service_healthy  # Wait for backend health check
    network_mode: host
    healthcheck:
      test: curl --fail http://127.0.0.1:3000 || exit 1
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 60s

  administration:
    image: ghcr.io/bcgov/cas-admin-frontend:${GITHUB_SHA}
    environment:
      PORT: 4001
      HOSTNAME: localhost
      NEXTAUTH_URL_INTERNAL: http://localhost:3000
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      API_URL: http://127.0.0.1:8000/api/
      KEYCLOAK_LOGIN_URL: ${KEYCLOAK_LOGIN_URL}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
    depends_on:
      backend:
        condition: service_healthy
    network_mode: host

  compliance:
    image: ghcr.io/bcgov/cas-compliance-frontend:${GITHUB_SHA}
    environment:
      PORT: 7000
      HOSTNAME: localhost
      NEXTAUTH_URL_INTERNAL: http://localhost:3000
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      API_URL: http://127.0.0.1:8000/api/
      KEYCLOAK_LOGIN_URL: ${KEYCLOAK_LOGIN_URL}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
    depends_on:
      backend:
        condition: service_healthy
    network_mode: host

  registration:
    image: ghcr.io/bcgov/cas-reg-frontend:${GITHUB_SHA}
    environment:
      PORT: 4000
      HOSTNAME: localhost
      NEXTAUTH_URL_INTERNAL: http://localhost:3000
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      API_URL: http://127.0.0.1:8000/api/
      KEYCLOAK_LOGIN_URL: ${KEYCLOAK_LOGIN_URL}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
    depends_on:
      backend:
        condition: service_healthy
    network_mode: host

  reporting:
    image: ghcr.io/bcgov/cas-rep-frontend:${GITHUB_SHA}
    environment:
      PORT: 5000
      HOSTNAME: localhost
      NEXTAUTH_URL_INTERNAL: http://localhost:3000
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      API_URL: http://127.0.0.1:8000/api/
      KEYCLOAK_LOGIN_URL: ${KEYCLOAK_LOGIN_URL}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
    depends_on:
      backend:
        condition: service_healthy
    network_mode: host

volumes:
  db:
    driver: local
