apiVersion: batch/v1
kind: CronJob
metadata:
  name: process-tasks
  labels: {{- include "cas-bciers.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "*/5 * * * *" # every 5 minutes
  concurrencyPolicy: Forbid  # Prevent overlapping executions
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 600
      template:
        metadata:
          labels: {{ include "cas-bciers.labels" . | nindent 12 }}
            component: job-with-database-access
        spec:
          activeDeadlineSeconds: 600
          restartPolicy: Never
          serviceAccountName: deployer
          containers:
          - name: process-tasks
            image: "{{ .Values.backend.image.repository }}:{{ .Values.defaultImageTag | default .Values.backend.image.tag }}"
            imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
            env:
              {{- include "cas-bciers.backendEnvVars" . | nindent 14 }}
            command:
              - /usr/bin/env
              - bash
              - -c
              - |
                set -euo pipefail;
                .venv/bin/python manage.py sync_tasks
                .venv/bin/python manage.py run_tasks
