{{- $gcsSecret := (randAlphaNum 32) | b64enc | quote }}
{{- $secretName := printf "gcp-%s-%s" .Values.sourceNamespace "obps-backups-service-account-key" }}

{{- $secret := (lookup "v1" "Secret" .Values.sourceNamespace $secretName ) }}
{{- if $secret }}
{{- $gcsSecret = index $secret.data "credentials.json" }}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels: {{ include "cas-obps-postgres-migration-test.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
type: Opaque
data:
  credentials: {{ $gcsSecret }}
