{{- if (hasSuffix "-dev" .Release.Namespace)}}

apiVersion: batch/v1
kind: Job
metadata:
  labels:
{{- include "cas-registration.labels" . | nindent 4 }}
    component: backend
  name: {{ template "cas-registration.fullname" . }}-load-dev-data
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-upgrade, post-install
spec:
  template:
    metadata:
      name: {{ template "cas-registration.fullname" . }}-load-dev-data
    spec:
      activeDeadlineSeconds: 300
      containers:
        - name:  {{ template "cas-registration.fullname" . }}-load-dev-data
          image: curlimages/curl
          command:
            - /bin/sh
            - -ec
            - "curl https://cas-reg-backend-dev.apps.silver.devops.gov.bc.ca/api/registration/test-setup"
      restartPolicy: Never
{{ end }}
