apiVersion: v1
kind: ConfigMap
metadata:
  name: terraform-modules
  namespace: {{ .Release.Namespace }}
data:
{{- range $path, $data := .Files.Glob "terraform/**.tf" }}
{{ $path | base | indent 2 }}: >-
{{- $data | toString | nindent 4 }}
{{ end }}
