name: "Set up registration dev environment"
description: "Sets up asdf and configures the cache"
runs:
  using: composite
  steps:
    - name: asdf setup
      uses: asdf-vm/actions/setup@v1
    - name: Install server dev tools
      working-directory: ./bc_obps
      shell: bash
      run: |
        make stop_pg
        make install_backend_asdf_tools
        make start_pg
        make create_db
    - uses: actions/cache@v3
      id: asdf-cache
      with:
        path: |
          ~/.asdf
        key: ${{ runner.os }}-asdf-cache-${{ hashFiles('.tool-versions') }}
    - uses: actions/cache@v3
      id: yarn-cache
      with:
        path: |
          ~/.cache/yarn
          ./client/node_modules
        key: ${{ runner.os }}-yarn-cache-${{ hashFiles('client/yarn.lock') }}-v2
    - name: Set up python
      id: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9.16"
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
    #----------------------------------------------
    # install dependencies if cache does not exist
    #----------------------------------------------
    - name: Install dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: poetry install --no-interaction --no-root
      working-directory: ./bc_obps
      shell: bash
