name: "Set up registration dev environment"
description: "Sets up asdf and configures the cache"
runs:
  using: composite
  steps:
    - name: asdf setup
      uses: asdf-vm/actions/setup@v3
    - uses: actions/cache@v4
      id: asdf-cache-bciers
      with:
        path: |
          ~/.asdf
          ./.tool-versions
        key: ${{ runner.os }}-asdf-cache-${{ hashFiles('.tool-versions') }}
    - uses: actions/cache@v4
      id: asdf-cache-backend
      with:
        path: |
          ~/.asdf
          ./bc_obps/.tool-versions
        key: ${{ runner.os }}-asdf-cache-backend-${{ hashFiles('bc_obps/.tool-versions') }}
    - name: yarn modern
      shell: bash
      run: |
        corepack enable
    - name: yarn cache
      id: yarn-cache
      uses: ./.github/actions/yarn-cache
    - name: Debug - Cache status
      shell: bash
      run: |
        echo "=== CACHE STATUS ==="
        echo "asdf-cache-bciers hit: ${{ steps.asdf-cache-bciers.outputs.cache-hit }}"
        echo "asdf-cache-backend hit: ${{ steps.asdf-cache-backend.outputs.cache-hit }}"
        echo "yarn-cache hit: ${{ steps.yarn-cache.outputs.cache-hit }}"
        echo ""
        echo "=== TOOL-VERSIONS FILES ==="
        echo "Root .tool-versions:"
        cat .tool-versions || echo "File not found"
        echo ""
        echo "bc_obps/.tool-versions:"
        cat bc_obps/.tool-versions || echo "File not found"
    - name: Install root asdf tools
      shell: bash
      run: |
        cat .tool-versions | cut -f 1 -d ' ' | xargs -n 1 asdf plugin add || true
        asdf plugin update --all
        asdf install
        asdf reshim
        echo ""
        echo "=== DEBUG - Root tool versions after installation ==="
        echo "Expected Node.js version from .tool-versions:"
        grep nodejs .tool-versions || echo "Not found"
        echo "Actual Node.js version:"
        node --version || echo "Node.js not found in PATH"
        echo "Node.js path:"
        which node || echo "Node.js not found in PATH"
        echo ""
        echo "Expected Python version from .tool-versions:"
        grep python .tool-versions || echo "Not found"
        echo "Actual Python version:"
        python --version || echo "Python not found in PATH"
        echo "Python path:"
        which python || echo "Python not found in PATH"
    - name: Install backend asdf tools
      working-directory: ./bc_obps
      shell: bash
      run: |
        cat .tool-versions | cut -f 1 -d ' ' | xargs -n 1 asdf plugin add || true
        asdf plugin update --all
        MAKELEVEL=0 POSTGRES_EXTRA_CONFIGURE_OPTIONS='--with-libxml' asdf install
        asdf reshim
        echo ""
        echo "=== DEBUG - Backend tool versions after installation ==="
        echo "Expected Python version from bc_obps/.tool-versions:"
        grep python .tool-versions || echo "Not found"
        echo "Actual Python version:"
        python --version || echo "Python not found in PATH"
        echo "Python path:"
        which python || echo "Python not found in PATH"
        echo ""
        echo "Expected Poetry version from bc_obps/.tool-versions:"
        grep poetry .tool-versions || echo "Not found"
        echo "Actual Poetry version:"
        poetry --version || echo "Poetry not found in PATH"
        echo "Poetry path:"
        which poetry || echo "Poetry not found in PATH"
        echo ""
        echo "asdf current versions:"
        asdf current || echo "asdf current failed"
        echo ""
        echo "=== Configure Poetry to use asdf Python ==="
        poetry config virtualenvs.create true
        poetry config virtualenvs.in-project true
        poetry config virtualenvs.prefer-active-python true
    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v4
      with:
        path: ./bc_obps/.venv
        key: venv-${{ runner.os }}-${{ hashFiles('bc_obps/.tool-versions') }}-${{ hashFiles('**/poetry.lock') }}
    - name: Debug - Poetry venv cache status
      shell: bash
      run: |
        echo "=== POETRY VENV CACHE STATUS ==="
        echo "venv cache hit: ${{ steps.cached-poetry-dependencies.outputs.cache-hit }}"
        echo "venv cache key: venv-${{ runner.os }}-${{ hashFiles('bc_obps/.tool-versions') }}-${{ hashFiles('**/poetry.lock') }}"
        if [ -d "./bc_obps/.venv" ]; then
          echo "venv directory exists"
          echo "venv Python version:"
          ./bc_obps/.venv/bin/python --version || echo "Could not get venv Python version"
          echo ""
          echo "Expected Python version from bc_obps/.tool-versions:"
          grep python ./bc_obps/.tool-versions || echo "Not found"
          echo ""
          echo "Checking if venv Python matches expected version..."
          VENV_PYTHON_VERSION=$(./bc_obps/.venv/bin/python --version 2>&1 | cut -d' ' -f2)
          EXPECTED_PYTHON_VERSION=$(grep python ./bc_obps/.tool-versions | cut -d' ' -f2)
          if [ "$VENV_PYTHON_VERSION" != "$EXPECTED_PYTHON_VERSION" ]; then
            echo "WARNING: venv Python version ($VENV_PYTHON_VERSION) does not match expected ($EXPECTED_PYTHON_VERSION)"
            echo "Removing venv to force recreation with correct Python version..."
            rm -rf ./bc_obps/.venv
          else
            echo "✓ venv Python version matches expected version"
          fi
        else
          echo "venv directory does not exist"
        fi
    #----------------------------------------------
    # install dependencies if cache does not exist
    #----------------------------------------------
    - name: Install dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      working-directory: ./bc_obps
      shell: bash
      run: |
        echo "=== Verifying Python version before Poetry install ==="
        echo "Python version:"
        python --version
        echo "Python path:"
        which python
        echo ""
        echo "Installing dependencies with Poetry..."
        poetry env use python
        poetry install --no-interaction --no-root
    - name: Install dependencies for PostgreSQL build
      working-directory: ./bc_obps
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libreadline-dev uuid-dev
    - name: Install server dev tools
      working-directory: ./bc_obps
      shell: bash
      run: |
        make start_pg
        make create_db
    - name: Install yarn dependencies
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: yarn install --immutable
      working-directory: ./bciers
      shell: bash
    - name: Debug - Final tool versions verification
      shell: bash
      run: |
        echo "=== FINAL VERIFICATION ==="
        echo "Node.js version:"
        node --version || echo "Node.js not found"
        echo "Node.js path:"
        which node || echo "Node.js not found"
        echo ""
        echo "Python version (from root):"
        python --version || echo "Python not found"
        echo "Python path:"
        which python || echo "Python not found"
        echo ""
        echo "Python version (from bc_obps context):"
        (cd bc_obps && python --version) || echo "Python not found"
        echo "Python path:"
        (cd bc_obps && which python) || echo "Python not found"
        echo ""
        echo "Poetry version:"
        (cd bc_obps && poetry --version) || echo "Poetry not found"
        echo "Poetry path:"
        (cd bc_obps && which poetry) || echo "Poetry not found"
        echo ""
        echo "Poetry env info:"
        (cd bc_obps && poetry env info) || echo "Poetry env info failed"
        echo ""
        echo "All asdf installed versions:"
        asdf list || echo "asdf list failed"
