name: "Set up registration dev environment"
description: "Sets up asdf and configures the cache"
runs:
  using: composite
  steps:
    - name: Get Node.js version from .tool-versions
      id: node-version
      shell: bash
      run: |
        NODE_VERSION=$(grep "^nodejs" .tool-versions | awk '{print $2}')
        echo "version=$NODE_VERSION" >> $GITHUB_OUTPUT
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ steps.node-version.outputs.version }}
    - name: asdf setup
      uses: asdf-vm/actions/setup@v4
    - uses: actions/cache@v4
      id: asdf-cache
      with:
        path: ~/.asdf
        key: ${{ runner.os }}-asdf-cache-${{ hashFiles('bc_obps/.tool-versions') }}
        restore-keys: |
          ${{ runner.os }}-asdf-cache-
    - name: Check asdf cache status
      shell: bash
      run: |
        if [ "${{ steps.asdf-cache.outputs.cache-hit }}" == "true" ]; then
          echo "✅ asdf cache HIT - skipping tool installation"
        else
          echo "❌ asdf cache MISS - will install tools (this may take 5-7 minutes for Postgres compilation)"
        fi
    - name: Get Python version from .tool-versions
      id: python-version
      shell: bash
      run: |
        PYTHON_VERSION=$(grep "^python" bc_obps/.tool-versions | awk '{print $2}')
        echo "version=$PYTHON_VERSION" >> $GITHUB_OUTPUT
    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v4
      with:
        path: ./bc_obps/.venv
        key: venv-${{ runner.os }}-python-${{ steps.python-version.outputs.version }}-${{ hashFiles('bc_obps/poetry.lock') }}
        restore-keys: |
          venv-${{ runner.os }}-python-${{ steps.python-version.outputs.version }}-
    - name: Check poetry cache status
      shell: bash
      run: |
        if [ "${{ steps.cached-poetry-dependencies.outputs.cache-hit }}" == "true" ]; then
          echo "✅ Poetry venv cache HIT - skipping dependency installation"
        else
          echo "❌ Poetry venv cache MISS - will install dependencies (this may take a few minutes)"
        fi
    - name: yarn modern
      shell: bash
      run: |
        corepack enable
    - name: yarn cache
      uses: ./.github/actions/yarn-cache
    - name: Install yarn dependencies
      run: yarn install --immutable
      working-directory: ./bciers
      shell: bash
    - name: Install dependencies for PostgreSQL build
      working-directory: ./bc_obps
      shell: bash
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y --no-install-recommends libreadline-dev uuid-dev
    - name: Install backend tool versions (Python, Poetry, Postgres)
      if: steps.asdf-cache.outputs.cache-hit != 'true'
      working-directory: ./bc_obps
      shell: bash
      run: |
        make install_backend_asdf_tools
    - name: Start PostgreSQL and create database
      working-directory: ./bc_obps
      shell: bash
      run: |
        make start_pg
        make create_db
    - name: Install Poetry dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      working-directory: ./bc_obps
      shell: bash
      run: |
        poetry install --no-interaction --no-root
