name: "Set up registration dev environment"
description: "Full asdf + Node + Yarn + Poetry + Postgres setup with proper caching"
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - name: Install asdf CLI
      uses: asdf-vm/actions/install@v4

    - name: Cache asdf tools (root)
      id: asdf-cache-root
      uses: actions/cache@v4
      with:
        path: ~/.asdf
        key: asdf-${{ runner.os }}-root-${{ hashFiles('.tool-versions') }}-${{ hashFiles('**/plugins/*.git') }}
        restore-keys: |
          asdf-${{ runner.os }}-root-

    - name: Cache asdf tools
      id: asdf-cache-backend
      uses: actions/cache@v4
      with:
        path: ~/.asdf # Same dir, but different key for subdir
        key: asdf-${{ runner.os }}-backend-${{ hashFiles('bc_obps/.tool-versions') }}-${{ hashFiles('**/plugins/*.git') }}
        restore-keys: |
          asdf-${{ runner.os }}-backend-

    - name: Install root asdf tools + reshim
      if: steps.asdf-cache-root.outputs.cache-hit != 'true'
      shell: bash
      run: |
        asdf install
        asdf reshim

    - name: Reshim root tools (always, for cache hits)
      shell: bash
      run: asdf reshim

    - name: Install backend asdf tools + reshim
      if: steps.asdf-cache-backend.outputs.cache-hit != 'true'
      working-directory: ./bc_obps
      shell: bash
      run: |
        asdf install
        asdf reshim

    - name: Reshim backend tools (always)
      working-directory: ./bc_obps
      shell: bash
      run: asdf reshim

    - name: Save asdf cache
      if: always() # Save even on failure for debugging
      uses: actions/cache@v4
      with:
        path: ~/.asdf
        key: asdf-${{ runner.os }}-combined-${{ hashFiles('**/.tool-versions') }}-${{ hashFiles('**/plugins/*.git') }}

    - uses: ./.github/actions/yarn-cache

    - name: Install Yarn dependencies (bciers)
      working-directory: ./bciers
      shell: bash
      run: |
        corepack enable
        yarn install --immutable --frozen-lockfile

    - name: Get Python version from bc_obps/.tool-versions
      id: python-version
      shell: bash
      working-directory: ./bc_obps
      run: |
        VERSION=$(grep "^python" .tool-versions | awk '{print $2}')
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Cache Poetry virtual environment
      id: poetry-cache
      uses: actions/cache@v4
      with:
        path: ./bc_obps/.venv
        key: venv-${{ runner.os }}-python-${{ steps.python-version.outputs.version }}-${{ hashFiles('bc_obps/poetry.lock') }}
        restore-keys: |
          venv-${{ runner.os }}-python-${{ steps.python-version.outputs.version }}-

    - name: Configure Poetry + install deps (only on miss)
      if: steps.poetry-cache.outputs.cache-hit != 'true'
      working-directory: ./bc_obps
      shell: bash
      run: |
        poetry config virtualenvs.in-project true
        poetry install --no-interaction --no-root

    - name: Configure Poetry venv (always – ensure correct Python)
      working-directory: ./bc_obps
      shell: bash
      run: |
        poetry config virtualenvs.in-project true
        poetry env use $(asdf which python) || true

    - name: Start PostgreSQL and create database
      working-directory: ./bc_obps
      shell: bash
      run: |
        make start_pg
        make create_db

    - name: Cache summary
      if: always()
      shell: bash
      run: |
        echo "asdf root cache: ${{ steps.asdf-cache-root.outputs.cache-hit == 'true' && 'HIT' || 'MISS' }}"
        echo "asdf backend cache: ${{ steps.asdf-cache-backend.outputs.cache-hit == 'true' && 'HIT' || 'MISS' }}"
        echo "Poetry .venv cache: ${{ steps.poetry-cache.outputs.cache-hit == 'true' && 'HIT' || 'MISS' }}"
