name: "Set up registration dev environment"
description: "Sets up asdf and configures the cache"
runs:
  using: composite
  steps:
    - name: asdf setup
      uses: asdf-vm/actions/setup@v4
    - uses: actions/cache@v4
      id: asdf-cache
      with:
        path: ~/.asdf
        key: ${{ runner.os }}-asdf-cache-${{ hashFiles('.tool-versions', 'bc_obps/.tool-versions') }}
    - name: Install root tool versions (Node.js, etc.)
      if: steps.asdf-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git || true
        if [ -f ~/.asdf/plugins/nodejs/bin/import-release-team-keyring ]; then
          bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring
        fi
        asdf plugin update --all || true
        asdf install
        asdf reshim
    - name: Verify Node.js version
      shell: bash
      run: |
        echo "Node.js version: $(node --version)"
        echo "Node.js path: $(which node)"
        if ! node --version | grep -q "v24"; then
          echo "Warning: Node.js version is not v24. Expected v24.11.1 from .tool-versions"
          exit 1
        fi
    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v4
      with:
        path: ./bc_obps/.venv
        key: venv-${{ runner.os }}-python-3.12.11-${{ hashFiles('bc_obps/poetry.lock') }}
    - name: yarn modern
      shell: bash
      run: |
        corepack enable
    - name: yarn cache
      uses: ./.github/actions/yarn-cache
    - name: Install dependencies for PostgreSQL build
      working-directory: ./bc_obps
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libreadline-dev uuid-dev
    - name: Install backend tool versions (Python, Poetry, Postgres)
      if: steps.asdf-cache.outputs.cache-hit != 'true'
      working-directory: ./bc_obps
      shell: bash
      run: |
        make install_backend_asdf_tools
    - name: Start PostgreSQL and create database
      working-directory: ./bc_obps
      shell: bash
      run: |
        make start_pg
        make create_db
    - name: Install Poetry dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      working-directory: ./bc_obps
      shell: bash
      run: |
        poetry install --no-interaction --no-root
    - name: Install yarn dependencies
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: yarn install --immutable
      working-directory: ./bciers
      shell: bash
