name: "Set up registration dev environment"
description: "Sets up asdf and configures the cache"
runs:
  using: composite
  steps:
    - name: Get Node.js version from .tool-versions
      id: node-version
      shell: bash
      run: |
        NODE_VERSION=$(grep "^nodejs" .tool-versions | awk '{print $2}')
        echo "version=$NODE_VERSION" >> $GITHUB_OUTPUT
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ steps.node-version.outputs.version }}
    - name: asdf setup
      uses: asdf-vm/actions/setup@v4
    - uses: actions/cache@v4
      id: asdf-cache
      with:
        path: ~/.asdf
        key: ${{ runner.os }}-asdf-cache-${{ hashFiles('bc_obps/.tool-versions') }}
        restore-keys: |
          ${{ runner.os }}-asdf-cache-
    - name: Check asdf cache status
      shell: bash
      run: |
        if [ "${{ steps.asdf-cache.outputs.cache-hit }}" == "true" ]; then
          echo "✅ asdf cache HIT - skipping tool installation"
        else
          echo "❌ asdf cache MISS - will install tools (this may take 5-7 minutes for Postgres compilation)"
        fi
    - name: Get Python version from .tool-versions
      id: python-version
      shell: bash
      run: |
        PYTHON_VERSION=$(grep "^python" bc_obps/.tool-versions | awk '{print $2}')
        echo "version=$PYTHON_VERSION" >> $GITHUB_OUTPUT
    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v4
      with:
        path: ./bc_obps/.venv
        key: venv-${{ runner.os }}-python-${{ steps.python-version.outputs.version }}-${{ hashFiles('bc_obps/poetry.lock') }}
        restore-keys: |
          venv-${{ runner.os }}-python-${{ steps.python-version.outputs.version }}-
    - name: Check poetry cache status
      shell: bash
      run: |
        if [ "${{ steps.cached-poetry-dependencies.outputs.cache-hit }}" == "true" ]; then
          echo "✅ Poetry venv cache HIT - skipping dependency installation"
        else
          echo "❌ Poetry venv cache MISS - will install dependencies (this may take a few minutes)"
        fi
    - name: yarn modern
      shell: bash
      run: |
        corepack enable
    - name: yarn cache
      uses: ./.github/actions/yarn-cache
    - name: Install yarn dependencies
      shell: bash
      working-directory: ./bciers
      run: |
        echo "Installing yarn dependencies (this will create state files even if cache hit)..."
        # Always run yarn install to ensure state files are created
        # Even when cache hits, yarn needs to set up its internal state
        yarn install --immutable || {
          echo "yarn install failed, retrying..."
          yarn install --immutable
        }
        echo "Verifying yarn installation..."
        yarn --version
        echo "Verifying yarn can find packages..."
        yarn happo --version || {
          echo "ERROR: Happo not found after yarn install"
          echo "Checking if node_modules exists..."
          ls -la node_modules/.bin/happo || echo "Happo binary not found in node_modules"
          exit 1
        }
        echo "✅ Yarn installation verified successfully"
    - name: Install dependencies for PostgreSQL build
      working-directory: ./bc_obps
      shell: bash
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y --no-install-recommends libreadline-dev uuid-dev
    - name: Install backend tool versions (Python, Poetry, Postgres)
      if: steps.asdf-cache.outputs.cache-hit != 'true'
      working-directory: ./bc_obps
      shell: bash
      run: |
        make install_backend_asdf_tools
    - name: Reshim asdf tools (needed even when cache hits)
      working-directory: ./bc_obps
      shell: bash
      run: |
        echo "Reshimming asdf to ensure tools are available..."
        asdf reshim
        echo "Verifying Python is available:"
        asdf which python || echo "Warning: Python not found via asdf"
        python --version || echo "Warning: python command not found"
    - name: Start PostgreSQL and create database
      working-directory: ./bc_obps
      shell: bash
      run: |
        make start_pg
        make create_db
    - name: Configure Poetry to use asdf Python
      working-directory: ./bc_obps
      shell: bash
      run: |
        # Get asdf Python path
        ASDF_PYTHON=$(asdf which python)
        if [ -z "$ASDF_PYTHON" ]; then
          echo "ERROR: asdf Python not found"
          echo "Checking asdf Python installation:"
          asdf list python || echo "Python not installed via asdf"
          exit 1
        fi
        echo "Configuring Poetry to use asdf Python: $ASDF_PYTHON"
        echo "Python version: $($ASDF_PYTHON --version)"
        # Ensure asdf Python is first in PATH
        export PATH="$(asdf where python)/bin:$PATH"
        echo "After PATH update, python is: $(which python)"
        echo "Python version in PATH: $(python --version)"
        # Configure Poetry to use in-project virtualenvs (easier to control)
        poetry config virtualenvs.in-project true
        # Set POETRY_PYTHON to force Poetry to use the correct Python
        export POETRY_PYTHON="$ASDF_PYTHON"
        echo "Final PATH check - python is: $(which python)"
        echo "Python version: $(python --version)"
        # Get expected Python version from .tool-versions
        EXPECTED_VERSION=$(grep "^python" .tool-versions | awk '{print $2}')
        # Check if .venv exists (from cache) and verify its Python version
        if [ -d ".venv" ]; then
          echo ".venv exists, checking Python version..."
          VENV_PYTHON_VERSION=$(.venv/bin/python --version 2>&1 | awk '{print $2}')
          if [ "$VENV_PYTHON_VERSION" != "$EXPECTED_VERSION" ]; then
            echo "WARNING: Cached .venv uses Python $VENV_PYTHON_VERSION, expected $EXPECTED_VERSION"
            echo "Removing cached .venv and recreating with correct Python..."
            rm -rf .venv
          else
            echo "✅ Cached .venv uses correct Python version: $VENV_PYTHON_VERSION"
          fi
        fi
        # Create virtualenv manually using asdf Python if it doesn't exist or was removed
        if [ ! -d ".venv" ]; then
          echo "Creating virtualenv manually with asdf Python..."
          "$ASDF_PYTHON" -m venv .venv
          echo "Virtualenv created at: .venv"
        fi
        echo "Virtualenv Python version: $(.venv/bin/python --version)"
        # Configure Poetry to use the virtualenv
        poetry env use .venv/bin/python
        # Verify the virtualenv uses the correct Python
        poetry env info
    - name: Install Poetry dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      working-directory: ./bc_obps
      shell: bash
      run: |
        # Ensure asdf Python is in PATH when installing dependencies
        export PATH="$(asdf where python)/bin:$PATH"
        export POETRY_PYTHON="$(asdf which python)"
        echo "Using Python: $POETRY_PYTHON"
        poetry install --no-interaction --no-root
