import FieldTemplate from "@bciers/components/form/fields/FieldTemplate";
import {
  emissionsOnlyUiSchema,
  sourceSubTypeWithoutFuelUiSchema,
  fuelsFieldsUiSchema,
  sourceTypeCheckboxUiSchema,
} from "./common";

const uiSchema = {
  "ui:FieldTemplate": FieldTemplate,
  "ui:classNames": "form-heading-label",
  associatedGasFlaring: sourceTypeCheckboxUiSchema,
  associatedGasVenting: sourceTypeCheckboxUiSchema,
  blowdownVenting: sourceTypeCheckboxUiSchema,
  dehydratorVenting: sourceTypeCheckboxUiSchema,
  drillingFlaring: sourceTypeCheckboxUiSchema,
  drillingVenting: sourceTypeCheckboxUiSchema,
  enhancedOilRecoveryHydrocarbonLiquids: sourceTypeCheckboxUiSchema,
  enhancedOilrecoveryInjectionPumpBlowdowns: sourceTypeCheckboxUiSchema,
  equipmentLeaksDetectedLearkerEmissionFactorMethods:
    sourceTypeCheckboxUiSchema,
  flaringStacks: sourceTypeCheckboxUiSchema,
  hydraulicFracturingFlaring: sourceTypeCheckboxUiSchema,
  naturalGasPneumatciHighBleedDeviceVenting: sourceTypeCheckboxUiSchema,
  naturalGasPneumaticIntermittentBleedDeviceVenting: sourceTypeCheckboxUiSchema,
  naturalGasPneumaticLowBleedDeviceVenting: sourceTypeCheckboxUiSchema,
  naturalGasPneumaticPumpVenting: sourceTypeCheckboxUiSchema,
  otherFugitiveSources: sourceTypeCheckboxUiSchema,
  otherVentingSources: sourceTypeCheckboxUiSchema,
  populationCountSources: sourceTypeCheckboxUiSchema,
  producedWaterDissolvedCarbonDioxideMethane: sourceTypeCheckboxUiSchema,
  releasesFromTanksUsedForStorageProductionProcessing:
    sourceTypeCheckboxUiSchema,
  thirdPartyLineHitsWithReleaseOfGas: sourceTypeCheckboxUiSchema,
  transmissionStorageTanks: sourceTypeCheckboxUiSchema,
  wellTestingFlaring: sourceTypeCheckboxUiSchema,
  wellTestingVenting: sourceTypeCheckboxUiSchema,
  wellVentingDuringWellCompletionsHydraulicFracturing:
    sourceTypeCheckboxUiSchema,
  wellVentingForLiquidsUnloading: sourceTypeCheckboxUiSchema,
  sourceTypes: {
    "ui:FieldTemplate": FieldTemplate,
    "ui:options": {
      label: false,
    },
    associatedGasFlaring: fuelsFieldsUiSchema,
    associatedGasVenting: emissionsOnlyUiSchema,
    blowdownVenting: emissionsOnlyUiSchema,
    dehydratorVenting: emissionsOnlyUiSchema,
    drillingFlaring: fuelsFieldsUiSchema,
    drillingVenting: emissionsOnlyUiSchema,
    enhancedOilRecoveryHydrocarbonLiquids: emissionsOnlyUiSchema,
    enhancedOilrecoveryInjectionPumpBlowdowns: emissionsOnlyUiSchema,
    equipmentLeaksDetectedLearkerEmissionFactorMethods: emissionsOnlyUiSchema,
    flaringStacks: fuelsFieldsUiSchema,
    hydraulicFracturingFlaring: fuelsFieldsUiSchema,
    naturalGasPneumatciHighBleedDeviceVenting: fuelsFieldsUiSchema,
    naturalGasPneumaticIntermittentBleedDeviceVenting: fuelsFieldsUiSchema,
    naturalGasPneumaticLowBleedDeviceVenting: fuelsFieldsUiSchema,
    naturalGasPneumaticPumpVenting: fuelsFieldsUiSchema,
    otherFugitiveSources: sourceSubTypeWithoutFuelUiSchema,
    otherVentingSources: emissionsOnlyUiSchema,
    populationCountSources: emissionsOnlyUiSchema,
    producedWaterDissolvedCarbonDioxideMethane: emissionsOnlyUiSchema,
    releasesFromTanksUsedForStorageProductionProcessing: emissionsOnlyUiSchema,
    thirdPartyLineHitsWithReleaseOfGas: emissionsOnlyUiSchema,
    transmissionStorageTanks: emissionsOnlyUiSchema,
    wellTestingFlaring: fuelsFieldsUiSchema,
    wellTestingVenting: emissionsOnlyUiSchema,
    wellVentingDuringWellCompletionsHydraulicFracturing: emissionsOnlyUiSchema,
    wellVentingForLiquidsUnloading: emissionsOnlyUiSchema,
  },
};

export default uiSchema;
