name: "Build and push Docker image for Nx frontend app in /bciers directory"
description: "Reusable action to build and push a Docker image for an Nx app in the /bciers directory"

inputs:
  project:
    description: "Nx project name"
    required: true
  image_url:
    description: "Docker image URL"
    required: true
  github_token:
    description: "GitHub token"
    required: true
  host_administration:
    description: "Host for administration - only used for e2e CI builds"
    required: false
  host_coam:
    description: "Host for COAM - only used for e2e CI builds"
    required: false
  host_registration:
    description: "Host for registration - only used for e2e CI builds"
    required: false
  host_reporting:
    description: "Host for reporting - only used for e2e CI builds"
    required: false

runs:
  using: composite
  steps:
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.image_url }}
        tags: |
          type=sha,format=long,prefix=
          latest
          type=ref,event=pr
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.github_token }}
    - name: Install dependencies
      shell: bash
      run: |
        corepack enable
        yarn install --immutable
        cd bciers && yarn install --immutable
    - uses: actions/setup-node@v4
    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      uses: nrwl/nx-set-shas@v4
      with:
        main-branch-name: "develop"
    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-bciers-${{ inputs.project }}${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-bciers-${{ inputs.project }}
    - name: Build images
      shell: bash
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_PUSH: true
        INPUT_TAGS: ${{ steps.meta.outputs.tags }}
        INPUT_LABELS: ${{ steps.meta.output.labels }}
        INPUT_CACHE_FROM: type=local,src=/tmp/.buildx-cache
        INPUT_CACHE_TO: type=local,dest=/tmp/.buildx-cache-new
        HOST_ADMINISTRATION: ${{ inputs.host_administration }}
        HOST_COAM: ${{ inputs.host_coam }}
        HOST_REGISTRATION: ${{ inputs.host_registration }}
        HOST_REPORTING: ${{ inputs.host_reporting }}

      run: |
        npx nx container ${{ inputs.project }} --skip-nx-cache
      working-directory: ./bciers
      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
    - name: Move cache
      shell: bash
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
