name: "Local Registration app run"
description: "Runs the Registration app locally"

inputs:
  django_secret_key:
    description: "Django secret key"
    required: true
  keycloak_client_id:
    description: "Identifier for keycloak dev client"
    required: true
  keycloak_client_secret:
    description: "Keycloak client secret"
    required: true
  nextauth_secret:
    description: "NextAuth client secret"
    required: true
  image_url:
    description: "Docker image URL minus the tag which will be the pull request sha"
    required: true

runs:
  using: composite
  steps:
    - name: start backend
      uses: ./.github/actions/run-backend
      with:
        django_secret_key: ${{ inputs.django_secret_key }}
    - name: start frontend
      shell: bash
      run: docker run -d --network=host -e "NEXTAUTH_URL_INTERNAL=http://localhost:3000/" -e "NEXTAUTH_URL=http://localhost:3000/" -e "NEXTAUTH_SECRET=${{ inputs.nextauth_secret }}" -e "API_URL=http://127.0.0.1:8000/api/" -e "KEYCLOAK_LOGIN_URL=https://dev.loginproxy.gov.bc.ca/auth/realms/standard" -e "KEYCLOAK_CLIENT_SECRET=${{ inputs.keycloak_client_secret }}" -e "KEYCLOAK_CLIENT_ID=${{ inputs.keycloak_client_id }}" ${{ inputs.image_url }}:${{ github.sha }}
