apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "cas-registration.fullname" . }}-frontend
  labels:
{{ include "cas-registration.labels" . | indent 4 }}
  annotations:
    haproxy.router.openshift.io/balance: roundrobin

spec:
  host: {{ .Values.frontend.route.host }}
  port:
    targetPort: {{ template "cas-registration.fullname" . }}-frontend
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name:  {{ template "cas-registration.fullname" . }}-frontend
    weight: 100
