{{- $nextauthSecret := (randAlphaNum 60) | b64enc | quote }}
{{- $secretName := print (include "cas-registration.fullname" .) "-frontend" }}

{{- $existingNextauthSecret := (lookup "v1" "Secret" .Release.Namespace $secretName ) }}
{{- if $existingNextauthSecret }}
{{- $nextauthSecret = index $existingNextauthSecret.data "nextauth-secret-key" }}
{{- end -}}


apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-frontend
  labels: {{ include "cas-registration.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
type: Opaque
data:
 nextauth-secret-key: {{ $nextauthSecret }}
