{{- $nextAuthSecret := (randAlphaNum 32) | b64enc | quote }}
{{- $secretName := "cas-registration-nextauth" }}

{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName ) }}
{{- if $secret }}
{{- $nextAuthSecret = index $secret.data "nextauth-secret" }}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels: {{ include "cas-registration.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
type: Opaque
data:
  nextauth-secret: {{ $nextAuthSecret }}
