<<<<<<< HEAD
{{- $nextauthSecret := (randAlphaNum 60) | b64enc | quote }}
{{- $secretName := print (include "cas-registration.fullname" .) "-frontend" }}

{{- $existingNextauthSecret := (lookup "v1" "Secret" .Release.Namespace $secretName ) }}
{{- if $existingNextauthSecret }}
{{- $nextauthSecret = index $existingNextauthSecret.data "nextauth-secret-key" }}
{{- end -}}


apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-frontend
=======
{{- $nextAuthSecret := (randAlphaNum 32) | b64enc | quote }}
{{- $secretName := "cas-registration-nextauth" }}

{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName ) }}
{{- if $secret }}
{{- $nextAuthSecret = index $secret.data "nextauth-secret" }}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
>>>>>>> chore: create secret & add env vars for auth
  labels: {{ include "cas-registration.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
type: Opaque
data:
<<<<<<< HEAD
 nextauth-secret-key: {{ $nextauthSecret }}
=======
  nextauth-secret: {{ $nextAuthSecret }}
>>>>>>> chore: create secret & add env vars for auth
