apiVersion: batch/v1
kind: Job
metadata:
  name: backend-migration-job
spec:
  template:
    spec:
      containers:
        - name: migration-runner
          image: "{{ .Values.backend.image.tag }}"
          command: ["python", "manage.py", "migrate"]
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secrets
      restartPolicy: Never
