# Generated by Django 5.1.15 on 2026-02-14 01:06

from django.db import migrations
from django.core.management import call_command


# rls.migrations.0001_rls_role_setup
def init_roles(apps, _):
    call_command("init_roles")


def reverse_init_roles(apps, _):
    call_command("init_roles", "--reverse")


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(
            code=init_roles,
            reverse_code=reverse_init_roles,
        ),
    ]
