# Generated by Django 5.0.11 on 2025-01-25 00:29
import logging
from django.core.management import call_command
from django.db import migrations

logger = logging.getLogger(__name__)


def init_roles(apps, _):
    call_command("init_roles")


def reverse_init_roles(apps, _):
    call_command("init_roles", "--reverse")


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.RunPython(init_roles, reverse_init_roles),
    ]
