# Generated by Django 5.0.8 on 2024-12-04 21:33

from django.db import migrations
from django.db import connection


def init_roles(apps, schema_monitor):
    with connection.cursor() as cursor:
        cursor.execute(
            """\
          select role_name from erc.app_role;
          """
        )
        roles = cursor.fetchall()
        for role in roles:
            cursor.execute(f'create role "{role[0]}" ')
            cursor.execute(f'grant usage on schema erc to "{role[0]}" ')


def reverse_init_roles(apps, schema_monitor):
    with connection.cursor() as cursor:
        cursor.execute(
            """\
          select role_name from erc.app_role;
          """
        )
        roles = cursor.fetchall()
        for role in roles:
            cursor.execute(f'revoke usage on schema erc from "{role[0]}" ')
            cursor.execute(f'drop role "{role[0]}" ')


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0025_V1_15_0'),
    ]

    operations = [migrations.RunPython(init_roles, reverse_init_roles)]
