# Generated by Django 5.0.13 on 2025-03-17 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rls', '0001_rls_role_setup'),
    ]

    operations = []
