# Generated by Django 5.0.13 on 2025-03-17 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rls', '0002_V2_0_0'),
    ]

    operations = []
