# Generated by Django 5.0.13 on 2025-03-27 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rls', '0003_V2_0_1'),
    ]

    operations = []
