# Generated by Django 5.0.14 on 2025-05-05 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rls', '0007_V3_0_0'),
    ]

    operations = []
