# Generated by Django 5.0.14 on 2025-05-14 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rls', '0008_V3_1_0'),
    ]

    operations = []
