# Generated by Django 5.0.14 on 2025-05-29 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rls', '0011_V3_3_0'),
    ]

    operations = []
