# Generated by Django 5.0.14 on 2025-05-30 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rls', '0012_V3_4_1'),
    ]

    operations = []
