# Generated by Django 5.1.10 on 2025-06-19 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rls', '0015_V3_7_0'),
    ]

    operations = []
