# Generated by Django 5.1.10 on 2025-07-30 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rls', '0021_V3_12_0'),
    ]

    operations = []
