# Generated by Django 5.1.10 on 2025-08-06 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rls', '0022_V3_13_0'),
    ]

    operations = []
