# Generated by Django 5.1.10 on 2025-09-09 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rls', '0026_V3_17_1'),
    ]

    operations = []
