# Generated by Django 5.1.15 on 2026-01-27 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rls', '0001_rls_role_setup_squashed_0041_V5_0_0'),
    ]

    operations = []
