# Generated by Django 5.1.15 on 2026-02-28 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rls', '0045_V5_3_0'),
    ]

    operations = []
