# Generated by Django 5.1.15 on 2026-06-08 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rls', '0058_V5_12_0'),
    ]

    operations = []
