# Generated by Django 5.2.16 on 2026-08-12 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rls', '0067_V5_18_1'),
    ]

    operations = []
