# Generated by Django 6.0.8 on 2026-09-01 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rls', '0069_V5_19_1'),
    ]

    operations = []
