from enum import Enum


class ReportingTableNames(Enum):
    ACTIVITY_JSON_SCHEMA = 'activity_json_schema'
    ACTIVITY_SOURCE_TYPE_JSON_SCHEMA = 'activity_source_type_json_schema'
    CONFIGURATION_ELEMENT = 'configuration_element'
    CONFIGURATION = 'configuration'
    CUSTOM_METHODOLOGY_SCHEMA = 'custom_methodology_schema'
    EMISSION_CATEGORY_MAPPING = 'emission_category_mapping'
    EMISSION_CATEGORY = 'emission_category'
    FACILITY_REPORT = 'facility_report'
    FUEL_TYPE = 'fuel_type'
    GAS_TYPE = 'gas_type'
    METHODOLOGY = 'methodology'
    NAICS_REGULATORY_VALUE = 'naics_regulatory_value'
    PRODUCT_EMISSION_INTENSITY = 'product_emission_intensity'
    REPORT_ACTIVITY = 'report_activity'
    REPORT_ADDITIONAL_DATA = 'report_additional_data'
    REPORT_ATTACHMENT = 'report_attachment'
    REPORT_EMISSION = 'report_emission'
    REPORT_FUEL = 'report_fuel'
    REPORT_METHODOLOGY = 'report_methodology'
    REPORT_NEW_ENTRANT_EMISSION = 'report_new_entrant_emission'
    REPORT_NEW_ENTRANT_PRODUCTION = 'report_new_entrant_production'
    REPORT_NEW_ENTRANT = 'report_new_entrant'
    REPORT_NON_ATTRIBUTABLE_EMISSIONS = 'report_non_attributable_emissions'
    REPORT_OPERATION_REPRESENTATIVE = 'report_operation_representative'
    REPORT_OPERATION = 'report_operation'
    REPORT_PERSON_RESPONSIBLE = 'report_person_responsible'
    REPORT_PRODUCT_EMISSION_ALLOCATION = 'report_product_emission_allocation'
    REPORT_PRODUCT = 'report_product'
    REPORT_RAW_ACTIVITY_DATA = 'report_raw_activity_data'
    REPORT_SOURCE_TYPE = 'report_source_type'
    REPORT_UNIT = 'report_unit'
    REPORT_VERIFICATION_VISIT = 'report_verification_visit'
    REPORT_VERSION = 'report_version'
    REPORT = 'report'
    REPORTING_FIELD = 'reporting_field'
    REPORTING_YEAR = 'reporting_year'
    SOURCE_TYPE = 'source_type'

    # M2M tables
    CONFIGURATION_ELEMENT_REPORTING_FIELDS = 'configuration_element_reporting_fields'
    REPORT_EMISSION_EMISSION_CATEGORIES = 'report_emission_emission_categories'
    REPORT_NON_ATTRIBUTABLE_EMISSIONS_GAS_TYPE = 'report_non_attributable_emissions_gas_type'
    REPORT_OPERATION_ACTIVITIES = 'report_operation_activities'
    REPORT_OPERATION_REGULATED_PRODUCTS = 'report_operation_regulated_products'
