import {
  ActivePage,
  generateManageObligationTaskList,
} from "@/compliance/src/app/components/taskLists/1_manageObligationTaskList";
import CompliancePageLayout from "@/compliance/src/app/components/layout/CompliancePageLayout";
import { ObligationTrackPaymentsComponent } from "./ObligationTrackPaymentsComponent";
import { getObligationData } from "@/compliance/src/app/utils/getObligation";
import {
  ObligationData,
  PayObligationTrackPaymentsFormData,
} from "@/compliance/src/app/types";

interface Props {
  readonly compliance_summary_id: string;
}

export default async function ObligationTrackPaymentsPayPage({
  compliance_summary_id: complianceReportVersionId,
}: Props) {
  const obligationWithPayments: ObligationData = await getObligationData(
    complianceReportVersionId,
  );

  const data: PayObligationTrackPaymentsFormData = {
    ...obligationWithPayments,
    payments: obligationWithPayments.payment_data.rows.map((payment) => ({
      ...payment,
      payment_header: "", // Will be generated by widget
    })),
  };

  const taskListElements = generateManageObligationTaskList(
    complianceReportVersionId,
    data.reporting_year,
    ActivePage.PayObligationTrackPayments,
    data.penalty_status,
  );

  return (
    <CompliancePageLayout
      taskListElements={taskListElements}
      complianceSummaryId={complianceReportVersionId}
    >
      <ObligationTrackPaymentsComponent
        data={data}
        complianceSummaryId={complianceReportVersionId}
      />
    </CompliancePageLayout>
  );
}
