import {
  ActivePage,
  generateManageObligationTaskList,
} from "@/compliance/src/app/components/taskLists/1_manageObligationTaskList";
import CompliancePageLayout from "@/compliance/src/app/components/layout/CompliancePageLayout";
import { ObligationTrackPaymentsComponent } from "./ObligationTrackPaymentsComponent";
import { getObligationData } from "@/compliance/src/app/utils/getObligation";
import {
  HasComplianceReportVersion,
  ObligationData,
  PayObligationTrackPaymentsFormData,
} from "@/compliance/src/app/types";

export default async function ObligationTrackPaymentsPayPage({
  compliance_report_version_id: complianceReportVersionId,
}: HasComplianceReportVersion) {
  const obligationWithPayments: ObligationData = await getObligationData(
    complianceReportVersionId,
  );

  const data: PayObligationTrackPaymentsFormData = {
    ...obligationWithPayments,
    payments: obligationWithPayments.payment_data.rows.map((payment) => ({
      ...payment,
      payment_header: "", // Will be generated by widget
    })),
  };

  const taskListElements = generateManageObligationTaskList(
    complianceReportVersionId,
    data,
    ActivePage.PayObligationTrackPayments,
    data.penalty_status,
  );

  return (
    <CompliancePageLayout
      taskListElements={taskListElements}
      complianceReportVersionId={complianceReportVersionId}
    >
      <ObligationTrackPaymentsComponent
        data={data}
        complianceReportVersionId={complianceReportVersionId}
      />
    </CompliancePageLayout>
  );
}
