
backend:
  replicaCount: 1

  image:
    tag: "latest"

  environment: production

frontend:
  replicaCount: 1

  image:
    tag: "latest"

  route:
    host: registration.industrialemissions.gov.bc.ca

  environment: production

  auth:
    keycloakAuthUrl: https://loginproxy.gov.bc.ca/auth
    siteminderAuthUrl: https://logon7.gov.bc.ca
