
backend:
  replicaCount: 2

  image:
    tag: "latest"

  environment: production

  resources:
    limits:
      cpu: 800m
      memory: 600Mi
    requests:
      cpu: 300m
      memory: 300Mi

frontend:
  replicaCount: 2

  image:
    tag: "latest"

  route:
    host: registration.industrialemissions.gov.bc.ca

  environment: production

  auth:
    keycloakAuthUrl: https://loginproxy.gov.bc.ca/auth
    siteminderAuthUrl: https://logon7.gov.bc.ca

  resources:
    limits:
      cpu: 400m
      memory: 500Mi
    requests:
      cpu: 200m
      memory: 250Mi
