
backend:
  replicaCount: 1

  image:
    tag: "latest"

  route:
    host: cas-reg-backend-dev.apps.silver.devops.gov.bc.ca

  environment: production

frontend:
  replicaCount: 1

  image:
    tag: "latest"

  route:
    host: cas-reg-frontend-dev.apps.silver.devops.gov.bc.ca

  apiUrl: https://cas-reg-backend-dev.apps.silver.devops.gov.bc.ca/api/

  environment: production
