backend:
  replicaCount: 2

  image:
    tag: "latest"

  environment: prod

  sentry:
    traceSampleRate: 0.1

  resources:
    limits:
      cpu: 1000m
      memory: 600Mi
    requests:
      cpu: 300m
      memory: 300Mi

registration1Frontend:
  replicaCount: 2

  image:
    tag: "latest"

  route:
    host: registration.industrialemissions.gov.bc.ca

  environment: prod

  auth:
    keycloakAuthUrl: https://loginproxy.gov.bc.ca/auth
    siteminderAuthUrl: https://logon7.gov.bc.ca

  sentry:
    traceSampleRate: 0.1

  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 200m
      memory: 250Mi

growthbook:
  clientKey: sdk-GUXYZ3Z60wN04tHG
