
backend:
  replicaCount: 2

  image:
    tag: "latest"

  route:
    host: cas-reg-backend-test.apps.silver.devops.gov.bc.ca

  environment: test

  resources:
    limits:
      cpu: 800m
      memory: 600Mi
    requests:
      cpu: 300m
      memory: 300Mi

frontend:
  replicaCount: 2

  image:
    tag: "latest"

  route:
    host: cas-reg-frontend-test.apps.silver.devops.gov.bc.ca

  environment: test

  auth:
    keycloakAuthUrl: https://test.loginproxy.gov.bc.ca/auth
    siteminderAuthUrl: https://logontest7.gov.bc.ca

  resources:
    limits:
      cpu: 400m
      memory: 500Mi
    requests:
      cpu: 200m
      memory: 250Mi
