
backend:
  replicaCount: 1

  image:
    tag: "latest"

  route:
    host: cas-reg-backend-test.apps.silver.devops.gov.bc.ca

  environment: test

frontend:
  replicaCount: 1

  image:
    tag: "latest"

  route:
    host: cas-reg-frontend-test.apps.silver.devops.gov.bc.ca

  apiUrl: https://cas-reg-backend-test.apps.silver.devops.gov.bc.ca/api/

  environment: test
