# Default values for cas-registration.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

backend:
  replicaCount: 1

  image:
    repository: ghcr.io/bcgov/cas-reg-backend
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

  service:
    type: ClusterIP
    port: 8000

  route:
    host: ~

  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 60m
      memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

frontend:
  replicaCount: 1

  image:
    repository: ghcr.io/bcgov/cas-reg-frontend
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

  service:
    type: ClusterIP
    port: 3000

  route:
    host: ~

  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 60m
      memory: 192Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

devops:
  image:
    repository: ghcr.io/bcgov/cas-reg-devops
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 64Mi
