
backend:
  replicaCount: 2

  image:
    tag: "latest"

  route:
    host: cas-reg-backend-test.apps.silver.devops.gov.bc.ca

  environment: test

  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 60m
      memory: 256Mi

registration1Frontend:
  replicaCount: 2

  image:
    tag: "latest"

  route:
    host: cas-reg-frontend-test.apps.silver.devops.gov.bc.ca

  environment: test

  auth:
    keycloakAuthUrl: https://test.loginproxy.gov.bc.ca/auth
    siteminderAuthUrl: https://logontest7.gov.bc.ca

  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 60m
      memory: 256Mi

growthbook:
  clientKey: sdk-9Vyna67jpIYdjMa
