name: "Yarn cache"
description: "Cache Yarn dependencies"
outputs:
  cache-hit:
    description: "Whether the cache was hit"
    value: ${{ steps.yarn-cache.outputs.cache-hit }}
runs:
  using: composite
  steps:
    - uses: actions/cache@v4
      id: yarn-cache
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-cache-${{ hashFiles('bciers/yarn.lock') }}-v2
