name: "Yarn cache"
description: "Cache Yarn dependencies"
runs:
  using: composite
  steps:
    - uses: actions/cache@v4
      id: yarn-cache-dependencies
      with:
        path: |
          ~/.cache/yarn
          ./client/node_modules
        key: ${{ runner.os }}-yarn-cache-${{ hashFiles('client/yarn.lock') }}-v2
    - name: Install yarn dependencies
      if: steps.yarn-cache-dependencies.outputs.cache-hit != 'true'
      run: yarn install
      working-directory: ./client
      shell: bash
