name: "Yarn cache"
description: "Cache Yarn dependencies"
# Test run 1: yarn-only cache miss
runs:
  using: composite
  steps:
    - uses: actions/cache@v4
      id: yarn-cache
      with:
        path: |
          ~/.cache/yarn
          ./bciers/node_modules
        key: ${{ runner.os }}-yarn-cache-${{ hashFiles('bciers/yarn.lock') }}-v2
