name: "Yarn cache"
description: "Cache Yarn dependencies"
runs:
  using: composite
  steps:
    - uses: actions/cache@v4
      id: yarn-cache
      with:
        path: |
          ~/.cache/yarn
          ./bciers/node_modules
          ./bciers/apps/*/.next/cache
          ./bciers/dist/*/.next/cache
        key: ${{ runner.os }}-yarn-nextjs-${{ hashFiles('bciers/yarn.lock') }}-${{ hashFiles('bciers/**/*.{js,jsx,ts,tsx}') }}-v3
        restore-keys: |
          ${{ runner.os }}-yarn-nextjs-${{ hashFiles('bciers/yarn.lock') }}-
