apiVersion: v2
name: cas-obps-backend-migration-test
description: A Helm chart deploying a locally-configured bciers
             backend for migration testing purposes.
type: application

version: 0.3.2

appVersion: "5.20.0"
