{{- if (.Values.registrationFrontend.enabled) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cas-registration.fullname" . }}-registration-frontend
  labels:
    component: registration-frontend
{{- include "cas-registration.labels" . | nindent 4 }}
spec:
{{- if not .Values.registrationFrontend.autoscaling.enabled }}
  replicas: {{ .Values.registrationFrontend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cas-registration.selectorLabels" . | nindent 6 }}
      component: registration-frontend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
{{- include "cas-registration.selectorLabels" . | nindent 8 }}
        component: registration-frontend
    spec:
      containers:
        - name: {{ template "cas-registration.fullname" . }}-registration-frontend
          env:
            - name: API_URL
              value: http://{{ include "cas-registration.fullname" . }}-backend.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.backend.service.port }}/api/
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-gold-client-secret
                  key: kcClientSecret
            - name: KEYCLOAK_AUTH_URL
              value: {{ .Values.registrationFrontend.auth.keycloakAuthUrl}}
            - name: KEYCLOAK_REALMS
              value: {{ .Values.registrationFrontend.auth.keycloakRealms}}
            - name: KEYCLOAK_OIDC
              value: {{ .Values.registrationFrontend.auth.keycloakOidc}}
            - name: KEYCLOAK_LOGIN_URL
              value: {{ .Values.registrationFrontend.auth.keycloakAuthUrl}}{{ .Values.registrationFrontend.auth.keycloakRealms }}
            - name: KEYCLOAK_LOGOUT_URL
              value: {{ .Values.registrationFrontend.auth.keycloakAuthUrl}}{{ .Values.registrationFrontend.auth.keycloakRealms }}{{ .Values.registrationFrontend.auth.keycloakOidc}}/logout
            - name: KEYCLOAK_TOKEN_URL
              value: {{ .Values.registrationFrontend.auth.keycloakAuthUrl}}{{ .Values.registrationFrontend.auth.keycloakRealms }}{{ .Values.registrationFrontend.auth.keycloakOidc}}/token
            - name: NEXTAUTH_URL
              value: https://{{ .Values.registrationFrontend.route.host }}
            - name: SITEMINDER_AUTH_URL
              value: {{ .Values.registrationFrontend.auth.siteminderAuthUrl }}
            - name: SITEMINDER_LOGOUT_URL
              value: {{ .Values.registrationFrontend.auth.siteminderAuthUrl }}/clp-cgi/logoff.cgi
            - name: NEXT_PUBLIC_KEYCLOAK_LOGOUT_URL
              value: {{ .Values.registrationFrontend.auth.siteminderAuthUrl }}/clp-cgi/logoff.cgi?retnow=1&returl={{ .Values.registrationFrontend.auth.keycloakAuthUrl}}{{ .Values.registrationFrontend.auth.keycloakRealms }}{{ .Values.registrationFrontend.auth.keycloakOidc}}/logout
            - name: KEYCLOAK_CLIENT_ID
              value: {{ .Values.registrationFrontend.auth.keycloakClientId }}
            - name: SITEMINDER_KEYCLOAK_LOGOUT_URL
              value: {{ .Values.registrationFrontend.auth.siteminderAuthUrl }}/clp-cgi/logoff.cgi?retnow=1&returl={{ .Values.registrationFrontend.auth.keycloakAuthUrl}}{{ .Values.registrationFrontend.auth.keycloakRealms }}{{ .Values.registrationFrontend.auth.keycloakOidc}}/logout
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "cas-registration.fullname" . }}-nextauth
                  key: nextauth-secret
            - name: NEXT_PUBLIC_GROWTHBOOK_CLIENT_KEY
              value: {{ .Values.growthbook.clientKey }}
            {{- if hasSuffix "-prod" .Release.Namespace }}
            - name: SENTRY_ENVIRONMENT
              value: {{ include "cas-registration.namespaceSuffix" . }}
            - name: SENTRY_RELEASE
              value: {{ .Values.registrationFrontend.image.tag }}
            - name: SENTRY_TRACE_SAMPLE_RATE
              value: {{ .Values.registrationFrontend.sentry.traceSampleRate | quote }}
            {{- end }}
          image: "{{ .Values.registrationFrontend.image.repository }}:{{ .Values.defaultImageTag | default .Values.registrationFrontend.image.tag }}"
          imagePullPolicy: {{ .Values.registrationFrontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.registrationFrontend.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.registrationFrontend.resources | nindent 12 }}
      restartPolicy: Always
{{- end }}
