{{- if (.Values.reportingFrontend.enabled) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cas-registration.fullname" . }}-reporting-frontend
  labels:
    component: reporting-frontend
    role: frontend
{{- include "cas-registration.labels" . | nindent 4 }}
spec:
{{- if not .Values.reportingFrontend.autoscaling.enabled }}
  replicas: {{ .Values.reportingFrontend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cas-registration.selectorLabels" . | nindent 6 }}
      component: reporting-frontend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
{{- include "cas-registration.selectorLabels" . | nindent 8 }}
        component: reporting-frontend
        role: frontend
    spec:
      containers:
        - name: {{ template "cas-registration.fullname" . }}-reporting-frontend
          env:
            - name: API_URL
              value: http://{{ include "cas-registration.fullname" . }}-backend.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.backend.service.port }}/api/
            - name: AUTH_TRUST_HOST
              value: "true"
          image: "{{ .Values.reportingFrontend.image.repository }}:{{ .Values.defaultImageTag | default .Values.reportingFrontend.image.tag }}"
          imagePullPolicy: {{ .Values.reportingFrontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.reportingFrontend.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.reportingFrontend.resources | nindent 12 }}
      restartPolicy: Always
{{- end }}
