{{- if (.Values.reportingFrontend.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cas-registration.fullname" . }}-reporting-frontend
  labels:
    role: frontend
    {{- include "cas-registration.labels" . | nindent 4 }}
spec:
  type: {{ .Values.reportingFrontend.service.type }}
  ports:
    - port: {{ .Values.reportingFrontend.service.port }}
      targetPort: 3000
      protocol: TCP
      name: {{ include "cas-registration.fullname" . }}-reporting-frontend
  selector:
    {{- include "cas-registration.selectorLabels" . | nindent 4 }}
    component: reporting-frontend
{{- end }}
