kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "cas-bciers.fullname" . }}-intra-frontend-by-name
  labels: {{ include "cas-bciers.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      role: frontend
  ingress:
  - from:
    - podSelector:
        matchLabels:
          role: frontend
