kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "cas-bciers.fullname" . }}-dev-intra-release-by-name
  labels: {{ include "cas-bciers.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cas-bciers.fullname" . }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          release: {{ include "cas-bciers.fullname" . }}
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ include "cas-bciers.fullname" . }}
