kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "cas-bciers.fullname" . }}-postgres-job-ingress
  labels: {{ include "cas-bciers.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: cas-obps-postgres
  ingress:
  - from:
    - podSelector:
        matchLabels:
          release: {{ include "cas-bciers.fullname" . }}
          component: job-with-database-access
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ include "cas-bciers.fullname" . }}
          component: job-with-database-access
