kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "cas-bciers.fullname" . }}-postgres-data-warehouse-ingress
  labels: {{ include "cas-bciers.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: cas-obps-postgres
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/instance: cas-data-warehouse
      namespaceSelector:
        matchLabels:
          environment: {{ .Values.environment }}
          name: 09269b
