{{- if .Values.administrationFrontend.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "cas-bciers.fullname" . }}-administration-frontend-hpa
  labels: {{- include "cas-bciers.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "cas-bciers.fullname" . }}-administration-frontend
  minReplicas: {{ .Values.administrationFrontend.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.administrationFrontend.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.administrationFrontend.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.administrationFrontend.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if .Values.administrationFrontend.autoscaling.targetMemoryUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.administrationFrontend.autoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
{{- end }}
