import {
  ActivePage,
  generateAutomaticOverduePenaltyTaskList,
} from "@/compliance/src/app/components/taskLists/automaticOverduePenaltyTaskList";
import CompliancePageLayout from "@/compliance/src/app/components/layout/CompliancePageLayout";
import { PenaltyTrackPaymentsComponent } from "./PenaltyTrackPaymentsComponent";
import { getPenaltyData } from "@/compliance/src/app/utils/getPenalty";
import {
  HasComplianceReportVersion,
  PayPenaltyTrackPaymentsFormData,
  PenaltyData,
} from "@/compliance/src/app/types";
import { getReportingYear } from "@reporting/src/app/utils/getReportingYear";

export default async function PenaltyTrackPaymentsPayPage({
  compliance_report_version_id: complianceReportVersionId,
}: HasComplianceReportVersion) {
  const penaltyWithPayments: PenaltyData = await getPenaltyData(
    complianceReportVersionId,
  );

  const data: PayPenaltyTrackPaymentsFormData = {
    ...penaltyWithPayments,
    payments: penaltyWithPayments.payment_data.rows.map((payment) => ({
      ...payment,
      payment_header: "", // Will be generated by widget
    })),
  };

  const { reporting_year: reportingYearData } = await getReportingYear();

  const taskListElements = generateAutomaticOverduePenaltyTaskList(
    complianceReportVersionId,
    reportingYearData,
    ActivePage.PayPenaltyTrackPayments,
  );

  return (
    <CompliancePageLayout
      taskListElements={taskListElements}
      complianceReportVersionId={complianceReportVersionId}
    >
      <PenaltyTrackPaymentsComponent
        data={data}
        complianceReportVersionId={complianceReportVersionId}
      />
    </CompliancePageLayout>
  );
}
