
backend:
  replicaCount: 2

  image:
    tag: "latest"

  route:
    host: cas-bciers-backend-test.apps.silver.devops.gov.bc.ca

  environment: test

  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 150m
      memory: 512Mi

administrationFrontend:
  replicaCount: 1

  image:
    tag: "latest"

  route:
    host: cas-bciers-frontend-test.apps.silver.devops.gov.bc.ca
    path: "/administration"

  environment: test

  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 60m
      memory: 128Mi

registrationFrontend:
  replicaCount: 1

  image:
    tag: "latest"

  route:
    host: cas-bciers-frontend-test.apps.silver.devops.gov.bc.ca
    path: "/registration"

  environment: test

  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 60m
      memory: 128Mi

reportingFrontend:
  replicaCount: 1

  image:
    tag: "latest"

  route:
    host: cas-bciers-frontend-test.apps.silver.devops.gov.bc.ca
    path: "/reporting"

  environment: test

  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 60m
      memory: 128Mi

complianceFrontend:
  replicaCount: 1

  image:
    tag: "latest"

  route:
    host: cas-bciers-frontend-test.apps.silver.devops.gov.bc.ca
    path: "/compliance"

  environment: test

  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 60m
      memory: 128Mi

dashboardFrontend:
  replicaCount: 1

  image:
    tag: "latest"

  route:
    host: cas-bciers-frontend-test.apps.silver.devops.gov.bc.ca
    path: "/"

  environment: test

  auth:
    keycloakAuthUrl: https://test.loginproxy.gov.bc.ca/auth
    siteminderAuthUrl: https://logontest7.gov.bc.ca

  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 60m
      memory: 128Mi

download-dags:
  airflowEndpoint: https://cas-airflow-test.apps.silver.devops.gov.bc.ca

cas-logging-sidecar:
  host: ~
  index: "cas-bciers-test-logs"
  prefix: "cas-bciers"
  tag: "oc-cas-bciers"
  logName: "cas-bciers-test-logs"
