environment: prod

enable_pdb: true

backend:
  replicaCount: 2

  image:
    tag: "latest"

  environment: prod

  resources:
    limits:
      memory: 1125Mi
    requests:
      cpu: 250m
      memory: 600Mi

  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 80

administrationFrontend:
  replicaCount: 2

  image:
    tag: "latest"

  route:
    host: industrialemissions.gov.bc.ca
    path: "/administration"

  environment: prod

  resources:
    limits:
      memory: 432Mi
    requests:
      cpu: 60m
      memory: 192Mi

  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 80

registrationFrontend:
  replicaCount: 2

  image:
    tag: "latest"

  route:
    host: industrialemissions.gov.bc.ca
    path: "/registration"

  environment: prod

  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 60m
      memory: 128Mi

  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 80

reportingFrontend:
  replicaCount: 2

  image:
    tag: "latest"

  route:
    host: industrialemissions.gov.bc.ca
    path: "/reporting"

  environment: prod

  resources:
    limits:
      memory: 464Mi
    requests:
      cpu: 60m
      memory: 192Mi

  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 80

complianceFrontend:
  replicaCount: 2

  image:
    tag: "latest"

  route:
    host: industrialemissions.gov.bc.ca
    path: "/compliance"

  environment: prod

  resources:
    limits:
      memory: 304Mi
    requests:
      cpu: 60m
      memory: 128Mi

dashboardFrontend:
  replicaCount: 2

  image:
    tag: "latest"

  route:
    host: industrialemissions.gov.bc.ca
    path: "/"

  environment: prod

  auth:
    keycloakAuthUrl: https://loginproxy.gov.bc.ca/auth
    siteminderAuthUrl: https://logon7.gov.bc.ca

  resources:
    limits:
      memory: 400Mi
    requests:
      cpu: 60m
      memory: 192Mi

  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 80

run-reset-data-dag-on-upgrade:
  enabled: false

cas-logging-sidecar:
  host: ~
  index: "cas-bciers-prod-logs"
  prefix: "cas-bciers-prod-logs"
  tag: "oc-cas-bciers"
  logName: "cas-bciers-prod-logs"
