# Development environment values for cas-bciers.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

backend:
  replicaCount: 2

  image:
    tag: "latest"

  route:
    host: cas-bciers-backend-dev.apps.silver.devops.gov.bc.ca

  environment: dev

  deployRoute: true

  resources:
    limits:
      memory: 750Mi
    requests:
      cpu: 60m
      memory: 512Mi

administrationFrontend:
  replicaCount: 1

  image:
    tag: "latest"

  route:
    host: cas-bciers-frontend-dev.apps.silver.devops.gov.bc.ca
    path: "/administration"

  environment: dev

  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 60m
      memory: 128Mi

registrationFrontend:
  replicaCount: 1

  image:
    tag: "latest"

  route:
    host: cas-bciers-frontend-dev.apps.silver.devops.gov.bc.ca
    path: "/registration"

  environment: dev

  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 60m
      memory: 128Mi

reportingFrontend:
  enabled: true

  image:
    tag: "latest"

  route:
    host: cas-bciers-frontend-dev.apps.silver.devops.gov.bc.ca
    path: "/reporting"

  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 60m
      memory: 128Mi

complianceFrontend:
  replicaCount: 1

  image:
    tag: "latest"

  route:
    host: cas-bciers-frontend-dev.apps.silver.devops.gov.bc.ca
    path: "/compliance"

  environment: dev

  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 60m
      memory: 128Mi

dashboardFrontend:
  enabled: true

  image:
    tag: "latest"

  route:
    host: cas-bciers-frontend-dev.apps.silver.devops.gov.bc.ca
    path: "/"

  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 60m
      memory: 128Mi

  auth:
    keycloakAuthUrl: https://dev.loginproxy.gov.bc.ca/auth
    siteminderAuthUrl: https://logontest7.gov.bc.ca

growthbook:
  clientKey: sdk-YMBcx9KglRDGzGTE

download-dags:
  airflowEndpoint: https://cas-airflow-dev.apps.silver.devops.gov.bc.ca

cas-logging-sidecar:
  host: ~
  index: "cas-bciers-dev-logs"
  prefix: "cas-bciers"
  tag: "oc-cas-bciers"
  logName: "cas-bciers-dev-logs"
