# Development environment values for cas-bciers.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

backend:
  replicaCount: 2

  image:
    tag: "latest"

  route:
    host: cas-bciers-backend-dev.apps.silver.devops.gov.bc.ca

  environment: dev

  deployRoute: true

  resources:
    requests:
      cpu: 60m
      memory: 256Mi

administrationFrontend:
  replicaCount: 1

  image:
    tag: "latest"

  route:
    host: cas-bciers-frontend-dev.apps.silver.devops.gov.bc.ca
    path: "/administration"

  environment: dev

  resources:
    requests:
      cpu: 60m
      memory: 128Mi

registrationFrontend:
  replicaCount: 1

  image:
    tag: "latest"

  route:
    host: cas-bciers-frontend-dev.apps.silver.devops.gov.bc.ca
    path: "/registration"

  environment: dev

  resources:
    requests:
      cpu: 60m
      memory: 128Mi

reportingFrontend:
  enabled: true

  image:
    tag: "latest"

  route:
    host: cas-bciers-frontend-dev.apps.silver.devops.gov.bc.ca
    path: "/reporting"

  resources:
    requests:
      cpu: 60m
      memory: 128Mi

complianceFrontend:
  replicaCount: 1

  image:
    tag: "latest"

  route:
    host: cas-bciers-frontend-dev.apps.silver.devops.gov.bc.ca
    path: "/compliance"

  environment: dev

  resources:
    requests:
      cpu: 60m
      memory: 128Mi

dashboardFrontend:
  enabled: true

  image:
    tag: "latest"

  route:
    host: cas-bciers-frontend-dev.apps.silver.devops.gov.bc.ca
    path: "/"

  resources:
    requests:
      cpu: 60m
      memory: 128Mi

  auth:
    keycloakAuthUrl: https://dev.loginproxy.gov.bc.ca/auth
    siteminderAuthUrl: https://logontest7.gov.bc.ca

growthbook:
  clientKey: sdk-YMBcx9KglRDGzGTE

download-dags:
  airflowEndpoint: https://cas-airflow-dev.apps.silver.devops.gov.bc.ca
