name: "Build and push Docker image"
description: "Reusable action to build and push a Docker image"

inputs:
  project:
    description: "Nx project name"
    required: true
  image_url:
    description: "Docker image URL"
    required: true
  registry:
    description: "Docker registry"
    required: true
  cache_key:
    description: "Unique cache key name"
    required: true
  github_token:
    description: "GitHub token"
    required: true

runs:
  using: composite
  steps:
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Docker metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ inputs.image_url }}
        tags: |
          type=sha,format=long,prefix=
          latest
          type=ref,event=pr
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.github_token }}
    - name: Install dependencies
      shell: bash
      run: |
        corepack enable
        yarn install --immutable
        cd bciers && yarn install --immutable
    - uses: actions/setup-node@v3
    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      uses: nrwl/nx-set-shas@v4
      with:
        # This will need to be updated when giraffe-develop merges with develop
        main-branch-name: "develop"
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-${{ inputs.cache_key }}${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.cache_key }}
    - name: Build images
      shell: bash
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_PUSH: true
        INPUT_TAGS: ${{ steps.meta.outputs.tags }}
        INPUT_LABELS: ${{ steps.meta.output.labels }}
        INPUT_CACHE_FROM: type=local,src=/tmp/.buildx-cache
        INPUT_CACHE_TO: type=local,dest=/tmp/.buildx-cache-new
      run: |
        npx nx container ${{ inputs.project }} --skip-nx-cache
      working-directory: ./bciers
      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
    - name: Move cache
      shell: bash
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
