import { Page, expect } from "@playwright/test";
import { ComplianceTaskTitles } from "@/compliance-e2e/utils/enums";
import {
  DOWNLOAD_PAYMENT_INSTRUCTIONS_URL_PATTERN,
  PENALTY_CALCULATOR_URL_PATTERN,
} from "@/compliance-e2e/utils/constants";

export class ManageObligationTaskListPOM {
  readonly page: Page;

  constructor(page: Page) {
    this.page = page;
  }

  /**
   * Clicks the "Download Payment Instructions" task list item
   * and waits for the URL to reach the download-payment-instructions route.
   *
   * Uses expect.toPass to retry the entire "locate + click + navigate" block.
   */
  async clickDownloadPaymentInstructions(options?: { timeout?: number }) {
    const timeout = options?.timeout ?? 30_000;

    const labelRegex = new RegExp(
      ComplianceTaskTitles.DOWNLOAD_PAYMENT_INSTRUCTIONS,
      "i",
    );

    await expect(async () => {
      const button = this.page.getByRole("button", { name: labelRegex });
      const count = await button.count().catch(() => 0);
      expect(count).toBeGreaterThan(0);
      await expect(button).toBeVisible();
      await expect(button).toBeEnabled();

      await Promise.all([
        this.page.waitForURL(DOWNLOAD_PAYMENT_INSTRUCTIONS_URL_PATTERN, {
          timeout,
        }),
        button.click(),
      ]);

      await expect(this.page).toHaveURL(
        DOWNLOAD_PAYMENT_INSTRUCTIONS_URL_PATTERN,
      );
    }).toPass({ timeout });
  }

  /**
   * Clicks the "Penalty calculator" task list item and waits
   * for the URL to reach the penalty-calculator route.
   */
  async clickPenaltyCalculator(options?: { timeout?: number }) {
    const timeout = options?.timeout ?? 30_000;
    const labelRegex = new RegExp(ComplianceTaskTitles.PENALTY_CALCULATOR, "i");

    await expect(async () => {
      // Handles either link or button markup generated by TaskListElement
      const item = this.page
        .getByRole("button", { name: labelRegex })
        .or(this.page.getByRole("link", { name: labelRegex }));

      const count = await item.count().catch(() => 0);
      expect(count).toBeGreaterThan(0);
      await expect(item.first()).toBeVisible();
      await expect(item.first()).toBeEnabled();

      await Promise.all([
        this.page.waitForURL(PENALTY_CALCULATOR_URL_PATTERN, { timeout }),
        item.first().click(),
      ]);

      await expect(this.page).toHaveURL(PENALTY_CALCULATOR_URL_PATTERN);
    }).toPass({ timeout });
  }
}
