# Generated by Django 6.1.1 on 2026-09-22 17:45

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
import simple_history.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0070_alter_compliancereportversionmanualhandling_context'),
        ('registration', '0196_V5_21_0'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                (
                    'created_at',
                    models.DateTimeField(
                        blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
                    ),
                ),
                (
                    'archived_at',
                    models.DateTimeField(
                        blank=True,
                        db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                        null=True,
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        db_comment='Primary key to identify the registry account',
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        db_comment='The name of the account as it should be displayed in the frontend', max_length=1000
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[('Active', 'Active'), ('Closed', 'Closed'), ('Pending', 'Pending')],
                        db_comment='Indicates whether the account is active or not.',
                        max_length=50,
                    ),
                ),
                (
                    'archived_by',
                    models.ForeignKey(
                        blank=True,
                        db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_archived',
                        to='registration.user',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        db_comment='ID of the user who created the record. Foreign key to erc.user',
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_created',
                        to='registration.user',
                    ),
                ),
                (
                    'operation_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='registry_account',
                        to='registration.operation',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_updated',
                        to='registration.user',
                    ),
                ),
            ],
            options={
                'db_table': 'erc"."account',
                'db_table_comment': 'Table containing account information relating to the internal BC Carbon Registry',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalAccount',
            fields=[
                (
                    'created_at',
                    models.DateTimeField(
                        blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
                    ),
                ),
                (
                    'archived_at',
                    models.DateTimeField(
                        blank=True,
                        db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                        null=True,
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        db_comment='Primary key to identify the registry account', db_index=True, default=uuid.uuid4
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        db_comment='The name of the account as it should be displayed in the frontend', max_length=1000
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[('Active', 'Active'), ('Closed', 'Closed'), ('Pending', 'Pending')],
                        db_comment='Indicates whether the account is active or not.',
                        max_length=50,
                    ),
                ),
                ('history_user_id', models.UUIDField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                (
                    'history_type',
                    models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
                ),
                (
                    'archived_by',
                    models.ForeignKey(
                        blank=True,
                        db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.user',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        db_comment='ID of the user who created the record. Foreign key to erc.user',
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.user',
                    ),
                ),
                (
                    'operation_id',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.operation',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.user',
                    ),
                ),
            ],
            options={
                'verbose_name': 'historical account',
                'verbose_name_plural': 'historical accounts',
                'db_table': 'erc_history"."account_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSubAccount',
            fields=[
                (
                    'created_at',
                    models.DateTimeField(
                        blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
                    ),
                ),
                (
                    'archived_at',
                    models.DateTimeField(
                        blank=True,
                        db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                        null=True,
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        db_comment='Primary key to identify the registry sub-account.',
                        db_index=True,
                        default=uuid.uuid4,
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        db_comment='The name of the sub-account as it should be displayed in the frontend.',
                        max_length=1000,
                    ),
                ),
                ('history_user_id', models.UUIDField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                (
                    'history_type',
                    models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
                ),
                (
                    'archived_by',
                    models.ForeignKey(
                        blank=True,
                        db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.user',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        db_comment='ID of the user who created the record. Foreign key to erc.user',
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.user',
                    ),
                ),
                (
                    'parent_account',
                    models.ForeignKey(
                        blank=True,
                        db_comment='The registry account under which the sub-account falls.',
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registry.account',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.user',
                    ),
                ),
            ],
            options={
                'verbose_name': 'historical sub account',
                'verbose_name_plural': 'historical sub accounts',
                'db_table': 'erc_history"."sub_account_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SubAccount',
            fields=[
                (
                    'created_at',
                    models.DateTimeField(
                        blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
                    ),
                ),
                (
                    'archived_at',
                    models.DateTimeField(
                        blank=True,
                        db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                        null=True,
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        db_comment='Primary key to identify the registry sub-account.',
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        db_comment='The name of the sub-account as it should be displayed in the frontend.',
                        max_length=1000,
                    ),
                ),
                (
                    'archived_by',
                    models.ForeignKey(
                        blank=True,
                        db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_archived',
                        to='registration.user',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        db_comment='ID of the user who created the record. Foreign key to erc.user',
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_created',
                        to='registration.user',
                    ),
                ),
                (
                    'parent_account',
                    models.ForeignKey(
                        db_comment='The registry account under which the sub-account falls.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='parent_account',
                        to='registry.account',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_updated',
                        to='registration.user',
                    ),
                ),
            ],
            options={
                'db_table': 'erc"."sub_account',
                'db_table_comment': '',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                (
                    'created_at',
                    models.DateTimeField(
                        blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
                    ),
                ),
                (
                    'archived_at',
                    models.DateTimeField(
                        blank=True,
                        db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                        null=True,
                    ),
                ),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                (
                    'unit_type',
                    models.CharField(
                        choices=[('Earned Credit', 'Earned Credit'), ('Carbon Offset', 'Offset')],
                        db_comment='Indicates whether the type of unit is an Earned Credit or a Carbon Offset.',
                        max_length=50,
                    ),
                ),
                (
                    'serial_number',
                    models.CharField(db_comment='The serial number of the unit as set by BCCR', max_length=200),
                ),
                (
                    'is_public',
                    models.BooleanField(
                        db_comment='Boolean value indicating whether the status and owning account of the unit should be visible to the public from the public-view of the registry',
                        default=True,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('Issued', 'Issued'),
                            ('Active', 'Active'),
                            ('Retired', 'Retired'),
                            ('Cancelled', 'Cancelled'),
                            ('Pending', 'Pending'),
                        ],
                        db_comment='Indicates whether the unit is active, retired, pending, cancelled, or issued.',
                        max_length=50,
                    ),
                ),
                ('vintage', models.CharField(max_length=10)),
                (
                    'archived_by',
                    models.ForeignKey(
                        blank=True,
                        db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_archived',
                        to='registration.user',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        db_comment='ID of the user who created the record. Foreign key to erc.user',
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_created',
                        to='registration.user',
                    ),
                ),
                (
                    'sub_account',
                    models.ForeignKey(
                        db_comment='Foreign key reference to the sub-account that currently holds the unit/s',
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='units',
                        to='registry.subaccount',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_updated',
                        to='registration.user',
                    ),
                ),
            ],
            options={
                'db_table': 'erc"."unit',
                'db_table_comment': '',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                (
                    'created_at',
                    models.DateTimeField(
                        blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
                    ),
                ),
                (
                    'archived_at',
                    models.DateTimeField(
                        blank=True,
                        db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                        null=True,
                    ),
                ),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                (
                    'effective_datetime',
                    models.DateTimeField(db_comment='The date and time at which the transfer took effect.'),
                ),
                (
                    'request_datetime',
                    models.DateTimeField(db_comment='The date and time when the request to transfer was made.'),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Complete', 'Complete')],
                        db_comment='The status of the transfer (pending, cancelled, or complete)',
                        max_length=50,
                    ),
                ),
                (
                    'comment',
                    models.CharField(
                        db_comment='Free-form comment field to capture input from the internal user reviewing the transfer request.',
                        max_length=1000,
                    ),
                ),
                (
                    'archived_by',
                    models.ForeignKey(
                        blank=True,
                        db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_archived',
                        to='registration.user',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        db_comment='ID of the user who created the record. Foreign key to erc.user',
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_created',
                        to='registration.user',
                    ),
                ),
                (
                    'from_sub_account',
                    models.ForeignKey(
                        db_comment='The sub-account ID from which the units are transferring.',
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='transfers_from',
                        to='registry.subaccount',
                    ),
                ),
                (
                    'requested_by',
                    models.ForeignKey(
                        db_comment='The ID of the user who requested the transfer.',
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='transfer_requested_by',
                        to='registration.user',
                    ),
                ),
                (
                    'reviewed_by',
                    models.ForeignKey(
                        blank=True,
                        db_comment='The ID of the IRC user who reviewed the transfer request and made a decision',
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='transfer_reviewed_by',
                        to='registration.user',
                    ),
                ),
                (
                    'to_sub_account',
                    models.ForeignKey(
                        db_comment='The sub-account ID to which the units are being transferred.',
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='transfers_to',
                        to='registry.subaccount',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_updated',
                        to='registration.user',
                    ),
                ),
                (
                    'unit',
                    models.ForeignKey(
                        db_comment='Identifier of the unit(s) being transferred',
                        on_delete=django.db.models.deletion.PROTECT,
                        to='registry.unit',
                    ),
                ),
            ],
            options={
                'db_table': 'erc"."trasfer',
                'db_table_comment': 'Records all requested transfers of earned credits and carbon offsets to and from sub-accounts.',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Retirement',
            fields=[
                (
                    'created_at',
                    models.DateTimeField(
                        blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
                    ),
                ),
                (
                    'archived_at',
                    models.DateTimeField(
                        blank=True,
                        db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                        null=True,
                    ),
                ),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                (
                    'status',
                    models.CharField(
                        choices=[('Approved', 'Approved'), ('Cancelled', 'Cancelled'), ('Declined', 'Declined')],
                        max_length=50,
                    ),
                ),
                (
                    'comment',
                    models.CharField(
                        db_comment="Free-form text field to capture the internal reviewer's comments regarding the requested retirement.",
                        max_length=1000,
                    ),
                ),
                (
                    'archived_by',
                    models.ForeignKey(
                        blank=True,
                        db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_archived',
                        to='registration.user',
                    ),
                ),
                (
                    'compliance_obligation',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to='compliance.complianceobligation'
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        db_comment='ID of the user who created the record. Foreign key to erc.user',
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_created',
                        to='registration.user',
                    ),
                ),
                (
                    'reviewed_by',
                    models.ForeignKey(
                        db_comment='The IRC user who reviewed the request to retire the unit/s and made a decision',
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='registration.user',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_updated',
                        to='registration.user',
                    ),
                ),
                (
                    'from_account',
                    models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registry.subaccount'),
                ),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registry.unit')),
            ],
            options={
                'db_table': 'erc"."retirement',
                'db_table_comment': 'A record of all requests to retire unit/s against a compliance obligation.',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalTransfer',
            fields=[
                (
                    'created_at',
                    models.DateTimeField(
                        blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
                    ),
                ),
                (
                    'archived_at',
                    models.DateTimeField(
                        blank=True,
                        db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                        null=True,
                    ),
                ),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                (
                    'effective_datetime',
                    models.DateTimeField(db_comment='The date and time at which the transfer took effect.'),
                ),
                (
                    'request_datetime',
                    models.DateTimeField(db_comment='The date and time when the request to transfer was made.'),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Complete', 'Complete')],
                        db_comment='The status of the transfer (pending, cancelled, or complete)',
                        max_length=50,
                    ),
                ),
                (
                    'comment',
                    models.CharField(
                        db_comment='Free-form comment field to capture input from the internal user reviewing the transfer request.',
                        max_length=1000,
                    ),
                ),
                ('history_user_id', models.UUIDField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                (
                    'history_type',
                    models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
                ),
                (
                    'archived_by',
                    models.ForeignKey(
                        blank=True,
                        db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.user',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        db_comment='ID of the user who created the record. Foreign key to erc.user',
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.user',
                    ),
                ),
                (
                    'requested_by',
                    models.ForeignKey(
                        blank=True,
                        db_comment='The ID of the user who requested the transfer.',
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.user',
                    ),
                ),
                (
                    'reviewed_by',
                    models.ForeignKey(
                        blank=True,
                        db_comment='The ID of the IRC user who reviewed the transfer request and made a decision',
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.user',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.user',
                    ),
                ),
                (
                    'from_sub_account',
                    models.ForeignKey(
                        blank=True,
                        db_comment='The sub-account ID from which the units are transferring.',
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registry.subaccount',
                    ),
                ),
                (
                    'to_sub_account',
                    models.ForeignKey(
                        blank=True,
                        db_comment='The sub-account ID to which the units are being transferred.',
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registry.subaccount',
                    ),
                ),
                (
                    'unit',
                    models.ForeignKey(
                        blank=True,
                        db_comment='Identifier of the unit(s) being transferred',
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registry.unit',
                    ),
                ),
            ],
            options={
                'verbose_name': 'historical transfer',
                'verbose_name_plural': 'historical transfers',
                'db_table': 'erc_history"."credit_transfer_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRetirement',
            fields=[
                (
                    'created_at',
                    models.DateTimeField(
                        blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
                    ),
                ),
                (
                    'archived_at',
                    models.DateTimeField(
                        blank=True,
                        db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                        null=True,
                    ),
                ),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('date_time', models.DateTimeField()),
                (
                    'status',
                    models.CharField(
                        choices=[('Approved', 'Approved'), ('Cancelled', 'Cancelled'), ('Declined', 'Declined')],
                        max_length=50,
                    ),
                ),
                (
                    'comment',
                    models.CharField(
                        db_comment="Free-form text field to capture the internal reviewer's comments regarding the requested retirement.",
                        max_length=1000,
                    ),
                ),
                ('history_user_id', models.UUIDField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                (
                    'history_type',
                    models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
                ),
                (
                    'archived_by',
                    models.ForeignKey(
                        blank=True,
                        db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.user',
                    ),
                ),
                (
                    'compliance_obligation',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='compliance.complianceobligation',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        db_comment='ID of the user who created the record. Foreign key to erc.user',
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.user',
                    ),
                ),
                (
                    'reviewed_by',
                    models.ForeignKey(
                        blank=True,
                        db_comment='The IRC user who reviewed the request to retire the unit/s and made a decision',
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.user',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registration.user',
                    ),
                ),
                (
                    'from_account',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registry.subaccount',
                    ),
                ),
                (
                    'unit',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='registry.unit',
                    ),
                ),
            ],
            options={
                'verbose_name': 'historical retirement',
                'verbose_name_plural': 'historical retirements',
                'db_table': 'erc_history"."credit_retirement_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='account',
            trigger=pgtrigger.compiler.Trigger(
                name='set_created_audit_columns',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="new.created_by_id = (select nullif(current_setting('my.guid', true), '')); new.created_at = now(); return new;",
                    hash='1658d91085a6df3223d90b4de3b11b61f27d1e34',
                    operation='INSERT',
                    pgid='pgtrigger_set_created_audit_columns_459d6',
                    table='erc"."account',
                    when='BEFORE',
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='account',
            trigger=pgtrigger.compiler.Trigger(
                name='set_updated_audit_columns',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="new.updated_by_id = (select nullif(current_setting('my.guid', true), '')); new.updated_at = now(); return new;",
                    hash='bf8837776722f5f5196d895bb00e4ecf7ce86ac3',
                    operation='UPDATE',
                    pgid='pgtrigger_set_updated_audit_columns_02aa9',
                    table='erc"."account',
                    when='BEFORE',
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='subaccount',
            trigger=pgtrigger.compiler.Trigger(
                name='set_created_audit_columns',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="new.created_by_id = (select nullif(current_setting('my.guid', true), '')); new.created_at = now(); return new;",
                    hash='da8ced05772c7a0a1d14fb499cce87b577cad7ae',
                    operation='INSERT',
                    pgid='pgtrigger_set_created_audit_columns_7bd3f',
                    table='erc"."sub_account',
                    when='BEFORE',
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='subaccount',
            trigger=pgtrigger.compiler.Trigger(
                name='set_updated_audit_columns',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="new.updated_by_id = (select nullif(current_setting('my.guid', true), '')); new.updated_at = now(); return new;",
                    hash='c106396a3864f20ecc8aee2886fbc297a4f4980c',
                    operation='UPDATE',
                    pgid='pgtrigger_set_updated_audit_columns_fffdf',
                    table='erc"."sub_account',
                    when='BEFORE',
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='unit',
            trigger=pgtrigger.compiler.Trigger(
                name='set_created_audit_columns',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="new.created_by_id = (select nullif(current_setting('my.guid', true), '')); new.created_at = now(); return new;",
                    hash='1dda4714b0c04bf8d9fd34d1945b42d6b78eed22',
                    operation='INSERT',
                    pgid='pgtrigger_set_created_audit_columns_b3328',
                    table='erc"."unit',
                    when='BEFORE',
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='unit',
            trigger=pgtrigger.compiler.Trigger(
                name='set_updated_audit_columns',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="new.updated_by_id = (select nullif(current_setting('my.guid', true), '')); new.updated_at = now(); return new;",
                    hash='24f8ecc7a139ec67bdddb88339bb4f2676d4ced2',
                    operation='UPDATE',
                    pgid='pgtrigger_set_updated_audit_columns_1b713',
                    table='erc"."unit',
                    when='BEFORE',
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='transfer',
            trigger=pgtrigger.compiler.Trigger(
                name='set_created_audit_columns',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="new.created_by_id = (select nullif(current_setting('my.guid', true), '')); new.created_at = now(); return new;",
                    hash='ec8f56297e7abdfa3e6e43326bc9ff4aaea807bc',
                    operation='INSERT',
                    pgid='pgtrigger_set_created_audit_columns_44db5',
                    table='erc"."trasfer',
                    when='BEFORE',
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='transfer',
            trigger=pgtrigger.compiler.Trigger(
                name='set_updated_audit_columns',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="new.updated_by_id = (select nullif(current_setting('my.guid', true), '')); new.updated_at = now(); return new;",
                    hash='3547b69942295ef8303587f28295b54c7bcacd3b',
                    operation='UPDATE',
                    pgid='pgtrigger_set_updated_audit_columns_a12b3',
                    table='erc"."trasfer',
                    when='BEFORE',
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='retirement',
            trigger=pgtrigger.compiler.Trigger(
                name='set_created_audit_columns',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="new.created_by_id = (select nullif(current_setting('my.guid', true), '')); new.created_at = now(); return new;",
                    hash='27854e4eb2dcb2bd5de0a4771ef1c3429ac09316',
                    operation='INSERT',
                    pgid='pgtrigger_set_created_audit_columns_20aa0',
                    table='erc"."retirement',
                    when='BEFORE',
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='retirement',
            trigger=pgtrigger.compiler.Trigger(
                name='set_updated_audit_columns',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="new.updated_by_id = (select nullif(current_setting('my.guid', true), '')); new.updated_at = now(); return new;",
                    hash='f851d2db7d01d08dde60a9151150dc2aabc8d16d',
                    operation='UPDATE',
                    pgid='pgtrigger_set_updated_audit_columns_fac74',
                    table='erc"."retirement',
                    when='BEFORE',
                ),
            ),
        ),
    ]
