# Generated by Django 5.2.16 on 2026-08-06 23:02

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ('task_scheduler', '0014_V5_0_1'),
        ('task_scheduler', '0015_V5_1_0'),
        ('task_scheduler', '0016_V5_2_0'),
        ('task_scheduler', '0017_V5_3_0'),
        ('task_scheduler', '0018_V5_3_1'),
        ('task_scheduler', '0019_V5_4_0'),
        ('task_scheduler', '0020_V5_4_1'),
        ('task_scheduler', '0021_V5_4_2'),
        ('task_scheduler', '0022_V5_4_3'),
        ('task_scheduler', '0023_V5_5_0'),
        ('task_scheduler', '0024_V5_6_0'),
        ('task_scheduler', '0025_V5_7_0'),
        ('task_scheduler', '0026_V5_8_0'),
        ('task_scheduler', '0027_V5_9_0'),
        ('task_scheduler', '0028_V5_10_0'),
        ('task_scheduler', '0029_V5_11_0'),
        ('task_scheduler', '0030_V5_12_0'),
        ('task_scheduler', '0031_V5_13_0'),
        ('task_scheduler', '0032_V5_13_1'),
        ('task_scheduler', '0033_V5_14_0'),
        ('task_scheduler', '0034_V5_15_0'),
        ('task_scheduler', '0035_V5_15_1'),
        ('task_scheduler', '0036_V5_16_0'),
        ('task_scheduler', '0037_V5_17_0'),
        ('task_scheduler', '0038_V5_18_0'),
    ]

    dependencies = [
        ('task_scheduler', '0001_initial_squashed_0013_V5_0_0'),
    ]

    operations = []
