# Generated by Django 5.1.12 on 2025-09-23 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_scheduler', '0001_initial'),
    ]

    operations = []
