# Generated by Django 5.1.10 on 2025-08-19 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_scheduler', '0001_initial'),
    ]

    operations = []
