# Generated by Django 5.1.12 on 2025-09-25 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_scheduler', '0002_V4_0_0'),
    ]

    operations = []
