# Generated by Django 5.1.12 on 2025-10-15 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_scheduler', '0004_V4_1_0'),
    ]

    operations = []
