# Generated by Django 5.1.12 on 2025-10-31 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_scheduler', '0005_V4_2_0'),
    ]

    operations = []
