# Generated by Django 5.1.14 on 2025-11-14 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_scheduler', '0006_V4_3_0'),
    ]

    operations = []
