# Generated by Django 5.1.15 on 2026-02-27 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_scheduler', '0016_V5_2_0'),
    ]

    operations = []
