# Generated by Django 5.1.15 on 2026-03-04 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_scheduler', '0018_V5_3_1'),
    ]

    operations = []
