# Generated by Django 5.1.15 on 2026-06-18 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_scheduler', '0032_V5_13_1'),
    ]

    operations = []
