# Generated by Django 5.1.15 on 2026-06-30 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_scheduler', '0033_V5_14_0'),
    ]

    operations = []
