# Generated by Django 5.1.15 on 2026-07-15 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_scheduler', '0035_V5_15_1'),
    ]

    operations = []
