# Generated by Django 5.0.6 on 2024-06-25 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0021_V1_6_0'),
        ('reporting', '0002_prod_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySourceTypeFuelJsonSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'json_schema',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='activity_source_type_fuel_json_schemas',
                        to='reporting.jsonschema',
                    ),
                ),
                (
                    'reporting_activity',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='activity_source_type_fuel_json_schemas',
                        to='registration.reportingactivity',
                    ),
                ),
                (
                    'source_type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='activity_source_type_fuel_json_schemas',
                        to='reporting.sourcetype',
                    ),
                ),
                (
                    'valid_from',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reporting.configuration'
                    ),
                ),
                (
                    'valid_to',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reporting.configuration'
                    ),
                ),
            ],
            options={
                'db_table': 'erc"."activity_source_type_fuel_json_schema',
                'db_table_comment': 'Intersection table that assigns a json_schema for a fuel as valid for a period of time given an activity & source type',
            },
        ),
        migrations.CreateModel(
            name='ActivitySourceTypeGasTypeJsonSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'gas_type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='activity_source_type_gas_type_json_schemas',
                        to='reporting.gastype',
                    ),
                ),
                (
                    'json_schema',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='activity_source_type_gas_type_json_schemas',
                        to='reporting.jsonschema',
                    ),
                ),
                (
                    'reporting_activity',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='activity_source_type_gas_type_json_schemas',
                        to='registration.reportingactivity',
                    ),
                ),
                (
                    'source_type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='activity_source_type_gas_type_json_schemas',
                        to='reporting.sourcetype',
                    ),
                ),
                (
                    'valid_from',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reporting.configuration'
                    ),
                ),
                (
                    'valid_to',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reporting.configuration'
                    ),
                ),
            ],
            options={
                'db_table': 'erc"."activity_source_type_gas_type_json_schema',
                'db_table_comment': 'Intersection table that assigns a json_schema for a gas_type (emission) as valid for a period of time given an activity & source type',
            },
        ),
        migrations.CreateModel(
            name='ActivitySourceTypeUnitJsonSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'json_schema',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='activity_source_type_unit_json_schemas',
                        to='reporting.jsonschema',
                    ),
                ),
                (
                    'reporting_activity',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='activity_source_type_unit_json_schemas',
                        to='registration.reportingactivity',
                    ),
                ),
                (
                    'source_type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='activity_source_type_unit_json_schemas',
                        to='reporting.sourcetype',
                    ),
                ),
                (
                    'valid_from',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reporting.configuration'
                    ),
                ),
                (
                    'valid_to',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reporting.configuration'
                    ),
                ),
            ],
            options={
                'db_table': 'erc"."activity_source_type_unit_json_schema',
                'db_table_comment': 'Intersection table that assigns a json_schema for a unit as valid for a period of time given an activity & source type',
            },
        ),
    ]
