# Generated by Django 5.0.6 on 2024-06-21 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_prod_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysourcetypejsonschema',
            name='has_fuel',
            field=models.BooleanField(
                db_comment='Whether or not this source type should collect fuel data. If true, add a fuel schema when buidling the form object',
                default=True,
            ),
        ),
        migrations.AddField(
            model_name='activitysourcetypejsonschema',
            name='has_unit',
            field=models.BooleanField(
                db_comment='Whether or not this source type should collect unit data. If true, add a unit schema when buidling the form object',
                default=True,
            ),
        ),
    ]
