# Generated by Django 5.0.6 on 2024-06-03 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_alter_address_table_comment_and_more'),
        ('reporting', '0002_sourcetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'operator_legal_name',
                    models.CharField(
                        db_comment='The legal name of the operator operating this operation', max_length=1000
                    ),
                ),
                (
                    'operator_trade_name',
                    models.CharField(
                        db_comment='The trade name of the operator operating this operation', max_length=1000
                    ),
                ),
                (
                    'operation_name',
                    models.CharField(db_comment='The name of the operation, for which this report is', max_length=1000),
                ),
                (
                    'operation_type',
                    models.CharField(
                        choices=[('sfo', 'Sfo'), ('lfo', 'Lfo')],
                        db_comment='The type of the operation, LFO or SFO',
                        max_length=1000,
                    ),
                ),
                (
                    'operation_bcghg_id',
                    models.CharField(
                        blank=True, db_comment='The BCGHGH ID of the operation', max_length=1000, null=True
                    ),
                ),
                (
                    'bc_obps_regulated_operation_id',
                    models.CharField(
                        db_comment='The BC OBPS Regulated Operation ID (BORO ID) for this operation', max_length=255
                    ),
                ),
                (
                    'operation_representative_name',
                    models.CharField(db_comment='The full name of the operation representative', max_length=1000),
                ),
                (
                    'report',
                    models.OneToOneField(
                        db_comment='The report this operation information relates to',
                        on_delete=django.db.models.deletion.CASCADE,
                        to='reporting.report',
                    ),
                ),
                ('reporting_activities', models.ManyToManyField(to='registration.reportingactivity')),
            ],
            options={
                'db_table': 'erc"."report_operation',
                'db_table_comment': 'A table to store operation information as part of a report',
            },
        ),
    ]
