# Generated by Django 5.0.6 on 2024-06-14 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0021_V1_6_0'),
        ('reporting', '0003_reportfacility_reportoperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='operation',
            field=models.ForeignKey(
                db_comment='The operation to which this report belongs',
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='registration.operation',
            ),
        ),
        migrations.AddField(
            model_name='report',
            name='reporting_year',
            field=models.IntegerField(db_comment='The reporting year for which this report was filed', default=2024),
        ),
    ]
