# Generated by Django 4.2.8 on 2024-05-08 18:19

from django.db import migrations
from reporting.migrations.data.gas_type_data import init_gas_type_data
from reporting.migrations.data.methodology_data import init_methodology_data
from reporting.migrations.data.source_type_data import init_source_type_data


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_configuration_configurationelement'),
    ]

    operations = [
        migrations.RunPython(init_source_type_data),
        migrations.RunPython(init_methodology_data),
        migrations.RunPython(init_gas_type_data),
    ]
