# Generated by Django 5.0.6 on 2024-06-27 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_alter_reportoperation_operator_trade_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportingyear',
            old_name='reporting_period_end',
            new_name='reporting_window_end',
        ),
        migrations.RenameField(
            model_name='reportingyear',
            old_name='reporting_period_start',
            new_name='reporting_window_start',
        ),
    ]
