# Generated by Django 4.2.8 on 2024-05-10 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_configuration_configurationelement'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='configurationelement',
            constraint=models.UniqueConstraint(
                fields=(
                    'reporting_activity',
                    'reporting_source_type',
                    'reporting_gas_type',
                    'reporting_methodology',
                    'valid_from',
                    'valid_to',
                ),
                name='unique_per_config',
            ),
        ),
    ]
