# Generated by Django 5.0.6 on 2024-06-28 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_V1_6_0'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SourceType',
        ),
    ]
