# Generated by Django 5.0.6 on 2024-06-18 17:02

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import reporting.models.configuration
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_remove_activitysourcetypebaseschema_unique_per_acivity_source_type_base_schema_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='configuration',
            name='exclude_overlapping_asb_records_by_date_range',
        ),
        migrations.AddConstraint(
            model_name='configuration',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[
                    (
                        reporting.models.configuration.TsTzRange(
                            'valid_from', 'valid_to', django.contrib.postgres.fields.ranges.RangeBoundary()
                        ),
                        '&&',
                    )
                ],
                name='exclude_overlapping_configuration_records_by_date_range',
            ),
        ),
    ]
