# Generated by Django 5.0.7 on 2024-08-13 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_delete_models'),
    ]

    operations = []
