# Generated by Django 5.0.6 on 2024-07-02 21:15

from django.db import migrations
from registration.models import ReportingActivity
from reporting.models import Configuration, ConfigurationElement, ReportingField, SourceType, GasType, Methodology


def init_configuration_data(apps, schema_monitor):
    '''
    Add initial data to erc.configuration
    '''

    Configuration = apps.get_model('reporting', 'Configuration')
    Configuration.objects.bulk_create([Configuration(slug='2024', valid_from='2024-01-01', valid_to='2099-12-31')])


def reverse_init_configuration_data(apps, schema_monitor):
    '''
    Remove initial data from erc.configuration
    '''
    Configuration = apps.get_model('reporting', 'Configuration')
    Configuration.objects.filter(slug__in=['2024']).delete()


def init_source_type_data(apps, schema_monitor):
    '''
    Add initial data to erc.sourcetype
    '''
    SourceType = apps.get_model('reporting', 'SourceType')
    SourceType.objects.bulk_create(
        [
            SourceType(name='General stationary combustion of fuel or waste with production of useful energy'),
            SourceType(name='General stationary combustion of waste without production of useful energy'),
            SourceType(name='Fuel combustion by mobile equipment that is part of the facility'),
            SourceType(
                name='Anode consumption in electrolysis cells, anode and cathode baking or green coke calcination'
            ),
            SourceType(name='Anode effects'),
            SourceType(name='Cover gas from electrolysis cells'),
            SourceType(name='Steam reformation or gasification of a hydrocarbon during ammonia production'),
            SourceType(
                name='Calcination of limestone, shale, sand, slag or other raw materials used to produce clinker, as well as the oxidization of organic carbon in the raw material'
            ),
            SourceType(name='Coal when broken or exposed to the atmosphere during mining'),
            SourceType(name='Stored coal piles'),
            SourceType(name='Removal of impurities using carbonate flux reagents'),
            SourceType(name='Use of reducing agents'),
            SourceType(
                name='Use of material (e.g., coke) for slag cleaning and the consumption of graphite or carbon electrodes'
            ),
            SourceType(name='The solvent extraction and electrowinning process, also known as SX-EW'),
            SourceType(name='Fuel combustion for electricity generation'),
            SourceType(name='Acid gas scrubbers and acid gas reagents'),
            SourceType(name='Cooling units'),
            SourceType(name='Geothermal geyser steam or fluids'),
            SourceType(name='Installation, maintenance, operation and decommission-ing of electrical equipment'),
            SourceType(
                name='Electronics manufacturing, including the cleaning of chemical vapour deposition chambers and plasma'
            ),
            SourceType(
                name='Removal of impurities using carbonate flux reagents, the use of reducing agents, the use of material (e.g. coke) for slag cleaning, and the consumption of graphite or carbon electrodes during ferroalloy production'
            ),
            SourceType(name='Calcination of carbonate materials'),
            SourceType(
                name='Steam reformation of hydrocarbons, partial oxidation of hydrocarbons or other transformation of hydrocarbon feedstock'
            ),
            SourceType(name='Industrial wastewater process using anaerobic digestion'),
            SourceType(name='Oil-water separators'),
            SourceType(name='Use of reducing agents during lead production'),
            SourceType(name='Calcination of carbonate materials in lime manufacturing'),
            SourceType(name='Use of reducing agents in magnesium production'),
            SourceType(name='Cover gases or carrier gases in magnesium production'),
            SourceType(
                name='Catalytic oxidation, condensation and absorption processes during nitric acid manufacturing'
            ),
            SourceType(name='Flares and oxidizers'),
            SourceType(name='Process vents'),
            SourceType(name='Equipment leaks'),
            SourceType(name='Ethylene production'),
            SourceType(name='Process units'),
            SourceType(name='Catalyst regeneration'),
            SourceType(name='Asphalt production'),
            SourceType(name='Sulphur recovery'),
            SourceType(
                name='Flares, the flare pilot, the combustion of purge gas and the destruction of low Btu gases'
            ),
            SourceType(name='Above-ground storage tanks at refineries'),
            SourceType(name='Oil-water separators at refineries'),
            SourceType(name='Equipment leaks at refineries'),
            SourceType(name='Wastewater processing using anaerobic digestion at refineries'),
            SourceType(name='Uncontrolled blowdown systems used at refineries'),
            SourceType(name='Loading operations at refineries and terminals'),
            SourceType(name='Delayed coking units at refineries'),
            SourceType(name='Coke calcining at refineries'),
            SourceType(name='Reaction of calcium carbonate with sulphuric acid'),
            SourceType(name='Pulping and chemical recovery'),
            SourceType(name='Combustion of refinery fuel gas, still gas, flexigas or associated gas'),
            SourceType(name='Use of reducing agents during zinc production'),
            SourceType(name='Above-ground storage tanks'),
            SourceType(name='Carbonates used but not consumed in other activities set out in column 2'),
            SourceType(
                name='General stationary combustion of fuel or waste at a linear facilities operation resulting in the production of useful energy'
            ),
            SourceType(
                name='General stationary combustion of fuel or waste at a linear facilities operation not resulting in the production of useful energy'
            ),
            SourceType(name='Field gas or process vent gas combustion at a linear facilities operation'),
            SourceType(name='Natural gas pneumatic high bleed device venting'),
            SourceType(name='Natural gas pneumatic pump venting'),
            SourceType(name='Natural gas pneumatic low bleed device venting'),
            SourceType(name='Natural gas pneumatic intermittent bleed device venting'),
            SourceType(name='Acid gas removal venting or incineration'),
            SourceType(name='Dehydrator venting'),
            SourceType(name='Blowdown venting'),
            SourceType(name='Releases from tanks used for storage, production or processing'),
            SourceType(name='Associated gas venting'),
            SourceType(name='Associated gas flaring'),
            SourceType(name='Flaring stacks'),
            SourceType(name='Centrifugal compressor venting'),
            SourceType(name='Reciprocating compressor venting'),
            SourceType(name='Equipment leaks detected using leak detection and leaker emission factor methods'),
            SourceType(name='Population count sources'),
            SourceType(name='Transmission storage tanks'),
            SourceType(name='Enhanced oil recovery injection pump blowdowns'),
            SourceType(name='Produced water dissolved carbon dioxide and methane'),
            SourceType(name='Enhanced oil recovery produced hydrocarbon liquids dissolved carbon dioxide'),
            SourceType(name='Other venting sources'),
            SourceType(name='Other fugitive sources'),
            SourceType(name='Third-party line hits with release of gas'),
            SourceType(name='Natural gas pneumatic high bleed device venting'),
            SourceType(name='Natural gas pneumatic pump venting'),
            SourceType(name='Dehydrator venting'),
            SourceType(name='Well venting for liquids unloading'),
            SourceType(
                name='Gas well venting during well completions and workovers with or without hydraulic fracturing'
            ),
            SourceType(name='Drilling flaring'),
            SourceType(name='Drilling venting'),
            SourceType(name='Hydraulic fracturing flaring'),
            SourceType(name='Well testing venting'),
            SourceType(name='Well testing flaring'),
            SourceType(name='Associated gas venting'),
            SourceType(name='Associated gas flaring'),
            SourceType(name='Centrifugal compressor venting'),
            SourceType(name='Reciprocating compressor venting'),
            SourceType(name='Equipment leaks detected using leak detection and leaker emission factor methods'),
            SourceType(name='Population count sources'),
            SourceType(name='Enhanced oil recovery injection pump blowdowns'),
            SourceType(name='Produced water dissolved carbon dioxide and methane'),
            SourceType(name='Enhanced oil recovery hydrocarbon liquids dissolved carbon dioxide'),
            SourceType(name='Other venting sources'),
            SourceType(name='Other fugitive sources'),
            SourceType(name='Third-party line hits with release of gas'),
            SourceType(name='Installation, maintenance, operation and decommissioning of electrical equipment'),
            SourceType(name='Flare stacks'),
            SourceType(name='Natural gas pneumatic low bleed device venting'),
            SourceType(name='Natural gas pneumatic intermittent bleed device venting'),
            SourceType(name='Blowdown venting'),
            SourceType(name='Transmission storage tanks'),
            SourceType(name='Natural gas pneumatic intermittent bleed device'),
            SourceType(name='Third party line hits with release of gas'),
        ]
    )


def reverse_init_source_type_data(apps, schema_monitor):
    '''
    Remove initial data from erc.reportingactivity
    '''
    SourceType = apps.get_model('reporting', 'SourceType')
    SourceType.objects.filter(
        name__in=[
            'General stationary combustion of fuel or waste with production of useful energy',
            'General stationary combustion of waste without production of useful energy',
            'Fuel combustion by mobile equipment that is part of the facility',
            'Anode consumption in electrolysis cells, anode and cathode baking or green coke calcination',
            'Anode effects',
            'Cover gas from electrolysis cells',
            'Steam reformation or gasification of a hydrocarbon during ammonia production',
            'Calcination of limestone, shale, sand, slag or other raw materials used to produce clinker, as well as the oxidization of organic carbon in the raw material',
            'Coal when broken or exposed to the atmosphere during mining',
            'Stored coal piles',
            'Removal of impurities using carbonate flux reagents',
            'Use of reducing agents',
            'Use of material (e.g., coke) for slag cleaning and the consumption of graphite or carbon electrodes',
            'The solvent extraction and electrowinning process, also known as SX-EW',
            'Fuel combustion for electricity generation',
            'Acid gas scrubbers and acid gas reagents',
            'Cooling units',
            'Geothermal geyser steam or fluids',
            'Installation, maintenance, operation and decommission-ing of electrical equipment',
            'Electronics manufacturing, including the cleaning of chemical vapour deposition chambers and plasma/dry etching processes',
            'Removal of impurities using carbonate flux reagents, the use of reducing agents, the use of material (e.g. coke) for slag cleaning, and the consumption of graphite or carbon electrodes during ferroalloy production',
            'Calcination of carbonate materials',
            'Steam reformation of hydrocarbons, partial oxidation of hydrocarbons or other transformation of hydrocarbon feedstock',
            'Industrial wastewater process using anaerobic digestion',
            'Oil-water separators',
            'Use of reducing agents during lead production',
            'Calcination of carbonate materials in lime manufacturing',
            'Use of reducing agents in magnesium production',
            'Cover gases or carrier gases in magnesium production',
            'Catalytic oxidation, condensation and absorption processes during nitric acid manufacturing',
            'Flares and oxidizers',
            'Process vents',
            'Equipment leaks',
            'Ethylene production',
            'Process units',
            'Catalyst regeneration',
            'Asphalt production',
            'Sulphur recovery',
            'Flares, the flare pilot, the combustion of purge gas and the destruction of low Btu gases',
            'Above-ground storage tanks at refineries',
            'Oil-water separators at refineries',
            'Equipment leaks at refineries',
            'Wastewater processing using anaerobic digestion at refineries',
            'Uncontrolled blowdown systems used at refineries',
            'Loading operations at refineries and terminals',
            'Delayed coking units at refineries',
            'Coke calcining at refineries',
            'Reaction of calcium carbonate with sulphuric acid',
            'Pulping and chemical recovery',
            'Combustion of refinery fuel gas, still gas, flexigas or associated gas',
            'Use of reducing agents during zinc production',
            'Above-ground storage tanks',
            'Carbonates used but not consumed in other activities set out in column 2',
            'General stationary combustion of fuel or waste at a linear facilities operation resulting in the production of useful energy',
            'General stationary combustion of fuel or waste at a linear facilities operation not resulting in the production of useful energy',
            'Field gas or process vent gas combustion at a linear facilities operation',
            'Natural gas pneumatic high bleed device venting',
            'Natural gas pneumatic pump venting',
            'Natural gas pneumatic low bleed device venting',
            'Natural gas pneumatic intermittent bleed device venting',
            'Acid gas removal venting or incineration',
            'Dehydrator venting',
            'Blowdown venting',
            'Releases from tanks used for storage, production or processing',
            'Associated gas venting',
            'Associated gas flaring',
            'Flaring stacks',
            'Centrifugal compressor venting',
            'Reciprocating compressor venting',
            'Equipment leaks detected using leak detection and leaker emission factor methods',
            'Population count sources',
            'Transmission storage tanks',
            'Enhanced oil recovery injection pump blowdowns',
            'Produced water dissolved carbon dioxide and methane',
            'Enhanced oil recovery produced hydrocarbon liquids dissolved carbon dioxide',
            'Other venting sources',
            'Other fugitive sources',
            'Third-party line hits with release of gas',
            'Natural gas pneumatic high bleed device venting',
            'Natural gas pneumatic pump venting',
            'Dehydrator venting',
            'Well venting for liquids unloading',
            'Gas well venting during well completions and workovers with or without hydraulic fracturing',
            'Drilling flaring',
            'Drilling venting',
            'Hydraulic fracturing flaring',
            'Well testing venting',
            'Well testing flaring',
            'Associated gas venting',
            'Associated gas flaring',
            'Centrifugal compressor venting',
            'Reciprocating compressor venting',
            'Equipment leaks detected using leak detection and leaker emission factor methods',
            'Population count sources',
            'Enhanced oil recovery injection pump blowdowns',
            'Produced water dissolved carbon dioxide and methane',
            'Enhanced oil recovery hydrocarbon liquids dissolved carbon dioxide',
            'Other venting sources',
            'Other fugitive sources',
            'Third-party line hits with release of gas',
            'Installation, maintenance, operation and decommissioning of electrical equipment',
            'Flare stacks',
            'Natural gas pneumatic low bleed device venting',
            'Natural gas pneumatic intermittent bleed device venting',
            'Blowdown venting',
            'Transmission storage tanks',
            'Natural gas pneumatic intermittent bleed device',
            'Third party line hits with release of gas',
        ]
    ).delete()


def init_gas_type_data(apps, schema_monitor):
    '''
    Add initial data to erc.gas_type
    '''
    GasType = apps.get_model('reporting', 'GasType')
    GasType.objects.bulk_create(
        [
            GasType(name='Carbon Dioxide', chemical_formula='CO2'),
            GasType(name='Nitrous Oxide', chemical_formula='N2O'),
            GasType(name='Methane', chemical_formula='CH4'),
            GasType(name='Sulfur Hexafluoride', chemical_formula='SF6'),
            GasType(name='Tetrafluoromethane', chemical_formula='CF4'),
            GasType(name='Perfluoroethane', chemical_formula='C2F6'),
            GasType(name='Difluoromethane', chemical_formula='CH2F2'),
            GasType(name='Pentafluoroethane', chemical_formula='C2HF5'),
            GasType(name='1,1,1,2-Tetrafluoroethane', chemical_formula='C2H2F4'),
        ]
    )


def reverse_init_gas_type_data(apps, schema_monitor):
    '''
    Remove initial data from erc.gas_type
    '''
    GasType = apps.get_model('reporting', 'GasType')
    GasType.objects.filter(
        chemical_formula__in=['CO2', 'N2O', 'CH4', 'SF6', 'CF4', 'C2F6', 'CH2F2', 'C2HF5', 'C2H2F4']
    ).delete()


def init_fuel_type_data(apps, schema_monitor):
    '''
    Add initial data to erc.fuel_type
    '''
    FuelType = apps.get_model('reporting', 'FuelType')
    FuelType.objects.bulk_create(
        [
            FuelType(name="Acetylene", unit="Sm^3"),
            FuelType(name="Agricultural Byproducts", unit="bone dry tonnes"),
            FuelType(name="ANFO", unit="tonnes"),
            FuelType(name="Anthracite Coal", unit="tonnes"),
            FuelType(name="Asphalt & Road Oil", unit="kilolitres"),
            FuelType(name="Aviation Gasoline", unit="kilolitres"),
            FuelType(name="Aviation Turbo Fuel", unit="kilolitres"),
            FuelType(name="Biodiesel (100%)", unit="kilolitres"),
            FuelType(name="Biogas (captured methane)", unit="Sm^3"),
            FuelType(name="Bituminous Coal", unit="tonnes"),
            FuelType(name="Bone char - organics", unit="tonnes"),
            FuelType(name="Butane", unit="kilolitres"),
            FuelType(name="Butylene", unit="kilolitres"),
            FuelType(name="Carpet fibre", unit="tonnes"),
            FuelType(name="Coal Coke", unit="tonnes"),
            FuelType(name="Coke Oven Gas", unit="Sm^3"),
            FuelType(name="Comubistlbe Tall Oil", unit="kilolitres"),
            FuelType(name="Concentrated Non-Condensible Gases (CNCGs)", unit="Sm^3"),
            FuelType(name="Crude Oil", unit="kilolitres"),
            FuelType(name="Crude Sulfate Turpentine (CST)", unit="kilolitres"),
            FuelType(name="Crude Tall Oil (CTO)", unit="kilolitres"),
            FuelType(name="Diesel", unit="kilolitres"),
            FuelType(name="Digester Gas", unit="Sm^3"),
            FuelType(name="Dilute non-condensible gases (DNCGs)", unit="Sm^3"),
            FuelType(name="Distilate Fuel Oil No.1", unit="kilolitres"),
            FuelType(name="Distilate Fuel Oil No.2", unit="kilolitres"),
            FuelType(name="Distilate Fuel Oil No.4", unit="kilolitres"),
            FuelType(name="Ethane", unit="kilolitres"),
            FuelType(name="Ethanol (100%)", unit="kilolitres"),
            FuelType(name="Ethylene", unit="kilolitres"),
            FuelType(name="E-waste", unit="tonnes"),
            FuelType(name="Explosives", unit="tonnes"),
            FuelType(name="Field gas", unit="Sm^3"),
            FuelType(name="Field gas or process vent gas", unit="Sm^3"),
            FuelType(name="Foreign Bituminous Coal", unit="tonnes"),
            FuelType(name="Gasoline", unit="kilolitres"),
            FuelType(name="Isobutane", unit="kilolitres"),
            FuelType(name="Isobutylene", unit="kilolitres"),
            FuelType(name="Kerosene", unit="kilolitres"),
            FuelType(name="Kerosene -type Jet Fuel", unit="kilolitres"),
            FuelType(name="Landfill Gas", unit="Sm^3"),
            FuelType(name="Light Fuel Oil", unit="kilolitres"),
            FuelType(name="Lignite", unit="tonnes"),
            FuelType(name="Liquified Petroleum Gases (LPG)", unit="kilolitres"),
            FuelType(name="Lubricants", unit="kilolitres"),
            FuelType(name="Motor Gasoline - Off-road", unit="kilolitres"),
            FuelType(name="Motor Gasoline", unit="kilolitres"),
            FuelType(name="Municipal Solid Waste - non-biomass component", unit="tonnes"),
            FuelType(name="Municipal Solide Waste - biomass component", unit="bone dry tonnes"),
            FuelType(name="Naphtha", unit="kilolitres"),
            FuelType(name="Natural Gas", unit="Sm^3"),
            FuelType(name="Natural Gasoline", unit="kilolitres"),
            FuelType(name="Nitrous Oxide", unit="Sm^3"),
            FuelType(name="Oily Rags", unit=""),
            FuelType(name="Peat", unit="bone dry tonnes"),
            FuelType(name="Petrochemical Feedstocks", unit="kilolitres"),
            FuelType(name="Petroleum Coke - Refinery Use", unit="kilolitres"),
            FuelType(name="Petroleum Coke - Upgrader Use", unit="kilolitres"),
            FuelType(name="Petroleum Coke", unit="kilolitres"),
            FuelType(name="Plastic Recycle", unit=""),
            FuelType(name="Plastics", unit="tonnes"),
            FuelType(name="Process vent gas", unit="Sm^3"),
            FuelType(name="Propane", unit="kilolitres"),
            FuelType(name="Propylene", unit="kilolitres"),
            FuelType(name="Refinery Fuel Gas - Type 1", unit="Sm^3"),
            FuelType(name="Refinery Fuel Gas - Type 2", unit="Flexigas, m^3"),
            FuelType(name="Refinery Fuel Gas", unit="Sm^3"),
            FuelType(name="Rendered Animal Fat", unit="kilolitres"),
            FuelType(name="Renewable diesel", unit="kilolitres"),
            FuelType(name="Renewable natural gas", unit="Sm^3"),
            FuelType(name="Residual Fuel Oil (#5 & 6)", unit="kilolitres"),
            FuelType(name="SMR PSA Tail Gas", unit="Sm^3"),
            FuelType(name="Sodium Bicarbonate", unit="tonnes"),
            FuelType(name="Solid Byproducts", unit="bone dry tonnes"),
            FuelType(name="Special substance X", unit=""),
            FuelType(name="Spent Pulping Liquor", unit="bone dry tonnes"),
            FuelType(name="Still Gas - Refineries", unit="Sm^3"),
            FuelType(name="Still Gas - Upgrader Use", unit="Sm^3"),
            FuelType(name="Still gas", unit="Sm^3"),
            FuelType(name="Sub-Bituminous Coal", unit="tonnes"),
            FuelType(name="Tail gas", unit="Sm^3"),
            FuelType(name="Tires - biomass component", unit="bone dry tonnes"),
            FuelType(name="Tires - non-biomass component", unit="tonnes"),
            FuelType(name="Trona", unit=""),
            FuelType(name="Turpentine", unit="kilolitres"),
            FuelType(name="Vegetable Oil", unit="kilolitres"),
            FuelType(name="Waste Plastics", unit=""),
            FuelType(name="Wood Waste", unit="bone dry tonnes"),
        ]
    )


def reverse_init_fuel_type_data(apps, schema_monitor):
    '''
    Remove initial data from erc.fuel_type
    '''
    FuelType = apps.get_model('reporting', 'FuelType')
    FuelType.objects.filter(
        name__in=[
            "Acetylene",
            "Agricultural Byproducts",
            "ANFO",
            "Anthracite Coal",
            "Asphalt & Road Oil",
            "Aviation Gasoline",
            "Aviation Turbo Fuel",
            "Biodiesel (100%)",
            "Biogas (captured methane)",
            "Bituminous Coal",
            "Bone char - organics",
            "Butane",
            "Butylene",
            "Carpet fibre",
            "Coal Coke",
            "Coke Oven Gas",
            "Comubistlbe Tall Oil",
            "Concentrated Non-Condensible Gases (CNCGs)",
            "Crude Oil",
            "Crude Sulfate Turpentine (CST)",
            "Crude Tall Oil (CTO)",
            "Diesel",
            "Digester Gas",
            "Dilute non-condensible gases (DNCGs)",
            "Distilate Fuel Oil No.1",
            "Distilate Fuel Oil No.2",
            "Distilate Fuel Oil No.4",
            "Ethane",
            "Ethanol (100%)",
            "Ethylene",
            "E-waste",
            "Explosives",
            "Field gas",
            "Field gas or process vent gas",
            "Foreign Bituminous Coal",
            "Gasoline",
            "Isobutane",
            "Isobutylene",
            "Kerosene",
            "Kerosene -type Jet Fuel",
            "Landfill Gas",
            "Light Fuel Oil",
            "Lignite",
            "Liquified Petroleum Gases",
            "Lubricants",
            "Motor Gasoline - Off-road",
            "Motor Gasoline",
            "Municipal Solid Waste - non-biomass component",
            "Municipal Solide Waste - biomass component",
            "Naphtha",
            "Natural Gas",
            "Natural Gasoline",
            "Nitrous Oxide",
            "Oily Rags",
            "Peat",
            "Petrochemical Feedstocks",
            "Petroleum Coke - Refinery Use",
            "Petroleum Coke - Upgrader Use",
            "Petroleum Coke",
            "Plastic Recycle",
            "Plastics",
            "Process vent gas",
            "Propane",
            "Propylene",
            "Refinery Fuel Gas - Type 1",
            "Refinery Fuel Gas - Type 2",
            "Refinery Fuel Gas",
            "Rendered Animal Fat",
            "Renewable diesel",
            "Renewable natural gas",
            "Residual Fuel Oil (#5 & 6)",
            "SMR PSA Tail Gas",
            "Sodium Bicarbonate",
            "Solid Byproducts",
            "Special substance X",
            "Spent Pulping Liquor",
            "Still Gas - Refineries",
            "Still Gas - Upgrader Use",
            "Still gas",
            "Sub-Bituminous Coal",
            "Tail gas",
            "Tires - biomass component",
            "Tires - non-biomass component",
            "Trona",
            "Turpentine",
            "Vegetable Oil",
            "Waste Plastics",
            "Wood Waste",
        ]
    ).delete()


def init_methodology_data(apps, schema_monitor):
    '''
    Add initial data to erc.methodology
    '''
    Methodology = apps.get_model('reporting', 'Methodology')
    Methodology.objects.bulk_create(
        [
            Methodology(name='Default HHV/Default EF'),
            Methodology(name='Default EF'),
            Methodology(name='Measured HHV/Default EF'),
            Methodology(name='Measured Steam/Default EF'),
            Methodology(name='Measured CC'),
            Methodology(name='Measured Steam/Measured EF'),
            Methodology(name='Alternative Parameter Measurement'),
            Methodology(name='Replacement Methodology'),
            Methodology(name='Anode Consumption'),
            Methodology(name='Slope method'),
            Methodology(name='Overvoltage method'),
            Methodology(name='C2F6 anode effects'),
            Methodology(name='Inventory'),
            Methodology(name='Input/output'),
            Methodology(name='Heat Input/Default EF'),
            Methodology(name='Measured EF'),
        ]
    )


def reverse_init_methodology_data(apps, schema_monitor):
    '''
    Remove initial data from erc.methodology
    '''
    Methodology = apps.get_model('reporting', 'Methodology')
    Methodology.objects.filter(
        name__in=[
            'Default HHV/Default EF'
            'Default EF'
            'Measured HHV/Default EF'
            'Measured Steam/Default EF'
            'Measured CC'
            'Measured Steam/Measured EF'
            'Alternative Parameter Measurement'
            'Replacement Methodology'
            'Anode Consumption'
            'Slope method'
            'Overvoltage method'
            'C2F6 anode effects'
            'Inventory'
            'Input/output'
            'Heat Input/Default EF'
            'Measured EF'
        ]
    ).delete()


def init_configuration_element_data(apps, schema_monitor):
    '''
    Add initial data to erc.configuration_element
    '''

    ConfigurationElement = apps.get_model('reporting', 'ConfigurationElement')
    # General stationary combustion of fuel or waste with production of useful energy
    ConfigurationElement.objects.bulk_create(
        [
            # CO2
            ConfigurationElement(
                reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
                source_type_id=SourceType.objects.get(
                    name='General stationary combustion of fuel or waste with production of useful energy'
                ).id,
                gas_type_id=GasType.objects.get(chemical_formula='CO2').id,
                methodology_id=Methodology.objects.get(name='Default HHV/Default EF').id,
                valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
                valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
            ),
            ConfigurationElement(
                reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
                source_type_id=SourceType.objects.get(
                    name='General stationary combustion of fuel or waste with production of useful energy'
                ).id,
                gas_type_id=GasType.objects.get(chemical_formula='CO2').id,
                methodology_id=Methodology.objects.get(name='Default EF').id,
                valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
                valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
            ),
            ConfigurationElement(
                reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
                source_type_id=SourceType.objects.get(
                    name='General stationary combustion of fuel or waste with production of useful energy'
                ).id,
                gas_type_id=GasType.objects.get(chemical_formula='CO2').id,
                methodology_id=Methodology.objects.get(name='Measured HHV/Default EF').id,
                valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
                valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
            ),
            ConfigurationElement(
                reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
                source_type_id=SourceType.objects.get(
                    name='General stationary combustion of fuel or waste with production of useful energy'
                ).id,
                gas_type_id=GasType.objects.get(chemical_formula='CO2').id,
                methodology_id=Methodology.objects.get(name='Measured Steam/Default EF').id,
                valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
                valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
            ),
            ConfigurationElement(
                reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
                source_type_id=SourceType.objects.get(
                    name='General stationary combustion of fuel or waste with production of useful energy'
                ).id,
                gas_type_id=GasType.objects.get(chemical_formula='CO2').id,
                methodology_id=Methodology.objects.get(name='Measured CC').id,
                valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
                valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
            ),
            ConfigurationElement(
                reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
                source_type_id=SourceType.objects.get(
                    name='General stationary combustion of fuel or waste with production of useful energy'
                ).id,
                gas_type_id=GasType.objects.get(chemical_formula='CO2').id,
                methodology_id=Methodology.objects.get(name='Measured Steam/Measured EF').id,
                valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
                valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
            ),
            ConfigurationElement(
                reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
                source_type_id=SourceType.objects.get(
                    name='General stationary combustion of fuel or waste with production of useful energy'
                ).id,
                gas_type_id=GasType.objects.get(chemical_formula='CO2').id,
                methodology_id=Methodology.objects.get(name='Alternative Parameter Measurement').id,
                valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
                valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
            ),
            ConfigurationElement(
                reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
                source_type_id=SourceType.objects.get(
                    name='General stationary combustion of fuel or waste with production of useful energy'
                ).id,
                gas_type_id=GasType.objects.get(chemical_formula='CO2').id,
                methodology_id=Methodology.objects.get(name='Replacement Methodology').id,
                valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
                valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
            ),
            # CH4
            ConfigurationElement(
                reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
                source_type_id=SourceType.objects.get(
                    name='General stationary combustion of fuel or waste with production of useful energy'
                ).id,
                gas_type_id=GasType.objects.get(chemical_formula='CH4').id,
                methodology_id=Methodology.objects.get(name='Default HHV/Default EF').id,
                valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
                valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
            ),
            ConfigurationElement(
                reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
                source_type_id=SourceType.objects.get(
                    name='General stationary combustion of fuel or waste with production of useful energy'
                ).id,
                gas_type_id=GasType.objects.get(chemical_formula='CH4').id,
                methodology_id=Methodology.objects.get(name='Default EF').id,
                valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
                valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
            ),
            ConfigurationElement(
                reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
                source_type_id=SourceType.objects.get(
                    name='General stationary combustion of fuel or waste with production of useful energy'
                ).id,
                gas_type_id=GasType.objects.get(chemical_formula='CH4').id,
                methodology_id=Methodology.objects.get(name='Measured HHV/Default EF').id,
                valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
                valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
            ),
            ConfigurationElement(
                reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
                source_type_id=SourceType.objects.get(
                    name='General stationary combustion of fuel or waste with production of useful energy'
                ).id,
                gas_type_id=GasType.objects.get(chemical_formula='CH4').id,
                methodology_id=Methodology.objects.get(name='Measured EF').id,
                valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
                valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
            ),
            ConfigurationElement(
                reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
                source_type_id=SourceType.objects.get(
                    name='General stationary combustion of fuel or waste with production of useful energy'
                ).id,
                gas_type_id=GasType.objects.get(chemical_formula='CH4').id,
                methodology_id=Methodology.objects.get(name='Measured Steam/Default EF').id,
                valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
                valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
            ),
            ConfigurationElement(
                reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
                source_type_id=SourceType.objects.get(
                    name='General stationary combustion of fuel or waste with production of useful energy'
                ).id,
                gas_type_id=GasType.objects.get(chemical_formula='CH4').id,
                methodology_id=Methodology.objects.get(name='Heat Input/Default EF').id,
                valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
                valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
            ),
            ConfigurationElement(
                reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
                source_type_id=SourceType.objects.get(
                    name='General stationary combustion of fuel or waste with production of useful energy'
                ).id,
                gas_type_id=GasType.objects.get(chemical_formula='CH4').id,
                methodology_id=Methodology.objects.get(name='Alternative Parameter Measurement').id,
                valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
                valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
            ),
            ConfigurationElement(
                reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
                source_type_id=SourceType.objects.get(
                    name='General stationary combustion of fuel or waste with production of useful energy'
                ).id,
                gas_type_id=GasType.objects.get(chemical_formula='CH4').id,
                methodology_id=Methodology.objects.get(name='Replacement Methodology').id,
                valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
                valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
            ),
            # N2O
            ConfigurationElement(
                reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
                source_type_id=SourceType.objects.get(
                    name='General stationary combustion of fuel or waste with production of useful energy'
                ).id,
                gas_type_id=GasType.objects.get(chemical_formula='N2O').id,
                methodology_id=Methodology.objects.get(name='Default HHV/Default EF').id,
                valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
                valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
            ),
            ConfigurationElement(
                reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
                source_type_id=SourceType.objects.get(
                    name='General stationary combustion of fuel or waste with production of useful energy'
                ).id,
                gas_type_id=GasType.objects.get(chemical_formula='N2O').id,
                methodology_id=Methodology.objects.get(name='Default EF').id,
                valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
                valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
            ),
            ConfigurationElement(
                reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
                source_type_id=SourceType.objects.get(
                    name='General stationary combustion of fuel or waste with production of useful energy'
                ).id,
                gas_type_id=GasType.objects.get(chemical_formula='N2O').id,
                methodology_id=Methodology.objects.get(name='Measured HHV/Default EF').id,
                valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
                valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
            ),
            ConfigurationElement(
                reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
                source_type_id=SourceType.objects.get(
                    name='General stationary combustion of fuel or waste with production of useful energy'
                ).id,
                gas_type_id=GasType.objects.get(chemical_formula='N2O').id,
                methodology_id=Methodology.objects.get(name='Measured EF').id,
                valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
                valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
            ),
            ConfigurationElement(
                reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
                source_type_id=SourceType.objects.get(
                    name='General stationary combustion of fuel or waste with production of useful energy'
                ).id,
                gas_type_id=GasType.objects.get(chemical_formula='N2O').id,
                methodology_id=Methodology.objects.get(name='Measured Steam/Default EF').id,
                valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
                valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
            ),
            ConfigurationElement(
                reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
                source_type_id=SourceType.objects.get(
                    name='General stationary combustion of fuel or waste with production of useful energy'
                ).id,
                gas_type_id=GasType.objects.get(chemical_formula='N2O').id,
                methodology_id=Methodology.objects.get(name='Heat Input/Default EF').id,
                valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
                valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
            ),
            ConfigurationElement(
                reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
                source_type_id=SourceType.objects.get(
                    name='General stationary combustion of fuel or waste with production of useful energy'
                ).id,
                gas_type_id=GasType.objects.get(chemical_formula='N2O').id,
                methodology_id=Methodology.objects.get(name='Alternative Parameter Measurement').id,
                valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
                valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
            ),
            ConfigurationElement(
                reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
                source_type_id=SourceType.objects.get(
                    name='General stationary combustion of fuel or waste with production of useful energy'
                ).id,
                gas_type_id=GasType.objects.get(chemical_formula='N2O').id,
                methodology_id=Methodology.objects.get(name='Replacement Methodology').id,
                valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
                valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
            ),
        ]
    )
    # General stationary combustion of waste without production of useful energy
    ConfigurationElement.objects.bulk_create(
        [
            # CO2
            ConfigurationElement(
                reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
                source_type_id=SourceType.objects.get(
                    name='General stationary combustion of waste without production of useful energy'
                ).id,
                gas_type_id=GasType.objects.get(chemical_formula='CO2').id,
                methodology_id=Methodology.objects.get(name='Default HHV/Default EF').id,
                valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
                valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
            ),
            ConfigurationElement(
                reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
                source_type_id=SourceType.objects.get(
                    name='General stationary combustion of waste without production of useful energy'
                ).id,
                gas_type_id=GasType.objects.get(chemical_formula='CO2').id,
                methodology_id=Methodology.objects.get(name='Default EF').id,
                valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
                valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
            ),
            ConfigurationElement(
                reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
                source_type_id=SourceType.objects.get(
                    name='General stationary combustion of waste without production of useful energy'
                ).id,
                gas_type_id=GasType.objects.get(chemical_formula='CO2').id,
                methodology_id=Methodology.objects.get(name='Measured HHV/Default EF').id,
                valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
                valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
            ),
            ConfigurationElement(
                reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
                source_type_id=SourceType.objects.get(
                    name='General stationary combustion of waste without production of useful energy'
                ).id,
                gas_type_id=GasType.objects.get(chemical_formula='CO2').id,
                methodology_id=Methodology.objects.get(name='Measured Steam/Default EF').id,
                valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
                valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
            ),
            ConfigurationElement(
                reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
                source_type_id=SourceType.objects.get(
                    name='General stationary combustion of waste without production of useful energy'
                ).id,
                gas_type_id=GasType.objects.get(chemical_formula='CO2').id,
                methodology_id=Methodology.objects.get(name='Measured CC').id,
                valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
                valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
            ),
            ConfigurationElement(
                reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
                source_type_id=SourceType.objects.get(
                    name='General stationary combustion of waste without production of useful energy'
                ).id,
                gas_type_id=GasType.objects.get(chemical_formula='CO2').id,
                methodology_id=Methodology.objects.get(name='Measured Steam/Measured EF').id,
                valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
                valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
            ),
            ConfigurationElement(
                reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
                source_type_id=SourceType.objects.get(
                    name='General stationary combustion of waste without production of useful energy'
                ).id,
                gas_type_id=GasType.objects.get(chemical_formula='CO2').id,
                methodology_id=Methodology.objects.get(name='Alternative Parameter Measurement').id,
                valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
                valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
            ),
            ConfigurationElement(
                reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
                source_type_id=SourceType.objects.get(
                    name='General stationary combustion of waste without production of useful energy'
                ).id,
                gas_type_id=GasType.objects.get(chemical_formula='CO2').id,
                methodology_id=Methodology.objects.get(name='Replacement Methodology').id,
                valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
                valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
            ),
            # CH4
            ConfigurationElement(
                reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
                source_type_id=SourceType.objects.get(
                    name='General stationary combustion of waste without production of useful energy'
                ).id,
                gas_type_id=GasType.objects.get(chemical_formula='CH4').id,
                methodology_id=Methodology.objects.get(name='Default HHV/Default EF').id,
                valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
                valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
            ),
            ConfigurationElement(
                reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
                source_type_id=SourceType.objects.get(
                    name='General stationary combustion of waste without production of useful energy'
                ).id,
                gas_type_id=GasType.objects.get(chemical_formula='CH4').id,
                methodology_id=Methodology.objects.get(name='Default EF').id,
                valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
                valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
            ),
            ConfigurationElement(
                reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
                source_type_id=SourceType.objects.get(
                    name='General stationary combustion of waste without production of useful energy'
                ).id,
                gas_type_id=GasType.objects.get(chemical_formula='CH4').id,
                methodology_id=Methodology.objects.get(name='Measured HHV/Default EF').id,
                valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
                valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
            ),
            ConfigurationElement(
                reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
                source_type_id=SourceType.objects.get(
                    name='General stationary combustion of waste without production of useful energy'
                ).id,
                gas_type_id=GasType.objects.get(chemical_formula='CH4').id,
                methodology_id=Methodology.objects.get(name='Measured EF').id,
                valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
                valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
            ),
            ConfigurationElement(
                reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
                source_type_id=SourceType.objects.get(
                    name='General stationary combustion of waste without production of useful energy'
                ).id,
                gas_type_id=GasType.objects.get(chemical_formula='CH4').id,
                methodology_id=Methodology.objects.get(name='Measured Steam/Default EF').id,
                valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
                valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
            ),
            ConfigurationElement(
                reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
                source_type_id=SourceType.objects.get(
                    name='General stationary combustion of waste without production of useful energy'
                ).id,
                gas_type_id=GasType.objects.get(chemical_formula='CH4').id,
                methodology_id=Methodology.objects.get(name='Heat Input/Default EF').id,
                valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
                valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
            ),
            ConfigurationElement(
                reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
                source_type_id=SourceType.objects.get(
                    name='General stationary combustion of waste without production of useful energy'
                ).id,
                gas_type_id=GasType.objects.get(chemical_formula='CH4').id,
                methodology_id=Methodology.objects.get(name='Alternative Parameter Measurement').id,
                valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
                valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
            ),
            ConfigurationElement(
                reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
                source_type_id=SourceType.objects.get(
                    name='General stationary combustion of waste without production of useful energy'
                ).id,
                gas_type_id=GasType.objects.get(chemical_formula='CH4').id,
                methodology_id=Methodology.objects.get(name='Replacement Methodology').id,
                valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
                valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
            ),
            # N2O
            ConfigurationElement(
                reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
                source_type_id=SourceType.objects.get(
                    name='General stationary combustion of waste without production of useful energy'
                ).id,
                gas_type_id=GasType.objects.get(chemical_formula='N2O').id,
                methodology_id=Methodology.objects.get(name='Default HHV/Default EF').id,
                valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
                valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
            ),
            ConfigurationElement(
                reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
                source_type_id=SourceType.objects.get(
                    name='General stationary combustion of waste without production of useful energy'
                ).id,
                gas_type_id=GasType.objects.get(chemical_formula='N2O').id,
                methodology_id=Methodology.objects.get(name='Default EF').id,
                valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
                valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
            ),
            ConfigurationElement(
                reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
                source_type_id=SourceType.objects.get(
                    name='General stationary combustion of waste without production of useful energy'
                ).id,
                gas_type_id=GasType.objects.get(chemical_formula='N2O').id,
                methodology_id=Methodology.objects.get(name='Measured HHV/Default EF').id,
                valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
                valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
            ),
            ConfigurationElement(
                reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
                source_type_id=SourceType.objects.get(
                    name='General stationary combustion of waste without production of useful energy'
                ).id,
                gas_type_id=GasType.objects.get(chemical_formula='N2O').id,
                methodology_id=Methodology.objects.get(name='Measured EF').id,
                valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
                valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
            ),
            ConfigurationElement(
                reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
                source_type_id=SourceType.objects.get(
                    name='General stationary combustion of waste without production of useful energy'
                ).id,
                gas_type_id=GasType.objects.get(chemical_formula='N2O').id,
                methodology_id=Methodology.objects.get(name='Measured Steam/Default EF').id,
                valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
                valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
            ),
            ConfigurationElement(
                reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
                source_type_id=SourceType.objects.get(
                    name='General stationary combustion of waste without production of useful energy'
                ).id,
                gas_type_id=GasType.objects.get(chemical_formula='N2O').id,
                methodology_id=Methodology.objects.get(name='Heat Input/Default EF').id,
                valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
                valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
            ),
            ConfigurationElement(
                reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
                source_type_id=SourceType.objects.get(
                    name='General stationary combustion of waste without production of useful energy'
                ).id,
                gas_type_id=GasType.objects.get(chemical_formula='N2O').id,
                methodology_id=Methodology.objects.get(name='Alternative Parameter Measurement').id,
                valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
                valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
            ),
            ConfigurationElement(
                reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
                source_type_id=SourceType.objects.get(
                    name='General stationary combustion of waste without production of useful energy'
                ).id,
                gas_type_id=GasType.objects.get(chemical_formula='N2O').id,
                methodology_id=Methodology.objects.get(name='Replacement Methodology').id,
                valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
                valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
            ),
        ]
    )


def reverse_init_configuration_element_data(apps, schema_monitor):
    '''
    Remove initial data from erc.configuration_element
    '''
    ASTBS = apps.get_model('reporting', 'ActivitySourceTypeBaseSchema')
    ASTBS.objects.filter(
        valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
        valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
    ).delete()


def init_reporting_field_data(apps, schema_monitor):
    '''
    Add initial data to erc.reporting_field
    '''

    ReportingField = apps.get_model('reporting', 'ReportingField')
    ReportingField.objects.bulk_create(
        [
            ReportingField(field_name='Fuel Default High Heating Value', field_type='number', field_units=None),
            ReportingField(
                field_name='Unit-Fuel-CO2 Default Emission Factor', field_type='number', field_units='kg/GJ'
            ),
            ReportingField(
                field_name='Unit-Fuel-CO2 Default Emission Factor', field_type='number', field_units='kg/fuel units'
            ),
            ReportingField(
                field_name='Fuel Annual Weighted Average High Heating Value', field_type='number', field_units=None
            ),
            ReportingField(field_name='Unit-Fuel Annual Steam Generated', field_type='number', field_units=None),
            ReportingField(field_name='Boiler Ratio', field_type='number', field_units=None),
            ReportingField(field_name='Unit-Fuel-CO2 Emission Factor', field_type='number', field_units='kg/GJ'),
            ReportingField(
                field_name='Fuel Annual Weighted Average Carbon Content (weight fraction)',
                field_type='number',
                field_units=None,
            ),
            ReportingField(field_name='Unit-Fuel-CO2 Measured Emission Factor', field_type='number', field_units=None),
            ReportingField(field_name='Description', field_type='string', field_units=None),
            ReportingField(
                field_name='Unit-Fuel-CH4 Default Emission Factor', field_type='number', field_units='kg/GJ'
            ),
            ReportingField(
                field_name='Unit-Fuel-CH4 Default Emission Factor', field_type='number', field_units='kg/fuel units'
            ),
            ReportingField(
                field_name='Unit-Fuel-CH4 Measured Emission Factor', field_type='number', field_units='kg/fuel units'
            ),
            ReportingField(field_name='Unit-Fuel Heat Input', field_type='number', field_units=None),
            ReportingField(
                field_name='Unit-Fuel-N2O Default Emission Factor', field_type='number', field_units='kg/GJ'
            ),
            ReportingField(
                field_name='Unit-Fuel-N2O Default Emission Factor', field_type='number', field_units='kg/fuel units'
            ),
            ReportingField(
                field_name='Unit-Fuel-N2O Measured Emission Factor', field_type='number', field_units='kg/fuel units'
            ),
        ]
    )


def reverse_init_reporting_field_data(apps, schema_monitor):
    '''
    Remove initial data from erc.reporting_field
    '''
    ReportingField = apps.get_model('reporting', 'ReportingField')
    ReportingField.objects.filter(
        field_name__in=[
            'Unit-Fuel-CO2 Measured Emission Factor'
            'Unit-Fuel Heat Input'
            'Unit-Fuel-CO2 Default Emission Factor'
            'Unit-Fuel-CH4 Measured Emission Factor'
            'Unit-Fuel Annual Steam Generated'
            'Description'
            'Unit-Fuel-CO2 Emission Factor'
            'Boiler Ratio'
            'Unit-Fuel-N2O Default Emission Factor'
            'Unit-Fuel-CH4 Default Emission Factor'
            'Fuel Annual Weighted Average High Heating Value'
            'Unit-Fuel-N2O Measured Emission Factor'
            'Fuel Default High Heating Value'
            'Fuel Annual Weighted Average Carbon Content (weight fraction)'
        ]
    ).delete()


def init_configuration_element_reporting_fields_data(apps, schema_monitor):
    '''
    Add initial data to erc.activity_source_type_base_schema
    '''
    # CO2 - Default HHV/Default EF - Fuel Default High Heating Value
    ConfigurationElement.objects.get(
        reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
        source_type_id=SourceType.objects.get(
            name='General stationary combustion of fuel or waste with production of useful energy'
        ).id,
        gas_type_id=GasType.objects.get(chemical_formula='CO2').id,
        methodology_id=Methodology.objects.get(name='Default HHV/Default EF').id,
        valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
        valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
    ).reporting_fields.add(
        ReportingField.objects.get(field_name='Fuel Default High Heating Value', field_units__isnull=True)
    )
    # CO2 - Default HHV/Default EF - Unit-Fuel-CO2 Default Emission Factor
    ConfigurationElement.objects.get(
        reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
        source_type_id=SourceType.objects.get(
            name='General stationary combustion of fuel or waste with production of useful energy'
        ).id,
        gas_type_id=GasType.objects.get(chemical_formula='CO2').id,
        methodology_id=Methodology.objects.get(name='Default HHV/Default EF').id,
        valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
        valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
    ).reporting_fields.add(
        ReportingField.objects.get(field_name='Unit-Fuel-CO2 Default Emission Factor', field_units='kg/GJ')
    )
    # CO2 - Default EF - Unit-Fuel-CO2 Default Emission Factor
    ConfigurationElement.objects.get(
        reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
        source_type_id=SourceType.objects.get(
            name='General stationary combustion of fuel or waste with production of useful energy'
        ).id,
        gas_type_id=GasType.objects.get(chemical_formula='CO2').id,
        methodology_id=Methodology.objects.get(name='Default EF').id,
        valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
        valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
    ).reporting_fields.add(
        ReportingField.objects.get(field_name='Unit-Fuel-CO2 Default Emission Factor', field_units='kg/fuel units')
    )
    # CO2 - Measured HHV/Default EF - Fuel Annual Weighted Average High Heating Value
    ConfigurationElement.objects.get(
        reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
        source_type_id=SourceType.objects.get(
            name='General stationary combustion of fuel or waste with production of useful energy'
        ).id,
        gas_type_id=GasType.objects.get(chemical_formula='CO2').id,
        methodology_id=Methodology.objects.get(name='Measured HHV/Default EF').id,
        valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
        valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
    ).reporting_fields.add(
        ReportingField.objects.get(
            field_name='Fuel Annual Weighted Average High Heating Value', field_units__isnull=True
        )
    )
    # CO2 - Measured HHV/Default EF - Unit-Fuel-CO2 Default Emission Factor
    ConfigurationElement.objects.get(
        reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
        source_type_id=SourceType.objects.get(
            name='General stationary combustion of fuel or waste with production of useful energy'
        ).id,
        gas_type_id=GasType.objects.get(chemical_formula='CO2').id,
        methodology_id=Methodology.objects.get(name='Measured HHV/Default EF').id,
        valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
        valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
    ).reporting_fields.add(
        ReportingField.objects.get(field_name='Unit-Fuel-CO2 Default Emission Factor', field_units='kg/GJ')
    )
    # CO2 - Measured Steam/Default EF - Unit-Fuel Annual Steam Generated
    ConfigurationElement.objects.get(
        reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
        source_type_id=SourceType.objects.get(
            name='General stationary combustion of fuel or waste with production of useful energy'
        ).id,
        gas_type_id=GasType.objects.get(chemical_formula='CO2').id,
        methodology_id=Methodology.objects.get(name='Measured Steam/Default EF').id,
        valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
        valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
    ).reporting_fields.add(
        ReportingField.objects.get(field_name='Unit-Fuel Annual Steam Generated', field_units__isnull=True)
    )
    # CO2 - Measured Steam/Default EF - Boiler Ratio
    ConfigurationElement.objects.get(
        reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
        source_type_id=SourceType.objects.get(
            name='General stationary combustion of fuel or waste with production of useful energy'
        ).id,
        gas_type_id=GasType.objects.get(chemical_formula='CO2').id,
        methodology_id=Methodology.objects.get(name='Measured Steam/Default EF').id,
        valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
        valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
    ).reporting_fields.add(ReportingField.objects.get(field_name='Boiler Ratio', field_units__isnull=True))
    # CO2 - Measured Steam/Default EF - Unit-Fuel-CO2 Emission Factor
    ConfigurationElement.objects.get(
        reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
        source_type_id=SourceType.objects.get(
            name='General stationary combustion of fuel or waste with production of useful energy'
        ).id,
        gas_type_id=GasType.objects.get(chemical_formula='CO2').id,
        methodology_id=Methodology.objects.get(name='Measured Steam/Default EF').id,
        valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
        valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
    ).reporting_fields.add(ReportingField.objects.get(field_name='Unit-Fuel-CO2 Emission Factor', field_units='kg/GJ'))
    # CO2 - Measured CC - Fuel Annual Weighted Average Carbon Content (weight fraction)
    ConfigurationElement.objects.get(
        reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
        source_type_id=SourceType.objects.get(
            name='General stationary combustion of fuel or waste with production of useful energy'
        ).id,
        gas_type_id=GasType.objects.get(chemical_formula='CO2').id,
        methodology_id=Methodology.objects.get(name='Measured CC').id,
        valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
        valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
    ).reporting_fields.add(
        ReportingField.objects.get(
            field_name='Fuel Annual Weighted Average Carbon Content (weight fraction)', field_units__isnull=True
        )
    )
    # CO2 - Measured Steam/Measured EF - Unit-Fuel Annual Steam Generated
    ConfigurationElement.objects.get(
        reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
        source_type_id=SourceType.objects.get(
            name='General stationary combustion of fuel or waste with production of useful energy'
        ).id,
        gas_type_id=GasType.objects.get(chemical_formula='CO2').id,
        methodology_id=Methodology.objects.get(name='Measured Steam/Measured EF').id,
        valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
        valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
    ).reporting_fields.add(
        ReportingField.objects.get(field_name='Unit-Fuel Annual Steam Generated', field_units__isnull=True)
    )
    # CO2 - Measured Steam/Measured EF - Unit-Fuel-CO2 Measured Emission Factor
    ConfigurationElement.objects.get(
        reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
        source_type_id=SourceType.objects.get(
            name='General stationary combustion of fuel or waste with production of useful energy'
        ).id,
        gas_type_id=GasType.objects.get(chemical_formula='CO2').id,
        methodology_id=Methodology.objects.get(name='Measured Steam/Measured EF').id,
        valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
        valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
    ).reporting_fields.add(
        ReportingField.objects.get(field_name='Unit-Fuel-CO2 Measured Emission Factor', field_units__isnull=True)
    )
    # CO2 - Alternative Parameter Measurement - Description
    ConfigurationElement.objects.get(
        reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
        source_type_id=SourceType.objects.get(
            name='General stationary combustion of fuel or waste with production of useful energy'
        ).id,
        gas_type_id=GasType.objects.get(chemical_formula='CO2').id,
        methodology_id=Methodology.objects.get(name='Alternative Parameter Measurement').id,
        valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
        valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
    ).reporting_fields.add(ReportingField.objects.get(field_name='Description', field_units__isnull=True))
    # CO2 - Replacement Methodology - Description
    ConfigurationElement.objects.get(
        reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
        source_type_id=SourceType.objects.get(
            name='General stationary combustion of fuel or waste with production of useful energy'
        ).id,
        gas_type_id=GasType.objects.get(chemical_formula='CO2').id,
        methodology_id=Methodology.objects.get(name='Replacement Methodology').id,
        valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
        valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
    ).reporting_fields.add(ReportingField.objects.get(field_name='Description', field_units__isnull=True))

    # #CH4 - Default HHV/Default EF - Fuel Default High Heating Value
    ConfigurationElement.objects.get(
        reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
        source_type_id=SourceType.objects.get(
            name='General stationary combustion of fuel or waste with production of useful energy'
        ).id,
        gas_type_id=GasType.objects.get(chemical_formula='CH4').id,
        methodology_id=Methodology.objects.get(name='Default HHV/Default EF').id,
        valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
        valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
    ).reporting_fields.add(
        ReportingField.objects.get(field_name='Fuel Default High Heating Value', field_units__isnull=True)
    )
    # CH4 - Default HHV/Default EF - Unit-Fuel-CH4 Default Emission Factor
    ConfigurationElement.objects.get(
        reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
        source_type_id=SourceType.objects.get(
            name='General stationary combustion of fuel or waste with production of useful energy'
        ).id,
        gas_type_id=GasType.objects.get(chemical_formula='CH4').id,
        methodology_id=Methodology.objects.get(name='Default HHV/Default EF').id,
        valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
        valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
    ).reporting_fields.add(
        ReportingField.objects.get(field_name='Unit-Fuel-CH4 Default Emission Factor', field_units='kg/GJ')
    )
    # CH4 - Default EF - Unit-Fuel-CH4 Default Emission Factor
    ConfigurationElement.objects.get(
        reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
        source_type_id=SourceType.objects.get(
            name='General stationary combustion of fuel or waste with production of useful energy'
        ).id,
        gas_type_id=GasType.objects.get(chemical_formula='CH4').id,
        methodology_id=Methodology.objects.get(name='Default EF').id,
        valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
        valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
    ).reporting_fields.add(
        ReportingField.objects.get(field_name='Unit-Fuel-CH4 Default Emission Factor', field_units='kg/fuel units')
    )
    # CH4 - Measured HHV/Default EF - Fuel Annual Weighted Average High Heating Value
    ConfigurationElement.objects.get(
        reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
        source_type_id=SourceType.objects.get(
            name='General stationary combustion of fuel or waste with production of useful energy'
        ).id,
        gas_type_id=GasType.objects.get(chemical_formula='CH4').id,
        methodology_id=Methodology.objects.get(name='Measured HHV/Default EF').id,
        valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
        valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
    ).reporting_fields.add(
        ReportingField.objects.get(
            field_name='Fuel Annual Weighted Average High Heating Value', field_units__isnull=True
        )
    )
    # CH4 - Measured HHV/Default EF - Unit-Fuel-CH4 Default Emission Factor
    ConfigurationElement.objects.get(
        reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
        source_type_id=SourceType.objects.get(
            name='General stationary combustion of fuel or waste with production of useful energy'
        ).id,
        gas_type_id=GasType.objects.get(chemical_formula='CH4').id,
        methodology_id=Methodology.objects.get(name='Measured HHV/Default EF').id,
        valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
        valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
    ).reporting_fields.add(
        ReportingField.objects.get(field_name='Unit-Fuel-CH4 Default Emission Factor', field_units='kg/GJ')
    )
    # CH4 - Measured EF - Unit-Fuel-CH4 Measured Emission Factor
    ConfigurationElement.objects.get(
        reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
        source_type_id=SourceType.objects.get(
            name='General stationary combustion of fuel or waste with production of useful energy'
        ).id,
        gas_type_id=GasType.objects.get(chemical_formula='CH4').id,
        methodology_id=Methodology.objects.get(name='Measured EF').id,
        valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
        valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
    ).reporting_fields.add(
        ReportingField.objects.get(field_name='Unit-Fuel-CH4 Measured Emission Factor', field_units='kg/fuel units')
    )
    # CH4 - Measured Steam/Default EF - Unit-Fuel Annual Steam Generated
    ConfigurationElement.objects.get(
        reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
        source_type_id=SourceType.objects.get(
            name='General stationary combustion of fuel or waste with production of useful energy'
        ).id,
        gas_type_id=GasType.objects.get(chemical_formula='CH4').id,
        methodology_id=Methodology.objects.get(name='Measured Steam/Default EF').id,
        valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
        valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
    ).reporting_fields.add(
        ReportingField.objects.get(field_name='Unit-Fuel Annual Steam Generated', field_units__isnull=True)
    )
    # CH4 - Measured Steam/Default EF - Boiler Ratio
    ConfigurationElement.objects.get(
        reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
        source_type_id=SourceType.objects.get(
            name='General stationary combustion of fuel or waste with production of useful energy'
        ).id,
        gas_type_id=GasType.objects.get(chemical_formula='CH4').id,
        methodology_id=Methodology.objects.get(name='Measured Steam/Default EF').id,
        valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
        valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
    ).reporting_fields.add(ReportingField.objects.get(field_name='Boiler Ratio', field_units__isnull=True))
    # CH4 - Measured Steam/Default EF - Unit-Fuel-CH4 Default Emission Factor
    ConfigurationElement.objects.get(
        reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
        source_type_id=SourceType.objects.get(
            name='General stationary combustion of fuel or waste with production of useful energy'
        ).id,
        gas_type_id=GasType.objects.get(chemical_formula='CH4').id,
        methodology_id=Methodology.objects.get(name='Measured Steam/Default EF').id,
        valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
        valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
    ).reporting_fields.add(
        ReportingField.objects.get(field_name='Unit-Fuel-CH4 Default Emission Factor', field_units='kg/GJ')
    )
    # CH4 - Heat Input/Default EF - Unit-Fuel Heat Input
    ConfigurationElement.objects.get(
        reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
        source_type_id=SourceType.objects.get(
            name='General stationary combustion of fuel or waste with production of useful energy'
        ).id,
        gas_type_id=GasType.objects.get(chemical_formula='CH4').id,
        methodology_id=Methodology.objects.get(name='Heat Input/Default EF').id,
        valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
        valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
    ).reporting_fields.add(ReportingField.objects.get(field_name='Unit-Fuel Heat Input', field_units__isnull=True))
    # CH4 - Heat Input/Default EF - Unit-Fuel-CH4 Default Emission Factor
    ConfigurationElement.objects.get(
        reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
        source_type_id=SourceType.objects.get(
            name='General stationary combustion of fuel or waste with production of useful energy'
        ).id,
        gas_type_id=GasType.objects.get(chemical_formula='CH4').id,
        methodology_id=Methodology.objects.get(name='Heat Input/Default EF').id,
        valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
        valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
    ).reporting_fields.add(
        ReportingField.objects.get(field_name='Unit-Fuel-CH4 Default Emission Factor', field_units='kg/GJ')
    )
    # CH4 - Alternative Parameter Measurement - Description
    ConfigurationElement.objects.get(
        reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
        source_type_id=SourceType.objects.get(
            name='General stationary combustion of fuel or waste with production of useful energy'
        ).id,
        gas_type_id=GasType.objects.get(chemical_formula='CH4').id,
        methodology_id=Methodology.objects.get(name='Alternative Parameter Measurement').id,
        valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
        valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
    ).reporting_fields.add(ReportingField.objects.get(field_name='Description', field_units__isnull=True))
    # CH4 - Replacement Methodology - Description
    ConfigurationElement.objects.get(
        reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
        source_type_id=SourceType.objects.get(
            name='General stationary combustion of fuel or waste with production of useful energy'
        ).id,
        gas_type_id=GasType.objects.get(chemical_formula='CH4').id,
        methodology_id=Methodology.objects.get(name='Replacement Methodology').id,
        valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
        valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
    ).reporting_fields.add(ReportingField.objects.get(field_name='Description', field_units__isnull=True))

    # N2O - Default HHV/Default EF - Fuel Default High Heating Value
    ConfigurationElement.objects.get(
        reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
        source_type_id=SourceType.objects.get(
            name='General stationary combustion of fuel or waste with production of useful energy'
        ).id,
        gas_type_id=GasType.objects.get(chemical_formula='N2O').id,
        methodology_id=Methodology.objects.get(name='Default HHV/Default EF').id,
        valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
        valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
    ).reporting_fields.add(
        ReportingField.objects.get(field_name='Fuel Default High Heating Value', field_units__isnull=True)
    )
    # N2O - Default HHV/Default EF - Unit-Fuel-N2O Default Emission Factor
    ConfigurationElement.objects.get(
        reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
        source_type_id=SourceType.objects.get(
            name='General stationary combustion of fuel or waste with production of useful energy'
        ).id,
        gas_type_id=GasType.objects.get(chemical_formula='N2O').id,
        methodology_id=Methodology.objects.get(name='Default HHV/Default EF').id,
        valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
        valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
    ).reporting_fields.add(
        ReportingField.objects.get(field_name='Unit-Fuel-N2O Default Emission Factor', field_units='kg/GJ')
    )
    # N2O - Default EF - Unit-Fuel-N2O Default Emission Factor
    ConfigurationElement.objects.get(
        reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
        source_type_id=SourceType.objects.get(
            name='General stationary combustion of fuel or waste with production of useful energy'
        ).id,
        gas_type_id=GasType.objects.get(chemical_formula='N2O').id,
        methodology_id=Methodology.objects.get(name='Default EF').id,
        valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
        valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
    ).reporting_fields.add(
        ReportingField.objects.get(field_name='Unit-Fuel-N2O Default Emission Factor', field_units='kg/fuel units')
    )
    # N2O - Measured HHV/Default EF - Fuel Annual Weighted Average High Heating Value
    ConfigurationElement.objects.get(
        reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
        source_type_id=SourceType.objects.get(
            name='General stationary combustion of fuel or waste with production of useful energy'
        ).id,
        gas_type_id=GasType.objects.get(chemical_formula='N2O').id,
        methodology_id=Methodology.objects.get(name='Measured HHV/Default EF').id,
        valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
        valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
    ).reporting_fields.add(
        ReportingField.objects.get(
            field_name='Fuel Annual Weighted Average High Heating Value', field_units__isnull=True
        )
    )
    # N2O - Measured HHV/Default EF - Unit-Fuel-N2O Default Emission Factor
    ConfigurationElement.objects.get(
        reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
        source_type_id=SourceType.objects.get(
            name='General stationary combustion of fuel or waste with production of useful energy'
        ).id,
        gas_type_id=GasType.objects.get(chemical_formula='N2O').id,
        methodology_id=Methodology.objects.get(name='Measured HHV/Default EF').id,
        valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
        valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
    ).reporting_fields.add(
        ReportingField.objects.get(field_name='Unit-Fuel-N2O Default Emission Factor', field_units='kg/GJ')
    )
    # N2O - Measured EF - Unit-Fuel-N2O Measured Emission Factor
    ConfigurationElement.objects.get(
        reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
        source_type_id=SourceType.objects.get(
            name='General stationary combustion of fuel or waste with production of useful energy'
        ).id,
        gas_type_id=GasType.objects.get(chemical_formula='N2O').id,
        methodology_id=Methodology.objects.get(name='Measured EF').id,
        valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
        valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
    ).reporting_fields.add(
        ReportingField.objects.get(field_name='Unit-Fuel-N2O Measured Emission Factor', field_units='kg/fuel units')
    )
    # N2O - Measured Steam/Default EF - Unit-Fuel Annual Steam Generated
    ConfigurationElement.objects.get(
        reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
        source_type_id=SourceType.objects.get(
            name='General stationary combustion of fuel or waste with production of useful energy'
        ).id,
        gas_type_id=GasType.objects.get(chemical_formula='N2O').id,
        methodology_id=Methodology.objects.get(name='Measured Steam/Default EF').id,
        valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
        valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
    ).reporting_fields.add(
        ReportingField.objects.get(field_name='Unit-Fuel Annual Steam Generated', field_units__isnull=True)
    )
    # N2O - Measured Steam/Default EF - Boiler Ratio
    ConfigurationElement.objects.get(
        reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
        source_type_id=SourceType.objects.get(
            name='General stationary combustion of fuel or waste with production of useful energy'
        ).id,
        gas_type_id=GasType.objects.get(chemical_formula='N2O').id,
        methodology_id=Methodology.objects.get(name='Measured Steam/Default EF').id,
        valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
        valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
    ).reporting_fields.add(ReportingField.objects.get(field_name='Boiler Ratio', field_units__isnull=True))
    # N2O - Measured Steam/Default EF - Unit-Fuel-N2O Default Emission Factor
    ConfigurationElement.objects.get(
        reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
        source_type_id=SourceType.objects.get(
            name='General stationary combustion of fuel or waste with production of useful energy'
        ).id,
        gas_type_id=GasType.objects.get(chemical_formula='N2O').id,
        methodology_id=Methodology.objects.get(name='Measured Steam/Default EF').id,
        valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
        valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
    ).reporting_fields.add(
        ReportingField.objects.get(field_name='Unit-Fuel-N2O Default Emission Factor', field_units='kg/GJ')
    )
    # N2O - Heat Input/Default EF - Unit-Fuel Heat Input
    ConfigurationElement.objects.get(
        reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
        source_type_id=SourceType.objects.get(
            name='General stationary combustion of fuel or waste with production of useful energy'
        ).id,
        gas_type_id=GasType.objects.get(chemical_formula='N2O').id,
        methodology_id=Methodology.objects.get(name='Heat Input/Default EF').id,
        valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
        valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
    ).reporting_fields.add(ReportingField.objects.get(field_name='Unit-Fuel Heat Input', field_units__isnull=True))
    # N2O - Heat Input/Default EF - Unit-Fuel-N2O Default Emission Factor
    ConfigurationElement.objects.get(
        reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
        source_type_id=SourceType.objects.get(
            name='General stationary combustion of fuel or waste with production of useful energy'
        ).id,
        gas_type_id=GasType.objects.get(chemical_formula='N2O').id,
        methodology_id=Methodology.objects.get(name='Heat Input/Default EF').id,
        valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
        valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
    ).reporting_fields.add(
        ReportingField.objects.get(field_name='Unit-Fuel-N2O Default Emission Factor', field_units='kg/GJ')
    )
    # N2O - Alternative Parameter Measurement - Description
    ConfigurationElement.objects.get(
        reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
        source_type_id=SourceType.objects.get(
            name='General stationary combustion of fuel or waste with production of useful energy'
        ).id,
        gas_type_id=GasType.objects.get(chemical_formula='N2O').id,
        methodology_id=Methodology.objects.get(name='Alternative Parameter Measurement').id,
        valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
        valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
    ).reporting_fields.add(ReportingField.objects.get(field_name='Description', field_units__isnull=True))
    # N2O - Replacement Methodology - Description
    ConfigurationElement.objects.get(
        reporting_activity_id=ReportingActivity.objects.get(name='General stationary combustion').id,
        source_type_id=SourceType.objects.get(
            name='General stationary combustion of fuel or waste with production of useful energy'
        ).id,
        gas_type_id=GasType.objects.get(chemical_formula='N2O').id,
        methodology_id=Methodology.objects.get(name='Replacement Methodology').id,
        valid_from_id=Configuration.objects.get(valid_from='2024-01-01').id,
        valid_to_id=Configuration.objects.get(valid_to='2099-12-31').id,
    ).reporting_fields.add(ReportingField.objects.get(field_name='Description', field_units__isnull=True))


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0006_reinit'),
    ]

    operations = [
        migrations.RunPython(init_source_type_data, reverse_init_source_type_data),
        migrations.RunPython(init_gas_type_data, reverse_init_gas_type_data),
        migrations.RunPython(init_fuel_type_data, reverse_init_fuel_type_data),
        migrations.RunPython(init_methodology_data, reverse_init_methodology_data),
        migrations.RunPython(init_configuration_data, reverse_init_configuration_data),
        migrations.RunPython(init_configuration_element_data, reverse_init_configuration_element_data),
        migrations.RunPython(init_reporting_field_data, reverse_init_reporting_field_data),
        migrations.RunPython(init_configuration_element_reporting_fields_data),
    ]
