# Generated by Django 5.0.7 on 2024-07-22 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0022_remove_historicalwellauthorizationnumber_facility_and_more'),
        ('reporting', '0008_general_stationary_combustion_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'json_data',
                    models.JSONField(db_comment='A flat JSON object representing the data collected for this model'),
                ),
                (
                    'activity',
                    models.ForeignKey(
                        db_comment='The reporting activity this data applies to',
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='registration.reportingactivity',
                    ),
                ),
                (
                    'activity_base_schema',
                    models.ForeignKey(
                        db_comment='The activity base schema used to render the form that collected this data',
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='reporting.activityjsonschema',
                    ),
                ),
                (
                    'report_version_id',
                    models.ForeignKey(
                        db_comment='The report version this data belongs to',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='+',
                        to='reporting.reportversion',
                    ),
                ),
            ],
            options={
                'db_table': 'erc"."report_activity',
                'db_table_comment': 'A table to store the reported activity-specific data, in a JSON format',
            },
        ),
        migrations.CreateModel(
            name='ReportFuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'json_data',
                    models.JSONField(db_comment='A flat JSON object representing the data collected for this model'),
                ),
                (
                    'fuel_type',
                    models.ForeignKey(
                        db_comment='The fuel type this data applies to',
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='reporting.fueltype',
                    ),
                ),
                (
                    'report_version_id',
                    models.ForeignKey(
                        db_comment='The report version this data belongs to',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='+',
                        to='reporting.reportversion',
                    ),
                ),
            ],
            options={
                'db_table': 'erc"."report_fuel',
                'db_table_comment': 'A table to store the reported activity-specific data, in a JSON format',
            },
        ),
        migrations.CreateModel(
            name='ReportEmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'json_data',
                    models.JSONField(db_comment='A flat JSON object representing the data collected for this model'),
                ),
                (
                    'gas_type',
                    models.ForeignKey(
                        db_comment='The gas type this emission data applies to',
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='reporting.gastype',
                    ),
                ),
                (
                    'report_version_id',
                    models.ForeignKey(
                        db_comment='The report version this data belongs to',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='+',
                        to='reporting.reportversion',
                    ),
                ),
                (
                    'fuel_form_data',
                    models.ForeignKey(
                        db_comment='The fuel data this emission data belongs to, if applicable',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='reporting.reportfuel',
                    ),
                ),
            ],
            options={
                'db_table': 'erc"."report_emission',
                'db_table_comment': 'A table to store the reported activity-specific data, in a JSON format',
            },
        ),
        migrations.CreateModel(
            name='ReportMethodology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'json_data',
                    models.JSONField(db_comment='A flat JSON object representing the data collected for this model'),
                ),
                (
                    'report_emission',
                    models.OneToOneField(
                        db_comment='The emission data this methodology applies to',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='report_methodology',
                        to='reporting.reportemission',
                    ),
                ),
                (
                    'report_version_id',
                    models.ForeignKey(
                        db_comment='The report version this data belongs to',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='+',
                        to='reporting.reportversion',
                    ),
                ),
            ],
            options={
                'db_table': 'erc"."report_methodology',
                'db_table_comment': 'A table to store the reported activity-specific data, in a JSON format',
            },
        ),
        migrations.CreateModel(
            name='ReportSourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'json_data',
                    models.JSONField(db_comment='A flat JSON object representing the data collected for this model'),
                ),
                (
                    'activity_source_type_base_schema',
                    models.ForeignKey(
                        db_comment='The activity-source-type base schema used to render the form that collected this data',
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='reporting.activitysourcetypejsonschema',
                    ),
                ),
                (
                    'report_activity',
                    models.ForeignKey(
                        db_comment='The activity data record this source type data belongs to',
                        on_delete=django.db.models.deletion.CASCADE,
                        to='reporting.reportactivity',
                    ),
                ),
                (
                    'report_version_id',
                    models.ForeignKey(
                        db_comment='The report version this data belongs to',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='+',
                        to='reporting.reportversion',
                    ),
                ),
                (
                    'source_type',
                    models.ForeignKey(
                        db_comment='The source type this data applies to',
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='reporting.sourcetype',
                    ),
                ),
            ],
            options={
                'db_table': 'erc"."report_source_type',
                'db_table_comment': 'A table to store the reported activity-specific data, in a JSON format',
            },
        ),
        migrations.AddField(
            model_name='reportfuel',
            name='report_source_type',
            field=models.ForeignKey(
                db_comment='The source type data this unit data belongs to',
                on_delete=django.db.models.deletion.CASCADE,
                to='reporting.reportsourcetype',
            ),
        ),
        migrations.AddField(
            model_name='reportemission',
            name='report_source_type',
            field=models.ForeignKey(
                db_comment='The source type data this emission data belongs to',
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='reporting.reportsourcetype',
            ),
        ),
        migrations.CreateModel(
            name='ReportUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'json_data',
                    models.JSONField(db_comment='A flat JSON object representing the data collected for this model'),
                ),
                (
                    'report_source_type',
                    models.ForeignKey(
                        db_comment='The source type data this unit data belongs to',
                        on_delete=django.db.models.deletion.CASCADE,
                        to='reporting.reportsourcetype',
                    ),
                ),
                (
                    'report_version_id',
                    models.ForeignKey(
                        db_comment='The report version this data belongs to',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='+',
                        to='reporting.reportversion',
                    ),
                ),
            ],
            options={
                'db_table': 'erc"."report_unit',
                'db_table_comment': 'A table to store the reported activity-specific data, in a JSON format',
            },
        ),
        migrations.AddField(
            model_name='reportfuel',
            name='report_unit',
            field=models.ForeignKey(
                db_comment='The unit form data this fuel data belongs to, if applicable',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='reporting.reportunit',
            ),
        ),
    ]
