# Generated by Django 5.0.6 on 2024-07-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0022_remove_historicalwellauthorizationnumber_facility_and_more'),
        ('reporting', '0008_general_stationary_combustion_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportoperation',
            name='activities',
        ),
        migrations.AddField(
            model_name='reportoperation',
            name='regulated_products',
            field=models.ManyToManyField(related_name='+', to='registration.regulatedproduct'),
        ),
        migrations.AddField(
            model_name='reportoperation',
            name='reporting_activities',
            field=models.ManyToManyField(related_name='+', to='registration.reportingactivity'),
        ),
        migrations.AlterField(
            model_name='reportoperation',
            name='operation_type',
            field=models.CharField(db_comment='The type of the operation, LFO or SFO', max_length=1000),
        ),
    ]
