# Generated by Django 5.0.7 on 2024-07-30 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0009_remove_reportoperation_activities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportingyear',
            name='report_due_date',
            field=models.DateTimeField(
                db_comment="Due date for the annual report this year's reporting cycle, UTC-based",
                default=datetime.datetime(2025, 5, 31, 23, 59, 59, 999000, tzinfo=datetime.timezone.utc),
            ),
            preserve_default=False,
        ),
    ]
