# Generated by Django 5.0.7 on 2024-08-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0033_alter_historicaloperation_status_and_more'),
        ('reporting', '0012_gsc_non_compression_non_processing'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(
                fields=('operation', 'reporting_year'), name='unique_report_per_reporting_year'
            ),
        ),
    ]
