# Generated by Django 5.0.7 on 2024-09-11 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0015_gsc_non_compression_non_processing'),
    ]

    operations = [
        migrations.CreateModel(
            name='customMethodologySchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('json_schema', models.JSONField()),
            ],
            options={
                'db_table': 'erc"."custom_methodology_schema',
                'db_table_comment': 'Custom methodology schema used to define additional fields for reporting',
            },
        ),
        migrations.AddField(
            model_name='configurationelement',
            name='custom_methodology_schema',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='configuration_elements',
                to='reporting.custommethodologyschema',
            ),
        ),
    ]
