# Generated by Django 5.0.7 on 2024-09-16 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0040_alter_facility_address_and_more'),
        ('reporting', '0015_gsc_non_compression_non_processing'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMethodologySchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_schema', models.JSONField()),
                (
                    'activity',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registration.activity'
                    ),
                ),
                (
                    'gas_type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reporting.gastype'
                    ),
                ),
                (
                    'methodology',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reporting.methodology'
                    ),
                ),
                (
                    'source_type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reporting.sourcetype'
                    ),
                ),
                (
                    'valid_from',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reporting.configuration'
                    ),
                ),
                (
                    'valid_to',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reporting.configuration'
                    ),
                ),
            ],
            options={
                'db_table': 'erc"."custom_methodology_schema',
                'db_table_comment': 'Custom methodology schema used to define additional fields for reporting',
            },
        ),
        migrations.AddField(
            model_name='configurationelement',
            name='custom_methodology_schema',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='configuration_elements',
                to='reporting.custommethodologyschema',
            ),
        ),
    ]
