# Generated by Django 5.0.8 on 2024-10-08 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0044_facilitydesignatedoperationtimeline_status_and_more'),
        ('reporting', '0019_alter_reportactivity_json_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportemission',
            name='report_fuel',
            field=models.ForeignKey(
                blank=True,
                db_comment='The fuel data this emission data belongs to, if applicable',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='%(class)s_records',
                to='reporting.reportfuel',
            ),
        ),
        migrations.AlterField(
            model_name='reportfuel',
            name='report_unit',
            field=models.ForeignKey(
                blank=True,
                db_comment='The unit form data this fuel data belongs to, if applicable',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='%(class)s_records',
                to='reporting.reportunit',
            ),
        ),
        migrations.AddConstraint(
            model_name='activitysourcetypejsonschema',
            constraint=models.CheckConstraint(
                check=models.Q(('has_unit', True), ('has_fuel', False), _negated=True),
                name='invalid_if_has_unit_and_no_fuel',
                violation_error_message='A Source Type configuration cannot specify a unit without a fuel',
            ),
        ),
    ]
