# Generated by Django 5.0.8 on 2024-10-08 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0019_alter_reportactivity_json_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportemission',
            name='report_fuel',
            field=models.ForeignKey(
                blank=True,
                db_comment='The fuel data this emission data belongs to, if applicable',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='%(class)s_records',
                to='reporting.reportfuel',
            ),
        ),
        migrations.AlterField(
            model_name='reportfuel',
            name='report_unit',
            field=models.ForeignKey(
                blank=True,
                db_comment='The unit form data this fuel data belongs to, if applicable',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='%(class)s_records',
                to='reporting.reportunit',
            ),
        ),
    ]
