# Generated by Django 5.0.9 on 2024-10-17 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0045_V1_11_0'),
        ('reporting', '0021_reportproduct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAdditionalData',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                (
                    'report_version',
                    models.OneToOneField(
                        db_comment='The report version this report additional data applies to',
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name='report_additional_data',
                        serialize=False,
                        to='reporting.reportversion',
                    ),
                ),
                (
                    'capture_emissions',
                    models.BooleanField(db_comment='Whether or not capture emissions was selected', default=False),
                ),
                (
                    'emissions_on_site_use',
                    models.IntegerField(blank=True, db_comment='Emissions on site use', null=True),
                ),
                (
                    'emissions_on_site_sequestration',
                    models.IntegerField(blank=True, db_comment='Emissions on site sequestration', null=True),
                ),
                (
                    'emissions_off_site_transfer',
                    models.IntegerField(blank=True, db_comment='Emissions off-site transfer', null=True),
                ),
                (
                    'electricity_generated',
                    models.IntegerField(blank=True, db_comment='Electricity generated', null=True),
                ),
                (
                    'archived_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_archived',
                        to='registration.user',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_created',
                        to='registration.user',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_updated',
                        to='registration.user',
                    ),
                ),
            ],
            options={
                'db_table': 'erc"."report_additional_data',
                'db_table_comment': 'A table to store the additional data for the report',
            },
        ),
    ]
