# Generated by Django 5.0.6 on 2024-10-28 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0023_emission_category_mapping_with_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmethodology',
            name='methodology',
            field=models.ForeignKey(
                db_comment='The methodology this data applies to',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_records',
                to='reporting.methodology',
            ),
        ),
    ]
