# Generated by Django 5.0.8 on 2024-10-30 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0025_reportproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilityreport',
            name='products',
        ),
    ]
