# Generated by Django 5.0.8 on 2024-11-14 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0054_V1_13_0'),
        ('reporting', '0030_report_non_attributable_emissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                (
                    'attachment',
                    models.FileField(
                        db_comment='A file uploaded as an attachment to a report', upload_to='report_attachments/%Y/'
                    ),
                ),
                (
                    'attachment_type',
                    models.CharField(
                        choices=[
                            ('verification_statement', 'Verification Statement'),
                            ('wci_352_362', 'Wci 352 362'),
                            ('additional_reportable_information', 'Additional Reportable Information'),
                            ('confidentiality_request', 'Confidentiality Request'),
                            ('other', 'Other'),
                        ],
                        db_comment='The type of attachment this record represents',
                        max_length=1000,
                    ),
                ),
                (
                    'archived_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_archived',
                        to='registration.user',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_created',
                        to='registration.user',
                    ),
                ),
                (
                    'report_version',
                    models.ForeignKey(
                        db_comment='The report version this attachment belongs to',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='report_attachments',
                        to='reporting.reportversion',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_updated',
                        to='registration.user',
                    ),
                ),
            ],
            options={
                'db_table': 'erc"."report_attachment',
                'db_table_comment': 'Table containing the file information for the report attachments',
            },
        ),
        migrations.AddConstraint(
            model_name='reportattachment',
            constraint=models.UniqueConstraint(
                condition=models.Q(('attachment_type', 'other'), _negated=True),
                fields=('report_version', 'attachment_type'),
                name='unique_attachment_type_per_report_version',
            ),
        ),
    ]
