# Generated by Django 5.0.8 on 2024-11-18 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0055_V1_14_0'),
        ('reporting', '0031_alter_reportemission_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportVerification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                (
                    'report_version',
                    models.OneToOneField(
                        db_comment='The report version of this report verification',
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name='report_verification',
                        serialize=False,
                        to='reporting.reportversion',
                    ),
                ),
                (
                    'verification_body_name',
                    models.CharField(
                        db_comment='The name of the verification body conducting the verification', max_length=1000
                    ),
                ),
                (
                    'accredited_by',
                    models.CharField(
                        choices=[('ANAB', 'Anab'), ('SCC', 'Scc')],
                        db_comment='The verification accreditation body',
                        max_length=10,
                    ),
                ),
                (
                    'scope_of_verification',
                    models.CharField(
                        choices=[
                            ('B.C. OBPS Annual Report', 'Bc Obps'),
                            ('Supplementary Report', 'Supplementary'),
                            ('Corrected Report', 'Corrected'),
                        ],
                        db_comment='The scope of the verification',
                        max_length=50,
                    ),
                ),
                (
                    'threats_to_independence',
                    models.CharField(
                        choices=[('Yes', 'Yes'), ('No', 'No')],
                        db_comment='The indication of threats to independence',
                        max_length=3,
                    ),
                ),
                (
                    'verification_conclusion',
                    models.CharField(
                        choices=[('Positive', 'Positive'), ('Modified', 'Modified'), ('Negative', 'Negative')],
                        db_comment='The conclusion of the verification',
                        max_length=8,
                    ),
                ),
                ('visit_name', models.CharField(db_comment='The name of the site visited', max_length=100)),
                (
                    'visit_type',
                    models.CharField(
                        blank=True,
                        choices=[('In person', 'In Person'), ('Virtual', 'Virtual')],
                        db_comment='Optional field to store the type of visit conducted',
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    'other_facility_name',
                    models.CharField(
                        blank=True,
                        db_comment='Optional field to store the name of an other facility visited',
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    'other_facility_coordinates',
                    models.CharField(
                        blank=True,
                        db_comment='Optional field to store geographic coordinates of an other facility visited',
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    'archived_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_archived',
                        to='registration.user',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_created',
                        to='registration.user',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_updated',
                        to='registration.user',
                    ),
                ),
            ],
            options={
                'db_table': 'erc"."report_verification',
                'db_table_comment': 'Table to store verification information associated with a report version',
            },
        ),
    ]
