# Generated by Django 5.0.8 on 2024-12-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0039_reportproductemissionallocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportproductemissionallocation',
            name='allocated_quantity',
            field=models.DecimalField(
                db_comment='The quantity of emissions allocated to this product in tonnes of CO2 equivalent(tCO2e)',
                decimal_places=4,
                max_digits=20,
            ),
        ),
    ]
