# Generated by Django 5.0.10 on 2025-01-03 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0066_V1_17_1'),
        ('reporting', '0041_reportnewentrant_reportnewentrantemission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportversion',
            name='report_type',
            field=models.CharField(
                choices=[('Annual Report', 'Annual Report'), ('Simple Report', 'Simple Report')],
                db_comment='Report type',
                default='Annual Report',
                max_length=1000,
            ),
        ),
        migrations.AddConstraint(
            model_name='reportversion',
            constraint=models.UniqueConstraint(
                condition=models.Q(('status', 'draft')),
                fields=('report',),
                name='unique_report_version_with_draft_status_per_report',
                violation_error_message='Only one draft report version can exist on a report.',
            ),
        ),
    ]
