# Generated by Django 5.0.8 on 2025-01-21 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0068_V1_18_0'),
        ('reporting', '0043_alter_reportversion_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportOperationRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                (
                    'representative_name',
                    models.CharField(db_comment='The name of the operation representative.', max_length=1000),
                ),
                (
                    'selected_for_report',
                    models.BooleanField(
                        db_comment='Indicates whether this representative is selected for reporting.', default=True
                    ),
                ),
            ],
            options={
                'db_table': 'erc"."report_operation_representative',
                'db_table_comment': 'Stores information about operation representatives linked to report versions, including their selection status for reports.',
            },
        ),
        migrations.RemoveField(
            model_name='reportoperation',
            name='operation_representative_name',
        ),
        migrations.AlterField(
            model_name='reportpersonresponsible',
            name='report_version',
            field=models.OneToOneField(
                db_comment='The report version this person responsible applies to',
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name='report_person_responsible',
                serialize=False,
                to='reporting.reportversion',
            ),
        ),
        migrations.AlterField(
            model_name='reportversion',
            name='report_type',
            field=models.CharField(
                choices=[('Annual Report', 'Annual Report'), ('Simple Report', 'Simple Report')],
                db_comment='Report type',
                default='Annual Report',
                max_length=1000,
            ),
        ),
        migrations.AddConstraint(
            model_name='reportversion',
            constraint=models.UniqueConstraint(
                condition=models.Q(('status', 'Draft')),
                fields=('report',),
                name='unique_report_version_with_draft_status_per_report',
                violation_error_message='Only one draft report version can exist on a report.',
            ),
        ),
        migrations.AddField(
            model_name='reportoperationrepresentative',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AddField(
            model_name='reportoperationrepresentative',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AddField(
            model_name='reportoperationrepresentative',
            name='report_version',
            field=models.ForeignKey(
                db_comment='The report version associated with this operation representative.',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='report_operation_representatives',
                to='reporting.reportversion',
            ),
        ),
        migrations.AddField(
            model_name='reportoperationrepresentative',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
    ]
