# Generated by Django 5.0.9 on 2025-01-14 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0044_reportoperationrepresentative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportoperation',
            name='operation_representative_name',
        ),
    ]
