# Generated by Django 5.0.10 on 2025-01-20 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0068_V1_18_0'),
        ('reporting', '0045_remove_reportoperation_operation_representative_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportverification',
            name='other_facility_coordinates',
        ),
        migrations.RemoveField(
            model_name='reportverification',
            name='other_facility_name',
        ),
        migrations.RemoveField(
            model_name='reportverification',
            name='visit_name',
        ),
        migrations.RemoveField(
            model_name='reportverification',
            name='visit_type',
        ),
        migrations.CreateModel(
            name='ReportVerificationVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                (
                    'visit_name',
                    models.CharField(
                        db_comment='The name of the site visited (Facility X, Other, or None)', max_length=100
                    ),
                ),
                (
                    'visit_type',
                    models.CharField(
                        blank=True,
                        choices=[('In person', 'In Person'), ('Virtual', 'Virtual')],
                        db_comment='The type of visit conducted (Virtual or In Person)',
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    'other_facility_name',
                    models.CharField(
                        blank=True,
                        db_comment="Name of the other facility visited if 'Other' is selected",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    'other_facility_coordinates',
                    models.CharField(
                        blank=True,
                        db_comment='Geographic location of the other facility visited',
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    'archived_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_archived',
                        to='registration.user',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_created',
                        to='registration.user',
                    ),
                ),
                (
                    'report_verification',
                    models.ForeignKey(
                        db_comment='The report verification associated with this visit',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(class)s_records',
                        to='reporting.reportverification',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_updated',
                        to='registration.user',
                    ),
                ),
            ],
            options={
                'db_table': 'erc"."verification_visit',
                'db_table_comment': 'Table to store individual verification visit information',
            },
        ),
    ]
