# Generated by Django 5.0.11 on 2025-01-30 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0047_reportemission_report_unit_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='activitysourcetypejsonschema',
            name='invalid_if_has_unit_and_no_fuel',
        ),
    ]
