# Generated by Django 5.1.5 on 2025-01-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0050_remove_reportverification_other_facility_coordinates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityreport',
            name='is_completed',
            field=models.BooleanField(
                db_comment='Indicates whether the facility report has been completed.', default=False
            ),
        ),
    ]
