# Generated by Django 5.0.11 on 2025-02-19 19:51

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0068_lead_production'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='reportverificationvisit',
            name='set_created_audit_columns',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='reportverificationvisit',
            name='set_updated_audit_columns',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='reportverificationvisit',
            name='immutable_report_version',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='reportverificationvisit',
            trigger=pgtrigger.compiler.Trigger(
                name='set_created_audit_columns',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="new.created_by_id = (select current_setting('my.guid', true)); new.created_at = now(); return new;",
                    hash='cb4b1713568f237db7d475fea8ba73fa2e56e17f',
                    operation='INSERT',
                    pgid='pgtrigger_set_created_audit_columns_94fd8',
                    table='erc"."report_verification_visit',
                    when='BEFORE',
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='reportverificationvisit',
            trigger=pgtrigger.compiler.Trigger(
                name='set_updated_audit_columns',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="new.updated_by_id = (select current_setting('my.guid', true)); new.updated_at = now(); return new;",
                    hash='10da55097dd264321136899eb608f93936ee58b5',
                    operation='UPDATE',
                    pgid='pgtrigger_set_updated_audit_columns_f0954',
                    table='erc"."report_verification_visit',
                    when='BEFORE',
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='reportverificationvisit',
            trigger=pgtrigger.compiler.Trigger(
                name='immutable_report_version',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='\n            declare\n                status text;\n            begin\n                select rel1.status into status\n                from "erc"."report_version" rel1\n                join "erc"."report_verification" rel2 on rel2.report_version_id=rel1.id\n                join "erc"."report_verification_visit" rel3 on rel3.report_verification_id=rel2.id\n                where rel3.id=new.id\n                limit 1;\n\n                if status=\'Submitted\' then\n                    raise exception \'reportverificationvisit record is immutable after a report version has been submitted\';\n                end if;\n\n                return new;\n            end;\n            ',
                    hash='207c50d383c8a924b1b07972636eeb72f4fa8d18',
                    operation='UPDATE',
                    pgid='pgtrigger_immutable_report_version_4239c',
                    table='erc"."report_verification_visit',
                    when='BEFORE',
                ),
            ),
        ),
    ]
