# Generated by Django 5.0.11 on 2025-02-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0070_reportoperation_registration_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportoperation',
            name='registration_purpose',
            field=models.CharField(
                db_comment='The Registration purpose of the operation',
                default='OBPS Regulated Operation',
                max_length=1000,
            ),
        ),
    ]
