# Generated by Django 5.0.11 on 2025-03-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0071_alter_reportoperation_registration_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportverification',
            name='scope_of_verification',
            field=models.CharField(blank=True, db_comment='The scope of the verification', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reportverification',
            name='verification_conclusion',
            field=models.CharField(
                blank=True, db_comment='The conclusion of the verification', max_length=8, null=True
            ),
        ),
    ]
