# Generated by Django 5.0.13 on 2025-03-12 21:27

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0088_contact_unique_email_per_operator'),
        ('reporting', '0078_not_applicable_methodology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportproduct',
            name='production_methodology',
            field=models.CharField(
                choices=[
                    ('OBPS Calculator', 'Obps Calculator'),
                    ('other', 'Other'),
                    ('Not Applicable', 'Not Applicable'),
                ],
                db_comment='The production methodoogy used to make this product',
                default='OBPS Calculator',
                max_length=10000,
            ),
        ),
        migrations.CreateModel(
            name='ReportEmissionAllocationNoProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                (
                    'allocation_methodology',
                    models.CharField(
                        choices=[
                            ('OBPS Allocation Calculator', 'Calculator'),
                            ('Other', 'Other'),
                            ('Not Applicable', 'Not Applicable'),
                        ],
                        db_comment='The methodology used to calculate the allocated emissions',
                        default='Not Applicable',
                        max_length=255,
                    ),
                ),
                (
                    'allocation_other_methodology_description',
                    models.TextField(
                        blank=True, db_comment="A description of the methodology used if 'Other' is selected", null=True
                    ),
                ),
                (
                    'archived_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_archived',
                        to='registration.user',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_created',
                        to='registration.user',
                    ),
                ),
                (
                    'facility_report',
                    models.ForeignKey(
                        db_comment='The facility report this data belongs to',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(class)s_records',
                        to='reporting.facilityreport',
                    ),
                ),
                (
                    'report_version',
                    models.ForeignKey(
                        db_comment='The report version this data is associated with',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(class)s_records',
                        to='reporting.reportversion',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_updated',
                        to='registration.user',
                    ),
                ),
            ],
            options={
                'db_table': 'erc"."report_emission_allocation_no_product',
                'db_table_comment': "A table to store the methodology associated with the allocation of emissions IF there's no products",
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='reportemissionallocationnoproduct',
            constraint=models.UniqueConstraint(
                fields=('report_version', 'facility_report'),
                name='no_product_unique_report_emission_allocation',
                violation_error_message='A FacilityReport can only have one ReportEmissionAllocationNoProduct per Report',
            ),
        ),
        migrations.AddConstraint(
            model_name='reportemissionallocationnoproduct',
            constraint=models.CheckConstraint(
                check=models.Q(
                    ('allocation_methodology', 'Other'),
                    ('allocation_other_methodology_description__isnull', True),
                    _negated=True,
                ),
                name='no_product_allocation_other_methodology_must_have_description',
                violation_error_message="A value for allocation_other_methodology_description must be provided if allocation_methodology is 'Other'",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='reportemissionallocationnoproduct',
            trigger=pgtrigger.compiler.Trigger(
                name='set_created_audit_columns',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="new.created_by_id = (select current_setting('my.guid', true)); new.created_at = now(); return new;",
                    hash='52681bb2907b31cd31e3651f9715981a10ee0e7e',
                    operation='INSERT',
                    pgid='pgtrigger_set_created_audit_columns_d99ca',
                    table='erc"."report_emission_allocation_no_product',
                    when='BEFORE',
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='reportemissionallocationnoproduct',
            trigger=pgtrigger.compiler.Trigger(
                name='set_updated_audit_columns',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="new.updated_by_id = (select current_setting('my.guid', true)); new.updated_at = now(); return new;",
                    hash='e93050c814298911dadfb1904214f89bbd7ffadd',
                    operation='UPDATE',
                    pgid='pgtrigger_set_updated_audit_columns_6b4d3',
                    table='erc"."report_emission_allocation_no_product',
                    when='BEFORE',
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='reportemissionallocationnoproduct',
            trigger=pgtrigger.compiler.Trigger(
                name='immutable_report_version',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='\n            declare\n                status text;\n            begin\n                select rel1.status into status\n                from "erc"."report_version" rel1\n                join "erc"."report_emission_allocation_no_product" rel2 on rel2.report_version_id=rel1.id\n                where rel2.id=new.id\n                limit 1;\n\n                if status=\'Submitted\' then\n                    raise exception \'reportemissionallocationnoproduct record is immutable after a report version has been submitted\';\n                end if;\n\n                return new;\n            end;\n            ',
                    hash='9dacc5990869b738b3acc102acf5014ba85d45c5',
                    operation='UPDATE',
                    pgid='pgtrigger_immutable_report_version_a7deb',
                    table='erc"."report_emission_allocation_no_product',
                    when='BEFORE',
                ),
            ),
        ),
    ]
