# Generated by Django 5.0.14 on 2025-04-03 22:44

from django.db import migrations


def update_unit(apps, schema_monitor):
    ReportingField = apps.get_model("reporting", "ReportingField")

    ReportingField.objects.filter(field_name="Fuel Annual Weighted Average Carbon Content (weight fraction)").update(
        field_units="kg carbon/fuel unit"
    )


def reverse_unit(apps, schema_monitor):
    ReportingField = apps.get_model("reporting", "ReportingField")

    ReportingField.objects.filter(field_name="Fuel Annual Weighted Average Carbon Content (weight fraction)").update(
        field_units=None
    )


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0082_reportemissionallocation_and_more"),
    ]

    operations = [migrations.RunPython(update_unit, reverse_unit)]
