# Generated by Django 5.0.13 on 2025-04-08 20:36

from django.db import migrations


def add_missing_product_emission_intensity_data(apps, schema_monitor):
    '''
    Add data to erc.product_emission_intensity for missing products added to regulated_product table
    '''

    Product = apps.get_model('registration', 'RegulatedProduct')
    ProductEmissionIntensity = apps.get_model('reporting', 'ProductEmissionIntensity')
    ProductEmissionIntensity.objects.bulk_create(
        [
            ProductEmissionIntensity(
                product_id=(Product.objects.get(name='Mining: critical mineral, other than copper').id),
                product_weighted_average_emission_intensity='0',
                valid_from='2023-01-01',
                valid_to='9999-12-31',
            ),
            ProductEmissionIntensity(
                product_id=(
                    Product.objects.get(name='Smelting: critical mineral, other than aluminun and lead-zinc').id
                ),
                product_weighted_average_emission_intensity='0',
                valid_from='2023-01-01',
                valid_to='9999-12-31',
            ),
        ]
    )


def revert_add_missing_product_emission_intensity_data(apps, schema_monitor):
    '''
    Revert function
    '''

    Product = apps.get_model('registration', 'RegulatedProduct')
    ProductEmissionIntensity = apps.get_model('reporting', 'ProductEmissionIntensity')
    ProductEmissionIntensity.objects.get(
        product_id=Product.objects.get(name='Mining: critical mineral, other than copper').id
    ).delete()
    ProductEmissionIntensity.objects.get(
        product_id=Product.objects.get(name='Smelting: critical mineral, other than aluminun and lead-zinc').id
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0103_product_units_non_nullable_add_missing_products'),
        ('reporting', '0082_reportemissionallocation_and_more'),
    ]

    operations = [
        migrations.RunPython(
            add_missing_product_emission_intensity_data, revert_add_missing_product_emission_intensity_data
        )
    ]
