# Generated by Django 5.0.14 on 2025-04-07 17:54

import json
import os
from django.db import migrations


def reload_other_fugitive_sources_schema(apps, schema_monitor):
    """
    The "other fugitives sources" schema for 2024 has had some updates in the source sub-type name.
    We just reload it in the right ActivitySourceTypeSchema records
    """
    cwd = os.getcwd()
    with open(
        f"{cwd}/reporting/json_schemas/2024/og_extraction_other_than_ncnp/other_fugitive_sources.json"
    ) as og_other_fugitive_sources_schema_file:
        og_other_fugitive_sources_schema = json.load(og_other_fugitive_sources_schema_file)

    ActivitySourceTypeSchema = apps.get_model("reporting", "ActivitySourceTypeJsonSchema")
    Activity = apps.get_model("registration", "Activity")
    SourceType = apps.get_model("reporting", "SourceType")
    Configuration = apps.get_model("reporting", "Configuration")

    ActivitySourceTypeSchema(
        activity_id=Activity.objects.get(
            name="Oil and gas extraction and gas processing activities, other than non- compression and non-processing activities"
        ).id,
        source_type_id=SourceType.objects.get(name="Other fugitive sources").id,
        valid_from_id=Configuration.objects.get(valid_from="2023-01-01").id,
        valid_to_id=Configuration.objects.get(valid_to="2099-12-31").id,
    ).update(json_schema=og_other_fugitive_sources_schema)


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0082_reportemissionallocation_and_more"),
    ]

    operations = [migrations.RunPython(reload_other_fugitive_sources_schema)]
