# Generated by Django 5.0.14 on 2025-04-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0105_V2_3_0'),
        ('reporting', '0084_V2_3_0'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reportemissionallocation',
            name='unique_report_emission_allocation',
        ),
        migrations.RemoveConstraint(
            model_name='reportnewentrantemission',
            name='unique_new_entrant_emissions',
        ),
        migrations.RemoveConstraint(
            model_name='reportnewentrantproduction',
            name='unique_new_entrant_production',
        ),
        migrations.RemoveConstraint(
            model_name='reportproduct',
            name='unique_report_product_per_product_and_facility_report',
        ),
        migrations.RemoveConstraint(
            model_name='reportproductemissionallocation',
            name='unique_report_product_emission_allocation',
        ),
        migrations.AddConstraint(
            model_name='reportemissionallocation',
            constraint=models.UniqueConstraint(
                fields=('report_version', 'facility_report'), name='unique_report_emission_allocation'
            ),
        ),
        migrations.AddConstraint(
            model_name='reportnewentrantemission',
            constraint=models.UniqueConstraint(
                fields=('report_new_entrant', 'emission_category'), name='unique_new_entrant_emissions'
            ),
        ),
        migrations.AddConstraint(
            model_name='reportnewentrantproduction',
            constraint=models.UniqueConstraint(
                fields=('product', 'report_new_entrant'), name='unique_new_entrant_production'
            ),
        ),
        migrations.AddConstraint(
            model_name='reportproduct',
            constraint=models.UniqueConstraint(
                fields=('facility_report', 'product'), name='unique_report_product_per_product_and_facility_report'
            ),
        ),
        migrations.AddConstraint(
            model_name='reportproductemissionallocation',
            constraint=models.UniqueConstraint(
                fields=('report_emission_allocation', 'report_version', 'report_product', 'emission_category'),
                name='unique_report_product_emission_allocation',
            ),
        ),
    ]
