# Generated by Django 5.2 on 2025-04-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0084_V2_3_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsignoff',
            name='acknowledgement_of_corrections',
            field=models.BooleanField(
                blank=True,
                db_comment='Whether the user has understood that correction of any errors, omissions, or misstatements in the new submission of this report may lead to an additional compliance obligation, and, if submitted after the compliance obligation deadline, applicable interest.',
                null=True,
            ),
        ),
    ]
