# Generated by Django 5.0.14 on 2025-04-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "reporting",
            "0085_remove_reportemissionallocation_unique_report_emission_allocation_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="reportattachment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Unscanned", "Unscanned"),
                    ("Clean", "Clean"),
                    ("Quarantined", "Quarantined"),
                ],
                default="Unscanned",
                max_length=100,
            ),
        ),
    ]
