# Generated by Django 5.2 on 2025-04-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0087_update_storage_of_petroleum_products_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsignoff',
            name='acknowledgement_of_corrections',
            field=models.BooleanField(
                blank=True,
                db_comment='Whether the user has understood that correction of any errors, omissions, or misstatements in the new submission of this report may lead to an additional compliance obligation, and, if submitted after the compliance obligation deadline, applicable interest.',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='reportsignoff',
            name='acknowledgement_of_possible_costs',
            field=models.BooleanField(
                blank=True,
                db_comment='Whether the user has understood that the information provided in this report can impact any compliance obligation of this operation and that any errors, omissions, or misstatements can lead to an additional compliance obligation or administrative penalties.',
                null=True,
            ),
        ),
    ]
