# Generated by Django 5.0.14 on 2025-04-17 22:42

from django.db import migrations
import json

# Configuration constants
ACTIVITY = "Electricity generation"
VALID_FROM = "2023-01-01"
VALID_TO = "2099-12-31"
JSON_SCHEMAS_PATH = "reporting/json_schemas/2024/electricity_generation"


def init_activity_source_type_schema_data(apps, schema_monitor):
    """
    Add activity source type schema data to erc.activity_source_type_schema
    """
    # Import JSON data
    import os

    cwd = os.getcwd()

    # Retrieve models from the app registry to interact with the database
    ActivitySourceTypeSchema = apps.get_model("reporting", "ActivitySourceTypeJsonSchema")
    Activity = apps.get_model("registration", "Activity")
    SourceType = apps.get_model("reporting", "SourceType")
    Configuration = apps.get_model("reporting", "Configuration")

    # Fetch the configuration constants
    activity = Activity.objects.get(name=ACTIVITY)
    valid_from = Configuration.objects.get(valid_from=VALID_FROM)
    valid_to = Configuration.objects.get(valid_to=VALID_TO)

    with open(f"{cwd}/{JSON_SCHEMAS_PATH}/3_cooling_units.json") as schema_file:
        schema = json.load(schema_file)

    ActivitySourceTypeSchema.objects.filter(
        activity=activity, source_type=SourceType.objects.get(name="Cooling units")
    ).update(
        activity=activity,
        source_type=SourceType.objects.get(name="Cooling units"),
        has_unit=False,
        has_fuel=False,
        json_schema=schema,
        valid_from=valid_from,
        valid_to=valid_to,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0089_reportattachment_status'),
    ]

    operations = [
        migrations.RunPython(
            init_activity_source_type_schema_data,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
