# Generated by Django 5.0.14 on 2025-04-22 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0090_reload_cooling_units_json_schema'),
    ]

    operations = []
