# Generated by Django 5.0.14 on 2025-05-01 22:09

from django.db import migrations
from reporting.service.compliance_service import ComplianceService
import common.lib.pgtrigger as pgtrigger


def populate_compliance_data_for_existing_reports(apps, schema_monitor):
    """
    Persist compliance summary data for submitted report versions
    """

    # Retrieve submitted report versions & persist the compliance data for those versions
    ReportVersion = apps.get_model("reporting", "ReportVersion")
    with pgtrigger.ignore(
        "reporting.ReportVersion:immutable_report_version", "reporting.ReportVersion.set_updated_audit_columns"
    ):
        for r in ReportVersion.objects.filter(status='Submitted'):
            ComplianceService.save_compliance_data(r.id)


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0092_report_compliance_summary_models'),
    ]

    operations = [
        migrations.RunPython(
            populate_compliance_data_for_existing_reports,
            reverse_code=migrations.RunPython.noop,  # save is idempotent. Do not want to delete summary data on revert.
        ),
    ]
