# Generated by Django 5.0.14 on 2025-05-05 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0094_reportattachmentconfirmation_and_more'),
    ]

    operations = []
