# Generated by Django 5.0.14 on 2025-05-08 20:32

from django.db import migrations


def update_gwp(apps, _):
    apps.get_model('reporting', 'GasType').objects.filter(chemical_formula='C2F6').update(gwp=11100)


class Migration(migrations.Migration):
    dependencies = [
        ('reporting', '0097_reportsignoff_acknowledgement_of_errors'),
    ]

    operations = [
        migrations.RunPython(update_gwp),
    ]
