# Generated by Django 5.0.14 on 2025-05-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0100_update_gwp_perfluoroethane'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportverification',
            name='accredited_by',
            field=models.CharField(
                blank=True,
                choices=[('ANAB', 'Anab'), ('SCC', 'Scc')],
                db_comment='The verification accreditation body',
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='reportverification',
            name='threats_to_independence',
            field=models.BooleanField(
                blank=True, db_comment='Indicates whether there were any threats to independence noted', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportverification',
            name='verification_body_name',
            field=models.CharField(
                blank=True,
                db_comment='The name of the verification body conducting the verification',
                max_length=1000,
                null=True,
            ),
        ),
    ]
