# Generated by Django 5.0.14 on 2025-05-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0101_alter_reportverification_accredited_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportversion',
            name='reason_for_change',
            field=models.TextField(
                blank=True, db_comment='Reason explaining why a supplementary report change was made.'
            ),
        ),
    ]
