# Generated by Django 5.0.14 on 2025-05-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0102_V3_2_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportversion',
            name='reason_for_change',
            field=models.TextField(
                blank=True, db_comment='Reason explaining why a supplementary report change was made.'
            ),
        ),
    ]
