# Generated by Django 5.0.14 on 2025-05-30 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0110_remove_facilityreport_immutable_report_version_and_more'),
    ]

    operations = []
