# Generated by Django 5.0.14 on 2025-06-11 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0112_V3_6_0'),
    ]

    operations = []
