# Generated by Django 5.0.14 on 2025-06-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0113_V3_7_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportversion',
            name='test_field',
            field=models.BooleanField(db_comment='Test field to be removed and never committed', default=False),
        ),
    ]
