# Generated by Django 5.1.10 on 2025-06-23 23:26


import json
import os
from django.db import migrations


def reload_schemas_with_equivalent_emissions(apps, schema_monitor):
    """
    We've changed the type of equivalent emissions from string to number in all 2024 schemas. We reload it in the ActivitySourceTypeJsonSchema records
    """
    ActivitySourceTypeJsonSchema = apps.get_model("reporting", "ActivitySourceTypeJsonSchema")
    Activity = apps.get_model("registration", "Activity")
    SourceType = apps.get_model("reporting", "SourceType")
    Configuration = apps.get_model("reporting", "Configuration")

    items = [
        (
            '/reporting/json_schemas/2024/aluminum_production/anode_effects.json',
            'Aluminum or alumina production',
            'Anode effects',
        ),
        (
            '/reporting/json_schemas/2024/aluminum_production/cover_gas_from_electrolysis.json',
            'Aluminum or alumina production',
            'Cover gas from electrolysis cells',
        ),
        (
            '/reporting/json_schemas/2024/aluminum_production/anode_consumption_acbgcc.json',
            'Aluminum or alumina production',
            'Anode consumption in electrolysis cells, anode and cathode baking or green coke calcination',
        ),
        (
            '/reporting/json_schemas/2024/carbonates_use/carbonates_use.json',
            'Carbonate use',
            'Carbonates used but not consumed in other activities set out in column 2',
        ),
        (
            '/reporting/json_schemas/2024/cement_production/calcination_of_lssso.json',
            'Cement production',
            'Calcination of limestone, shale, sand, slag or other raw materials used to produce clinker, as well as the oxidization of organic carbon in the raw material',
        ),
        (
            '/reporting/json_schemas/2024/coal_storage/1_stored_coal_piles.json',
            'Coal storage at facilities that combust coal',
            'Stored coal piles',
        ),
        (
            '/reporting/json_schemas/2024/electricity_generation/3_cooling_units.json',
            'Electricity generation',
            'Cooling units',
        ),
        (
            '/reporting/json_schemas/2024/electricity_generation/5_electrical_equipment_install_maint_decom.json',
            'Electricity generation',
            'Installation, maintenance, operation and decommissioning of electrical equipment',
        ),
        (
            '/reporting/json_schemas/2024/electricity_generation/4_geothermal_geyser_steam_fluids.json',
            'Electricity generation',
            'Geothermal geyser steam or fluids',
        ),
        (
            '/reporting/json_schemas/2024/electricity_generation/2_acid_gas_scrubbers_reagents.json',
            'Electricity generation',
            'Acid gas scrubbers and acid gas reagents',
        ),
        (
            '/reporting/json_schemas/2024/electricity_generation/1_fuel_combustion_electricity_gen.json',
            'Electricity generation',
            'Fuel combustion for electricity generation',
        ),
        (
            '/reporting/json_schemas/2024/electricity_transmission/installation_maint_operation_electrical_equipment.json',
            'Electricity transmission',
            'Installation, maintenance, operation and decommissioning of electrical equipment',
        ),
        (
            '/reporting/json_schemas/2024/fuel_combustion_mobile/combustion_by_equipment.json',
            'Fuel combustion by mobile equipment',
            'Fuel combustion by mobile equipment that is part of the facility',
        ),
        (
            '/reporting/json_schemas/2024/gsc_excluding_line_tracing/with_useful_energy.json',
            'General stationary combustion excluding line tracing',
            'General stationary combustion of fuel or waste with production of useful energy',
        ),
        (
            '/reporting/json_schemas/2024/gsc_excluding_line_tracing/without_useful_energy.json',
            'General stationary combustion excluding line tracing',
            'General stationary combustion of waste without production of useful energy',
        ),
        (
            '/reporting/json_schemas/2024/gsc_other_than_non_compression/without_useful_energy.json',
            'General stationary combustion, other than non-compression and non-processing combustion',
            'General stationary combustion of fuel or waste at a linear facilities operation not resulting in the production of useful energy',
        ),
        (
            '/reporting/json_schemas/2024/gsc_other_than_non_compression/field_gas_process_vent_gas_at_lfo.json',
            'General stationary combustion, other than non-compression and non-processing combustion',
            'Field gas or process vent gas combustion at a linear facilities operation',
        ),
        (
            '/reporting/json_schemas/2024/gsc_other_than_non_compression/with_useful_energy.json',
            'General stationary combustion, other than non-compression and non-processing combustion',
            'General stationary combustion of fuel or waste at a linear facilities operation resulting in the production of useful energy',
        ),
        (
            '/reporting/json_schemas/2024/gsc_solely_for_line_tracing/with_useful_energy.json',
            'General stationary combustion solely for the purpose of line tracing',
            'General stationary combustion of fuel or waste with production of useful energy',
        ),
        (
            '/reporting/json_schemas/2024/gsc_non_compression_non_combustion/without_useful_energy.json',
            'General stationary non-compression and non-processing combustion',
            'General stationary combustion of fuel or waste at a linear facilities operation not resulting in the production of useful energy',
        ),
        (
            '/reporting/json_schemas/2024/gsc_non_compression_non_combustion/field_gas_process_vent_gas_at_lfo.json',
            'General stationary non-compression and non-processing combustion',
            'Field gas or process vent gas combustion at a linear facilities operation',
        ),
        (
            '/reporting/json_schemas/2024/gsc_non_compression_non_combustion/with_useful_energy.json',
            'General stationary non-compression and non-processing combustion',
            'General stationary combustion of fuel or waste at a linear facilities operation resulting in the production of useful energy',
        ),
        (
            '/reporting/json_schemas/2024/hydrogen_production/steam_reformation_or_gasification.json',
            'Hydrogen production',
            'Steam reformation of hydrocarbons, partial oxidation of hydrocarbons or other transformation of hydrocarbon feedstock',
        ),
        (
            '/reporting/json_schemas/2024/industrial_water_processing/wastewater_processing_using_anaerobic.json',
            'Industrial wastewater processing',
            'Industrial wastewater process using anaerobic digestion',
        ),
        (
            '/reporting/json_schemas/2024/industrial_water_processing/oil_water_separators.json',
            'Industrial wastewater processing',
            'Oil-water separators',
        ),
        (
            '/reporting/json_schemas/2024/lead_production/1_reducing agents.json',
            'Lead production',
            'Use of reducing agents during lead production',
        ),
        (
            '/reporting/json_schemas/2024/lime_manufacturing/1_calcination_of_carbonate.json',
            'Lime manufacturing',
            'Calcination of carbonate materials in lime manufacturing',
        ),
        (
            '/reporting/json_schemas/2024/lng_activities/20_third_party_line_hits_with_release_of_gas.json',
            'LNG activities',
            'Third party line hits with release of gas',
        ),
        (
            '/reporting/json_schemas/2024/lng_activities/8_releases_from_tanks_used_for_storage.json',
            'LNG activities',
            'Releases from tanks used for storage, production or processing',
        ),
        ('/reporting/json_schemas/2024/lng_activities/9_flare_stacks.json', 'LNG activities', 'Flare stacks'),
        (
            '/reporting/json_schemas/2024/lng_activities/10_centrifugal_compressor_venting.json',
            'LNG activities',
            'Centrifugal compressor venting',
        ),
        (
            '/reporting/json_schemas/2024/lng_activities/11_reciprocating_compressor_venting.json',
            'LNG activities',
            'Reciprocating compressor venting',
        ),
        (
            '/reporting/json_schemas/2024/lng_activities/12_equipment_leaks_detected_using_leak_detection.json',
            'LNG activities',
            'Equipment leaks detected using leak detection and leaker emission factor methods',
        ),
        (
            '/reporting/json_schemas/2024/lng_activities/13_population_count_sources.json',
            'LNG activities',
            'Population count sources',
        ),
        (
            '/reporting/json_schemas/2024/lng_activities/14_transmission_storage_tanks.json',
            'LNG activities',
            'Transmission storage tanks',
        ),
        (
            '/reporting/json_schemas/2024/lng_activities/15_enhanced_oil_recovery_injection_pump_blowdowns.json',
            'LNG activities',
            'Enhanced oil recovery injection pump blowdowns',
        ),
        (
            '/reporting/json_schemas/2024/lng_activities/16_produced_water_dissolved_carbon_dioxide_methane.json',
            'LNG activities',
            'Produced water dissolved carbon dioxide and methane',
        ),
        (
            '/reporting/json_schemas/2024/lng_activities/17_enhanced_oil_recovery_produced_hydrocarbon_liquids.json',
            'LNG activities',
            'Enhanced oil recovery produced hydrocarbon liquids dissolved carbon dioxide',
        ),
        (
            '/reporting/json_schemas/2024/lng_activities/18_other_venting_sources.json',
            'LNG activities',
            'Other venting sources',
        ),
        (
            '/reporting/json_schemas/2024/lng_activities/19_other_fugitive_sources.json',
            'LNG activities',
            'Other fugitive sources',
        ),
        (
            '/reporting/json_schemas/2024/lng_activities/1_ng_pneumatic_high_bleed_device_venting.json',
            'LNG activities',
            'Natural gas pneumatic high bleed device venting',
        ),
        (
            '/reporting/json_schemas/2024/lng_activities/2_ng_pneumatic_pump_venting.json',
            'LNG activities',
            'Natural gas pneumatic pump venting',
        ),
        (
            '/reporting/json_schemas/2024/lng_activities/3_ng_pneumatic_low_bleed_device_venting.json',
            'LNG activities',
            'Natural gas pneumatic low bleed device venting',
        ),
        (
            '/reporting/json_schemas/2024/lng_activities/4_ng_pneumatic_intermittent_device_venting.json',
            'LNG activities',
            'Natural gas pneumatic intermittent bleed device venting',
        ),
        (
            '/reporting/json_schemas/2024/lng_activities/5_acid_gas_removal_venting_or_incineration.json',
            'LNG activities',
            'Acid gas removal venting or incineration',
        ),
        (
            '/reporting/json_schemas/2024/lng_activities/6_dehydrator_venting.json',
            'LNG activities',
            'Dehydrator venting',
        ),
        ('/reporting/json_schemas/2024/lng_activities/7_blowdown_venting.json', 'LNG activities', 'Blowdown venting'),
        (
            '/reporting/json_schemas/2024/ng_other_than_non_compression/2_ng_pneumatic_pump_venting.json',
            'Activities for the purpose of natural gas transmission, natural gas distribution, natural gas storage, carbon dioxide transportation or oil transmission, other than non-compression and non-processing activities',
            'Natural gas pneumatic pump venting',
        ),
        (
            '/reporting/json_schemas/2024/ng_other_than_non_compression/1_ng_pneumatic_high_bleed_device_venting.json',
            'Activities for the purpose of natural gas transmission, natural gas distribution, natural gas storage, carbon dioxide transportation or oil transmission, other than non-compression and non-processing activities',
            'Natural gas pneumatic high bleed device venting',
        ),
        (
            '/reporting/json_schemas/2024/ng_other_than_non_compression/13_other_fugitive_sources.json',
            'Activities for the purpose of natural gas transmission, natural gas distribution, natural gas storage, carbon dioxide transportation or oil transmission, other than non-compression and non-processing activities',
            'Other fugitive sources',
        ),
        (
            '/reporting/json_schemas/2024/ng_other_than_non_compression/9_equipment_leaks_detected_using_leak_detection.json',
            'Activities for the purpose of natural gas transmission, natural gas distribution, natural gas storage, carbon dioxide transportation or oil transmission, other than non-compression and non-processing activities',
            'Equipment leaks detected using leak detection and leaker emission factor methods',
        ),
        (
            '/reporting/json_schemas/2024/ng_other_than_non_compression/8_reciprocating_compressor_venting.json',
            'Activities for the purpose of natural gas transmission, natural gas distribution, natural gas storage, carbon dioxide transportation or oil transmission, other than non-compression and non-processing activities',
            'Reciprocating compressor venting',
        ),
        (
            '/reporting/json_schemas/2024/ng_other_than_non_compression/12_other_venting_sources.json',
            'Activities for the purpose of natural gas transmission, natural gas distribution, natural gas storage, carbon dioxide transportation or oil transmission, other than non-compression and non-processing activities',
            'Other venting sources',
        ),
        (
            '/reporting/json_schemas/2024/ng_other_than_non_compression/7_centrifugal_compressor_venting.json',
            'Activities for the purpose of natural gas transmission, natural gas distribution, natural gas storage, carbon dioxide transportation or oil transmission, other than non-compression and non-processing activities',
            'Centrifugal compressor venting',
        ),
        (
            '/reporting/json_schemas/2024/ng_other_than_non_compression/11_transmission_storage_tanks.json',
            'Activities for the purpose of natural gas transmission, natural gas distribution, natural gas storage, carbon dioxide transportation or oil transmission, other than non-compression and non-processing activities',
            'Transmission storage tanks',
        ),
        (
            '/reporting/json_schemas/2024/ng_other_than_non_compression/10_population_count_sources.json',
            'Activities for the purpose of natural gas transmission, natural gas distribution, natural gas storage, carbon dioxide transportation or oil transmission, other than non-compression and non-processing activities',
            'Population count sources',
        ),
        (
            '/reporting/json_schemas/2024/ng_other_than_non_compression/14_third_party_line_hits_with_release_of_gas.json',
            'Activities for the purpose of natural gas transmission, natural gas distribution, natural gas storage, carbon dioxide transportation or oil transmission, other than non-compression and non-processing activities',
            'Third party line hits with release of gas',
        ),
        (
            '/reporting/json_schemas/2024/ng_other_than_non_compression/6_flare_stacks.json',
            'Activities for the purpose of natural gas transmission, natural gas distribution, natural gas storage, carbon dioxide transportation or oil transmission, other than non-compression and non-processing activities',
            'Flare stacks',
        ),
        (
            '/reporting/json_schemas/2024/ng_other_than_non_compression/5_blowdown_venting.json',
            'Activities for the purpose of natural gas transmission, natural gas distribution, natural gas storage, carbon dioxide transportation or oil transmission, other than non-compression and non-processing activities',
            'Blowdown venting',
        ),
        (
            '/reporting/json_schemas/2024/ng_other_than_non_compression/4_ng_pneumatic_intermittent_device_venting.json',
            'Activities for the purpose of natural gas transmission, natural gas distribution, natural gas storage, carbon dioxide transportation or oil transmission, other than non-compression and non-processing activities',
            'Natural gas pneumatic intermittent bleed device venting',
        ),
        (
            '/reporting/json_schemas/2024/ng_other_than_non_compression/3_ng_pneumatic_low_bleed_device_venting.json',
            'Activities for the purpose of natural gas transmission, natural gas distribution, natural gas storage, carbon dioxide transportation or oil transmission, other than non-compression and non-processing activities',
            'Natural gas pneumatic low bleed device venting',
        ),
        (
            '/reporting/json_schemas/2024/ng_non_compression/12_third_party_line_hits_with_release_of_gas.json',
            'Non-compression and non-processing activities for the purpose of natural gas transmission, natural gas distribution, natural gas storage, carbon dioxide transportation or oil transmission',
            'Third party line hits with release of gas',
        ),
        (
            '/reporting/json_schemas/2024/ng_non_compression/11_other_fugitive_sources.json',
            'Non-compression and non-processing activities for the purpose of natural gas transmission, natural gas distribution, natural gas storage, carbon dioxide transportation or oil transmission',
            'Other fugitive sources',
        ),
        (
            '/reporting/json_schemas/2024/ng_non_compression/9_transmission_storage_tanks.json',
            'Non-compression and non-processing activities for the purpose of natural gas transmission, natural gas distribution, natural gas storage, carbon dioxide transportation or oil transmission',
            'Transmission storage tanks',
        ),
        (
            '/reporting/json_schemas/2024/ng_non_compression/8_population_count_sources.json',
            'Non-compression and non-processing activities for the purpose of natural gas transmission, natural gas distribution, natural gas storage, carbon dioxide transportation or oil transmission',
            'Population count sources',
        ),
        (
            '/reporting/json_schemas/2024/ng_non_compression/7_equipment_leaks_detected_using_leak_detection.json',
            'Non-compression and non-processing activities for the purpose of natural gas transmission, natural gas distribution, natural gas storage, carbon dioxide transportation or oil transmission',
            'Equipment leaks detected using leak detection and leaker emission factor methods',
        ),
        (
            '/reporting/json_schemas/2024/ng_non_compression/6_flare_stacks.json',
            'Non-compression and non-processing activities for the purpose of natural gas transmission, natural gas distribution, natural gas storage, carbon dioxide transportation or oil transmission',
            'Flare stacks',
        ),
        (
            '/reporting/json_schemas/2024/ng_non_compression/5_blowdown_venting.json',
            'Non-compression and non-processing activities for the purpose of natural gas transmission, natural gas distribution, natural gas storage, carbon dioxide transportation or oil transmission',
            'Blowdown venting',
        ),
        (
            '/reporting/json_schemas/2024/ng_non_compression/4_ng_pneumatic_intermittent_device_venting.json',
            'Non-compression and non-processing activities for the purpose of natural gas transmission, natural gas distribution, natural gas storage, carbon dioxide transportation or oil transmission',
            'Natural gas pneumatic intermittent bleed device venting',
        ),
        (
            '/reporting/json_schemas/2024/ng_non_compression/3_ng_pneumatic_low_bleed_device_venting.json',
            'Non-compression and non-processing activities for the purpose of natural gas transmission, natural gas distribution, natural gas storage, carbon dioxide transportation or oil transmission',
            'Natural gas pneumatic low bleed device venting',
        ),
        (
            '/reporting/json_schemas/2024/ng_non_compression/2_ng_pneumatic_pump_venting.json',
            'Non-compression and non-processing activities for the purpose of natural gas transmission, natural gas distribution, natural gas storage, carbon dioxide transportation or oil transmission',
            'Natural gas pneumatic pump venting',
        ),
        (
            '/reporting/json_schemas/2024/ng_non_compression/1_ng_pneumatic_high_bleed_device_venting.json',
            'Non-compression and non-processing activities for the purpose of natural gas transmission, natural gas distribution, natural gas storage, carbon dioxide transportation or oil transmission',
            'Natural gas pneumatic high bleed device venting',
        ),
        (
            '/reporting/json_schemas/2024/ng_non_compression/10_other_venting_sources.json',
            'Non-compression and non-processing activities for the purpose of natural gas transmission, natural gas distribution, natural gas storage, carbon dioxide transportation or oil transmission',
            'Other venting sources',
        ),
        (
            '/reporting/json_schemas/2024/og_extraction_non_compression/well_testing_flaring.json',
            'Non-compression and non-processing activities that are oil and gas extraction and gas processing activities',
            'Well testing flaring',
        ),
        (
            '/reporting/json_schemas/2024/og_extraction_non_compression/associated_gas_flaring.json',
            'Non-compression and non-processing activities that are oil and gas extraction and gas processing activities',
            'Associated gas flaring',
        ),
        (
            '/reporting/json_schemas/2024/og_extraction_non_compression/associated_gas_venting.json',
            'Non-compression and non-processing activities that are oil and gas extraction and gas processing activities',
            'Associated gas venting',
        ),
        (
            '/reporting/json_schemas/2024/og_extraction_non_compression/blowdown_venting.json',
            'Non-compression and non-processing activities that are oil and gas extraction and gas processing activities',
            'Blowdown venting',
        ),
        (
            '/reporting/json_schemas/2024/og_extraction_non_compression/dehydrator_venting.json',
            'Non-compression and non-processing activities that are oil and gas extraction and gas processing activities',
            'Dehydrator venting',
        ),
        (
            '/reporting/json_schemas/2024/og_extraction_non_compression/drilling_flaring.json',
            'Non-compression and non-processing activities that are oil and gas extraction and gas processing activities',
            'Drilling flaring',
        ),
        (
            '/reporting/json_schemas/2024/og_extraction_non_compression/drilling_venting.json',
            'Non-compression and non-processing activities that are oil and gas extraction and gas processing activities',
            'Drilling venting',
        ),
        (
            '/reporting/json_schemas/2024/og_extraction_non_compression/equipment_leaks_using_leak_detection.json',
            'Non-compression and non-processing activities that are oil and gas extraction and gas processing activities',
            'Equipment leaks detected using leak detection and leaker emission factor methods',
        ),
        (
            '/reporting/json_schemas/2024/og_extraction_non_compression/flaring_stacks.json',
            'Non-compression and non-processing activities that are oil and gas extraction and gas processing activities',
            'Flaring stacks',
        ),
        (
            '/reporting/json_schemas/2024/og_extraction_non_compression/hydraulic_fracturing_flaring.json',
            'Non-compression and non-processing activities that are oil and gas extraction and gas processing activities',
            'Hydraulic fracturing flaring',
        ),
        (
            '/reporting/json_schemas/2024/og_extraction_non_compression/ng_high_bleed_venting.json',
            'Non-compression and non-processing activities that are oil and gas extraction and gas processing activities',
            'Natural gas pneumatic high bleed device venting',
        ),
        (
            '/reporting/json_schemas/2024/og_extraction_non_compression/ng_intermittent_venting.json',
            'Non-compression and non-processing activities that are oil and gas extraction and gas processing activities',
            'Natural gas pneumatic intermittent bleed device venting',
        ),
        (
            '/reporting/json_schemas/2024/og_extraction_non_compression/ng_low_bleed_venting.json',
            'Non-compression and non-processing activities that are oil and gas extraction and gas processing activities',
            'Natural gas pneumatic low bleed device venting',
        ),
        (
            '/reporting/json_schemas/2024/og_extraction_non_compression/ng_pump_venting.json',
            'Non-compression and non-processing activities that are oil and gas extraction and gas processing activities',
            'Natural gas pneumatic pump venting',
        ),
        (
            '/reporting/json_schemas/2024/og_extraction_non_compression/oil_recovery_injection_pump_blowdowns.json',
            'Non-compression and non-processing activities that are oil and gas extraction and gas processing activities',
            'Enhanced oil recovery injection pump blowdowns',
        ),
        (
            '/reporting/json_schemas/2024/og_extraction_non_compression/oil_recovery_produced_hydrocarbon.json',
            'Non-compression and non-processing activities that are oil and gas extraction and gas processing activities',
            'Enhanced oil recovery produced hydrocarbon liquids dissolved carbon dioxide',
        ),
        (
            '/reporting/json_schemas/2024/og_extraction_non_compression/other_fugitive_sources.json',
            'Non-compression and non-processing activities that are oil and gas extraction and gas processing activities',
            'Other fugitive sources',
        ),
        (
            '/reporting/json_schemas/2024/og_extraction_non_compression/other_venting_sources.json',
            'Non-compression and non-processing activities that are oil and gas extraction and gas processing activities',
            'Other venting sources',
        ),
        (
            '/reporting/json_schemas/2024/og_extraction_non_compression/population_count_sources.json',
            'Non-compression and non-processing activities that are oil and gas extraction and gas processing activities',
            'Population count sources',
        ),
        (
            '/reporting/json_schemas/2024/og_extraction_non_compression/produced_water_dissolved_co2.json',
            'Non-compression and non-processing activities that are oil and gas extraction and gas processing activities',
            'Produced water dissolved carbon dioxide and methane',
        ),
        (
            '/reporting/json_schemas/2024/og_extraction_non_compression/releases_from_tanks_for_storage.json',
            'Non-compression and non-processing activities that are oil and gas extraction and gas processing activities',
            'Releases from tanks used for storage, production or processing',
        ),
        (
            '/reporting/json_schemas/2024/og_extraction_non_compression/third_party_line_hits.json',
            'Non-compression and non-processing activities that are oil and gas extraction and gas processing activities',
            'Third party line hits with release of gas',
        ),
        (
            '/reporting/json_schemas/2024/og_extraction_non_compression/transmission_storage_tanks.json',
            'Non-compression and non-processing activities that are oil and gas extraction and gas processing activities',
            'Transmission storage tanks',
        ),
        (
            '/reporting/json_schemas/2024/og_extraction_non_compression/well_testing_venting.json',
            'Non-compression and non-processing activities that are oil and gas extraction and gas processing activities',
            'Well testing venting',
        ),
        (
            '/reporting/json_schemas/2024/og_extraction_non_compression/well_venting_liquid_unloading.json',
            'Non-compression and non-processing activities that are oil and gas extraction and gas processing activities',
            'Well venting for liquids unloading',
        ),
        (
            '/reporting/json_schemas/2024/og_extraction_non_compression/well_venting_well_completion.json',
            'Non-compression and non-processing activities that are oil and gas extraction and gas processing activities',
            'Gas well venting during well completions and workovers with or without hydraulic fracturing',
        ),
        (
            '/reporting/json_schemas/2024/og_extraction_other_than_ncnp/associated_gas_venting.json',
            'Oil and gas extraction and gas processing activities, other than non- compression and non-processing activities',
            'Associated gas venting',
        ),
        (
            '/reporting/json_schemas/2024/og_extraction_other_than_ncnp/flaring_stacks.json',
            'Oil and gas extraction and gas processing activities, other than non- compression and non-processing activities',
            'Flaring stacks',
        ),
        (
            '/reporting/json_schemas/2024/og_extraction_other_than_ncnp/centrifugal_compressor_venting.json',
            'Oil and gas extraction and gas processing activities, other than non- compression and non-processing activities',
            'Centrifugal compressor venting',
        ),
        (
            '/reporting/json_schemas/2024/og_extraction_other_than_ncnp/reciprocating_compressor_venting.json',
            'Oil and gas extraction and gas processing activities, other than non- compression and non-processing activities',
            'Reciprocating compressor venting',
        ),
        (
            '/reporting/json_schemas/2024/og_extraction_other_than_ncnp/equipment_leaks_detected_using_leak_detection.json',
            'Oil and gas extraction and gas processing activities, other than non- compression and non-processing activities',
            'Equipment leaks detected using leak detection and leaker emission factor methods',
        ),
        (
            '/reporting/json_schemas/2024/og_extraction_other_than_ncnp/population_count_sources.json',
            'Oil and gas extraction and gas processing activities, other than non- compression and non-processing activities',
            'Population count sources',
        ),
        (
            '/reporting/json_schemas/2024/og_extraction_other_than_ncnp/transmission_storage_tanks.json',
            'Oil and gas extraction and gas processing activities, other than non- compression and non-processing activities',
            'Transmission storage tanks',
        ),
        (
            '/reporting/json_schemas/2024/og_extraction_other_than_ncnp/enhanced_oil_recovery_injection_pump_blowdowns.json',
            'Oil and gas extraction and gas processing activities, other than non- compression and non-processing activities',
            'Enhanced oil recovery injection pump blowdowns',
        ),
        (
            '/reporting/json_schemas/2024/og_extraction_other_than_ncnp/produced_water_dissolved_carbon_dioxide_methane.json',
            'Oil and gas extraction and gas processing activities, other than non- compression and non-processing activities',
            'Produced water dissolved carbon dioxide and methane',
        ),
        (
            '/reporting/json_schemas/2024/og_extraction_other_than_ncnp/enhanced_oil_recovery_produced_hydrocarbon_liquids.json',
            'Oil and gas extraction and gas processing activities, other than non- compression and non-processing activities',
            'Enhanced oil recovery produced hydrocarbon liquids dissolved carbon dioxide',
        ),
        (
            '/reporting/json_schemas/2024/og_extraction_other_than_ncnp/other_venting_sources.json',
            'Oil and gas extraction and gas processing activities, other than non- compression and non-processing activities',
            'Other venting sources',
        ),
        (
            '/reporting/json_schemas/2024/og_extraction_other_than_ncnp/third_party_line_hits.json',
            'Oil and gas extraction and gas processing activities, other than non- compression and non-processing activities',
            'Third party line hits with release of gas',
        ),
        (
            '/reporting/json_schemas/2024/og_extraction_other_than_ncnp/associated_gas_flaring.json',
            'Oil and gas extraction and gas processing activities, other than non- compression and non-processing activities',
            'Associated gas flaring',
        ),
        (
            '/reporting/json_schemas/2024/og_extraction_other_than_ncnp/releases_from_tanks_used_for_storage.json',
            'Oil and gas extraction and gas processing activities, other than non- compression and non-processing activities',
            'Releases from tanks used for storage, production or processing',
        ),
        (
            '/reporting/json_schemas/2024/og_extraction_other_than_ncnp/blowdown_venting.json',
            'Oil and gas extraction and gas processing activities, other than non- compression and non-processing activities',
            'Blowdown venting',
        ),
        (
            '/reporting/json_schemas/2024/og_extraction_other_than_ncnp/dehydrator_venting.json',
            'Oil and gas extraction and gas processing activities, other than non- compression and non-processing activities',
            'Dehydrator venting',
        ),
        (
            '/reporting/json_schemas/2024/og_extraction_other_than_ncnp/acid_gas_removal_venting_or_incineration.json',
            'Oil and gas extraction and gas processing activities, other than non- compression and non-processing activities',
            'Acid gas removal venting or incineration',
        ),
        (
            '/reporting/json_schemas/2024/og_extraction_other_than_ncnp/ng_pump_venting.json',
            'Oil and gas extraction and gas processing activities, other than non- compression and non-processing activities',
            'Natural gas pneumatic pump venting',
        ),
        (
            '/reporting/json_schemas/2024/og_extraction_other_than_ncnp/ng_low_bleed_venting.json',
            'Oil and gas extraction and gas processing activities, other than non- compression and non-processing activities',
            'Natural gas pneumatic low bleed device venting',
        ),
        (
            '/reporting/json_schemas/2024/og_extraction_other_than_ncnp/ng_intermittent_venting.json',
            'Oil and gas extraction and gas processing activities, other than non- compression and non-processing activities',
            'Natural gas pneumatic intermittent bleed device venting',
        ),
        (
            '/reporting/json_schemas/2024/og_extraction_other_than_ncnp/ng_high_bleed_venting.json',
            'Oil and gas extraction and gas processing activities, other than non- compression and non-processing activities',
            'Natural gas pneumatic high bleed device venting',
        ),
        (
            '/reporting/json_schemas/2024/og_extraction_other_than_ncnp/other_fugitive_sources.json',
            'Oil and gas extraction and gas processing activities, other than non- compression and non-processing activities',
            'Other fugitive sources',
        ),
        (
            '/reporting/json_schemas/2024/open_pit_coal_mining/coal_exposed_during_mining.json',
            'Open pit coal mining',
            'Coal when broken or exposed to the atmosphere during mining',
        ),
        ('/reporting/json_schemas/2024/petroleum_refining/2_process_vents.json', 'Petroleum refining', 'Process vents'),
        (
            '/reporting/json_schemas/2024/petroleum_refining/3_asphalt_production.json',
            'Petroleum refining',
            'Asphalt production',
        ),
        (
            '/reporting/json_schemas/2024/petroleum_refining/4_sulphur_recovery.json',
            'Petroleum refining',
            'Sulphur recovery',
        ),
        (
            '/reporting/json_schemas/2024/petroleum_refining/5_flares.json',
            'Petroleum refining',
            'Flares, the flare pilot, the combustion of purge gas and the destruction of low Btu gases',
        ),
        (
            '/reporting/json_schemas/2024/petroleum_refining/6_above_ground_storage_tanks.json',
            'Petroleum refining',
            'Above-ground storage tanks at refineries',
        ),
        (
            '/reporting/json_schemas/2024/petroleum_refining/7_oil_water_separators.json',
            'Petroleum refining',
            'Oil-water separators at refineries',
        ),
        (
            '/reporting/json_schemas/2024/petroleum_refining/9_wastewater_processing.json',
            'Petroleum refining',
            'Wastewater processing using anaerobic digestion at refineries',
        ),
        (
            '/reporting/json_schemas/2024/petroleum_refining/10_uncontrolled_blowdown_systems.json',
            'Petroleum refining',
            'Uncontrolled blowdown systems used at refineries',
        ),
        (
            '/reporting/json_schemas/2024/petroleum_refining/11_loading_operations.json',
            'Petroleum refining',
            'Loading operations at refineries and terminals',
        ),
        (
            '/reporting/json_schemas/2024/petroleum_refining/12_delayed_coking_units.json',
            'Petroleum refining',
            'Delayed coking units at refineries',
        ),
        (
            '/reporting/json_schemas/2024/petroleum_refining/13_coke_calcining.json',
            'Petroleum refining',
            'Coke calcining at refineries',
        ),
        (
            '/reporting/json_schemas/2024/petroleum_refining/8_equipment_leaks_at_refineries.json',
            'Petroleum refining',
            'Equipment leaks at refineries',
        ),
        (
            '/reporting/json_schemas/2024/petroleum_refining/1_catalyst_regeneration.json',
            'Petroleum refining',
            'Catalyst regeneration',
        ),
        (
            '/reporting/json_schemas/2024/pulp_and_paper_production/pulp_and_paper_production.json',
            'Pulp and paper production',
            'Pulping and chemical recovery',
        ),
        (
            '/reporting/json_schemas/2024/refinery_fuel_gas/combustion_of_refinery_gas.json',
            'Refinery fuel gas combustion',
            'Combustion of refinery fuel gas, still gas, flexigas or associated gas',
        ),
        (
            '/reporting/json_schemas/2024/storage_of_petroleum_products/above_ground_storage_tanks.json',
            'Storage of petroleum products',
            'Above-ground storage tanks',
        ),
        (
            '/reporting/json_schemas/2024/zinc_production/1_reducing agents.json',
            'Zinc production',
            'Use of reducing agents during zinc production',
        ),
    ]

    cwd = os.getcwd()

    for path, activity_name, source_name in items:
        with open(f"{cwd}/{path}") as schema_file:
            schema = json.load(schema_file)

        ActivitySourceTypeJsonSchema.objects.filter(
            activity_id=Activity.objects.get(name=activity_name).id,
            source_type_id=SourceType.objects.get(name=source_name).id,
            valid_from_id=Configuration.objects.get(valid_from="2023-01-01").id,
            valid_to_id=Configuration.objects.get(valid_to="2099-12-31").id,
        ).update(json_schema=schema)


class Migration(migrations.Migration):
    dependencies = [
        (
            "reporting",
            "0117_V3_10_0",
        ),
    ]

    operations = [migrations.RunPython(reload_schemas_with_equivalent_emissions)]
