# Generated by Django 5.1.10 on 2025-07-18 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0119_update_report_raw_activity_data_equivalent_emission'),
    ]

    operations = []
