# Generated by Django 5.1.10 on 2025-07-16 23:26

from django.db import migrations


def update_emission_category_mapping_data(apps, schema_monitor):
    '''
    Add initial data to erc.emission_category_mapping
    '''

    EmissionCategoryMapping = apps.get_model('reporting', 'EmissionCategoryMapping')
    EmissionCategory = apps.get_model('reporting', 'EmissionCategory')
    Activity = apps.get_model('registration', 'Activity')
    SourceType = apps.get_model('reporting', 'SourceType')
    EmissionCategoryMapping.objects.bulk_create(
        [
            EmissionCategoryMapping(
                activity=Activity.objects.get(name='General stationary non-compression and non-processing combustion'),
                source_type=SourceType.objects.get(name='General stationary combustion of fuel or waste at a linear facilities operation not resulting in the production of useful energy'),
                emission_category=EmissionCategory.objects.get(
                    category_name='Emissions from line tracing and non-processing and non-compression activities'
                ),
            ),
            EmissionCategoryMapping(
                activity=Activity.objects.get(name='General stationary non-compression and non-processing combustion'),
                source_type=SourceType.objects.get(name='Field gas or process vent gas combustion at a linear facilities operation'),
                emission_category=EmissionCategory.objects.get(
                    category_name='Emissions from line tracing and non-processing and non-compression activities'
                ),
            ),
        ]
    )


def reverse_update_emission_category_mapping_data(apps, schema_monitor):
    '''
    Remove initial data from erc.emission_category_mapping
    '''
    EmissionCategoryMapping = apps.get_model('reporting', 'EmissionCategoryMapping')
    EmissionCategory = apps.get_model('reporting', 'EmissionCategory')
    Activity = apps.get_model('registration', 'Activity')
    SourceType = apps.get_model('reporting', 'SourceType')
    EmissionCategoryMapping.objects.get(
                activity=Activity.objects.get(name='General stationary non-compression and non-processing combustion'),
                source_type=SourceType.objects.get(name='General stationary combustion of fuel or waste at a linear facilities operation not resulting in the production of useful energy'),
                emission_category=EmissionCategory.objects.get(
                    category_name='Emissions from line tracing and non-processing and non-compression activities'
                ),
    ).delete()
    EmissionCategoryMapping.objects.get(
                activity=Activity.objects.get(name='General stationary non-compression and non-processing combustion'),
                source_type=SourceType.objects.get(name='Field gas or process vent gas combustion at a linear facilities operation'),
                emission_category=EmissionCategory.objects.get(
                    category_name='Emissions from line tracing and non-processing and non-compression activities'
                ),
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0121_V3_12_0'),
    ]

    operations = [
        migrations.RunPython(update_emission_category_mapping_data, reverse_update_emission_category_mapping_data),
    ]
