# Generated by Django 5.1.12 on 2025-09-22 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0131_V3_20_0'),
    ]

    operations = []
