# Generated by Django 5.1.12 on 2025-10-01 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0133_V4_0_1'),
    ]

    operations = []
