# Generated by Django 5.1.12 on 2025-11-07 22:21

from django.db import migrations, models


def add_field_display_titles(apps, schema_editor):
    ReportingField = apps.get_model('reporting', 'ReportingField')

    ReportingField.objects.filter(field_name='Unit-Fuel Annual Steam Generated').update(
        field_display_title='Annual Steam Generated'
    )
    ReportingField.objects.filter(field_name='Unit-Fuel Heat Input').update(field_display_title='Heat Input')
    field_names = [
        'Unit-Fuel-CH4 Default EF',
        'Unit-Fuel-CH4 Default HHV-Default EF',
        'Unit-Fuel-CH4 Heat Input-Default EF',
        'Unit-Fuel-CH4 Measured EF',
        'Unit-Fuel-CH4 Measured HHV-Default EF',
        'Unit-Fuel-CH4 Measured Steam-Default EF',
        'Unit-Fuel-CH4 Site-specific EF',
        'Unit-Fuel-CO2 Default EF',
        'Unit-Fuel-CO2 Default HHV-Default EF',
        'Unit-Fuel-CO2 Measured HHV-Default EF',
        'Unit-Fuel-CO2 Measured Steam-Default EF',
        'Unit-Fuel-CO2 Measured Steam-Measured EF',
        'Unit-Fuel-CO2 Site-specific EF',
        'Unit-Fuel-N2O Default EF',
        'Unit-Fuel-N2O Default HHV-Default EF',
        'Unit-Fuel-N2O Heat Input-Default EF',
        'Unit-Fuel-N2O Measured EF',
        'Unit-Fuel-N2O Measured HHV-Default EF',
        'Unit-Fuel-N2O Measured Steam-Default EF',
        'Unit-Fuel-N2O Site-specific EF',
    ]

    for field_name in field_names:
        display_title = field_name.replace('Unit-Fuel-', '', 1)
        ReportingField.objects.filter(field_name=field_name).update(field_display_title=display_title)


def reverse_add_field_display_titles(apps, schema_editor):
    ReportingField = apps.get_model('reporting', 'ReportingField')
    ReportingField.objects.update(field_display_title=None)


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0137_V4_3_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportingfield',
            name='field_display_title',
            field=models.CharField(
                blank=True,
                db_comment='Optional display title for the field to be used in forms.',
                max_length=1000,
                null=True,
            ),
        ),
        migrations.RunPython(add_field_display_titles, reverse_add_field_display_titles),
    ]
