# Generated by Django 5.1.14 on 2025-11-14 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0138_reportingfield_field_display_title'),
    ]

    operations = []
