# Generated by Django 5.1.14 on 2025-11-27 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0140_V4_5_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportoperation',
            name='operation_opted_out_detail',
            field=models.CharField(
                blank=True,
                db_comment="The effective date for the operation's opting out of BCIERS, if applicable",
                max_length=1000,
                null=True,
            ),
        ),
    ]
