# Generated by Django 5.1.14 on 2025-11-18 23:30

from datetime import datetime
from django.db import migrations
from django.utils import timezone


def populate_report_open_date(apps, schema_editor):
    """
    Populate report_open_date for existing reporting years.
    """
    ReportingYear = apps.get_model('reporting', 'ReportingYear')

    reporting_year_2023 = ReportingYear.objects.get(reporting_year=2023)
    reporting_year_2023.report_open_date = timezone.make_aware(datetime(2024, 3, 1, 0, 0, 0))
    reporting_year_2023.save()

    reporting_year_2024 = ReportingYear.objects.get(reporting_year=2024)
    reporting_year_2024.report_open_date = timezone.make_aware(datetime(2025, 3, 1, 0, 0, 0))
    reporting_year_2024.save()

    reporting_year_2025 = ReportingYear.objects.get(reporting_year=2025)
    reporting_year_2025.report_open_date = timezone.make_aware(datetime(2026, 3, 5, 0, 0, 0))
    reporting_year_2025.save()

    reporting_year_2026 = ReportingYear.objects.get(reporting_year=2026)
    reporting_year_2026.report_open_date = timezone.make_aware(datetime(2027, 3, 1, 0, 0, 0))
    reporting_year_2026.save()


def reverse_populate_report_open_date(apps, schema_editor):
    """
    Reverse migration - set report_open_date to None for all reporting years.
    """
    ReportingYear = apps.get_model('reporting', 'ReportingYear')
    ReportingYear.objects.all().update(report_open_date=None)


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0140_reportingyear_report_open_date'),
    ]

    operations = [
        migrations.RunPython(populate_report_open_date, reverse_populate_report_open_date),
    ]
