# Generated by Django 5.1.14 on 2025-12-03 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0143_populate_report_open_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportoperation',
            name='operation_opted_out_final_reporting_year',
            field=models.IntegerField(
                blank=True,
                db_comment='The last year an operation will report for, if it has opted out of BCIERS',
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='reportoperation',
            name='operation_bcghgid',
            field=models.CharField(blank=True, db_comment='The BCGHG ID of the operation', max_length=1000, null=True),
        ),
    ]
