# Generated by Django 5.1.14 on 2025-12-01 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0143_populate_report_open_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportoperation',
            name='operation_opted_out_effective_date',
            field=models.CharField(
                blank=True,
                db_comment="The effective date for the operation's opt-out of BCIERS, if applicable",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='reportoperation',
            name='operation_bcghgid',
            field=models.CharField(blank=True, db_comment='The BCGHG ID of the operation', max_length=1000, null=True),
        ),
    ]
