# Generated by Django 5.1.15 on 2025-12-10 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0145_V4_6_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportoperation',
            name='operation_opted_out_final_reporting_year',
            field=models.IntegerField(
                blank=True,
                db_comment='The last year an operation will report for, if it has opted out of BCIERS',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='reportoperation',
            name='operation_bcghgid',
            field=models.CharField(blank=True, db_comment='The BCGHG ID of the operation', max_length=1000, null=True),
        ),
    ]
