# Generated by Django 5.1.15 on 2026-02-19 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0152_report_operation_final_reporting_year'),
    ]

    operations = []
