# Generated by Django 5.1.15 on 2026-02-05 20:05

from django.db import migrations


def update_configuration_elements(apps, schema_editor):
    """
    Update all existing ConfigurationElement records to span both 2024 and 2025 configurations.
    This allows configuration elements to remain valid across both years unless explicitly changed.
    """
    Configuration = apps.get_model('reporting', 'Configuration')
    ConfigurationElement = apps.get_model('reporting', 'ConfigurationElement')

    # Get the configurations
    config_2024 = Configuration.objects.get(slug='2024', valid_from='2023-01-01', valid_to='2024-12-31')
    config_2025 = Configuration.objects.get(slug='2025', valid_from='2025-01-01', valid_to='2099-12-31')

    # Update all ConfigurationElements that point to 2024 config to instead point to 2025 config
    ConfigurationElement.objects.filter(valid_to_id=config_2024.id).update(valid_to_id=config_2025.id)


def reverse_update_configuration_elements(apps, schema_editor):
    """
    Reverse the update by restoring ConfigurationElement records to point to the 2024 configuration.
    """
    Configuration = apps.get_model('reporting', 'Configuration')
    ConfigurationElement = apps.get_model('reporting', 'ConfigurationElement')

    config_2024 = Configuration.objects.get(slug='2024', valid_from='2023-01-01', valid_to='2024-12-31')

    # Restore all ConfigurationElements to point to the 2024 config
    ConfigurationElement.objects.filter(valid_to_id__isnull=False).update(valid_to_id=config_2024.id)


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0154_create_2025_configuration'),
    ]

    operations = [
        migrations.RunPython(update_configuration_elements, reverse_update_configuration_elements),
    ]
