# Generated by Django 5.1.15 on 2026-02-26 17:41

from django.db import migrations
from datetime import datetime
from zoneinfo import ZoneInfo


def update_report_open_date(apps, schema_editor):
    ReportingYear = apps.get_model('reporting', 'ReportingYear')
    reporting_year_2025 = ReportingYear.objects.get(reporting_year=2025)
    reporting_year_2025.report_open_date = datetime(2026, 3, 18, tzinfo=ZoneInfo("America/Vancouver"))
    reporting_year_2025.save()


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0160_compliance_summary_product_override_values'),
    ]

    operations = [migrations.RunPython(update_report_open_date, elidable=True)]
