# Generated by Django 5.1.15 on 2026-03-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0165_V5_4_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcompliancesummaryproduct',
            name='jan_mar_production',
            field=models.DecimalField(
                blank=True,
                db_comment='Amount of product produced between January & March',
                decimal_places=4,
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='reportproduct',
            name='production_data_jan_mar',
            field=models.FloatField(
                blank=True,
                db_comment='The total production amount for January to March period, expressed in the unit of this same model. This should only be relevant to reporting year 2025.',
                null=True,
            ),
        ),
    ]
