# Generated by Django 5.1.15 on 2026-03-13 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0167_report_compliance_summary_add_jan_mar_production'),
    ]

    operations = []
