# Generated by Django 5.1.15 on 2026-03-26 17:43
from django.db import migrations


def fix_municipal_solid_waste_fuel_name(apps, schema_editor):
    FuelType = apps.get_model("reporting", "FuelType")
    FuelType.objects.filter(name="Municipal Solide Waste - biomass component").update(
        name="Municipal Solid Waste - biomass component"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0170_V5_6_0'),
    ]

    operations = [
        migrations.RunPython(
            fix_municipal_solid_waste_fuel_name,
            migrations.RunPython.noop,
        ),
    ]
