# Generated by Django 5.1.15 on 2026-03-27 16:52

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0171_fix_municipal_solid_waste_fuel_name'),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name='activityjsonschema',
            trigger=pgtrigger.compiler.Trigger(
                name='no_overlapping_configuration_records',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='\n        declare\n            new_valid_from date;\n            new_valid_to date;\n        begin\n            select valid_from into new_valid_from\n            from "erc"."configuration" where id = new.valid_from_id;\n\n            select valid_to into new_valid_to\n            from "erc"."configuration" where id = new.valid_to_id;\n\n            if exists (\n                select 1\n                from "erc"."activity_json_schema" t\n                join "erc"."configuration" cf on cf.id = t.valid_from_id\n                join "erc"."configuration" ct on ct.id = t.valid_to_id\n                where t.activity_id = new.activity_id\n                  and (tg_op = \'INSERT\' or t.id != old.id)\n                  and new_valid_from <= ct.valid_to\n                  and new_valid_to >= cf.valid_from\n            ) then\n                raise exception \'This record will result in duplicate json schemas being returned for the date range % - % as it overlaps with a current record or records\', new_valid_from, new_valid_to;\n            end if;\n\n            return new;\n        end;\n        ',
                    hash='f86652fd49716f4c26c1539a2e82b3cbe88b6278',
                    operation='INSERT OR UPDATE',
                    pgid='pgtrigger_no_overlapping_configuration_records_f0ff8',
                    table='erc"."activity_json_schema',
                    when='BEFORE',
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='activitysourcetypejsonschema',
            trigger=pgtrigger.compiler.Trigger(
                name='no_overlapping_configuration_records',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='\n        declare\n            new_valid_from date;\n            new_valid_to date;\n        begin\n            select valid_from into new_valid_from\n            from "erc"."configuration" where id = new.valid_from_id;\n\n            select valid_to into new_valid_to\n            from "erc"."configuration" where id = new.valid_to_id;\n\n            if exists (\n                select 1\n                from "erc"."activity_source_type_json_schema" t\n                join "erc"."configuration" cf on cf.id = t.valid_from_id\n                join "erc"."configuration" ct on ct.id = t.valid_to_id\n                where t.activity_id = new.activity_id\n          and t.source_type_id = new.source_type_id\n          and (tg_op = \'INSERT\' or t.id != old.id)\n                  and new_valid_from <= ct.valid_to\n                  and new_valid_to >= cf.valid_from\n            ) then\n                raise exception \'This record will result in duplicate json schemas being returned for the date range % - % as it overlaps with a current record or records\', new_valid_from, new_valid_to;\n            end if;\n\n            return new;\n        end;\n        ',
                    hash='4183a64137f3e114ccab3d249d8dc2d8a7b0f6d2',
                    operation='INSERT OR UPDATE',
                    pgid='pgtrigger_no_overlapping_configuration_records_e384d',
                    table='erc"."activity_source_type_json_schema',
                    when='BEFORE',
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='configurationelement',
            trigger=pgtrigger.compiler.Trigger(
                name='no_overlapping_configuration_records',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='\n        declare\n            new_valid_from date;\n            new_valid_to date;\n        begin\n            select valid_from into new_valid_from\n            from "erc"."configuration" where id = new.valid_from_id;\n\n            select valid_to into new_valid_to\n            from "erc"."configuration" where id = new.valid_to_id;\n\n            if exists (\n                select 1\n                from "erc"."configuration_element" t\n                join "erc"."configuration" cf on cf.id = t.valid_from_id\n                join "erc"."configuration" ct on ct.id = t.valid_to_id\n                where t.activity_id = new.activity_id\n          and t.source_type_id = new.source_type_id\n  and t.gas_type_id = new.gas_type_id\n  and t.methodology_id = new.methodology_id\n          and (tg_op = \'INSERT\' or t.id != old.id)\n                  and new_valid_from <= ct.valid_to\n                  and new_valid_to >= cf.valid_from\n            ) then\n                raise exception \'This record will result in duplicate configuration elements being returned for the date range % - % as it overlaps with a current record or records\', new_valid_from, new_valid_to;\n            end if;\n\n            return new;\n        end;\n        ',
                    hash='28ff317dc62bada754fea938b98263a19cf8bb06',
                    operation='INSERT OR UPDATE',
                    pgid='pgtrigger_no_overlapping_configuration_records_7a741',
                    table='erc"."configuration_element',
                    when='BEFORE',
                ),
            ),
        ),
    ]
