# Generated by Django 5.1.15 on 2026-03-27 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0172_activityjsonschema_no_overlapping_configuration_records_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectedValueRangeFuelAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'lower_bound',
                    models.DecimalField(
                        db_comment='The lower bound of the value range for the related fuel type. The reported fuel_amount value should not be lower than this value',
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                    ),
                ),
                (
                    'upper_bound',
                    models.DecimalField(
                        db_comment='The upper bound of the value range for the related fuel type. The reported fuel_amount value should not be greater than this value',
                        decimal_places=2,
                        max_digits=20,
                    ),
                ),
                ('valid_from', models.DateField(db_comment='The date this range bound record took effect')),
                ('valid_to', models.DateField(db_comment='The last date this range bound record was in effect')),
                (
                    'fuel_type',
                    models.ForeignKey(
                        db_comment='The fuel type record that this value range applies to for the fuel_amount value',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='expected_value_range_fuel_amount',
                        to='reporting.fueltype',
                    ),
                ),
            ],
            options={
                'db_table': 'erc"."expected_value_range_fuel_amount',
                'db_table_comment': 'This table contains the expected range of values by fuel_type that a reported fuel_type value should fall within. Values reported outside of these bounds are to be considered extraordinary and should be reviewed.',
            },
        ),
        migrations.CreateModel(
            name='ExpectedValueRangeMethodology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'lower_bound',
                    models.DecimalField(
                        db_comment='The lower bound of the value range for the related methodology. The reported methodology value should not be lower than this value',
                        decimal_places=4,
                        default=0,
                        max_digits=10,
                    ),
                ),
                (
                    'upper_bound',
                    models.DecimalField(
                        db_comment='The upper bound of the value range for the related methodology. The reported methodology value should not be greater than this value',
                        decimal_places=4,
                        max_digits=20,
                    ),
                ),
                ('valid_from', models.DateField(db_comment='The date this range bound record took effect')),
                ('valid_to', models.DateField(db_comment='The last date this range bound record was in effect')),
                (
                    'fuel_type',
                    models.ForeignKey(
                        db_comment='The fuel_type record that this value range applies to for the methodolgy value',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='expected_value_range_methodology',
                        to='reporting.fueltype',
                    ),
                ),
                (
                    'gas_type',
                    models.ForeignKey(
                        db_comment='The gas_type record that this value range applies to for the methodology value',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='expected_value_range_methodology',
                        to='reporting.gastype',
                    ),
                ),
                (
                    'methodology',
                    models.ForeignKey(
                        db_comment='The methodology record that this value range applies to for the methodology value',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='expected_value_range_methodology',
                        to='reporting.methodology',
                    ),
                ),
            ],
            options={
                'db_table': 'erc"."expected_value_range_methodology',
                'db_table_comment': 'This table contains the expected range of values by fuel_type, gas_type and methodology that a reported methodology value should fall within. Values reported outside of these bounds are to be considered extraordinary and should be reviewed.',
            },
        ),
    ]
