# Generated by Django 5.1.15 on 2026-03-27 21:55

from django.db import migrations
from decimal import Decimal


def insert_validation_records(apps, schema_monitor):
    ExpectedValueRangeFuelAmount = apps.get_model('reporting', 'ExpectedValueRangeFuelAmount')
    ExpectedValueRangeMethodology = apps.get_model('reporting', 'ExpectedValueRangeMethodology')
    FuelType = apps.get_model('reporting', 'FuelType')
    Methodology = apps.get_model('reporting', 'Methodology')

    # Natural Gas fuel_amount bounds
    natural_gas = FuelType.objects.get(name='Natural Gas')
    ExpectedValueRangeFuelAmount.objects.create(
        fuel_type=natural_gas,
        lower_bound=Decimal('0'),
        upper_bound=Decimal('5000000.00'),
        valid_from='2023-01-01',
        valid_to='9999-12-31',
    )

    # Diesel bounds
    diesel = FuelType.objects.get(name='Diesel')
    ExpectedValueRangeFuelAmount.objects.create(
        fuel_type=diesel,
        lower_bound=Decimal('0'),
        upper_bound=Decimal('5000.00'),
        valid_from='2023-01-01',
        valid_to='9999-12-31',
    )

    # Propane bounds
    propane = FuelType.objects.get(name='Propane')
    ExpectedValueRangeFuelAmount.objects.create(
        fuel_type=propane,
        lower_bound=Decimal('0'),
        upper_bound=Decimal('1000.00'),
        valid_from='2023-01-01',
        valid_to='9999-12-31',
    )

    # Field Gas bounds
    field_gas = FuelType.objects.get(name='Field gas')
    ExpectedValueRangeFuelAmount.objects.create(
        fuel_type=field_gas,
        lower_bound=Decimal('0'),
        upper_bound=Decimal('5000.00'),
        valid_from='2023-01-01',
        valid_to='9999-12-31',
    )

    # Wood Waste bounds
    wood_waste = FuelType.objects.get(name='Wood Waste')
    ExpectedValueRangeFuelAmount.objects.create(
        fuel_type=wood_waste,
        lower_bound=Decimal('0'),
        upper_bound=Decimal('1000000.00'),
        valid_from='2023-01-01',
        valid_to='9999-12-31',
    )


def revert_validation_records(apps, schema_monitor):
    ExpectedValueRangeFuelAmount = apps.get_model('reporting', 'ExpectedValueRangeFuelAmount')

    ExpectedValueRangeFuelAmount.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0173_fuel_type_validation_models'),
    ]

    operations = [
        migrations.RunPython(insert_validation_records, revert_validation_records),
    ]
