# Generated by Django 5.1.15 on 2026-03-31 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0173_remove_duplicate_methodology_records'),
    ]

    operations = []
