# Generated by Django 5.1.15 on 2026-03-31 21:22

from django.db import migrations, models


# Helper function to turn a string into a camel-cased json key
def str_to_camel_case(st: str) -> str:
    output = "".join(x for x in st.title() if x.isalnum())
    return output[0].lower() + output[1:]


def populate_slug(apps, schema_monitor):
    ReportingField = apps.get_model('reporting', 'ReportingField')
    for reporting_field in ReportingField.objects.all():
        slug_to_insert = str_to_camel_case(reporting_field.field_name)
        reporting_field.slug = slug_to_insert
        reporting_field.save()


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0173_fuel_type_validation_models'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reportingfield',
            name='unique_reporting_field',
        ),
        migrations.AddField(
            model_name='reportingfield',
            name='slug',
            field=models.CharField(
                db_comment='camel-cased slug defines how this field is represented in the reported json data.',
                default='slug',
                max_length=1000,
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='reportingfield',
            constraint=models.UniqueConstraint(
                fields=('field_name', 'field_type', 'field_units', 'slug'), name='unique_reporting_field'
            ),
        ),
        migrations.RunPython(populate_slug, migrations.RunPython.noop),
    ]
