# Generated by Django 5.1.15 on 2026-03-27 21:55

from django.db import migrations
from decimal import Decimal


def insert_validation_records(apps, schema_monitor):
    ExpectedValueRangeFuelAmount = apps.get_model('reporting', 'ExpectedValueRangeFuelAmount')
    ExpectedValueRangeMethodologyField = apps.get_model('reporting', 'ExpectedValueRangeMethodologyField')
    FuelType = apps.get_model('reporting', 'FuelType')
    Methodology = apps.get_model('reporting', 'Methodology')
    ReportingField = apps.get_model('reporting', 'ReportingField')

    # Methodologies
    measured_hhv = Methodology.objects.get(name='Measured HHV/Default EF')  # Measured High Heating Value
    default_hhv = Methodology.objects.get(name='Default HHV/Default EF')  # Default High Heating Value
    measured_cc = Methodology.objects.get(name='Measured CC')  # CC Weight fraction
    default_ef = Methodology.objects.get(name='Default EF')  # Default EF
    measured_ef = Methodology.objects.get(name='Measured EF')  # Measured EF
    measured_steam_default_ef = Methodology.objects.get(name='Measured Steam/Default EF')  # Measured Steam Default EF
    measured_steam_measured_ef = Methodology.objects.get(
        name='Measured Steam/Measured EF'
    )  # Measured Steam Measured EF
    heat_input_default_ef = Methodology.objects.get(name='Heat Input/Default EF')  # Heat Input Default EF

    # Reporting Fields
    measured_high_heating_value_field = ReportingField.objects.get(slug='fuelAnnualWeightedAverageHighHeatingValue')
    default_high_heating_value_field = ReportingField.objects.get(slug='fuelDefaultHighHeatingValue')
    cc_weight_fraction_field = ReportingField.objects.get(slug='fuelAnnualWeightedAverageCarbonContentWeightFraction')

    ## CO2 Fields
    co2_measured_hhv_default_ef_field = ReportingField.objects.get(slug='unitFuelCo2MeasuredHhvDefaultEf')
    co2_default_hhv_default_ef_field = ReportingField.objects.get(slug='unitFuelCo2DefaultHhvDefaultEf')
    co2_default_ef_field = ReportingField.objects.get(slug='unitFuelCo2DefaultEf')
    co2_measured_steam_default_ef_field = ReportingField.objects.get(slug='unitFuelCo2MeasuredSteamDefaultEf')
    co2_measured_steam_measured_ef_field = ReportingField.objects.get(slug='unitFuelCo2MeasuredSteamMeasuredEf')

    ## CH4 Fields
    ch4_measured_hhv_default_ef_field = ReportingField.objects.get(slug='unitFuelCh4MeasuredHhvDefaultEf')
    ch4_default_hhv_default_ef_field = ReportingField.objects.get(slug='unitFuelCh4DefaultHhvDefaultEf')
    ch4_default_ef_field = ReportingField.objects.get(slug='unitFuelCh4DefaultEf')
    ch4_measured_ef_field = ReportingField.objects.get(slug='unitFuelCh4MeasuredEf')
    ch4_measured_steam_default_ef_field = ReportingField.objects.get(slug='unitFuelCh4MeasuredSteamDefaultEf')
    ch4_heat_input_default_ef_field = ReportingField.objects.get(slug='unitFuelCh4HeatInputDefaultEf')

    ## N2O Fields
    n2o_measured_hhv_default_ef_field = ReportingField.objects.get(slug='unitFuelN2OMeasuredHhvDefaultEf')
    n2o_default_hhv_default_ef_field = ReportingField.objects.get(slug='unitFuelN2ODefaultHhvDefaultEf')
    n2o_default_ef_field = ReportingField.objects.get(slug='unitFuelN2ODefaultEf')
    n2o_measured_ef_field = ReportingField.objects.get(slug='unitFuelN2OMeasuredEf')
    n2o_measured_steam_default_ef_field = ReportingField.objects.get(slug='unitFuelN2OMeasuredSteamDefaultEf')
    n2o_heat_input_default_ef_field = ReportingField.objects.get(slug='unitFuelN2OHeatInputDefaultEf')

    ####################
    #   NATURAL GAS    #
    ####################

    # Natural Gas fuel_amount bounds
    natural_gas = FuelType.objects.get(name='Natural Gas')
    ExpectedValueRangeFuelAmount.objects.create(
        fuel_type=natural_gas,
        lower_bound=Decimal('0'),
        upper_bound=Decimal('5000000.00'),
        valid_from='2023-01-01',
        valid_to='9999-12-31',
    )
    # Natural Gas Methodology bounds
    ### Measured High Heating Value
    ExpectedValueRangeMethodologyField.objects.create(
        fuel_type=natural_gas,
        methodology=measured_hhv,
        reporting_field=measured_high_heating_value_field,
        lower_bound=Decimal('0.02'),
        upper_bound=Decimal('0.06'),
        valid_from='2023-01-01',
        valid_to='9999-12-31',
    )
    ### Default High Heating Value
    ExpectedValueRangeMethodologyField.objects.create(
        fuel_type=natural_gas,
        methodology=default_hhv,
        reporting_field=default_high_heating_value_field,
        lower_bound=Decimal('0.02'),
        upper_bound=Decimal('0.06'),
        valid_from='2023-01-01',
        valid_to='9999-12-31',
    )
    ### CC Weight Fraction
    ExpectedValueRangeMethodologyField.objects.create(
        fuel_type=natural_gas,
        methodology=measured_cc,
        reporting_field=cc_weight_fraction_field,
        lower_bound=Decimal('0.3'),
        upper_bound=Decimal('1.5'),
        valid_from='2023-01-01',
        valid_to='9999-12-31',
    )
    ### CH4 Measured HHV Default EF
    ExpectedValueRangeMethodologyField.objects.create(
        fuel_type=natural_gas,
        methodology=measured_hhv,
        reporting_field=ch4_measured_hhv_default_ef_field,
        lower_bound=Decimal('0.5'),
        upper_bound=Decimal('2.0'),
        valid_from='2023-01-01',
        valid_to='9999-12-31',
    )
    ### CH4 Default HHV Default EF
    ExpectedValueRangeMethodologyField.objects.create(
        fuel_type=natural_gas,
        methodology=default_hhv,
        reporting_field=ch4_default_hhv_default_ef_field,
        lower_bound=Decimal('0.5'),
        upper_bound=Decimal('2.0'),
        valid_from='2023-01-01',
        valid_to='9999-12-31',
    )
    ### N2O Measured HHV Default EF
    ExpectedValueRangeMethodologyField.objects.create(
        fuel_type=natural_gas,
        methodology=measured_hhv,
        reporting_field=n2o_measured_hhv_default_ef_field,
        lower_bound=Decimal('0.5'),
        upper_bound=Decimal('3.0'),
        valid_from='2023-01-01',
        valid_to='9999-12-31',
    )
    ### N2O Default HHV Default EF
    ExpectedValueRangeMethodologyField.objects.create(
        fuel_type=natural_gas,
        methodology=default_hhv,
        reporting_field=n2o_default_hhv_default_ef_field,
        lower_bound=Decimal('0.5'),
        upper_bound=Decimal('3.0'),
        valid_from='2023-01-01',
        valid_to='9999-12-31',
    )
    ### CH4 Default EF
    ExpectedValueRangeMethodologyField.objects.create(
        fuel_type=natural_gas,
        methodology=default_ef,
        reporting_field=ch4_default_ef_field,
        lower_bound=Decimal('0.02'),
        upper_bound=Decimal('0.1'),
        valid_from='2023-01-01',
        valid_to='9999-12-31',
    )
    ### N2O Default EF
    ExpectedValueRangeMethodologyField.objects.create(
        fuel_type=natural_gas,
        methodology=default_ef,
        reporting_field=n2o_default_ef_field,
        lower_bound=Decimal('0.02'),
        upper_bound=Decimal('0.1'),
        valid_from='2023-01-01',
        valid_to='9999-12-31',
    )

    ####################
    #      DIESEL      #
    ####################

    # Diesel fuel_amount bounds
    diesel = FuelType.objects.get(name='Diesel')
    ExpectedValueRangeFuelAmount.objects.create(
        fuel_type=diesel,
        lower_bound=Decimal('0'),
        upper_bound=Decimal('5000.00'),
        valid_from='2023-01-01',
        valid_to='9999-12-31',
    )

    # Diesel Methodology bounds
    ### Measured High Heating Value
    ExpectedValueRangeMethodologyField.objects.create(
        fuel_type=diesel,
        methodology=measured_hhv,
        reporting_field=measured_high_heating_value_field,
        lower_bound=Decimal('20.0'),
        upper_bound=Decimal('80.0'),
        valid_from='2023-01-01',
        valid_to='9999-12-31',
    )
    ### Default High Heating Value
    ExpectedValueRangeMethodologyField.objects.create(
        fuel_type=diesel,
        methodology=default_hhv,
        reporting_field=default_high_heating_value_field,
        lower_bound=Decimal('20.0'),
        upper_bound=Decimal('80.0'),
        valid_from='2023-01-01',
        valid_to='9999-12-31',
    )
    ### CC Weight Fraction
    ExpectedValueRangeMethodologyField.objects.create(
        fuel_type=diesel,
        methodology=measured_cc,
        reporting_field=cc_weight_fraction_field,
        lower_bound=Decimal('300.0'),
        upper_bound=Decimal('1500.0'),
        valid_from='2023-01-01',
        valid_to='9999-12-31',
    )
    ## CO2 kg CO2/kl
    ### CO2 Measured HHV Default EF
    ExpectedValueRangeMethodologyField.objects.create(
        fuel_type=diesel,
        methodology=measured_hhv,
        reporting_field=co2_default_ef_field,
        lower_bound=Decimal('1000.0'),
        upper_bound=Decimal('5000.0'),
        valid_from='2023-01-01',
        valid_to='9999-12-31',
    )
    ### CO2 Default HHV Default EF
    ExpectedValueRangeMethodologyField.objects.create(
        fuel_type=diesel,
        methodology=default_hhv,
        reporting_field=co2_default_ef_field,
        lower_bound=Decimal('1000.0'),
        upper_bound=Decimal('5000.0'),
        valid_from='2023-01-01',
        valid_to='9999-12-31',
    )
    ### CO2 Default EF
    ExpectedValueRangeMethodologyField.objects.create(
        fuel_type=diesel,
        methodology=default_ef,
        reporting_field=co2_default_ef_field,
        lower_bound=Decimal('1000.0'),
        upper_bound=Decimal('5000.0'),
        valid_from='2023-01-01',
        valid_to='9999-12-31',
    )
    ### CO2 Measured Steam Default EF
    ExpectedValueRangeMethodologyField.objects.create(
        fuel_type=diesel,
        methodology=measured_steam_default_ef,
        reporting_field=co2_default_ef_field,
        lower_bound=Decimal('1000.0'),
        upper_bound=Decimal('5000.0'),
        valid_from='2023-01-01',
        valid_to='9999-12-31',
    )
    ### CO2 Measured Steam Measured EF
    ExpectedValueRangeMethodologyField.objects.create(
        fuel_type=diesel,
        methodology=measured_steam_measured_ef,
        reporting_field=co2_measured_steam_measured_ef_field,
        lower_bound=Decimal('1000.0'),
        upper_bound=Decimal('5000.0'),
        valid_from='2023-01-01',
        valid_to='9999-12-31',
    )
    ## CH4 kg CH4/kl
    ### CH4 Default EF
    ExpectedValueRangeMethodologyField.objects.create(
        fuel_type=diesel,
        methodology=default_ef,
        reporting_field=ch4_default_ef_field,
        lower_bound=Decimal('60.0'),
        upper_bound=Decimal('200.0'),
        valid_from='2023-01-01',
        valid_to='9999-12-31',
    )
    ### CH4 Measured EF
    ExpectedValueRangeMethodologyField.objects.create(
        fuel_type=diesel,
        methodology=measured_ef,
        reporting_field=ch4_measured_ef_field,
        lower_bound=Decimal('60.0'),
        upper_bound=Decimal('200.0'),
        valid_from='2023-01-01',
        valid_to='9999-12-31',
    )
    ## N2O kg N2O/kl
    ### N2O Default EF
    ExpectedValueRangeMethodologyField.objects.create(
        fuel_type=diesel,
        methodology=default_ef,
        reporting_field=n2o_default_ef_field,
        lower_bound=Decimal('200.0'),
        upper_bound=Decimal('800.0'),
        valid_from='2023-01-01',
        valid_to='9999-12-31',
    )
    ### N2O Measured EF
    ExpectedValueRangeMethodologyField.objects.create(
        fuel_type=diesel,
        methodology=measured_ef,
        reporting_field=n2o_measured_ef_field,
        lower_bound=Decimal('200.0'),
        upper_bound=Decimal('800.0'),
        valid_from='2023-01-01',
        valid_to='9999-12-31',
    )
    ## CO2 kg CO2/GJ
    ### CO2 Measured HHV Default EF
    ExpectedValueRangeMethodologyField.objects.create(
        fuel_type=diesel,
        methodology=measured_hhv,
        reporting_field=co2_measured_hhv_default_ef_field,
        lower_bound=Decimal('30.0'),
        upper_bound=Decimal('150.0'),
        valid_from='2023-01-01',
        valid_to='9999-12-31',
    )
    ### CO2 Default HHV Default EF
    ExpectedValueRangeMethodologyField.objects.create(
        fuel_type=diesel,
        methodology=default_hhv,
        reporting_field=co2_default_hhv_default_ef_field,
        lower_bound=Decimal('30.0'),
        upper_bound=Decimal('150.0'),
        valid_from='2023-01-01',
        valid_to='9999-12-31',
    )
    ### CO2 Measured Steam Default EF
    ExpectedValueRangeMethodologyField.objects.create(
        fuel_type=diesel,
        methodology=measured_steam_default_ef,
        reporting_field=co2_measured_steam_default_ef_field,
        lower_bound=Decimal('1000.0'),
        upper_bound=Decimal('5000.0'),
        valid_from='2023-01-01',
        valid_to='9999-12-31',
    )
    ## CH4 g CH4/GJ
    ### CH4 Measured HHV Default EF
    ExpectedValueRangeMethodologyField.objects.create(
        fuel_type=diesel,
        methodology=measured_hhv,
        reporting_field=ch4_measured_hhv_default_ef_field,
        lower_bound=Decimal('1.5'),
        upper_bound=Decimal('7.0'),
        valid_from='2023-01-01',
        valid_to='9999-12-31',
    )
    ### CH4 Default HHV Default EF
    ExpectedValueRangeMethodologyField.objects.create(
        fuel_type=diesel,
        methodology=default_hhv,
        reporting_field=ch4_default_hhv_default_ef_field,
        lower_bound=Decimal('1.5'),
        upper_bound=Decimal('7.0'),
        valid_from='2023-01-01',
        valid_to='9999-12-31',
    )
    ### N2O Measured Steam Default EF
    ExpectedValueRangeMethodologyField.objects.create(
        fuel_type=diesel,
        methodology=measured_steam_default_ef,
        reporting_field=ch4_measured_steam_default_ef_field,
        lower_bound=Decimal('1.5'),
        upper_bound=Decimal('7.0'),
        valid_from='2023-01-01',
        valid_to='9999-12-31',
    )
    ### CH4 Heat Input Default EF
    ExpectedValueRangeMethodologyField.objects.create(
        fuel_type=diesel,
        methodology=heat_input_default_ef,
        reporting_field=ch4_heat_input_default_ef_field,
        lower_bound=Decimal('1.5'),
        upper_bound=Decimal('7.0'),
        valid_from='2023-01-01',
        valid_to='9999-12-31',
    )
    ## N2O g N2O/GJ
    ### N2O Measured HHV Default EF
    ExpectedValueRangeMethodologyField.objects.create(
        fuel_type=diesel,
        methodology=measured_hhv,
        reporting_field=n2o_measured_hhv_default_ef_field,
        lower_bound=Decimal('5.0'),
        upper_bound=Decimal('20.0'),
        valid_from='2023-01-01',
        valid_to='9999-12-31',
    )
    ### N2O Default HHV Default EF
    ExpectedValueRangeMethodologyField.objects.create(
        fuel_type=diesel,
        methodology=default_hhv,
        reporting_field=n2o_default_hhv_default_ef_field,
        lower_bound=Decimal('5.0'),
        upper_bound=Decimal('20.0'),
        valid_from='2023-01-01',
        valid_to='9999-12-31',
    )
    ### N2O Measured Steam Default EF
    ExpectedValueRangeMethodologyField.objects.create(
        fuel_type=diesel,
        methodology=measured_steam_default_ef,
        reporting_field=n2o_measured_steam_default_ef_field,
        lower_bound=Decimal('5.0'),
        upper_bound=Decimal('20.0'),
        valid_from='2023-01-01',
        valid_to='9999-12-31',
    )
    ### N2O Heat Input Default EF
    ExpectedValueRangeMethodologyField.objects.create(
        fuel_type=diesel,
        methodology=heat_input_default_ef,
        reporting_field=n2o_heat_input_default_ef_field,
        lower_bound=Decimal('5.0'),
        upper_bound=Decimal('20.0'),
        valid_from='2023-01-01',
        valid_to='9999-12-31',
    )

    # Propane bounds
    propane = FuelType.objects.get(name='Propane')
    ExpectedValueRangeFuelAmount.objects.create(
        fuel_type=propane,
        lower_bound=Decimal('0'),
        upper_bound=Decimal('1000.00'),
        valid_from='2023-01-01',
        valid_to='9999-12-31',
    )

    # Field Gas bounds
    field_gas = FuelType.objects.get(name='Field gas')
    ExpectedValueRangeFuelAmount.objects.create(
        fuel_type=field_gas,
        lower_bound=Decimal('0'),
        upper_bound=Decimal('5000.00'),
        valid_from='2023-01-01',
        valid_to='9999-12-31',
    )

    # Wood Waste bounds
    wood_waste = FuelType.objects.get(name='Wood Waste')
    ExpectedValueRangeFuelAmount.objects.create(
        fuel_type=wood_waste,
        lower_bound=Decimal('0'),
        upper_bound=Decimal('1000000.00'),
        valid_from='2023-01-01',
        valid_to='9999-12-31',
    )


def revert_validation_records(apps, schema_monitor):
    ExpectedValueRangeFuelAmount = apps.get_model('reporting', 'ExpectedValueRangeFuelAmount')
    ExpectedValueRangeMethodologyField = apps.get_model('reporting', 'ExpectedValueRangeMethodologyField')

    ExpectedValueRangeMethodologyField.objects.all().delete()
    ExpectedValueRangeFuelAmount.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0176_add_slug_to_reporting_field_and_populate'),
    ]

    operations = [
        migrations.RunPython(insert_validation_records, revert_validation_records),
    ]
