# Generated by Django 5.1.15 on 2026-04-09 21:34

from django.db import migrations
import os
import json
from typing import Optional


def update_activity_slug_name(apps, schema_editor, slug_name: str, updated_slug: str) -> Optional[object]:
    """
    Update an existing Activity record based on the slug_name.
    This is used in this migration to revert changes made to slug names in migration 0150.

    Args:
        slug_name: The slug of the Activity to update.
        updated_slug: The new slug for the Activity.

    Returns:
        The updated Activity instance if found, otherwise None.
    """
    Activity = apps.get_model('registration', 'Activity')

    try:
        activity = Activity.objects.get(slug=slug_name)
    except Activity.DoesNotExist:
        return None

    activity.slug = updated_slug
    activity.save()
    return activity


def update_reporting_field_data(apps, schema_editor, field_name: str, update_data: dict) -> Optional[object]:
    """
    Update an existing ReportingField record based on the field_name.

    Args:
        field_name: The name of the field to update.
        update_data: A dictionary of fields to update on the ReportingField instance.

    Returns:
        The updated ReportingField instance if found, otherwise None.

    Raises:
        ReportingField.MultipleObjectsReturned: If multiple records match the field_name.
    """
    ReportingField = apps.get_model('reporting', 'ReportingField')

    try:
        reporting_field = ReportingField.objects.get(field_name=field_name)
    except ReportingField.DoesNotExist:
        return None

    for field, value in update_data.items():
        setattr(reporting_field, field, value)

    reporting_field.save()
    return reporting_field


# forward migration
def update_reporting_fields(apps, schema_editor):
    # applicable to all gas types
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Fuel Default High Heating Value",
        update_data={
            "field_display_title": "Default High Heating Value",
            "field_units": "GJ/Sm3 or GJ/kilolitre or GJ/tonne",
        },
    )
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Fuel Annual Weighted Average High Heating Value",
        update_data={
            "field_display_title": "Annual Weighted Average High Heating Value",
            "field_units": "GJ/Sm3 or GJ/kilolitre or GJ/tonne",
        },
    )
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Unit-Fuel Annual Steam Generated",
        update_data={"field_units": "tonnes steam"},
    )
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Unit-Fuel Heat Input",
        update_data={"field_units": "GJ"},
    )
    # CO2-specific
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Unit-Fuel-CO2 Default EF",
        update_data={
            "field_display_title": "CO2 Default Emission Factor",
            "field_units": "kgCO2/Sm3 or kgCO2/kilolitre or kgCO2/tonne",
        },
    )
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Boiler Ratio",
        update_data={"field_units": "GJ/tonnes steam"},
    )
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Annual Weighted Average Carbon Content",
        update_data={"field_units": "kg C/Sm3 or kg C/kilolitre or kg C/tonne"},
    )
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Unit-Fuel-CO2 Measured Steam-Measured EF",
        update_data={"field_display_title": "CO2 Measured Emission Factor", "field_units": "kgCO2/tonne steam"},
    )
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Unit-Fuel-CO2 Default HHV-Default EF",
        update_data={"field_display_title": "CO2 Default Emission Factor", "field_units": "kgCO2/GJ"},
    )
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Unit-Fuel-CO2 Measured HHV-Default EF",
        update_data={"field_display_title": "CO2 Default Emission Factor", "field_units": "kgCO2/GJ"},
    )
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Unit-Fuel-CO2 Measured Steam-Default EF",
        update_data={"field_display_title": "CO2 Default Emission Factor", "field_units": "kgCO2/GJ"},
    )
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Fuel Annual Weighted Average Carbon Content (weight fraction)",
        update_data={
            "field_display_title": "Annual Weighted Average Carbon Content",
            "field_units": "kgC/Sm3 or kgC/kilolitre or kgC/tonne",
        },
    )
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Annual Weighted Average Carbon Content",
        update_data={"field_display_title": "Annual Weighted Average Carbon Content (kg C/kg fuel)"},
    )
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Annual Weighted Average Molecular Weight",
        update_data={"field_display_title": "Annual Weighted Average Molecular Weight (kg/kg-mole)"},
    )
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Molar Volume Conversion Factor",
        update_data={"field_display_title": "Molar Volume Conversion Factor (Sm3/kg-mole)"},
    )
    # CH4-specific
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Unit-Fuel-CH4 Default EF",
        update_data={
            "field_display_title": "CH4 Default Emission Factor",
            "field_units": "gCH4/Sm3 or gCH4/kilolitre or gCH4/tonne",
        },
    )
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Unit-Fuel-CH4 Default HHV-Default EF",
        update_data={"field_display_title": "CH4 Default Emission Factor", "field_units": "gCH4/GJ"},
    )
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Unit-Fuel-CH4 Heat Input-Default EF",
        update_data={"field_display_title": "CH4 Default Emission Factor", "field_units": "gCH4/GJ"},
    )
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Unit-Fuel-CH4 Measured EF",
        update_data={
            "field_display_title": "CH4 Measured Emission Factor",
            "field_units": "gCH4/Sm3 or gCH4/kilolitre or gCH4/tonne",
        },
    )
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Unit-Fuel-CH4 Measured HHV-Default EF",
        update_data={"field_display_title": "CH4 Default Emission Factor", "field_units": "gCH4/GJ"},
    )
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Unit-Fuel-CH4 Measured Steam-Default EF",
        update_data={"field_display_title": "CH4 Default Emission Factor", "field_units": "gCH4/GJ"},
    )
    # N2O-specific
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Unit-Fuel-N2O Default EF",
        update_data={
            "field_display_title": "N2O Default Emission Factor",
            "field_units": "gN2O/Sm3 or gN2O/kilolitre or gN2O/tonne",
        },
    )
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Unit-Fuel-N2O Measured EF",
        update_data={
            "field_display_title": "N2O Measured Emission Factor",
            "field_units": "gN2O/Sm3 or gN2O/kilolitre or gN2O/tonne",
        },
    )
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Unit-Fuel-N2O Default HHV-Default EF",
        update_data={"field_display_title": "N2O Default Emission Factor", "field_units": "gN2O/GJ"},
    )
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Unit-Fuel-N2O Heat Input-Default EF",
        update_data={"field_display_title": "N2O Default Emission Factor", "field_units": "gN2O/GJ"},
    )
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Unit-Fuel-N2O Measured HHV-Default EF",
        update_data={"field_display_title": "N2O Default Emission Factor", "field_units": "gN2O/GJ"},
    )
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Unit-Fuel-N2O Measured Steam-Default EF",
        update_data={"field_display_title": "N2O Default Emission Factor", "field_units": "gN2O/GJ"},
    )


def update_slugs(apps, schema_editor):
    slug_mapping = [
        ('fuel_combustion_by_mobile', 'fuel_combustion_mobile'),
        ('ind_wastewater_processing', 'industrial_water_processing'),
        ('storage_petro_products', 'storage_of_petroleum_products'),
        ('carbonate_use', 'carbonates_use'),
        ('gsc_non_compression', 'gsc_non_compression_non_combustion'),
        ('natural_gas_activities_other_than_non_compression', 'ng_other_than_non_compression'),
        ('natural_gas_activities_non_compression', 'ng_non_compression'),
        ('og_activities_other_than_non_compression', 'og_extraction_other_than_ncnp'),
        ('og_activities_non_compression', 'og_extraction_non_compression'),
    ]
    for current_slug, new_slug in slug_mapping:
        update_activity_slug_name(apps, schema_editor, current_slug, new_slug)


def reload_activity_schema_data(apps, schema_editor):
    ActivitySchema = apps.get_model('reporting', 'ActivityJsonSchema')
    Activity = apps.get_model('registration', 'Activity')
    Configuration = apps.get_model('reporting', 'Configuration')

    cwd = os.getcwd()

    ACTIVITY_SCHEMA_MAPPING = [
        'gsc_excluding_line_tracing',
        'gsc_solely_for_line_tracing',
        'gsc_other_than_non_compression',
        'refinery_fuel_gas',
        'carbonates_use',
        'gsc_non_compression_non_combustion',
        'hydrogen_production',
        'open_pit_coal_mining',
        'storage_of_petroleum_products',
        'aluminum_production',
        'ng_non_compression',
        'ng_other_than_non_compression',
        'lng_activities',
        'og_extraction_non_compression',
        'og_extraction_other_than_ncnp',
        'electricity_generation',
        'industrial_water_processing',
        'cement_production',
        'lime_manufacturing',
        'coal_storage',
        'zinc_production',
        'petroleum_refining',
        'lead_production',
        'electricity_transmission',
    ]

    for schema_slug in ACTIVITY_SCHEMA_MAPPING:
        schema_path = f'{cwd}/reporting/json_schemas/2024/{schema_slug}/activity.json'
        with open(schema_path) as schema_file:
            schema = json.load(schema_file)
            ActivitySchema.objects.filter(activity=Activity.objects.get(slug=schema_slug)).update(json_schema=schema)

    # also load the one json file in /2025 json_schemas
    schema_slug = 'pulp_and_paper'
    schema_path = f'{cwd}/reporting/json_schemas/2025/pulp_and_paper_production/activity.json'
    with open(schema_path) as schema_file:
        schema = json.load(schema_file)
        ActivitySchema.objects.filter(
            activity=Activity.objects.get(slug=schema_slug), valid_from=Configuration.objects.get(slug=2025)
        ).update(
            json_schema=schema,
        )


# reverse migration
def undo_update_reporting_fields(apps, schema_editor):
    # applicable to all gas types
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Fuel Default High Heating Value",
        update_data={"field_display_title": None, "field_units": None},
    )
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Fuel Annual Weighted Average High Heating Value",
        update_data={"field_display_title": None, "field_units": None},
    )
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Unit-Fuel Annual Steam Generated",
        update_data={"field_units": None},
    )
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Unit-Fuel Heat Input",
        update_data={"field_units": None},
    )
    # CO2-specific
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Unit-Fuel-CO2 Default EF",
        update_data={"field_display_title": "CO2 Default EF", "field_units": "kg/fuel units"},
    )
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Boiler Ratio",
        update_data={"field_units": None},
    )
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Annual Weighted Average Carbon Content",
        update_data={"field_units": None},
    )
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Unit-Fuel-CO2 Measured Steam-Measured EF",
        update_data={"field_display_title": "CO2 Measured Steam-Measured EF", "field_units": "kg/fuel units"},
    )
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Unit-Fuel-CO2 Default HHV-Default EF",
        update_data={"field_display_title": "CO2 Default HHV/Default EF", "field_units": "kg/GJ"},
    )
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Unit-Fuel-CO2 Measured HHV-Default EF",
        update_data={"field_display_title": "CO2 Measured HHV-Default EF", "field_units": "kg/GJ"},
    )
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Unit-Fuel-CO2 Measured Steam-Default EF",
        update_data={"field_display_title": "CO2 Measured Steam-Default EF", "field_units": "kg/GJ"},
    )
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Fuel Annual Weighted Average Carbon Content (weight fraction)",
        update_data={"field_display_title": None, "field_units": "kg carbon/fuel unit"},
    )
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Annual Weighted Average Carbon Content",
        update_data={"field_display_title": None, "field_units": None},
    )
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Annual Weighted Average Molecular Weight",
        update_data={"field_display_title": None, "field_units": None},
    )
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Molar Volume Conversion Factor",
        update_data={"field_display_title": None, "field_units": None},
    )
    # CH4-specific
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Unit-Fuel-CH4 Default EF",
        update_data={"field_display_title": "CH4 Default EF", "field_units": "g/fuel units"},
    )
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Unit-Fuel-CH4 Default HHV-Default EF",
        update_data={"field_display_title": "CH4 Default HHV-Default EF", "field_units": "g/GJ"},
    )
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Unit-Fuel-CH4 Heat Input-Default EF",
        update_data={"field_display_title": "CH4 Heat Input-Default EF", "field_units": "g/GJ"},
    )
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Unit-Fuel-CH4 Measured EF",
        update_data={"field_display_title": "CH4 Measured EF", "field_units": "g/fuel units"},
    )
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Unit-Fuel-CH4 Measured HHV-Default EF",
        update_data={"field_display_title": "CH4 Measured HHV-Default EF", "field_units": "g/GJ"},
    )
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Unit-Fuel-CH4 Measured Steam-Default EF",
        update_data={"field_display_title": "CH4 Measured Steam-Default EF", "field_units": "g/GJ"},
    )
    # N2O-specific
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Unit-Fuel-N2O Default EF",
        update_data={"field_display_title": "N2O Default EF", "field_units": None},
    )
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Unit-Fuel-N2O Measured EF",
        update_data={"field_display_title": "N2O Measured EF", "field_units": "g/fuel units"},
    )
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Unit-Fuel-N2O Default HHV-Default EF",
        update_data={"field_display_title": "N2O Default HHV-Default EF", "field_units": "g/GJ"},
    )
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Unit-Fuel-N2O Heat Input-Default EF",
        update_data={"field_display_title": "N2O Heat Input-Default EF", "field_units": "g/GJ"},
    )
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Unit-Fuel-N2O Measured HHV-Default EF",
        update_data={"field_display_title": "N2O Measured HHV-Default EF", "field_units": "g/GJ"},
    )
    update_reporting_field_data(
        apps,
        schema_editor,
        field_name="Unit-Fuel-N2O Measured Steam-Default EF",
        update_data={"field_display_title": "N2O Measured Steam-Default EF", "field_units": "g/GJ"},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0178_fueltype_description'),
    ]

    operations = [
        migrations.RunPython(code=update_slugs, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(code=update_reporting_fields, reverse_code=undo_update_reporting_fields),
        migrations.RunPython(
            code=reload_activity_schema_data, reverse_code=migrations.operations.special.RunPython.noop
        ),
    ]
