# Generated by Django 5.1.15 on 2026-04-15 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0178_fueltype_description'),
    ]

    operations = []
