# Generated by Django 5.1.15 on 2026-04-29 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0183_V5_9_0'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportingyear',
            options={'ordering': ['reporting_year']},
        ),
    ]
