# Generated by Django 5.1.15 on 2026-05-07 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0185_configuration_immutable_slug_and_more'),
    ]

    operations = []
