# Generated by Django 5.1.15 on 2026-04-30 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0171_add_units_to_lng_product'),
        ('reporting', '0185_configuration_immutable_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportpersonresponsible',
            name='contact',
            field=models.ForeignKey(
                blank=True,
                db_comment='The source contact selected for this person responsible.',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='report_person_responsibles',
                to='registration.contact',
            ),
        ),
    ]
