# Generated by Django 5.1.15 on 2026-05-13 20:34

import django.db.models.deletion
from django.db import migrations, models


def populate_naics_code(apps, schema_editor):
    import common.lib.pgtrigger as pgtrigger

    ReportOperation = apps.get_model("reporting", "ReportOperation")
    for report_op in ReportOperation.objects.select_related("report_version__report__operation").all():
        operation = report_op.report_version.report.operation
        if operation.naics_code_id:
            with pgtrigger.ignore('reporting.ReportOperation:immutable_report_version'):
                report_op.naics_code_id = operation.naics_code_id
                report_op.save(update_fields=["naics_code_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0188_V5_11_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportoperation',
            name='naics_code',
            field=models.ForeignKey(
                blank=True,
                db_comment='The NAICS code of the operation at the time the report was created.',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='registration.naicscode',
            ),
        ),
        migrations.RunPython(populate_naics_code, migrations.RunPython.noop),
    ]
