# Generated by Django 5.1.15 on 2026-06-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0191_add_report_version_to_report_models_missing_it'),
    ]

    operations = []
