# Generated by Django 5.1.15 on 2026-05-26 20:56

from django.db import migrations
from reporting.migrations._helpers import load_activity_schemas_from_json, load_source_type_schemas_from_json


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0191_add_report_version_to_report_models_missing_it'),
    ]

    operations = [
        migrations.RunPython(load_activity_schemas_from_json, migrations.RunPython.noop, elidable=True),
        migrations.RunPython(load_source_type_schemas_from_json, migrations.RunPython.noop, elidable=True),
    ]
