# Generated by Django 5.1.15 on 2026-06-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0192_V5_12_0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportattachment',
            name='attachment',
            field=models.FileField(
                db_comment='A file uploaded as an attachment to a report',
                max_length=1000,
                upload_to='report_attachments/%Y/',
            ),
        ),
    ]
