# Generated by Django 5.1.15 on 2026-06-08 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0194_reload_json_schemas_updated_required_fields'),
    ]

    operations = []
