# Generated by Django 5.1.15 on 2026-06-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0196_V5_13_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportattachment',
            name='status',
            field=models.CharField(
                choices=[('Unscanned', 'Unscanned'), ('Clean', 'Clean'), ('Quarantined', 'Quarantined')],
                db_comment='The virus/malware scan status of the uploaded file. Set by the scanning service (Unscanned before scan, Clean if safe, Quarantined if malware detected)',
                default='Unscanned',
                max_length=100,
            ),
        ),
    ]
