# Generated by Django 5.1.15 on 2026-06-12 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0184_update_registration_metadata'),
        ('reporting', '0198_V5_14_0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityreport',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='facilityreport',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='facilityreport',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='facilityreport',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='facilityreport',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='facilityreport',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='report',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='report',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='report',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportactivity',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='reportactivity',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportactivity',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportactivity',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportactivity',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportactivity',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportadditionaldata',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='reportadditionaldata',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportadditionaldata',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportadditionaldata',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportadditionaldata',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportadditionaldata',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportattachment',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='reportattachment',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportattachment',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportattachment',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportattachment',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportattachment',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportattachmentconfirmation',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='reportattachmentconfirmation',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportattachmentconfirmation',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportattachmentconfirmation',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportattachmentconfirmation',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportattachmentconfirmation',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportcompliancesummary',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='reportcompliancesummary',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportcompliancesummary',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportcompliancesummary',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportcompliancesummary',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportcompliancesummary',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportcompliancesummaryproduct',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='reportcompliancesummaryproduct',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportcompliancesummaryproduct',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportcompliancesummaryproduct',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportcompliancesummaryproduct',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportcompliancesummaryproduct',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportelectricityimportdata',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='reportelectricityimportdata',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportelectricityimportdata',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportelectricityimportdata',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportelectricityimportdata',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportelectricityimportdata',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportemission',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='reportemission',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportemission',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportemission',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportemission',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportemission',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportemissionallocation',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='reportemissionallocation',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportemissionallocation',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportemissionallocation',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportemissionallocation',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportemissionallocation',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportfuel',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='reportfuel',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportfuel',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportfuel',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportfuel',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportfuel',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportmethodology',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='reportmethodology',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportmethodology',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportmethodology',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportmethodology',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportmethodology',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportnewentrant',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='reportnewentrant',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportnewentrant',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportnewentrant',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportnewentrant',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportnewentrant',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportnewentrantemission',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='reportnewentrantemission',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportnewentrantemission',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportnewentrantemission',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportnewentrantemission',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportnewentrantemission',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportnewentrantproduction',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='reportnewentrantproduction',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportnewentrantproduction',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportnewentrantproduction',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportnewentrantproduction',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportnewentrantproduction',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportnonattributableemissions',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='reportnonattributableemissions',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportnonattributableemissions',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportnonattributableemissions',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportnonattributableemissions',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportnonattributableemissions',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportoperation',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='reportoperation',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportoperation',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportoperation',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportoperation',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportoperation',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportoperationrepresentative',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='reportoperationrepresentative',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportoperationrepresentative',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportoperationrepresentative',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportoperationrepresentative',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportoperationrepresentative',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportpersonresponsible',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='reportpersonresponsible',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportpersonresponsible',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportpersonresponsible',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportpersonresponsible',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportpersonresponsible',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportproduct',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='reportproduct',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportproduct',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportproduct',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportproduct',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportproduct',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportproductemissionallocation',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='reportproductemissionallocation',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportproductemissionallocation',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportproductemissionallocation',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportproductemissionallocation',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportproductemissionallocation',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportrawactivitydata',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='reportrawactivitydata',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportrawactivitydata',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportrawactivitydata',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportrawactivitydata',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportrawactivitydata',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportsignoff',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='reportsignoff',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportsignoff',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportsignoff',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportsignoff',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportsignoff',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportsourcetype',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='reportsourcetype',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportsourcetype',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportsourcetype',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportsourcetype',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportsourcetype',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportunit',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='reportunit',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportunit',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportunit',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportunit',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportunit',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportverification',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='reportverification',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportverification',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportverification',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportverification',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportverification',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportverificationvisit',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='reportverificationvisit',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportverificationvisit',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportverificationvisit',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportverificationvisit',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportverificationvisit',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportversion',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='reportversion',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportversion',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportversion',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='reportversion',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='reportversion',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
    ]
