# Generated by Django 5.1.15 on 2026-06-22 18:44

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0184_update_registration_metadata'),
        ('reporting', '0199_alter_facilityreport_archived_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCommentHeadHonchoOfTheCongaLineBoii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(
                        blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
                    ),
                ),
                (
                    'archived_at',
                    models.DateTimeField(
                        blank=True,
                        db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                        null=True,
                    ),
                ),
                (
                    'page_slug',
                    models.TextField(
                        blank=True,
                        db_comment='The slug of the page this comment is associated with. This is used to display the comment on the correct page in the UI.',
                        null=True,
                    ),
                ),
                (
                    'is_resolved',
                    models.BooleanField(
                        db_comment='Whether this comment has been resolved. A comment is considered resolved when the issue it raises has been addressed and no further action is needed.',
                        default=False,
                    ),
                ),
                (
                    'is_visible_to_industry',
                    models.BooleanField(
                        db_comment='Whether this comment is visible to industry users. This allows for comments to be saved by government users that are not yet ready to be shared with industry.',
                        default=False,
                    ),
                ),
                (
                    'archived_by',
                    models.ForeignKey(
                        blank=True,
                        db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_archived',
                        to='registration.user',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        db_comment='ID of the user who created the record. Foreign key to erc.user',
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_created',
                        to='registration.user',
                    ),
                ),
                (
                    'facility',
                    models.ForeignKey(
                        blank=True,
                        db_comment='The facility this comment is associated with, if applicable. Foreign key to registration.facility',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='report_comments_head_of_the_conga_line',
                        to='registration.facility',
                    ),
                ),
                (
                    'report_version',
                    models.ForeignKey(
                        db_comment='The report version this comment belongs to. Foreign key to erc.report_version',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='report_comments_head_of_the_conga_line',
                        to='reporting.reportversion',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_updated',
                        to='registration.user',
                    ),
                ),
            ],
            options={
                'db_table': 'erc"."report_comment_headhonchoofthecongalineboii',
                'db_table_comment': 'Table containing comments from the head of the conga line about a report version',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportCommentBodyOfTheSnake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(
                        blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
                    ),
                ),
                (
                    'archived_at',
                    models.DateTimeField(
                        blank=True,
                        db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                        null=True,
                    ),
                ),
                ('comment', models.TextField(db_comment='The comment about a report')),
                (
                    'archived_by',
                    models.ForeignKey(
                        blank=True,
                        db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_archived',
                        to='registration.user',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        db_comment='ID of the user who created the record. Foreign key to erc.user',
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_created',
                        to='registration.user',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_updated',
                        to='registration.user',
                    ),
                ),
                (
                    'report_comment_headhonchoofthecongalineboii',
                    models.ForeignKey(
                        db_comment='The head of the conga line comment this body comment belongs to. Foreign key to erc.report_comment_headofthecongaline',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='report_comments_bodyofthesnake',
                        to='reporting.reportcommentheadhonchoofthecongalineboii',
                    ),
                ),
            ],
            options={
                'db_table': 'erc"."report_comment_bodyofthesnake',
                'db_table_comment': 'Table containing comments about a report, which are associated with a head of the conga line',
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='reportcommentheadhonchoofthecongalineboii',
            trigger=pgtrigger.compiler.Trigger(
                name='set_created_audit_columns',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="new.created_by_id = (select nullif(current_setting('my.guid', true), '')); new.created_at = now(); return new;",
                    hash='df0e0dd1a8ade5aa97898908a0b5ac7d7f8b62e0',
                    operation='INSERT',
                    pgid='pgtrigger_set_created_audit_columns_9dcad',
                    table='erc"."report_comment_headhonchoofthecongalineboii',
                    when='BEFORE',
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='reportcommentheadhonchoofthecongalineboii',
            trigger=pgtrigger.compiler.Trigger(
                name='set_updated_audit_columns',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="new.updated_by_id = (select nullif(current_setting('my.guid', true), '')); new.updated_at = now(); return new;",
                    hash='ba1cd95572105aecb2c0d4baf14b55d4ccf46da4',
                    operation='UPDATE',
                    pgid='pgtrigger_set_updated_audit_columns_1fb8f',
                    table='erc"."report_comment_headhonchoofthecongalineboii',
                    when='BEFORE',
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='reportcommentbodyofthesnake',
            trigger=pgtrigger.compiler.Trigger(
                name='set_created_audit_columns',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="new.created_by_id = (select nullif(current_setting('my.guid', true), '')); new.created_at = now(); return new;",
                    hash='5613368bd2ecf05e7abc6cd7c336df8235dcee13',
                    operation='INSERT',
                    pgid='pgtrigger_set_created_audit_columns_b2491',
                    table='erc"."report_comment_bodyofthesnake',
                    when='BEFORE',
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='reportcommentbodyofthesnake',
            trigger=pgtrigger.compiler.Trigger(
                name='set_updated_audit_columns',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="new.updated_by_id = (select nullif(current_setting('my.guid', true), '')); new.updated_at = now(); return new;",
                    hash='0336c3476a2777204fd4a93f116990774587f11f',
                    operation='UPDATE',
                    pgid='pgtrigger_set_updated_audit_columns_7d5a3',
                    table='erc"."report_comment_bodyofthesnake',
                    when='BEFORE',
                ),
            ),
        ),
    ]
