# Generated by Django 6.0.8 on 2026-08-25 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0209_V5_19_1'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reportverificationvisit',
            name='other_facility_must_have_coordinates',
        ),
        migrations.DeleteModel(
            name='ReportVerificationVisit',
        ),
    ]
