# Generated by Django 6.0.8 on 2026-09-08 18:15

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0195_V5_20_1'),
        ('reporting', '0213_V5_21_0'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(
                        blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
                    ),
                ),
                (
                    'archived_at',
                    models.DateTimeField(
                        blank=True,
                        db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                        null=True,
                    ),
                ),
                (
                    'archived_by',
                    models.ForeignKey(
                        blank=True,
                        db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_archived',
                        to='registration.user',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        db_comment='ID of the user who created the record. Foreign key to erc.user',
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_created',
                        to='registration.user',
                    ),
                ),
                (
                    'facility',
                    models.ForeignKey(
                        blank=True,
                        db_comment='The facility this thread is optionally associated with. Foreign key to registration.facility',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='comment_threads',
                        to='registration.facility',
                    ),
                ),
                (
                    'report',
                    models.ForeignKey(
                        db_comment='The report this thread belongs to. Foreign key to erc.report',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='comment_threads',
                        to='reporting.report',
                    ),
                ),
                (
                    'report_version',
                    models.ForeignKey(
                        blank=True,
                        db_comment='The report version this thread was started at. Foreign key to erc.report_version',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='comment_threads',
                        to='reporting.reportversion',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_updated',
                        to='registration.user',
                    ),
                ),
            ],
            options={
                'db_table': 'erc"."comment_thread',
                'db_table_comment': 'Table containing comment threads about a report',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(
                        blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
                    ),
                ),
                (
                    'archived_at',
                    models.DateTimeField(
                        blank=True,
                        db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                        null=True,
                    ),
                ),
                ('comment', models.TextField(db_comment='The comment about a report')),
                (
                    'archived_by',
                    models.ForeignKey(
                        blank=True,
                        db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_archived',
                        to='registration.user',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        db_comment='ID of the user who created the record. Foreign key to erc.user',
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_created',
                        to='registration.user',
                    ),
                ),
                (
                    'report_version',
                    models.ForeignKey(
                        blank=True,
                        db_comment='The report version this comment is related to. Foreign key to erc.report_version',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='comments',
                        to='reporting.reportversion',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_updated',
                        to='registration.user',
                    ),
                ),
                (
                    'comment_thread',
                    models.ForeignKey(
                        db_comment='The thread this comment belongs to. Foreign key to erc.comment_thread',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='comments',
                        to='reporting.commentthread',
                    ),
                ),
            ],
            options={
                'db_table': 'erc"."comment',
                'db_table_comment': 'Table containing comments about a report, which are associated with a thread',
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='commentthread',
            trigger=pgtrigger.compiler.Trigger(
                name='set_created_audit_columns',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="new.created_by_id = (select nullif(current_setting('my.guid', true), '')); new.created_at = now(); return new;",
                    hash='bd86fc9debdb05c4d80b2aaf80deb6df534f1c64',
                    operation='INSERT',
                    pgid='pgtrigger_set_created_audit_columns_51e42',
                    table='erc"."comment_thread',
                    when='BEFORE',
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='commentthread',
            trigger=pgtrigger.compiler.Trigger(
                name='set_updated_audit_columns',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="new.updated_by_id = (select nullif(current_setting('my.guid', true), '')); new.updated_at = now(); return new;",
                    hash='7670de4c99dee850ee8196310ebc528be9f007d0',
                    operation='UPDATE',
                    pgid='pgtrigger_set_updated_audit_columns_38cad',
                    table='erc"."comment_thread',
                    when='BEFORE',
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='comment',
            trigger=pgtrigger.compiler.Trigger(
                name='set_created_audit_columns',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="new.created_by_id = (select nullif(current_setting('my.guid', true), '')); new.created_at = now(); return new;",
                    hash='dd9d0855da20bf09d3ee59f5ba3cd9984997c10c',
                    operation='INSERT',
                    pgid='pgtrigger_set_created_audit_columns_beee5',
                    table='erc"."comment',
                    when='BEFORE',
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='comment',
            trigger=pgtrigger.compiler.Trigger(
                name='set_updated_audit_columns',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="new.updated_by_id = (select nullif(current_setting('my.guid', true), '')); new.updated_at = now(); return new;",
                    hash='2a730dc2fdb1751a8d1ea4500c55e8826dd1de8f',
                    operation='UPDATE',
                    pgid='pgtrigger_set_updated_audit_columns_822d1',
                    table='erc"."comment',
                    when='BEFORE',
                ),
            ),
        ),
    ]
