# Generated by Django 6.1.1 on 2026-09-22 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('registration', '0196_V5_21_0'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'entity_type',
                    models.CharField(
                        db_comment="The type of entity this audit log entry is about, e.g. 'operation' or 'report_version'. Matches a key in the audit_log app's AUDITED_VIEWS registry.",
                        max_length=100,
                    ),
                ),
                (
                    'entity_id',
                    models.CharField(
                        db_comment='The primary key of the audited entity, stringified since PKs vary between UUID and int across models.',
                        max_length=100,
                    ),
                ),
                (
                    'action',
                    models.CharField(
                        choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')],
                        db_comment='Whether the change that produced this entry was a create, update, or delete of the source record.',
                        max_length=10,
                    ),
                ),
                (
                    'actor_guid',
                    models.UUIDField(
                        blank=True,
                        db_comment="A redundant copy of the acting user's GUID, captured at write time in case the corresponding User row is later removed.",
                        null=True,
                    ),
                ),
                (
                    'timestamp',
                    models.DateTimeField(
                        db_comment='The date and time at which the change that produced this entry occurred.'
                    ),
                ),
                (
                    'snapshot',
                    models.JSONField(
                        db_comment="A point-in-time snapshot of all watched fields for the entity, keyed by field name: {field_key: {'label': ..., 'value': <resolved display string>}}."
                    ),
                ),
                (
                    'changed_fields',
                    models.JSONField(
                        db_comment='The list of watched field keys that changed as part of this event. Empty for delete events.',
                        default=list,
                    ),
                ),
                (
                    'reason',
                    models.TextField(
                        blank=True,
                        db_comment="A human-readable explanation of why the change was made, sourced from the triggering historical record's history_change_reason, when present.",
                        null=True,
                    ),
                ),
                (
                    'history_record_id',
                    models.CharField(
                        db_comment='The primary key of the source historical record this entry was derived from, stringified since historical record PKs can be int or UUID depending on the model.',
                        max_length=100,
                    ),
                ),
                (
                    'actor',
                    models.ForeignKey(
                        blank=True,
                        db_comment='The user who made the change, if known. Foreign key to erc.user. Null if the user record has since been removed or the change was system-driven.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='audit_logs',
                        to='registration.user',
                    ),
                ),
                (
                    'history_record_content_type',
                    models.ForeignKey(
                        db_comment='The content type of the source Historical<Model> record this entry was derived from, for traceability.',
                        on_delete=django.db.models.deletion.PROTECT,
                        to='contenttypes.contenttype',
                    ),
                ),
            ],
            options={
                'db_table': 'common"."audit_log',
                'db_table_comment': 'An append-only audit trail of changes to audited entities, derived from django-simple-history historical records.',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='audit_log_entity_idx')],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('history_record_content_type', 'history_record_id'),
                        name='unique_audit_log_per_history_record',
                        violation_error_message='An audit log entry already exists for this historical record.',
                    )
                ],
            },
        ),
    ]
