apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cas-bciers.fullname" . }}-registration-frontend
  labels:
    component: registration-frontend
    layer: frontend
{{- include "cas-bciers.labels" . | nindent 4 }}
spec:
{{- if not .Values.registrationFrontend.autoscaling.enabled }}
  replicas: {{ .Values.registrationFrontend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cas-bciers.selectorLabels" . | nindent 6 }}
      component: registration-frontend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
{{- include "cas-bciers.selectorLabels" . | nindent 8 }}
        component: registration-frontend
        layer: frontend
    spec:
      containers:
        - name: {{ template "cas-bciers.fullname" . }}-registration-frontend
          envFrom:
            - configMapRef:
                name: {{ template "cas-bciers.fullname" . }}-frontend-env-configmap
          image: "{{ .Values.registrationFrontend.image.repository }}:{{ .Values.defaultImageTag | default .Values.registrationFrontend.image.tag }}"
          imagePullPolicy: {{ .Values.registrationFrontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.registrationFrontend.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.registrationFrontend.resources | nindent 12 }}
      restartPolicy: Always
