apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cas-bciers.fullname" . }}-registration-frontend
  labels:
    component: registration-frontend
    layer: frontend
{{- include "cas-bciers.labels" . | nindent 4 }}
spec:
{{- if not .Values.registrationFrontend.autoscaling.enabled }}
  replicas: {{ .Values.registrationFrontend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cas-bciers.selectorLabels" . | nindent 6 }}
      component: registration-frontend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
{{- include "cas-bciers.selectorLabels" . | nindent 8 }}
        component: registration-frontend
        layer: frontend
    spec:
      serviceAccountName: {{ .Release.Name }}-pod-logger
      containers:
        - name: {{ template "cas-bciers.fullname" . }}-registration-frontend
          env:
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-gold-client-secret
                  key: kcClientSecret
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: cas-bciers-nextauth
                  key: nextauth-secret
          envFrom:
            - configMapRef:
                name: {{ template "cas-bciers.fullname" . }}-frontend-env-configmap
          image: "{{ .Values.registrationFrontend.image.repository }}:{{ .Values.defaultImageTag | default .Values.registrationFrontend.image.tag }}"
          imagePullPolicy: {{ .Values.registrationFrontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.registrationFrontend.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.registrationFrontend.resources | nindent 12 }}
          {{- $containerName := printf "%s-registration-frontend" (include "cas-bciers.fullname" .) }}
        {{- include "cas-logging-sidecar.containers" (dict
            "containerToSidecar" $containerName
            "logName" "cas-bciers-dev-logs"
            "host" (index .Values "cas-logging-sidecar" "host")  ) | nindent 8 }}
      restartPolicy: Always
      volumes:
        {{- include "cas-logging-sidecar.volumes" . | nindent 8 }}
