apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "cas-bciers.fullname" . }}-registration-frontend-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: cas-bciers
      component: registration-frontend
