apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cas-bciers.fullname" . }}-coam-frontend
  labels:
    component: coam-frontend
    layer: frontend
{{- include "cas-bciers.labels" . | nindent 4 }}
spec:
{{- if not .Values.coamFrontend.autoscaling.enabled }}
  replicas: {{ .Values.coamFrontend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cas-bciers.selectorLabels" . | nindent 6 }}
      component: coam-frontend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
{{- include "cas-bciers.selectorLabels" . | nindent 8 }}
        component: coam-frontend
        layer: frontend
    spec:
      containers:
        - name: {{ template "cas-bciers.fullname" . }}-coam-frontend
          envFrom:
            - configMapRef:
                name: {{ template "cas-bciers.fullname" . }}-frontend-env-configmap
          env:
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-gold-client-secret
                  key: kcClientSecret
            - name: NEXTAUTH_SECRET
              valueFrom:
                  secretKeyRef:
                    name: cas-bciers-nextauth
                    key: nextauth-secret
          image: "{{ .Values.coamFrontend.image.repository }}:{{ .Values.defaultImageTag | default .Values.coamFrontend.image.tag }}"
          imagePullPolicy: {{ .Values.coamFrontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.coamFrontend.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.coamFrontend.resources | nindent 12 }}
      restartPolicy: Always
