apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "cas-bciers.fullname" . }}-coam-frontend
  labels:
{{ include "cas-bciers.labels" . | indent 4 }}
  annotations:
    haproxy.router.openshift.io/balance: roundrobin
    haproxy.router.openshift.io/rewrite-target: {{ .Values.coamFrontend.route.path }}

spec:
  host: {{ .Values.coamFrontend.route.host }}
  path: {{ .Values.coamFrontend.route.path }}
  port:
    targetPort: {{ template "cas-bciers.fullname" . }}-coam-frontend
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ template "cas-bciers.fullname" . }}-coam-frontend
    weight: 100
