apiVersion: v1
kind: Service
metadata:
  name: {{ include "cas-bciers.fullname" . }}-coam-frontend
  labels:
    layer: frontend
    {{- include "cas-bciers.labels" . | nindent 4 }}
spec:
  type: {{ .Values.coamFrontend.service.type }}
  ports:
    - port: {{ .Values.coamFrontend.service.port }}
      targetPort: 3000
      protocol: TCP
      name: {{ include "cas-bciers.fullname" . }}-coam-frontend
  selector:
    {{- include "cas-bciers.selectorLabels" . | nindent 4 }}
    component: coam-frontend
