name: "Local Registration app run"
description: "Runs the Registration app locally"
runs:
  using: composite
  steps:
    - name: start backend
      shell: bash
      run: docker run -d --network=host -e "DB_USER=bc_obps" -e "DB_NAME=registration" -e "DB_PORT=5432" -e "DB_HOST=localhost" ghcr.io/bcgov/cas-reg-backend:${{ github.sha }}
    - name: start frontend
      shell: bash
      run: docker run -d --network=host ghcr.io/bcgov/cas-reg-frontend:${{ github.sha }} "/usr/bin/env" "bash" "-c" "yarn start"
