name: "Local Registration app run"
description: "Runs the Registration app locally"

inputs:
  django_secret_key:
    description: "Django secret key"
    required: true

runs:
  using: composite
  steps:
    - name: start backend
      shell: bash
      run: docker run -d --network=host -e "DB_USER=postgres" -e "DB_NAME=registration" -e "DB_PORT=5432" -e "DB_HOST=localhost" -e "DJANGO_SECRET_KEY=${{ inputs.django_secret_key }}" -e "ALLOWED_HOSTS=localhost,0.0.0.0,127.0.0.1" -e "ENVIRONMENT=develop" ghcr.io/bcgov/cas-reg-backend:${{ github.sha }}
    - name: start frontend
      shell: bash
      run: docker run -d --network=host -e "DB_USER=postgres" -e "DB_NAME=registration" -e "DB_PORT=5432" -e "DB_HOST=localhost" -e "API_URL=http://127.0.0.1:8000/api/" ghcr.io/bcgov/cas-reg-frontend:${{ github.sha }}
