name: "Local Registration app run"
description: "Runs the Registration app locally"

inputs:
  django_secret_key:
    description: "Django secret key"
    required: true
  ches_client_id:
    description: "Identifier for CHES dev client"
    required: true
  ches_client_secret:
    description: "CHES dev client secret"
    required: true
  ches_auth_endpoint:
    description: "Endpoint for fetching auth token to access CHES client"
    required: true
  ches_api_url:
    description: "URL for CHES dev API"
    required: true
  keycloak_client_id:
    description: "Identifier for keycloak dev client"
    required: true
  keycloak_client_secret:
    description: "Keycloak client secret"
    required: true
  nextauth_secret:
    description: "NextAuth client secret"
    required: true

runs:
  using: composite
  steps:
    - name: start backend
      shell: bash
      run: docker run -d --network=host -e "DB_USER=postgres" -e "DB_NAME=registration" -e "DB_PORT=5432" -e "DB_HOST=localhost" -e "DJANGO_SECRET_KEY=${{ inputs.django_secret_key }}" -e "CLIENT_ID=${{ inputs.ches_client_id }}" -e "CLIENT_SECRET=${{ inputs.ches_client_secret }}" -e "TOKEN_ENDPOINT=${{ inputs.ches_auth_endpoint }}" -e "CHES_API_URL=${{ inputs.ches_api_url }}" -e "ALLOWED_HOSTS=localhost,0.0.0.0,127.0.0.1" -e "ENVIRONMENT=develop" ghcr.io/bcgov/cas-reg-backend:${{ github.sha }}
    - name: start frontend
      shell: bash
      run: docker run -d --network=host -e "NEXTAUTH_URL_INTERNAL=http://localhost:3000/" -e "NEXTAUTH_URL=http://localhost:3000/" -e "NEXTAUTH_SECRET=${{ inputs.nextauth_secret }}" -e "API_URL=http://127.0.0.1:8000/api/" -e "KEYCLOAK_LOGIN_URL=https://dev.loginproxy.gov.bc.ca/auth/realms/standard" -e "KEYCLOAK_CLIENT_SECRET=${{ inputs.keycloak_client_secret }}" -e "KEYCLOAK_CLIENT_ID=${{ inputs.keycloak_client_id }}" ghcr.io/bcgov/cas-reg-frontend:${{ github.sha }}
