{{- if (hasSuffix "-dev" .Release.Namespace)}}

apiVersion: batch/v1
kind: Job
metadata:
  labels: {{- include "cas-bciers.labels" . | nindent 4 }}
    component: backend
  name: {{ template "cas-bciers.fullname" . }}-add-django-admin
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-upgrade, post-install
spec:
  template:
    metadata:
      name: {{ template "cas-bciers.fullname" . }}-add-django-admin
    spec:
      activeDeadlineSeconds: 300
      containers:
        - name: {{ template "cas-bciers.fullname" . }}-add-django-admin
          image: curlimages/curl
          env:
            - name: BACKEND_HOST
              value: {{ .Values.backend.route.host }}
            - name: DJANGO_SUPERUSER_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: django-superuser
            - name: DJANGO_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: django-superuser
          command:
            - /bin/sh
            - -ec
            - "curl --fail-with-body https://$(BACKEND_HOST)/api/common/create-superuser"
      restartPolicy: Never
{{ end }}
