apiVersion: batch/v1
kind: Job
metadata:
  name: terraform-apply
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 900
  parallelism: 1
  completions: 1
  template:
    spec:
      serviceAccountName: "terraform-kubernetes-service-account"
      containers:
        - name: terraform-apply
          resources:
            limits:
              cpu: 1000m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
          image: joshbutton/cas-reg-devops:0.0.1
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /etc/gcp
              name: service-account-credentials-volume
              readOnly: True
            - mountPath: /etc/tf
              name: terraform-backend-config-volume
              readOnly: True
            - name: tf-working-dir
              mountPath: /working
              readOnly: False
            - name: tf-cache
              mountPath: /.terraform
              readOnly: False
          env:
            - name: TF_VAR_project
              valueFrom:
                secretKeyRef:
                  name: gcp-credentials-secret
                  key: gcp_project_id
            - name: TF_VAR_openshift_nameplate
              valueFrom:
                secretKeyRef:
                  name: gcp-credentials-secret
                  key: openshift_nameplate
            - name: TF_VAR_openshift_environment
              valueFrom:
                secretKeyRef:
                  name: gcp-credentials-secret
                  key: openshift_environment
            - name: TF_VAR_kubernetes_host
              value: "https://api.silver.devops.gov.bc.ca:6443"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/etc/gcp/credentials.json"
          command:
            [
              "/bin/sh",
              "-c",
              "export TF_VAR_kubernetes_token='$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)' && terraform init -backend-config=/etc/tf/gcs.tfbackend && terraform plan -lock=false",
            ]
      restartPolicy: Never
      volumes:
        - name: service-account-credentials-volume
          secret:
            secretName: gcp-credentials-secret
            items:
              - key: sa_json
                path: credentials.json
        - name: terraform-backend-config-volume
          secret:
            secretName: gcp-credentials-secret
            items:
              - key: tf_backend
                path: gcs.tfbackend
        - name: tf-working-dir
          emptyDir: {}
        - name: tf-cache
          emptyDir: {}
