# Generated by Django 5.0.11 on 2025-02-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_complianceobligation_penalty_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complianceobligation',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='historicalcomplianceobligation',
            name='amount',
        ),
        migrations.AddField(
            model_name='complianceobligation',
            name='emissions_amount_tco2e',
            field=models.DecimalField(
                db_comment='The amount of excess emissions in tCO2e', decimal_places=4, default=100, max_digits=20
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcomplianceobligation',
            name='emissions_amount_tco2e',
            field=models.DecimalField(
                db_comment='The amount of excess emissions in tCO2e', decimal_places=4, default=100, max_digits=20
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compliancesummary',
            name='compliance_status',
            field=models.CharField(
                choices=[
                    ('OBLIGATION_NOT_MET', 'Obligation Not Met'),
                    ('OBLIGATION_FULLY_MET', 'Obligation Fully Met'),
                    ('EARNED_CREDITS', 'Earned Credits'),
                ],
                db_comment='The compliance status (e.g., PARTIALLY_MET, FULLY_MET, EARNED_CREDITS)',
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name='historicalcompliancesummary',
            name='compliance_status',
            field=models.CharField(
                choices=[
                    ('OBLIGATION_NOT_MET', 'Obligation Not Met'),
                    ('OBLIGATION_FULLY_MET', 'Obligation Fully Met'),
                    ('EARNED_CREDITS', 'Earned Credits'),
                ],
                db_comment='The compliance status (e.g., PARTIALLY_MET, FULLY_MET, EARNED_CREDITS)',
                max_length=50,
            ),
        ),
    ]
