# Generated by Django 5.0.11 on 2025-03-07 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_seed_compliance_periods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcomplianceproduct',
            name='archived_by',
        ),
        migrations.RemoveField(
            model_name='historicalcomplianceproduct',
            name='compliance_summary',
        ),
        migrations.RemoveField(
            model_name='historicalcomplianceproduct',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalcomplianceproduct',
            name='report_product',
        ),
        migrations.RemoveField(
            model_name='historicalcomplianceproduct',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='HistoricalCompliancePeriod',
        ),
        migrations.DeleteModel(
            name='HistoricalComplianceProduct',
        ),
    ]
