# Generated by Django 5.0.11 on 2025-02-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_remove_complianceobligation_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compliancesummary',
            name='compliance_status',
        ),
        migrations.AlterField(
            model_name='complianceobligation',
            name='penalty_status',
            field=models.CharField(
                choices=[('NONE', 'None'), ('ACCRUING', 'Accruing'), ('PAID', 'Paid')],
                db_comment='The status of the penalty (e.g., NONE, ACCRUING, PAID)',
                default='NONE',
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name='complianceobligation',
            name='status',
            field=models.CharField(
                choices=[('OBLIGATION_NOT_MET', 'Obligation Not Met'), ('OBLIGATION_MET', 'Obligation Met')],
                db_comment='The status of the obligation (e.g., OBLIGATION_NOT_MET, OBLIGATION_MET)',
                default='OBLIGATION_NOT_MET',
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name='historicalcomplianceobligation',
            name='penalty_status',
            field=models.CharField(
                choices=[('NONE', 'None'), ('ACCRUING', 'Accruing'), ('PAID', 'Paid')],
                db_comment='The status of the penalty (e.g., NONE, ACCRUING, PAID)',
                default='NONE',
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name='historicalcomplianceobligation',
            name='status',
            field=models.CharField(
                choices=[('OBLIGATION_NOT_MET', 'Obligation Not Met'), ('OBLIGATION_MET', 'Obligation Met')],
                db_comment='The status of the obligation (e.g., OBLIGATION_NOT_MET, OBLIGATION_MET)',
                default='OBLIGATION_NOT_MET',
                max_length=50,
            ),
        ),
        migrations.DeleteModel(
            name='HistoricalComplianceSummary',
        ),
    ]
