# Generated by Django 5.1.12 on 2025-09-22 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0004_generate_compliance_reports'),
    ]

    operations = []
