# Generated by Django 5.0.14 on 2025-04-22 06:38

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0005_add_complianceobligation_obligation_id'),
        ('registration', '0106_remove_facility_restrict_bcghg_id_unless_operation_registered_and_more'),
        ('reporting', '0090_reload_cooling_units_json_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceobligation',
            name='fee_amount_dollars',
            field=models.DecimalField(
                blank=True, db_comment='The fee amount in CAD dollars', decimal_places=2, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name='complianceobligation',
            name='fee_date',
            field=models.DateField(blank=True, db_comment='The date the fee was created', null=True),
        ),
        migrations.AddField(
            model_name='complianceobligation',
            name='fee_rate_dollars',
            field=models.DecimalField(
                blank=True,
                db_comment='The fee rate used to calculate the fee amount in CAD dollars per tCO2e',
                decimal_places=2,
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='historicalcomplianceobligation',
            name='fee_amount_dollars',
            field=models.DecimalField(
                blank=True, db_comment='The fee amount in CAD dollars', decimal_places=2, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name='historicalcomplianceobligation',
            name='fee_date',
            field=models.DateField(blank=True, db_comment='The date the fee was created', null=True),
        ),
        migrations.AddField(
            model_name='historicalcomplianceobligation',
            name='fee_rate_dollars',
            field=models.DecimalField(
                blank=True,
                db_comment='The fee rate used to calculate the fee amount in CAD dollars per tCO2e',
                decimal_places=2,
                max_digits=10,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name='ComplianceChargeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                (
                    'rate',
                    models.DecimalField(
                        db_comment='The compliance charge rate in CAD dollars per tCO2e',
                        decimal_places=2,
                        max_digits=10,
                    ),
                ),
                (
                    'archived_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_archived',
                        to='registration.user',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_created',
                        to='registration.user',
                    ),
                ),
                (
                    'reporting_year',
                    models.ForeignKey(
                        db_comment='The associated reporting year for this compliance charge rate',
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='compliance_charge_rate',
                        to='reporting.reportingyear',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_updated',
                        to='registration.user',
                    ),
                ),
            ],
            options={
                'db_table': 'erc"."compliance_charge_rate',
                'db_table_comment': 'A table to store compliance charge rates by reporting year',
                'ordering': ['reporting_year'],
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='compliancechargerate',
            trigger=pgtrigger.compiler.Trigger(
                name='set_created_audit_columns',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="new.created_by_id = (select current_setting('my.guid', true)); new.created_at = now(); return new;",
                    hash='d3e446e369c3a2f6b59e76b579fe59a5fb579e24',
                    operation='INSERT',
                    pgid='pgtrigger_set_created_audit_columns_2cb42',
                    table='erc"."compliance_charge_rate',
                    when='BEFORE',
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='compliancechargerate',
            trigger=pgtrigger.compiler.Trigger(
                name='set_updated_audit_columns',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="new.updated_by_id = (select current_setting('my.guid', true)); new.updated_at = now(); return new;",
                    hash='5fca83b3504eb217848db1223ae94a412f3e6931',
                    operation='UPDATE',
                    pgid='pgtrigger_set_updated_audit_columns_83590',
                    table='erc"."compliance_charge_rate',
                    when='BEFORE',
                ),
            ),
        ),
    ]
