# Generated by Django 5.0.14 on 2025-06-18 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0006_elicensing_models'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ELicensingLink',
        ),
    ]
