# Generated by Django 5.0.14 on 2025-06-12 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0006_elicensing_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceobligation',
            name='elicensing_invoice',
            field=models.OneToOneField(
                blank=True,
                db_comment='Foreign key to the elicensing_invoice in the OBPS data. The data in the elicensing_invoice table comes from elicensing',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='compliance_obligation',
                to='compliance.elicensinginvoice',
            ),
        ),
        migrations.AddField(
            model_name='historicalcomplianceobligation',
            name='elicensing_invoice',
            field=models.ForeignKey(
                blank=True,
                db_comment='Foreign key to the elicensing_invoice in the OBPS data. The data in the elicensing_invoice table comes from elicensing',
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='compliance.elicensinginvoice',
            ),
        ),
    ]
