# Generated by Django 5.0.14 on 2025-06-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0007_delete_elicensinglink'),
    ]

    operations = [
        migrations.AddField(
            model_name='elicensinglineitem',
            name='base_amount',
            field=models.DecimalField(
                db_comment='The amount of this line item. baseAmount in elicensing',
                decimal_places=2,
                default=1.0,
                max_digits=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elicensinglineitem',
            name='description',
            field=models.CharField(blank=True, db_comment='Description of the line item (fee).', null=True),
        ),
        migrations.AddField(
            model_name='elicensinglineitem',
            name='fee_date',
            field=models.DateTimeField(
                db_comment='The date of the fee. feeDueDate in elicensing', default="2025-11-30"
            ),
            preserve_default=False,
        ),
    ]
