# Generated by Django 5.1.12 on 2025-10-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0008_V4_2_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancereportversion',
            name='requires_manual_handling',
            field=models.BooleanField(
                db_comment='Boolean value identifies whether this record requires manual handling outside of the app',
                default=False,
            ),
        ),
        migrations.AlterField(
            model_name='compliancereportversion',
            name='status',
            field=models.CharField(
                choices=[
                    ('Obligation not met', 'Obligation Not Met'),
                    ('Obligation fully met', 'Obligation Fully Met'),
                    ('Obligation pending invoice creation', 'Obligation Pending Invoice Creation'),
                    ('Earned credits', 'Earned Credits'),
                    ('No obligation or earned credits', 'No Obligation Or Earned Credits'),
                    ('Superceded', 'Superceded'),
                    ('Requires manual handling', 'Requires Manual Handling'),
                ],
                db_comment='The status of this compliance report version. Options: [Obligation not met, Obligation fully met, Earned credits, No obligation or earned credits]',
                max_length=100,
            ),
        ),
    ]
