# Generated by Django 5.1.10 on 2025-06-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0010_elicensing_invoice_last_refreshed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancereportversion',
            name='status',
            field=models.CharField(
                choices=[
                    ('Obligation not met', 'Obligation Not Met'),
                    ('Obligation fully met', 'Obligation Fully Met'),
                    ('Earned credits', 'Earned Credits'),
                    ('No obligation or earned credits', 'No Obligation Or Earned Credits'),
                ],
                db_comment='The status of this compliance report version. Options: [Obligation not met, Obligation fully met, Earned credits]',
                max_length=100,
            ),
        ),
    ]
