# Generated by Django 5.1.13 on 2025-11-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0010_V4_3_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancereportversion',
            name='requires_manual_handling',
            field=models.BooleanField(
                db_comment='Boolean value identifies whether this record requires manual handling outside of the app',
                default=False,
            ),
        ),
    ]
