# Generated by Django 5.1.13 on 2025-11-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0010_V4_3_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceearnedcredit',
            name='supplementary_declined',
            field=models.BooleanField(
                db_comment='Boolean value identifies whether this earned credit record was declined due to a supplementary report changing the amount of earned credits',
                default=False,
            ),
        ),
        migrations.AddField(
            model_name='historicalcomplianceearnedcredit',
            name='supplementary_declined',
            field=models.BooleanField(
                db_comment='Boolean value identifies whether this earned credit record was declined due to a supplementary report changing the amount of earned credits',
                default=False,
            ),
        ),
    ]
