# Generated by Django 5.1.14 on 2025-11-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0011_compliancereportversion_requires_manual_handling'),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceearnedcredit',
            name='supplementary_declined',
            field=models.BooleanField(
                db_comment='Boolean value identifies whether this earned credit record was declined due to a supplementary report changing the amount of earned credits',
                default=False,
            ),
        ),
        migrations.AddField(
            model_name='historicalcomplianceearnedcredit',
            name='supplementary_declined',
            field=models.BooleanField(
                db_comment='Boolean value identifies whether this earned credit record was declined due to a supplementary report changing the amount of earned credits',
                default=False,
            ),
        ),
    ]
