# Generated by Django 5.1.10 on 2025-07-02 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0011_compliancereport_bccr_subaccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancereportversion',
            name='status',
            field=models.CharField(
                choices=[
                    ('Obligation not met', 'Obligation Not Met'),
                    ('Obligation fully met', 'Obligation Fully Met'),
                    ('Earned credits', 'Earned Credits'),
                    ('No obligation or earned credits', 'No Obligation Or Earned Credits'),
                ],
                db_comment='The status of this compliance report version.',
                max_length=100,
            ),
        ),
    ]
