# Generated by Django 5.1.10 on 2025-07-08 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0012_alter_compliancereportversion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancereportversion',
            name='is_supplementary',
            field=models.BooleanField(
                db_comment='Boolean value identifies whether this record is the result of a supplementary emissions report version',
                default=False,
            ),
        ),
    ]
