# Generated by Django 5.1.10 on 2025-07-10 18:17

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0013_complianceearnedcredit_restrict_bccr_trading_name_unless_not_issued'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='complianceearnedcredit',
            name='restrict_bccr_trading_name_unless_not_issued',
        ),
        migrations.AddField(
            model_name='complianceearnedcredit',
            name='analyst_submitted_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='The analyst who provided the suggestion',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='compliance_earned_credits_analyst_submitted_by',
                to='registration.user',
            ),
        ),
        migrations.AddField(
            model_name='complianceearnedcredit',
            name='analyst_submitted_date',
            field=models.DateField(
                blank=True, db_comment='The date on which the analyst provided the suggestion', null=True
            ),
        ),
        migrations.AddField(
            model_name='complianceearnedcredit',
            name='analyst_suggestion',
            field=models.CharField(
                blank=True,
                choices=[
                    ('Ready to approve', 'Ready To Approve'),
                    ('Requiring change of BCCR Holding Account ID', 'Requiring Change Of Bccr Holding Account Id'),
                    ('Requiring supplementary report', 'Requiring Supplementary Report'),
                ],
                db_comment='The suggestion from the analyst on whether or not to recommend issuance of the credits',
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='complianceearnedcredit',
            name='bccr_holding_account_id',
            field=models.CharField(
                blank=True,
                db_comment='The BCCR holding account ID. This is the ID of the account holder in the BC Carbon Registry',
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='complianceearnedcredit',
            name='issuance_requested_date',
            field=models.DateField(
                blank=True,
                db_comment='The date on which the earned credits were requested to be issued by the industry user',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='historicalcomplianceearnedcredit',
            name='analyst_submitted_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='The analyst who provided the suggestion',
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='registration.user',
            ),
        ),
        migrations.AddField(
            model_name='historicalcomplianceearnedcredit',
            name='analyst_submitted_date',
            field=models.DateField(
                blank=True, db_comment='The date on which the analyst provided the suggestion', null=True
            ),
        ),
        migrations.AddField(
            model_name='historicalcomplianceearnedcredit',
            name='analyst_suggestion',
            field=models.CharField(
                blank=True,
                choices=[
                    ('Ready to approve', 'Ready To Approve'),
                    ('Requiring change of BCCR Holding Account ID', 'Requiring Change Of Bccr Holding Account Id'),
                    ('Requiring supplementary report', 'Requiring Supplementary Report'),
                ],
                db_comment='The suggestion from the analyst on whether or not to recommend issuance of the credits',
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='historicalcomplianceearnedcredit',
            name='bccr_holding_account_id',
            field=models.CharField(
                blank=True,
                db_comment='The BCCR holding account ID. This is the ID of the account holder in the BC Carbon Registry',
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='historicalcomplianceearnedcredit',
            name='issuance_requested_date',
            field=models.DateField(
                blank=True,
                db_comment='The date on which the earned credits were requested to be issued by the industry user',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='complianceearnedcredit',
            name='issuance_status',
            field=models.CharField(
                choices=[
                    ('Credits Not Issued in BCCR', 'Credits Not Issued'),
                    ('Issuance Requested', 'Issuance Requested'),
                    ('Changes Required', 'Changes Required'),
                    ('Approved', 'Approved'),
                    ('Declined', 'Declined'),
                ],
                db_comment='The status of this of the earned credits in this record.',
                default='Credits Not Issued in BCCR',
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name='historicalcomplianceearnedcredit',
            name='issuance_status',
            field=models.CharField(
                choices=[
                    ('Credits Not Issued in BCCR', 'Credits Not Issued'),
                    ('Issuance Requested', 'Issuance Requested'),
                    ('Changes Required', 'Changes Required'),
                    ('Approved', 'Approved'),
                    ('Declined', 'Declined'),
                ],
                db_comment='The status of this of the earned credits in this record.',
                default='Credits Not Issued in BCCR',
                max_length=100,
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='complianceearnedcredit',
            trigger=pgtrigger.compiler.Trigger(
                name='restrict_bccr_fields_unless_not_issued',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (NEW."bccr_trading_name" IS NULL OR NEW."bccr_trading_name" = \'\' OR NEW."bccr_holding_account_id" IS NULL OR NEW."bccr_holding_account_id" = \'\')',
                    func='\n                    if new.issuance_status != \'Credits Not Issued in BCCR\' then\n                        if (new.bccr_trading_name is null or new.bccr_trading_name = \'\') then\n                            raise exception \'bccr_trading_name cannot be empty unless issuance_status is "Credits Not Issued in BCCR"\';\n                        end if;\n                        if (new.bccr_holding_account_id is null or new.bccr_holding_account_id = \'\') then\n                            raise exception \'bccr_holding_account_id cannot be empty unless issuance_status is "Credits Not Issued in BCCR"\';\n                        end if;\n                    end if;\n                    return new;\n                ',
                    hash='e6923343450ca6a271150a0b899c47aac4b6ac78',
                    operation='INSERT OR UPDATE',
                    pgid='pgtrigger_restrict_bccr_fields_unless_not_issued_aa36a',
                    table='erc"."compliance_earned_credit',
                    when='BEFORE',
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='complianceearnedcredit',
            trigger=pgtrigger.compiler.Trigger(
                name='populate_analyst_submission_info',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n                    -- Populate submission info whenever the analyst comment changes\n                    if old.analyst_comment is distinct from new.analyst_comment then\n                        new.analyst_submitted_date = current_date;\n                        new.analyst_submitted_by_id = (select nullif(current_setting('my.guid', true), ''));\n                    end if;\n                    return new;\n                ",
                    hash='c5474e37c0cdd565d9b73062d57d8f16130038da',
                    operation='UPDATE',
                    pgid='pgtrigger_populate_analyst_submission_info_be756',
                    table='erc"."compliance_earned_credit',
                    when='BEFORE',
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='complianceearnedcredit',
            trigger=pgtrigger.compiler.Trigger(
                name='populate_issued_date_issued_by_on_decision',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (NEW."issuance_status" IN (\'Approved\', \'Declined\'))',
                    func="\n                    new.issued_date = current_date;\n                    new.issued_by_id = (select nullif(current_setting('my.guid', true), ''));\n                    return new;\n                ",
                    hash='9fe490b5eae06ec1163013cdb1b62065e61e5742',
                    operation='UPDATE',
                    pgid='pgtrigger_populate_issued_date_issued_by_on_decision_fac9d',
                    table='erc"."compliance_earned_credit',
                    when='BEFORE',
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='complianceearnedcredit',
            trigger=pgtrigger.compiler.Trigger(
                name='populate_issuance_requested_date_when_requested',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (NEW."issuance_status" = \'Issuance Requested\')',
                    func='\n                    new.issuance_requested_date = current_date;\n                    return new;\n                ',
                    hash='30ab03943125239be269e638f61f21fbe106ebd7',
                    operation='UPDATE',
                    pgid='pgtrigger_populate_issuance_requested_date_when_requested_209d9',
                    table='erc"."compliance_earned_credit',
                    when='BEFORE',
                ),
            ),
        ),
    ]
