# Generated by Django 5.1.14 on 2025-11-17 14:50

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0013_V4_4_0'),
        ('registration', '0145_V4_4_0'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceReportVersionManualHandling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                (
                    'analyst_comment',
                    models.TextField(blank=True, db_comment='Optional comment entered by the analyst.', null=True),
                ),
                (
                    'analyst_submitted_date',
                    models.DateField(
                        blank=True,
                        db_comment='The date on which the analyst provided or updated the manual handling comment.',
                        null=True,
                    ),
                ),
                (
                    'director_comment',
                    models.TextField(blank=True, db_comment='Optional comment entered by the director.', null=True),
                ),
                (
                    'director_decision',
                    models.CharField(
                        choices=[
                            ('pending_manual_handling', 'Pending manual handling'),
                            ('issue_resolved', 'Issue has been resolved'),
                        ],
                        db_comment="Director's decision about the manual handling case.",
                        default='pending_manual_handling',
                        max_length=50,
                    ),
                ),
                (
                    'director_decision_date',
                    models.DateField(
                        blank=True, db_comment='The date on which the director made the decision.', null=True
                    ),
                ),
                (
                    'analyst_submitted_by',
                    models.ForeignKey(
                        blank=True,
                        db_comment='The analyst who provided the manual handling comment.',
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='compliance_manual_handling_analyst_submitted_by',
                        to='registration.user',
                    ),
                ),
                (
                    'archived_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_archived',
                        to='registration.user',
                    ),
                ),
                (
                    'compliance_report_version',
                    models.OneToOneField(
                        db_comment='The CRV that requires manual handling.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='manual_handling_record',
                        to='compliance.compliancereportversion',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_created',
                        to='registration.user',
                    ),
                ),
                (
                    'director_decision_by',
                    models.ForeignKey(
                        blank=True,
                        db_comment='The director who made the decision.',
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='compliance_manual_handling_director_decision_by',
                        to='registration.user',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_updated',
                        to='registration.user',
                    ),
                ),
            ],
            options={
                'db_table': 'erc"."compliance_report_version_manual_handling',
                'db_table_comment': 'Tracks analyst and director manual handling resolution for compliance report versions',
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='compliancereportversionmanualhandling',
            trigger=pgtrigger.compiler.Trigger(
                name='set_created_audit_columns',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="new.created_by_id = (select nullif(current_setting('my.guid', true), '')); new.created_at = now(); return new;",
                    hash='833cf93447101d21d373207d1dc3009657984067',
                    operation='INSERT',
                    pgid='pgtrigger_set_created_audit_columns_01cd7',
                    table='erc"."compliance_report_version_manual_handling',
                    when='BEFORE',
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='compliancereportversionmanualhandling',
            trigger=pgtrigger.compiler.Trigger(
                name='set_updated_audit_columns',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="new.updated_by_id = (select nullif(current_setting('my.guid', true), '')); new.updated_at = now(); return new;",
                    hash='ee58c8953ffccea21a4e9781d52e5f4233bc3529',
                    operation='UPDATE',
                    pgid='pgtrigger_set_updated_audit_columns_c889e',
                    table='erc"."compliance_report_version_manual_handling',
                    when='BEFORE',
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='compliancereportversionmanualhandling',
            trigger=pgtrigger.compiler.Trigger(
                name='mh_analyst_submit_info',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n                    -- Populate submission info whenever the analyst comment changes\n                    IF old.analyst_comment IS DISTINCT FROM new.analyst_comment THEN\n                        new.analyst_submitted_date = current_date;\n                        new.analyst_submitted_by_id =\n                            (SELECT nullif(current_setting('my.guid', true), ''));\n                    END IF;\n                    RETURN NEW;\n                ",
                    hash='d88605f5e8bc8bc0b8c1115d4479fed0aebce489',
                    operation='UPDATE',
                    pgid='pgtrigger_mh_analyst_submit_info_e6a6b',
                    table='erc"."compliance_report_version_manual_handling',
                    when='BEFORE',
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='compliancereportversionmanualhandling',
            trigger=pgtrigger.compiler.Trigger(
                name='mh_director_decision_info',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (NEW."director_decision" = \'issue_resolved\')',
                    func="\n                    -- When director marks the issue as resolved, stamp who/when\n                    IF old.director_decision IS DISTINCT FROM new.director_decision\n                       AND new.director_decision = 'issue_resolved' THEN\n                        new.director_decision_date = current_date;\n                        new.director_decision_by_id =\n                            (SELECT nullif(current_setting('my.guid', true), ''));\n                    END IF;\n                    RETURN NEW;\n                ",
                    hash='682419710a06f525513ddee32fdc0df279095758',
                    operation='UPDATE',
                    pgid='pgtrigger_mh_director_decision_info_db630',
                    table='erc"."compliance_report_version_manual_handling',
                    when='BEFORE',
                ),
            ),
        ),
    ]
