# Generated by Django 5.1.14 on 2025-11-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0014_compliancepenalty_accrual_final_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elicensinginvoice',
            name='invoice_fee_balance',
            field=models.DecimalField(
                db_comment='The balance of fees for this invoice. invoiceFeeBalance in elicensing. This value does not include FAA interest (invoice_interest_balance).',
                decimal_places=2,
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='elicensinginvoice',
            name='outstanding_balance',
            field=models.DecimalField(
                db_comment='The outstanding balance for this invoice. invoiceOutstandingBalance in elicensing. This value is the combination of invoice_fee_balance & invoice_interest_balance.',
                decimal_places=2,
                max_digits=20,
            ),
        ),
    ]
