# Generated by Django 5.1.14 on 2025-11-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0014_compliancepenalty_accrual_final_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancepenalty',
            name='status',
            field=models.CharField(
                choices=[('NOT PAID', 'Not Paid'), ('PAID', 'Paid')],
                db_comment='The status of this penalty (e.g., NOT PAID, PAID)',
                default='NOT PAID',
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name='compliancepenalty',
            name='accrual_frequency',
            field=models.CharField(
                choices=[('Daily', 'Daily'), ('Monthly', 'Monthly')],
                db_comment='Defines how often the penalty accrues (e.g., daily for Automatic Overdue, daily for Late Submission)',
                default='Daily',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='compliancepenalty',
            name='compounding_frequency',
            field=models.CharField(
                choices=[('Daily', 'Daily'), ('Monthly', 'Monthly')],
                db_comment='Defines how often interest is compounded for this penalty (e.g., daily or monthly).',
                default='Daily',
                max_length=20,
            ),
        ),
    ]
