# Generated by Django 5.1.10 on 2025-07-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0015_remove_complianceearnedcredit_restrict_bccr_trading_name_unless_not_issued_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancereportversion',
            name='status',
            field=models.CharField(
                choices=[
                    ('Obligation not met', 'Obligation Not Met'),
                    ('Obligation fully met', 'Obligation Fully Met'),
                    ('Obligation pending invoice creation', 'Obligation Pending Invoice Creation'),
                    ('Earned credits', 'Earned Credits'),
                    ('No obligation or earned credits', 'No Obligation Or Earned Credits'),
                ],
                db_comment='The status of this compliance report version. Options: [Obligation not met, Obligation fully met, Earned credits, No obligation or earned credits]',
                max_length=100,
            ),
        ),
    ]
