# Generated by Django 5.1.10 on 2025-07-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0015_remove_complianceearnedcredit_restrict_bccr_trading_name_unless_not_issued_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elicensingpayment',
            name='method',
            field=models.CharField(
                blank=True,
                db_comment='The method used to make the payment (e.g. wire transfer) from elicensing.',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='elicensingpayment',
            name='receipt_number',
            field=models.CharField(blank=True, db_comment='Receipt number of the payment in elicensing.', null=True),
        ),
    ]
