# Generated by Django 5.1.10 on 2025-07-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0016_elicensingpayment_method_and_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceearnedcredit',
            name='bccr_issuance_id',
            field=models.CharField(
                blank=True,
                db_comment='The BCCR issuance ID associated with this earned credit, for idempotency.',
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='complianceearnedcredit',
            name='bccr_project_id',
            field=models.CharField(
                blank=True,
                db_comment='The BCCR project ID associated with this earned credit, for idempotency.',
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='historicalcomplianceearnedcredit',
            name='bccr_issuance_id',
            field=models.CharField(
                blank=True,
                db_comment='The BCCR issuance ID associated with this earned credit, for idempotency.',
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='historicalcomplianceearnedcredit',
            name='bccr_project_id',
            field=models.CharField(
                blank=True,
                db_comment='The BCCR project ID associated with this earned credit, for idempotency.',
                max_length=50,
                null=True,
            ),
        ),
    ]
