# Generated by Django 5.1.14 on 2025-11-26 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0016_compliancepenalty_status_and_more'),
    ]

    operations = []
