# Generated by Django 5.1.15 on 2025-12-03 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0017_V4_5_0'),
    ]

    operations = []
