# Generated by Django 5.1.10 on 2025-07-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0018_penalty_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complianceobligation',
            name='penalty_status',
            field=models.CharField(
                choices=[('NONE', 'None'), ('ACCRUING', 'Accruing'), ('PAID', 'Paid'), ('NOT PAID', 'Not Paid')],
                db_comment='The status of the penalty (e.g., NONE, ACCRUING, PAID)',
                default='NONE',
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name='historicalcomplianceobligation',
            name='penalty_status',
            field=models.CharField(
                choices=[('NONE', 'None'), ('ACCRUING', 'Accruing'), ('PAID', 'Paid'), ('NOT PAID', 'Not Paid')],
                db_comment='The status of the penalty (e.g., NONE, ACCRUING, PAID)',
                default='NONE',
                max_length=50,
            ),
        ),
    ]
