# Generated by Django 5.1.10 on 2025-08-05 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0019_alter_elicensingpayment_received_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complianceobligation',
            name='penalty_status',
            field=models.CharField(
                choices=[('NONE', 'None'), ('ACCRUING', 'Accruing'), ('PAID', 'Paid'), ('NOT PAID', 'Not Paid')],
                db_comment='The status of the penalty (e.g., NONE, ACCRUING, PAID)',
                default='NONE',
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name='compliancepenalty',
            name='elicensing_invoice',
            field=models.OneToOneField(
                blank=True,
                db_comment='The invoice from elicensing that this penalty created',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='compliance_penalty',
                to='compliance.elicensinginvoice',
            ),
        ),
        migrations.AlterField(
            model_name='historicalcomplianceobligation',
            name='penalty_status',
            field=models.CharField(
                choices=[('NONE', 'None'), ('ACCRUING', 'Accruing'), ('PAID', 'Paid'), ('NOT PAID', 'Not Paid')],
                db_comment='The status of the penalty (e.g., NONE, ACCRUING, PAID)',
                default='NONE',
                max_length=50,
            ),
        ),
    ]
