# Generated by Django 5.1.15 on 2025-12-09 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0019_remove_compliancereportversion_requires_manual_handling_and_more'),
    ]

    operations = []
