# Generated by Django 5.1.10 on 2025-08-01 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0019_compliance_obligation_penalty_not_paid_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancepenalty',
            name='elicensing_invoice',
            field=models.OneToOneField(
                blank=True,
                db_comment='The invoice from elicensing that this penalty created',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='compliance_penalty',
                to='compliance.elicensinginvoice',
            ),
        ),
    ]
