# Generated by Django 5.1.10 on 2025-08-06 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0020_compliance_penalty_fkey_nullable_and_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='elicensingadjustment',
            name='supplementary_compliance_report_version',
            field=models.ForeignKey(
                blank=True,
                db_comment='Foreign key to the supplementary compliance report version that triggered this adjustment. When a supplementary report reduces excess emissions, an adjustment is created and applied to the existing invoice from the original compliance report version, but this field tracks which supplementary version caused the adjustment.',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='elicensing_adjustments',
                to='compliance.compliancereportversion',
            ),
        ),
    ]
