# Generated by Django 5.1.15 on 2026-01-07 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0021_remove_complianceobligation_obligation_deadline_and_more'),
    ]

    operations = []
