# Generated by Django 5.1.10 on 2025-08-13 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0022_alter_compliancereportversion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancepenalty',
            name='fee_date',
            field=models.DateField(blank=True, db_comment='The date the fee was created', null=True),
        ),
    ]
