# Generated by Django 5.1.15 on 2026-01-15 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0022_V4_7_0'),
    ]

    operations = []
