# Generated by Django 5.1.10 on 2025-08-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0023_compliancepenalty_fee_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elicensingadjustment',
            name='reason',
            field=models.CharField(
                blank=True,
                choices=[
                    ('Supplementary Report Adjustment', 'Supplementary Report Adjustment'),
                    ('Compliance Units Applied', 'Compliance Units Applied'),
                ],
                db_comment='Reason for adjustment in elicesning',
                null=True,
            ),
        ),
    ]
