# Generated by Django 5.1.10 on 2025-08-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0023_compliancepenalty_fee_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elicensingadjustment',
            name='adjustment_date',
            field=models.DateField(blank=True, db_comment='date of the adjustment in elicensing', null=True),
        ),
        migrations.AlterField(
            model_name='elicensinginvoice',
            name='due_date',
            field=models.DateField(db_comment='The due date of the invoice. invoicePaymentDueDate in elicensing'),
        ),
        migrations.AlterField(
            model_name='elicensinglineitem',
            name='fee_date',
            field=models.DateField(db_comment='The date of the fee. feeDueDate in elicensing'),
        ),
    ]
