# Generated by Django 5.1.10 on 2025-08-26 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0023_compliancepenalty_fee_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancereportversion',
            name='previous_version',
            field=models.ForeignKey(
                blank=True,
                db_comment='Reference to the previous version of this compliance report version.',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='subsequent_versions',
                to='compliance.compliancereportversion',
            ),
        ),
    ]
