# Generated by Django 5.2.16 on 2026-08-06 17:33

from decimal import Decimal

import common.lib.pgtrigger.core
import django.db.migrations.operations.special
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models

# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# compliance.migrations.0026_add_2025_compliance_period
# compliance.migrations.0037_complianceperiod_max_credit_usage_percentage
# compliance.migrations.0062_add_compliancepenaltyrates


def add_2025_compliance_period(apps, schema_editor):
    CompliancePeriod = apps.get_model('compliance', 'CompliancePeriod')
    ReportingYear = apps.get_model('reporting', 'ReportingYear')

    CompliancePeriod.objects.create(
        created_at='2025-01-01T00:00:00Z',
        updated_at='2025-01-01T00:00:00Z',
        start_date='2025-01-01',
        end_date='2025-12-31',
        compliance_deadline='2026-11-30',
        invoice_generation_date='2026-11-01',
        reporting_year=ReportingYear.objects.get(reporting_year=2025),
    )


def reverse_add_2025_compliance_period(apps, schema_editor):
    CompliancePeriod = apps.get_model('compliance', 'CompliancePeriod')
    CompliancePeriod.objects.filter(reporting_year=2025).delete()


def set_max_credit_usage_percentage(apps, schema_editor):
    CompliancePeriod = apps.get_model('compliance', 'CompliancePeriod')
    ReportingYear = apps.get_model('reporting', 'ReportingYear')

    CompliancePeriod.objects.filter(reporting_year=ReportingYear.objects.get(reporting_year=2024)).update(
        max_credit_usage_percentage=Decimal("0.50")
    )

    CompliancePeriod.objects.filter(reporting_year=ReportingYear.objects.get(reporting_year=2025)).update(
        max_credit_usage_percentage=Decimal("0.40")
    )


def add_compliance_penalty_rates(apps, schema_editor):
    CompliancePenaltyRate = apps.get_model('compliance', 'CompliancePenaltyRate')

    CompliancePenaltyRate.objects.create(
        rate=0.0038,
        is_current_rate=True,
    )


def reverse_add_compliance_penalty_rates(apps, schema_editor):
    CompliancePenaltyRate = apps.get_model('compliance', 'CompliancePenaltyRate')
    CompliancePenaltyRate.objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    replaces = [
        ('compliance', '0025_V5_0_1'),
        ('compliance', '0026_add_2025_compliance_period'),
        ('compliance', '0027_V5_1_0'),
        ('compliance', '0028_V5_2_0'),
        ('compliance', '0029_complianceobligation_add_invoice_number_and_populate'),
        ('compliance', '0030_V5_3_0'),
        ('compliance', '0031_V5_3_1'),
        ('compliance', '0032_V5_4_0'),
        ('compliance', '0033_V5_4_1'),
        ('compliance', '0034_V5_4_2'),
        ('compliance', '0035_V5_4_3'),
        ('compliance', '0036_V5_5_0'),
        ('compliance', '0037_complianceperiod_max_credit_usage_percentage'),
        ('compliance', '0038_remove_complianceearnedcredit_populate_analyst_submission_info_and_more'),
        ('compliance', '0039_V5_6_0'),
        ('compliance', '0040_alter_compliancereportversion_status'),
        ('compliance', '0041_compliancepenalty_invoice_number'),
        ('compliance', '0042_V5_7_0'),
        ('compliance', '0043_V5_8_0'),
        ('compliance', '0044_V5_9_0'),
        ('compliance', '0045_V5_10_0'),
        ('compliance', '0046_V5_11_0'),
        ('compliance', '0047_V5_12_0'),
        ('compliance', '0048_V5_13_0'),
        ('compliance', '0049_V5_13_1'),
        ('compliance', '0050_V5_14_0'),
        ('compliance', '0051_alter_compliancereportversionmanualhandling_table_comment_and_more'),
        ('compliance', '0052_update_timestamp_metadata'),
        ('compliance', '0053_V5_15_0'),
        ('compliance', '0054_V5_15_1'),
        ('compliance', '0055_alter_compliancereportversion_status'),
        ('compliance', '0056_backfill_obligation_met_interest_not_paid'),
        ('compliance', '0057_V5_16_0'),
        ('compliance', '0058_alter_compliancereportversionmanualhandling_context'),
        ('compliance', '0059_remove_elicensingadjustment_supp_reasons_require_supp_version_and_more'),
        ('compliance', '0060_V5_17_0'),
        ('compliance', '0061_alter_compliancepenaltyrate_options_and_more'),
        ('compliance', '0062_add_compliancepenaltyrates'),
        ('compliance', '0063_V5_18_0'),
    ]

    dependencies = [
        ('compliance', '0001_initial_squashed_0024_V5_0_0'),
        ('reporting', '0206_V5_18_0'),
        ('registration', '0189_V5_18_0'),
    ]

    operations = [
        migrations.RunPython(
            code=add_2025_compliance_period,
            reverse_code=reverse_add_2025_compliance_period,
        ),
        migrations.AddField(
            model_name='historicalcomplianceobligation',
            name='invoice_number',
            field=models.CharField(
                blank=True,
                db_comment='The invoice number for the related elicensing invoice. Populated immediately on invoice creation in elicensing to ensure the link is not lost between invoice creation in elicensing and the refresh function that creates the elicensing_invoice record in the erc data.',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='complianceobligation',
            name='invoice_number',
            field=models.CharField(
                blank=True,
                db_comment='The invoice number for the related elicensing invoice. Populated immediately on invoice creation in elicensing to ensure the link is not lost between invoice creation in elicensing and the refresh function that creates the elicensing_invoice record in the erc data.',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='complianceperiod',
            name='max_credit_usage_percentage',
            field=models.DecimalField(
                db_comment='Maximum percentage of the compliance obligation that can be met using compliance units (e.g. 0.50 = 50 percent)',
                decimal_places=2,
                max_digits=4,
                null=True,
            ),
        ),
        migrations.RunPython(
            code=set_max_credit_usage_percentage,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='complianceperiod',
            name='max_credit_usage_percentage',
            field=models.DecimalField(
                db_comment='Maximum percentage of the compliance obligation that can be met using compliance units (e.g. 0.50 = 50 percent)',
                decimal_places=2,
                max_digits=4,
            ),
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='complianceearnedcredit',
            name='populate_analyst_submission_info',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='complianceearnedcredit',
            trigger=pgtrigger.compiler.Trigger(
                name='populate_analyst_submission_info',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n                    -- Populate submission info whenever the analyst comment changes\n                    if old.analyst_suggestion is distinct from new.analyst_suggestion then\n                        new.analyst_submitted_date = current_date;\n                        new.analyst_submitted_by_id = (select nullif(current_setting('my.guid', true), ''));\n                    end if;\n                    return new;\n                ",
                    hash='0d0e9f7cdc5c04f8ffe9d4b12a66be76f34e4866',
                    operation='UPDATE',
                    pgid='pgtrigger_populate_analyst_submission_info_be756',
                    table='erc"."compliance_earned_credit',
                    when='BEFORE',
                ),
            ),
        ),
        migrations.AlterField(
            model_name='compliancechargerate',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='compliancechargerate',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='compliancechargerate',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='compliancechargerate',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='compliancechargerate',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='complianceearnedcredit',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='complianceearnedcredit',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='complianceearnedcredit',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='complianceearnedcredit',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='complianceearnedcredit',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='complianceearnedcredit',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='complianceobligation',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='complianceobligation',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='complianceobligation',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='complianceobligation',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='complianceobligation',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='complianceobligation',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='compliancepenalty',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='compliancepenalty',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='compliancepenalty',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='compliancepenalty',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='compliancepenalty',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='compliancepenalty',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='compliancepenaltyaccrual',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='compliancepenaltyaccrual',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='compliancepenaltyaccrual',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='compliancepenaltyaccrual',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='compliancepenaltyaccrual',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='compliancepenaltyaccrual',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='compliancepenaltyrate',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='compliancepenaltyrate',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='compliancepenaltyrate',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='compliancepenaltyrate',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='compliancepenaltyrate',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='compliancepenaltyrate',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='complianceperiod',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='complianceperiod',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='complianceperiod',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='complianceperiod',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='complianceperiod',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='complianceperiod',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='compliancereport',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='compliancereport',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='compliancereport',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='compliancereport',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='compliancereport',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='compliancereport',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='compliancereportversion',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='compliancereportversion',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='compliancereportversion',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='compliancereportversion',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='compliancereportversion',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='compliancereportversion',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='compliancereportversionmanualhandling',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='compliancereportversionmanualhandling',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='compliancereportversionmanualhandling',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='compliancereportversionmanualhandling',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='compliancereportversionmanualhandling',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='compliancereportversionmanualhandling',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='elicensingadjustment',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='elicensingadjustment',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='elicensingadjustment',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='elicensingadjustment',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='elicensingadjustment',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='elicensingadjustment',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='elicensingclientoperator',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='elicensingclientoperator',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='elicensingclientoperator',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='elicensingclientoperator',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='elicensingclientoperator',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='elicensingclientoperator',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='elicensinginvoice',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='elicensinginvoice',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='elicensinginvoice',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='elicensinginvoice',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='elicensinginvoice',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='elicensinginvoice',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='elicensinglineitem',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='elicensinglineitem',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='elicensinglineitem',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='elicensinglineitem',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='elicensinglineitem',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='elicensinglineitem',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='elicensingpayment',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='elicensingpayment',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='elicensingpayment',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='elicensingpayment',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='elicensingpayment',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='elicensingpayment',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='historicalcomplianceearnedcredit',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='historicalcomplianceearnedcredit',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='historicalcomplianceearnedcredit',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='historicalcomplianceearnedcredit',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='historicalcomplianceearnedcredit',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='historicalcomplianceearnedcredit',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='historicalcomplianceobligation',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='historicalcomplianceobligation',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='historicalcomplianceobligation',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='historicalcomplianceobligation',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='historicalcomplianceobligation',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='historicalcomplianceobligation',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='registration.user',
            ),
        ),
        migrations.AddField(
            model_name='compliancepenalty',
            name='invoice_number',
            field=models.CharField(
                blank=True,
                db_comment='The invoice number for the related elicensing invoice. Populated immediately on invoice creation in elicensing to ensure the link is not lost between invoice creation in elicensing and the refresh function that creates the elicensing_invoice record in the erc data.',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='compliancereportversion',
            name='status',
            field=models.CharField(
                choices=[
                    ('Obligation not met', 'Obligation Not Met'),
                    ('Obligation Met - Interest not paid', 'Obligation Met Interest Not Paid'),
                    ('Obligation fully met', 'Obligation Fully Met'),
                    ('Obligation pending invoice creation', 'Obligation Pending Invoice Creation'),
                    ('Earned credits', 'Earned Credits'),
                    ('No obligation or earned credits', 'No Obligation Or Earned Credits'),
                    ('Requires manual handling', 'Requires Manual Handling'),
                    ('Superceded', 'Superceded'),
                ],
                db_comment='The status of this compliance report version. Options: [Obligation not met, Obligation Met - Interest not paid, Obligation fully met, Earned credits, No obligation or earned credits, Requires manual handling]',
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name='compliancechargerate',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='compliancereportversionmanualhandling',
            name='context',
            field=models.CharField(
                choices=[
                    (
                        'obligation_refund_pool_cash',
                        'Obligation is fully paid and the refund pool contains refundable cash.',
                    ),
                    ('earned_credits_previously_approved', 'Earned credits have been previously approved.'),
                    (
                        'credits_over_allowed_percentage',
                        'A supplementary decrease pushed the applied compliance units over the allowed percentage.',
                    ),
                ],
                db_comment='Reason for requiring manual handling',
                max_length=100,
            ),
        ),
        migrations.RemoveConstraint(
            model_name='elicensingadjustment',
            name='supp_reasons_require_supp_version',
        ),
        migrations.AlterField(
            model_name='elicensingadjustment',
            name='reason',
            field=models.CharField(blank=True, db_comment='Reason for adjustment in elicensing', null=True),
        ),
        migrations.AddConstraint(
            model_name='elicensingadjustment',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        'reason__in',
                        ['Supplementary Report Adjustment', 'Supplementary Report Adjustment to Void Invoice'],
                    ),
                    ('supplementary_compliance_report_version__isnull', True),
                    _negated=True,
                ),
                name='supp_reasons_require_supp_version',
                violation_error_message='An adjustment with a supplementary report reason requires a supplementary report version',
            ),
        ),
        migrations.AlterModelOptions(
            name='compliancepenaltyrate',
            options={},
        ),
        migrations.RemoveField(
            model_name='compliancepenaltyrate',
            name='compliance_period',
        ),
        migrations.AddConstraint(
            model_name='compliancepenaltyrate',
            constraint=models.UniqueConstraint(
                condition=common.lib.pgtrigger.core.Q(('is_current_rate', True)),
                fields=('is_current_rate',),
                name='unique_is_current_rate_true_per_compliance_penalty_rate',
            ),
        ),
        migrations.RunPython(
            code=add_compliance_penalty_rates,
            reverse_code=reverse_add_compliance_penalty_rates,
        ),
    ]
