# Generated by Django 5.1.15 on 2026-01-24 00:37

from django.db import migrations


def add_2025_compliance_period(apps, schema_editor):
    CompliancePeriod = apps.get_model('compliance', 'CompliancePeriod')
    ReportingYear = apps.get_model('reporting', 'ReportingYear')

    CompliancePeriod.objects.create(
        created_at='2025-01-01T00:00:00Z',
        updated_at='2025-01-01T00:00:00Z',
        start_date='2025-01-01',
        end_date='2025-12-31',
        compliance_deadline='2026-11-30',
        invoice_generation_date='2026-11-01',
        reporting_year=ReportingYear.objects.get(reporting_year=2025),
    )


def reverse_add_2025_compliance_period(apps, schema_editor):
    CompliancePeriod = apps.get_model('compliance', 'CompliancePeriod')
    CompliancePeriod.objects.filter(reporting_year=2025).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0025_V5_0_1'),
    ]

    operations = [
        migrations.RunPython(add_2025_compliance_period, reverse_add_2025_compliance_period),
    ]
