# Generated by Django 5.1.15 on 2026-02-04 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0026_add_2025_compliance_period'),
    ]

    operations = []
