# Generated by Django 5.1.15 on 2026-02-19 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0027_V5_1_0'),
    ]

    operations = []
