# Generated by Django 5.1.10 on 2025-09-09 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0027_alter_elicensingadjustment_adjustment_date_and_more'),
        ('reporting', '0128_V3_17_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancechargerate',
            name='reporting_year',
            field=models.OneToOneField(
                db_comment='The associated reporting year for this compliance charge rate',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='compliance_charge_rate',
                to='reporting.reportingyear',
            ),
        ),
    ]
