# Generated by Django 5.1.10 on 2025-09-09 20:18

from django.db import migrations
from compliance.service.compliance_report_version_service import ComplianceReportVersionService
from compliance.models import ComplianceReport, CompliancePeriod
from reporting.models import ReportVersion
import logging
from django.conf import settings

logger = logging.getLogger(__name__)


def generate_compliance_reports_from_emission_reports():
    # Only generate compliance reports for the latest submitted version of reports from the 2024 reporting year for regulated operations
    report_versions_to_process = ReportVersion.objects.select_related('report', 'report_operation').filter(
        report__reporting_year_id=2024,
        report_operation__registration_purpose__in=[
            'OBPS Regulated Operation',
            'New Entrant Operation',
            'Opted-in Operation',
        ],
        is_latest_submitted=True,
    )
    for rv in report_versions_to_process:
        if not (
            ComplianceReport.objects.filter(
                report_id=rv.report_id,
            )
        ).exists():
            new_compliance_report = ComplianceReport.objects.create(
                report=rv.report,
                compliance_period=CompliancePeriod.objects.get(reporting_year=2024),
            )
            ComplianceReportVersionService.create_compliance_report_version(new_compliance_report, rv.id)
        else:
            logger.info(f"Compliance report already exists for report id {rv.report_id}")


def perform_migration(apps, schema_editor):
    # Only run this migration in production
    if settings.ENVIRONMENT == "prod":
        generate_compliance_reports_from_emission_reports()
    else:
        pass


def revert_perform_migration(apps, schema_editor):
    """
    Remove generated compliance reports
    """
    ComplianceReport = apps.get_model("compliance", "ComplianceReport")

    ComplianceReport.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0029_alter_compliancechargerate_reporting_year'),
    ]

    operations = [migrations.RunPython(perform_migration, revert_perform_migration)]
