# Generated by Django 5.1.15 on 2026-03-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0031_V5_3_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancepenalty',
            name='invoice_number',
            field=models.CharField(
                blank=True,
                db_comment='The invoice number for the related elicensing invoice. Populated immediately on invoice creation in elicensing to ensure the link is not lost between invoice creation in elicensing and the refresh function that creates the elicensing_invoice record in the erc data.',
                null=True,
            ),
        ),
    ]
