# Generated by Django 5.1.15 on 2026-03-12 15:35

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0034_V5_4_2'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='complianceearnedcredit',
            name='populate_analyst_submission_info',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='complianceearnedcredit',
            trigger=pgtrigger.compiler.Trigger(
                name='populate_analyst_submission_info',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n                    -- Populate submission info whenever the analyst comment changes\n                    if (old.analyst_comment is distinct from new.analyst_comment)\n                        or (old.analyst_suggestion is distinct from new.analyst_suggestion) then\n                        new.analyst_submitted_date = current_date;\n                        new.analyst_submitted_by_id = (select nullif(current_setting('my.guid', true), ''));\n                    end if;\n                    return new;\n                ",
                    hash='e1f0a467ad70e5e993e588cf0b09c0ff1aea4f37',
                    operation='UPDATE',
                    pgid='pgtrigger_populate_analyst_submission_info_be756',
                    table='erc"."compliance_earned_credit',
                    when='BEFORE',
                ),
            ),
        ),
    ]
