# Generated by Django 5.1.15 on 2026-03-13 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0035_V5_4_3'),
    ]

    operations = []
