# Generated by Django 5.1.15 on 2026-03-31 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0041_compliancepenalty_invoice_number'),
    ]

    operations = []
