# Generated by Django 5.1.15 on 2026-04-28 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0043_V5_8_0'),
    ]

    operations = []
