# Generated by Django 5.1.15 on 2026-05-14 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0045_V5_10_0'),
    ]

    operations = []
