# Generated by Django 5.1.15 on 2026-06-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0046_V5_11_0'),
    ]

    operations = []
