# Generated by Django 5.1.15 on 2026-06-11 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0048_V5_13_0'),
    ]

    operations = []
