# Generated by Django 5.1.15 on 2026-06-12 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0049_V5_13_1'),
        ('registration', '0183_update_registration_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancechargerate',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='compliancechargerate',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='compliancechargerate',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='compliancechargerate',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='compliancechargerate',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='compliancechargerate',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='complianceearnedcredit',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='complianceearnedcredit',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='complianceearnedcredit',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='complianceearnedcredit',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='complianceearnedcredit',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='complianceearnedcredit',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='complianceobligation',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='complianceobligation',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='complianceobligation',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='complianceobligation',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='complianceobligation',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='complianceobligation',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='compliancepenalty',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='compliancepenalty',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='compliancepenalty',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='compliancepenalty',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='compliancepenalty',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='compliancepenalty',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='compliancepenaltyaccrual',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='compliancepenaltyaccrual',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='compliancepenaltyaccrual',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='compliancepenaltyaccrual',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='compliancepenaltyaccrual',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='compliancepenaltyaccrual',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='compliancepenaltyrate',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='compliancepenaltyrate',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='compliancepenaltyrate',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='compliancepenaltyrate',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='compliancepenaltyrate',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='compliancepenaltyrate',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='complianceperiod',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='complianceperiod',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='complianceperiod',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='complianceperiod',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='complianceperiod',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='complianceperiod',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='compliancereport',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='compliancereport',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='compliancereport',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='compliancereport',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='compliancereport',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='compliancereport',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='compliancereportversion',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='compliancereportversion',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='compliancereportversion',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='compliancereportversion',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='compliancereportversion',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='compliancereportversion',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='compliancereportversionmanualhandling',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='compliancereportversionmanualhandling',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='compliancereportversionmanualhandling',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='compliancereportversionmanualhandling',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='compliancereportversionmanualhandling',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='compliancereportversionmanualhandling',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='elicensingadjustment',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='elicensingadjustment',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='elicensingadjustment',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='elicensingadjustment',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='elicensingadjustment',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='elicensingadjustment',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='elicensingclientoperator',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='elicensingclientoperator',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='elicensingclientoperator',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='elicensingclientoperator',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='elicensingclientoperator',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='elicensingclientoperator',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='elicensinginvoice',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='elicensinginvoice',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='elicensinginvoice',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='elicensinginvoice',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='elicensinginvoice',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='elicensinginvoice',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='elicensinglineitem',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='elicensinglineitem',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='elicensinglineitem',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='elicensinglineitem',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='elicensinglineitem',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='elicensinglineitem',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='elicensingpayment',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='elicensingpayment',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_archived',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='elicensingpayment',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='elicensingpayment',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_created',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='elicensingpayment',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='elicensingpayment',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)s_updated',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='historicalcomplianceearnedcredit',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='historicalcomplianceearnedcredit',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='historicalcomplianceearnedcredit',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='historicalcomplianceearnedcredit',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='historicalcomplianceearnedcredit',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='historicalcomplianceearnedcredit',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='historicalcomplianceobligation',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                db_comment='Timestamp with timezone of when the record was archived (soft-deleted). Null if the record is active',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='historicalcomplianceobligation',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who archived (soft-deleted) the record. Null if the record is active. Foreign key to erc.user',
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='historicalcomplianceobligation',
            name='created_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was created', null=True
            ),
        ),
        migrations.AlterField(
            model_name='historicalcomplianceobligation',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who created the record. Foreign key to erc.user',
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='registration.user',
            ),
        ),
        migrations.AlterField(
            model_name='historicalcomplianceobligation',
            name='updated_at',
            field=models.DateTimeField(
                blank=True, db_comment='Timestamp with timezone of when the record was last updated', null=True
            ),
        ),
        migrations.AlterField(
            model_name='historicalcomplianceobligation',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                db_comment='ID of the user who last updated the record. Foreign key to erc.user',
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='registration.user',
            ),
        ),
    ]
