# Generated by Django 5.1.15 on 2026-07-06 17:37

import common.lib.pgtrigger.core
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0053_V5_15_0'),
        ('registration', '0185_V5_15_0'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='compliancepenaltyrate',
            constraint=models.UniqueConstraint(
                condition=common.lib.pgtrigger.core.Q(('is_current_rate', True)),
                fields=('is_current_rate',),
                name='unique_is_current_rate_true_per_compliance_penalty_rate',
            ),
        ),
    ]
