# Generated by Django 5.1.15 on 2026-07-03 16:23

from django.db import migrations

OBLIGATION_FULLY_MET = "Obligation fully met"
OBLIGATION_MET_INTEREST_NOT_PAID = "Obligation Met - Interest not paid"


def reclassify_fully_met_with_unpaid_interest(apps, schema_editor):
    """
    Existing rows were marked OBLIGATION_FULLY_MET as soon as the fee balance hit $0,
    even if FAA interest was still outstanding. Reclassify those rows to the
    new OBLIGATION_MET_INTEREST_NOT_PAID status.
    """
    ComplianceReportVersion = apps.get_model("compliance", "ComplianceReportVersion")
    ComplianceReportVersion.objects.filter(
        status=OBLIGATION_FULLY_MET,
        obligation__elicensing_invoice__is_void=False,
        obligation__elicensing_invoice__invoice_interest_balance__gt=0,
    ).update(status=OBLIGATION_MET_INTEREST_NOT_PAID)


def revert_to_obligation_fully_met(apps, schema_editor):
    ComplianceReportVersion = apps.get_model("compliance", "ComplianceReportVersion")
    ComplianceReportVersion.objects.filter(status=OBLIGATION_MET_INTEREST_NOT_PAID).update(status=OBLIGATION_FULLY_MET)


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0054_alter_compliancereportversion_status"),
    ]

    operations = [
        migrations.RunPython(
            reclassify_fully_met_with_unpaid_interest,
            revert_to_obligation_fully_met,
            elidable=True,
        ),
    ]
