# Generated by Django 5.1.15 on 2026-07-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0054_V5_15_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancereportversion',
            name='status',
            field=models.CharField(
                choices=[
                    ('Obligation not met', 'Obligation Not Met'),
                    ('Obligation Met - Interest not paid', 'Obligation Met Interest Not Paid'),
                    ('Obligation fully met', 'Obligation Fully Met'),
                    ('Obligation pending invoice creation', 'Obligation Pending Invoice Creation'),
                    ('Earned credits', 'Earned Credits'),
                    ('No obligation or earned credits', 'No Obligation Or Earned Credits'),
                    ('Requires manual handling', 'Requires Manual Handling'),
                    ('Superceded', 'Superceded'),
                ],
                db_comment='The status of this compliance report version. Options: [Obligation not met, Obligation Met - Interest not paid, Obligation fully met, Earned credits, No obligation or earned credits, Requires manual handling]',
                max_length=100,
            ),
        ),
    ]
