# Generated by Django 5.1.15 on 2026-07-14 22:16

import common.lib.pgtrigger.core
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0056_backfill_obligation_met_interest_not_paid'),
        ('registration', '0186_V5_15_1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compliancepenaltyrate',
            options={},
        ),
        migrations.RemoveField(
            model_name='compliancepenaltyrate',
            name='compliance_period',
        ),
        migrations.AddConstraint(
            model_name='compliancepenaltyrate',
            constraint=models.UniqueConstraint(
                condition=common.lib.pgtrigger.core.Q(('is_current_rate', True)),
                fields=('is_current_rate',),
                name='unique_is_current_rate_true_per_compliance_penalty_rate',
            ),
        ),
    ]
