# Generated by Django 5.1.15 on 2026-07-14 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0057_V5_16_0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancereportversionmanualhandling',
            name='context',
            field=models.CharField(
                choices=[
                    (
                        'obligation_refund_pool_cash',
                        'Obligation is fully paid and the refund pool contains refundable cash.',
                    ),
                    ('earned_credits_previously_approved', 'Earned credits have been previously approved.'),
                    (
                        'credits_over_allowed_percentage',
                        'A supplementary decrease pushed the applied compliance units over the allowed percentage.',
                    ),
                ],
                db_comment='Reason for requiring manual handling',
                max_length=100,
            ),
        ),
    ]
