# Generated by Django 5.1.15 on 2026-07-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0058_alter_compliancereportversionmanualhandling_context'),
        ('registration', '0187_V5_16_0'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='elicensingadjustment',
            name='supp_reasons_require_supp_version',
        ),
        migrations.AlterField(
            model_name='elicensingadjustment',
            name='reason',
            field=models.CharField(blank=True, db_comment='Reason for adjustment in elicensing', null=True),
        ),
        migrations.AddConstraint(
            model_name='elicensingadjustment',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        'reason__in',
                        ['Supplementary Report Adjustment', 'Supplementary Report Adjustment to Void Invoice'],
                    ),
                    ('supplementary_compliance_report_version__isnull', True),
                    _negated=True,
                ),
                name='supp_reasons_require_supp_version',
                violation_error_message='An adjustment with a supplementary report reason requires a supplementary report version',
            ),
        ),
    ]
