# Generated by Django 5.1.15 on 2026-07-22 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0059_remove_elicensingadjustment_supp_reasons_require_supp_version_and_more'),
    ]

    operations = []
