# Generated by Django 5.2.16 on 2026-07-29 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0062_add_compliancepenaltyrates'),
    ]

    operations = []
