# Generated by Django 5.2.16 on 2026-08-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0064_V5_18_1'),
        ('registration', '0190_V5_18_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elicensinglineitem',
            name='line_item_type',
            field=models.CharField(
                choices=[('Fee', 'Fee'), ('Interest', 'Interest')],
                db_comment='The type of line item from elicensing.',
                default='Fee',
            ),
        ),
        migrations.AddConstraint(
            model_name='elicensinglineitem',
            constraint=models.UniqueConstraint(
                condition=models.Q(('line_item_type', 'Fee')),
                fields=('elicensing_invoice',),
                name='elicensing_line_item_unique_fee_line_item_per_invoice',
                violation_error_message='A Fee line item already exists for this invoice.',
            ),
        ),
    ]
