# Generated by Django 6.1.1 on 2026-09-16 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0069_V5_21_0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancereportversionmanualhandling',
            name='context',
            field=models.CharField(
                choices=[
                    (
                        'obligation_refund_pool_cash',
                        'Obligation is fully paid and the refund pool contains refundable cash.',
                    ),
                    ('earned_credits_previously_approved', 'Earned credits have been previously approved.'),
                    (
                        'credits_over_allowed_percentage',
                        'A supplementary decrease pushed the applied compliance units over the allowed percentage.',
                    ),
                    (
                        'compliance_units_applied_to_voided_invoice',
                        'A supplementary decrease voided an invoice that had compliance units applied to it.',
                    ),
                ],
                db_comment='Reason for requiring manual handling',
                max_length=100,
            ),
        ),
    ]
