# Generated by Django 6.1.1 on 2026-09-22 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0070_alter_compliancereportversionmanualhandling_context'),
    ]

    operations = []
