# Generated by Django 6.1.1 on 2026-10-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0071_V5_22_0'),
        ('registration', '0197_V5_22_0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elicensinglineitem',
            name='guid',
            field=models.UUIDField(
                blank=True,
                db_comment='The guid of the line item from elicensing. Automatically generated interest records will have an empty guid.',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='elicensinglineitem',
            name='line_item_type',
            field=models.CharField(
                choices=[('Fee', 'Fee'), ('Interest', 'Interest')],
                db_comment='The type of line item from elicensing.',
                default='Fee',
            ),
        ),
        migrations.AddConstraint(
            model_name='elicensinglineitem',
            constraint=models.UniqueConstraint(
                condition=models.Q(('line_item_type', 'Fee')),
                fields=('elicensing_invoice',),
                name='elicensing_line_item_unique_fee_line_item_per_invoice',
                violation_error_message='A Fee line item already exists for this invoice.',
            ),
        ),
    ]
