{{- if .Values.enable_pdb }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "cas-bciers.fullname" . }}-reporting-frontend-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: cas-bciers
      component: reporting-frontend
{{- end }}
