# Generated by Django 4.2.8 on 2024-04-11 23:13

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='EmailNotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'name',
                    models.CharField(
                        db_comment='Name of the email template as a unique identifier', max_length=255, unique=True
                    ),
                ),
                ('subject', models.CharField(db_comment='Subject of the email template', max_length=255)),
                ('body', models.TextField(db_comment='Body of the email template')),
            ],
            options={
                'db_table': 'common"."email_notification_template',
                'db_table_comment': 'Stores email templates for notifications',
            },
        ),
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                (
                    'transaction_id',
                    models.UUIDField(
                        db_comment='Transaction identifier for the email message in CHES API',
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'message_id',
                    models.UUIDField(db_comment='Message identifier for the email message in CHES API', editable=False),
                ),
                (
                    'recipients_email',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.EmailField(max_length=255),
                        db_comment='List of email addresses to send the email to',
                        size=None,
                    ),
                ),
                (
                    'template',
                    models.ForeignKey(
                        db_comment='Email template to use for the email notification',
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='email_notifications',
                        to='common.emailnotificationtemplate',
                    ),
                ),
            ],
            options={
                'db_table': 'common"."email_notification',
                'db_table_comment': 'Stores email notifications after they have been sent',
            },
        ),
    ]
