# Generated by Django 4.2.8 on 2024-04-11 23:15

from django.db import migrations


def create_admin_access_request_email_template(apps, schema_editor):
    """
    Create an EmailNotificationTemplate for the Admin Access Request Confirmation email
    """

    EmailNotificationTemplate = apps.get_model('common', 'EmailNotificationTemplate')
    EmailNotificationTemplate.objects.create(
        name='Admin Access Request Confirmation',
        subject='BCIERS Receipt Acknowledgement – Administrator access request to {{ operator_legal_name }}',
        body='''
            <p style="text-align: center;">Province of British Columbia</p>
            <p style="text-align: center;">B.C. Industrial Emissions Reporting System (BCIERS)</p><br>
            <p>Dear {{ external_user_full_name }},</p><br>
            <p>Your administrator access request to {{ operator_legal_name }} in BCIERS has been received by the Climate Action Secretariat (CAS).</p>
            <p>CAS is reviewing your request. Please allow 3-5 business days to process this request. Once a decision is made, you may expect a notification email.</p><br>
            <p>If you have any questions, please contact our support team at <a href="mailto:GHGRegulator@gov.bc.ca">GHGRegulator@gov.bc.ca.</a></p><br>
            <p>Sent to: {{ external_user_email_address }}</p>
            <p>On behalf of the Climate Action Secretariat</p>
        ''',
    )


def reverse_create_admin_access_request_email_template(apps, schema_editor):
    """
    Reverse the creation of the EmailNotificationTemplate for the Admin Access Request Confirmation email
    """

    EmailNotificationTemplate = apps.get_model('common', 'EmailNotificationTemplate')
    EmailNotificationTemplate.objects.get(name='Admin Access Request Confirmation').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_admin_access_request_email_template,
            reverse_create_admin_access_request_email_template,
            elidable=True,
        ),
    ]
