# Generated by Django 4.2.8 on 2024-04-17 21:02

from django.db import migrations


def create_operator_access_request_email_notification_templates(apps, schema_editor):
    """
    Create EmailNotificationTemplates for the Access Request to an existing operator with an existing admin
    """

    EmailNotificationTemplate = apps.get_model('common', 'EmailNotificationTemplate')
    EmailNotificationTemplate.objects.create(
        name='Operator With Admin Access Request Confirmation',
        subject='BCIERS Receipt Acknowledgement – Access request to {{ operator_legal_name }}',
        body='''
            <p style="text-align: center;">Province of British Columbia</p>
            <p style="text-align: center;">B.C. Industrial Emissions Reporting System (BCIERS)</p><br>
            <p>Dear {{ external_user_full_name }},</p><br>
            <p>Your access request to {{ operator_legal_name }} in BCIERS has been received.</p>
            <p>An operation representative with administrator access to {{ operator_legal_name }} should review your request. Once a decision is made, you may expect a notification email.</p><br>
            <p>If you have any questions, please contact our support team at <a href="mailto:GHGRegulator@gov.bc.ca">GHGRegulator@gov.bc.ca.</a></p><br>
            <p>Sent to: {{ external_user_email_address }}</p>
            <p>On behalf of the Climate Action Secretariat</p>
        ''',
    )
    EmailNotificationTemplate.objects.create(
        name='Operator With Admin Access Request Approved',
        subject='BCIERS Approval Notification – Access request to {{ operator_legal_name }}',
        body='''
            <p style="text-align: center;">Province of British Columbia</p>
            <p style="text-align: center;">B.C. Industrial Emissions Reporting System (BCIERS)</p><br>
            <p>Dear {{ external_user_full_name }},</p><br>
            <p>Your access request to {{ operator_legal_name }} in BCIERS has been approved by an operation representative with administrator access to {{ operator_legal_name }}.</p>
            <p>Please log back into <a href="https://registration.industrialemissions.gov.bc.ca">BCIERS</a> to perform additional tasks, such as starting an application for a BC OBPS Regulated Operation ID.</p><br>
            <p>If you have any questions, please contact our support team at <a href="mailto:GHGRegulator@gov.bc.ca">GHGRegulator@gov.bc.ca.</a></p><br>
            <p>Sent to: {{ external_user_email_address }}</p>
            <p>On behalf of the Climate Action Secretariat</p>
        ''',
    )
    EmailNotificationTemplate.objects.create(
        name='Operator With Admin Access Request Declined',
        subject='BCIERS Decline Notification – Access request to {{ operator_legal_name }}',
        body='''
            <p style="text-align: center;">Province of British Columbia</p>
            <p style="text-align: center;">B.C. Industrial Emissions Reporting System (BCIERS)</p><br>
            <p>Dear {{ external_user_full_name }},</p><br>
            <p>Your access request to {{ operator_legal_name }} in BCIERS has been declined by an operation representative with administrator access to {{ operator_legal_name }}.</p><br>
            <p>If you have any questions, please contact our support team at <a href="mailto:GHGRegulator@gov.bc.ca">GHGRegulator@gov.bc.ca.</a></p><br>
            <p>Sent to: {{ external_user_email_address }}</p>
            <p>On behalf of the Climate Action Secretariat</p>
        ''',
    )


def reverse_create_operator_access_request_email_notification_templates(apps, schema_editor):
    """
    Reverse the creation of the EmailNotificationTemplates for the Access Request to an existing operator with an existing admin
    """

    EmailNotificationTemplate = apps.get_model('common', 'EmailNotificationTemplate')
    EmailNotificationTemplate.objects.filter(
        name__in=[
            'Operator With Admin Access Request Confirmation',
            'Operator With Admin Access Request Approved',
            'Operator With Admin Access Request Declined',
        ],
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_admin_access_request_email_templates'),
    ]

    operations = [
        migrations.RunPython(
            create_operator_access_request_email_notification_templates,
            reverse_create_operator_access_request_email_notification_templates,
            elidable=True,
        ),
    ]
