# Generated by Django 4.2.8 on 2024-05-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_new_operator_and_admin_access_request_email_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotificationtemplate',
            name='brianna',
            field=models.TextField(db_comment='Body of the email template', default='dddd'),
            preserve_default=False,
        ),
    ]
