# Generated by Django 4.2.8 on 2024-05-14 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_operation_opt_in_and_boro_id_email_templates'),
    ]

    operations = []
