# Generated by Django 4.2.8 on 2024-05-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_V1_5_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data', models.JSONField()),
            ],
            options={
                'db_table': 'common"."dashboard_data',
                'db_table_comment': 'The JSON information for dashboard navigation tiles.',
            },
        ),
    ]
