# Generated by Django 4.2.8 on 2024-05-29 16:12
from django.db import migrations

def load_dashboard_fixtures(apps, schema_editor):
    from django.core.management import call_command

    fixture_files = [
        'common/fixtures/dashboard/bciers/external.json',
        'common/fixtures/dashboard/bciers/internal.json',
        'common/fixtures/dashboard/registration/operation/external.json',
        'common/fixtures/dashboard/registration/external.json',
        'common/fixtures/dashboard/registration/internal_admin.json',
        'common/fixtures/dashboard/registration/internal.json',
        'common/fixtures/dashboard/reporting/external.json',
        'common/fixtures/dashboard/reporting/internal.json',
    ]

    for fixture in fixture_files:
        call_command('loaddata', fixture)

class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_dashboarddata'), 
    ]

    operations = [
        migrations.RunPython(load_dashboard_fixtures),
    ]