# Generated by Django 5.0.6 on 2024-05-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_load_dashboard_fixtures'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='dashboarddata',
            table_comment='The JSON information for dashboard navigation tiles by app and ID type.',
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='data',
            field=models.JSONField(db_comment='JSON representation of dashboard navigation tiles.'),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='name',
            field=models.CharField(
                db_comment='Name of the dashboard by app and ID type used as a friendly unique identifier.',
                max_length=100,
                unique=True,
            ),
        ),
    ]
