# Generated by Django 5.0.7 on 2024-08-01 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_update_dashboard_data'),
    ]

    operations = []
