# Generated by Django 5.0.7 on 2024-08-07 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_V1_7_0'),
    ]

    operations = []
