# Generated by Django 5.0.8 on 2024-09-04 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_update_dashboard_data'),
    ]

    operations = []
