# Generated by Django 5.0.9 on 2024-10-23 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_update_dashboard_data'),
    ]

    operations = []
