# Generated by Django 5.0.9 on 2024-11-06 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_update_dashboard_data'),
    ]

    operations = []
