# Generated by Django 5.0.8 on 2024-11-15 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_V1_13_0'),
    ]

    operations = []
