# Generated by Django 5.0.9 on 2024-11-27 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_V1_14_0'),
    ]

    operations = []
