# Generated by Django 5.0.9 on 2024-12-18 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0027_V1_16_0'),
    ]

    operations = []
