# Generated by Django 5.0.11 on 2025-01-30 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0031_V1_19_0'),
    ]

    operations = []
