# Generated by Django 5.0.11 on 2025-02-05 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0033_update_dashboard_data'),
    ]

    operations = []
