# Generated by Django 5.0.11 on 2025-02-19 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0034_V1_21_0'),
    ]

    operations = []
