# Generated by Django 5.0.11 on 2025-02-28 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0035_V1_22_0'),
    ]

    operations = []
