# Generated by Django 5.0.11 on 2025-03-03 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0036_V1_23_0'),
    ]

    operations = []
