# Generated by Django 5.0.13 on 2025-03-13 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0037_V1_23_1'),
    ]

    operations = []
