# Generated by Django 5.0.13 on 2025-03-17 19:02

from django.db import migrations
from common.utils import reset_dashboard_data

def reset_dashboard_data_fn(_, schema_editor):
    reset_dashboard_data()

class Migration(migrations.Migration):

    dependencies = [
        ('common', '0038_V1_24_0'),
    ]

    operations = [
        migrations.RunPython(reset_dashboard_data_fn, elidable=True),
    ]