# Generated by Django 5.0.14 on 2025-04-22 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0045_V2_3_0'),
    ]

    operations = []
