# Generated by Django 5.0.13 on 2025-03-28 00:15

from django.db import migrations


def create_boro_id_issuance_email_notification_template(apps, schema_editor):
    """
    Create EmailNotificationTemplate for the Notification of Issuance of BORO ID
    """
    EmailNotificationTemplate = apps.get_model('common', 'EmailNotificationTemplate')
    EmailNotificationTemplate.objects.create(
        name='BORO ID Issuance',
        subject='BCIERS Notification - BORO ID issued for {{ operation_name }} of {{ operator_legal_name }}',
        body='''
            <p style="text-align: center;">Province of British Columbia</p>
            <p style="text-align: center;">B.C. Industrial Emissions Reporting System (BCIERS)</p><br>
            <p>Dear {{ external_user_full_name }},</p><br>
            <p>{{ operation_name }} of {{ operator_legal_name }} has been issued a B.C. OBPS Regulated Operation ID (BORO ID) in BCIERS.</p>
            <p>Please log back into <a href="https://industrialemissions.gov.bc.ca">BCIERS</a> to see {{ operation_name }}'s assigned BORO ID. This BORO ID is required to complete a carbon tax exemption certificate, which is available on <a href="https://www2.gov.bc.ca/gov/content/taxes/sales-taxes/motor-fuel-carbon-tax/business/exemptions/obps-carbon-tax-exemption">this webpage</a>.</p><br>
            <p>If you have any questions, please contact our support team at <a href="mailto:GHGRegulator@gov.bc.ca">GHGRegulator@gov.bc.ca.</a></p><br>
            <p>Sent to: {{ external_user_email_address }}</p>
            <p>On behalf of the Climate Action Secretariat</p>
        ''',
    )


def reverse_create_boro_id_issuance_email_notification_template(apps, schema_editor):
    """
    Reverse the creation of the EmailNotificationTemplate for the Notification of Issuance of BORO ID
    """
    EmailNotificationTemplate = apps.get_model('common', 'EmailNotificationTemplate')
    EmailNotificationTemplate.objects.filter(name__in=['BORO ID Issuance']).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('common', '0045_V2_3_0'),
    ]

    operations = [
        migrations.RunPython(
            create_boro_id_issuance_email_notification_template,
            reverse_create_boro_id_issuance_email_notification_template,
            elidable=True,
        )
    ]
