# Generated by Django 5.0.13 on 2025-04-02 17:01

from django.db import migrations


def update_admin_access_request_email_notification_templates(apps, schema_editor):
    """
    Update EmailNotificationTemplates for the admin Access Request workflow
    """

    EmailNotificationTemplate = apps.get_model('common', 'EmailNotificationTemplate')

    EmailNotificationTemplate.objects.filter(name='Admin Access Request Confirmation').update(
        subject='BCIERS Receipt Acknowledgement – Access Request to {{ operator_legal_name }}',
        body='''
            <p style="text-align: center;">Province of British Columbia</p>
            <p style="text-align: center;">B.C. Industrial Emissions Reporting System (BCIERS)</p><br>
            <p>Dear {{ external_user_full_name }},</p><br>
            <p>Your request to receive access to {{ operator_legal_name }} in BCIERS has been received by the Climate Action Secretariat (CAS).  </p>
            <p>CAS is reviewing your request and will contact you within 3 business days to provide a status update.</p><br>
            <p>If you have any questions, please contact our support team at <a href="mailto:GHGRegulator@gov.bc.ca">GHGRegulator@gov.bc.ca.</a></p><br>
            <p>Sent to: {{ external_user_email_address }}</p>
            <p>On behalf of the Climate Action Secretariat</p>
        ''',
    )

    EmailNotificationTemplate.objects.filter(name='Admin Access Request Approved').update(
        subject='BCIERS Approval Notification – Access request to {{ operator_legal_name }}',
        body='''
            <p style="text-align: center;">Province of British Columbia</p>
            <p style="text-align: center;">B.C. Industrial Emissions Reporting System (BCIERS)</p><br>
            <p>Dear {{ external_user_full_name }},</p><br>
            <p>Your request to receive access to {{ operator_legal_name }} in BCIERS has been approved by the Climate Action Secretariat. You may now log back into <a href="https://registration.industrialemissions.gov.bc.ca">BCIERS</a> to register your operation(s).</p>
            <p>You have been granted administrator access for {{ operator_legal_name }}. This user role allows you to grant access and assign user roles to other individuals from your organization.</p><br>
            <p>If you have any questions, please contact our support team at <a href="mailto:GHGRegulator@gov.bc.ca">GHGRegulator@gov.bc.ca.</a></p><br>
            <p>Sent to: {{ external_user_email_address }}</p>
            <p>On behalf of the Climate Action Secretariat</p>
        ''',
    )
    EmailNotificationTemplate.objects.filter(name='Admin Access Request Declined').update(
        subject='BCIERS Decline Notification – Access request to {{ operator_legal_name }}',
        body='''
            <p style="text-align: center;">Province of British Columbia</p>
            <p style="text-align: center;">B.C. Industrial Emissions Reporting System (BCIERS)</p><br>
            <p>Dear {{ external_user_full_name }},</p><br>
            <p>Your request to receive access to {{ operator_legal_name }} in BCIERS has been declined by the Climate Action Secretariat.
            </p><br>
            <p>f you have any questions, please contact our support team at <a href="mailto:GHGRegulator@gov.bc.ca">GHGRegulator@gov.bc.ca.</a></p><br>
            <p>Sent to: {{ external_user_email_address }}</p>
            <p>On behalf of the Climate Action Secretariat</p>
        ''',
    )


class Migration(migrations.Migration):
    dependencies = [
        ('common', '0047_boro_id_issuance_email_template'),
    ]

    operations = [
        migrations.RunPython(
            update_admin_access_request_email_notification_templates,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        )
    ]
