# Generated by Django 5.0.14 on 2025-05-26 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0056_update_dashboard_data'),
    ]

    operations = []
