# Generated by Django 5.0.14 on 2025-06-05 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0059_V3_5_0'),
    ]

    operations = []
