# Generated by Django 5.1.10 on 2025-06-26 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0063_V3_8_1'),
    ]

    operations = []
