# Generated by Django 5.1.10 on 2025-07-18 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0065_V3_10_0'),
    ]

    operations = []
