# Generated by Django 5.1.10 on 2025-07-24 16:35

from django.db import migrations
from common.utils import reset_dashboard_data


def reset_dashboard_data_fn(_, schema_editor):
    reset_dashboard_data()


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0067_V3_12_0"),
    ]

    operations = [
        migrations.RunPython(reset_dashboard_data_fn, elidable=True),
    ]
