# Generated by Django 5.1.10 on 2025-08-15 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0070_V3_15_0'),
    ]

    operations = []
