# Generated by Django 5.1.10 on 2025-08-27 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0073_update_dashboard_data'),
    ]

    operations = []
