# Generated by Django 5.1.10 on 2025-09-08 21:57

from django.db import migrations


def create_no_obligation_no_credits_notice_email_template(apps, schema_editor):
    EmailNotificationTemplate = apps.get_model('common', 'EmailNotificationTemplate')
    EmailNotificationTemplate.objects.create(
        name='No Obligation No Earned Credits Generated',
        subject='BCIERS Notification – Compliance Obligation Met',
        body='''
            <p style="text-align: center;">Province of British Columbia</p>
            <p style="text-align: center;">B.C. Industrial Emissions Reporting System (BCIERS)</p>
            <br>
            <p>Dear {{ operator_legal_name }},</p>
            <br>
            <p>Based on the information submitted in <b>{{operation_name}}</b>’s  Annual Report for the {{ compliance_year }} compliance period, you have met your compliance obligation with no excess emissions or earned credits.  You can now review your records in the BC Industrial Emissions Reporting System (BCIERS). There is no further action required at this time.</p>
            <p>To review your compliance obligation, including how it was calculated, please log-into BCIERS at <a
              href="https://industrialemissions.gov.bc.ca/onboarding">https://industrialemissions.gov.bc.ca/onboarding</a>.</p>
            <p><em>Please do not reply to this email. This email is auto-generated and sent from an unmonitored address. If you have
              any questions, or need further assistance, please reach out to our support team at <a href="mailto:GHGRegulator@gov.bc.ca">GHGRegulator@gov.bc.ca</a>.</em>
            </p>
            <br>
            <p>Best Regards,</p>
            <p>Ministry of Energy and Climate Solutions</p>
            <p>Email: <a href="mailto:GHGRegulator@gov.bc.ca">GHGRegulator@gov.bc.ca</a></p>
            <p>Website: <a href="https://www2.gov.bc.ca/gov/content/environment/climate-change/industry/bc-output-based-pricing-system">BC
              Government Website Link</a>
            </p>
        ''',
    )


def reverse_no_obligation_no_credits_notice_email_template(apps, schema_editor):
    EmailNotificationTemplate = apps.get_model('common', 'EmailNotificationTemplate')
    EmailNotificationTemplate.objects.filter(name='No Obligation No Earned Credits Generated').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('common', '0076_notice_of_earned_credits_generated_notification_email_template'),
    ]

    operations = [
        migrations.RunPython(
            create_no_obligation_no_credits_notice_email_template,
            reverse_no_obligation_no_credits_notice_email_template,
            elidable=True,
        )
    ]
