# Generated by Django 5.1.10 on 2025-09-09 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0077_notice_of_no_obligation_no_credits_generated_notification_email_template'),
    ]

    operations = []
