# Generated by Django 5.1.12 on 2025-09-15 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0079_update_internal_dashboard_data'),
    ]

    operations = []
