# Generated by Django 5.1.12 on 2025-09-17 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0081_notice_of_obligation_generated_notification_email_template'),
    ]

    operations = []
