# Generated by Django 5.1.10 on 2025-09-18 21:57

from django.db import migrations


def create_credits_requested_email_template(apps, schema_editor):
    EmailNotificationTemplate = apps.get_model('common', 'EmailNotificationTemplate')
    EmailNotificationTemplate.objects.create(
        name='Notice of Credits Requested',
        subject='BCIERS Notification – Earned Credits Requested ',
        body='''
            <p style="text-align: center;">Province of British Columbia</p>
            <p style="text-align: center;">B.C. Industrial Emissions Reporting System (BCIERS)</p>
            <br>
            <p>Hi there,</p>
            <br>
            <p><b>{{operator_name}}</b> has requested issuance of earned credits on behalf of <b>{{operation_name}}</b>. Please log-in to <a href="https://industrialemissions.gov.bc.ca/onboarding">BCIERS</a> to see the details of this request.
            </p>
            <br>
            <p>Best Regards,</p>
            <p>Ministry of Energy and Climate Solutions</p>
            <p>Email: <a href="mailto:GHGRegulator@gov.bc.ca">GHGRegulator@gov.bc.ca</a></p>
            <p>Website: <a href="https://www2.gov.bc.ca/gov/content/environment/climate-change/industry/bc-output-based-pricing-system">BC
              Government Website Link</a>
            </p>
        ''',
    )


def reverse_credits_requested_email_template(apps, schema_editor):
    EmailNotificationTemplate = apps.get_model('common', 'EmailNotificationTemplate')
    EmailNotificationTemplate.objects.filter(name='Notice of Credits Requested').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('common', '0082_V3_20_0'),
    ]

    operations = [
        migrations.RunPython(
            create_credits_requested_email_template,
            reverse_credits_requested_email_template,
            elidable=True,
        )
    ]
