# Generated by Django 5.1.10 on 2025-10-07 21:57

from django.db import migrations


def create_obligation_met_template(apps, schema_editor):
    EmailNotificationTemplate = apps.get_model('common', 'EmailNotificationTemplate')
    EmailNotificationTemplate.objects.create(
        name='Notice of Obligation Met',
        subject='BCIERS Notification – Compliance Obligation Met',
        body='''
            <p style="text-align: center;">Province of British Columbia</p>
            <p style="text-align: center;">B.C. Industrial Emissions Reporting System (BCIERS)</p>
            <br/>
            <p>Dear {{operator_legal_name}},</p>
            <br/>
            <p>This email confirms that the compliance obligation for <b>{{operation_name}}</b> based on its annual report for the {{compliance_period}} compliance period, has been met.
            </p>
            <br/>
            <p><em>Please do not reply to this email. This email is auto-generated. If you have any questions, or need further assistance, please reach out to our support team at <a href="mailto:GHGRegulator@gov.bc.ca">GHGRegulator@gov.bc.ca</a></em></p>
            <br/>
            <p>Best Regards,</p>
            <p>Ministry of Energy and Climate Solutions</p>
            <p>Email: <a href="mailto:GHGRegulator@gov.bc.ca">GHGRegulator@gov.bc.ca</a></p>
            <p>Website: <a href="https://www2.gov.bc.ca/gov/content/environment/climate-change/industry/bc-output-based-pricing-system">BC
              Government Website Link</a>
            </p>
        ''',
    )


def reverse_obligation_met_template(apps, schema_editor):
    EmailNotificationTemplate = apps.get_model('common', 'EmailNotificationTemplate')
    EmailNotificationTemplate.objects.filter(name='Notice of Obligation Met').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('common', '0091_reminder_of_obligation_due_email_template'),
    ]

    operations = [
        migrations.RunPython(
            create_obligation_met_template,
            reverse_obligation_met_template,
            elidable=True,
        )
    ]
