# Generated by Django 5.1.14 on 2025-11-14 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0095_notice_of_penalty_now_accruing_email_template'),
    ]

    operations = []
