# Generated by Django 5.1.10 on 2025-10-07 21:57

from django.db import migrations


def supplementary_report_submitted_after_deadline_template(apps, schema_editor):
    EmailNotificationTemplate = apps.get_model('common', 'EmailNotificationTemplate')
    EmailNotificationTemplate.objects.create(
        name='Supplementary Report Submitted after Deadline',
        subject='BCIERS Notification – Supplementary Report Submitted after Deadline',
        body='''
            <p style="text-align: center;">Province of British Columbia</p>
            <p style="text-align: center;">B.C. Industrial Emissions Reporting System (BCIERS)</p>
            <br/>
            <p>Dear {{operator_legal_name}},</p>
            <br/>
            <p>Thank you for submitting a supplementary report through the BC Industrial Emissions Reporting System (BCIERS).
            </p>
            <br/>
            <p>Because your supplementary report results in an increased amount of excess emissions, <b>you must meet an additional compliance obligation</b>. Based on the information submitted in <b>{{operation_name}}</b>’s supplementary report and the applicable compliance charge rate, an additional compliance obligation for excess emissions of {{tonnes_of_co2}} at an equivalent amount of {{outstanding_balance}} is now payable.   </p>
            <br/>
            <p><b>Because the supplementary report was submitted after the compliance obligation deadline</b>, the additional compliance obligation is subject to interest under the Greenhouse Gas Emission Administrative Penalty and Appeals Regulation (GGEAPAR). Interest is calculated at the prime lending rate + 3%, compounded monthly from the compliance obligation deadline of November 30, {{year_due}} and applies until you resolve the overdue obligation.</p>
            <br/><p>To review your compliance obligation and how it was calculated, please log-into BCIERS at <a
              href="https://industrialemissions.gov.bc.ca/onboarding">https://industrialemissions.gov.bc.ca/onboarding</a>.</p><br/>
            <p>To meet your compliance obligation:  </p>
            <ol>
            <li>Navigate to the Compliance module and click <em>My Compliance > Compliance Summaries</em>.</li>
            <li>Find your operation in the grid and click <em>Manage Obligation</em>.</li>
            </ol>
            <p>If you do not meet the additional compliance obligation <b>within 30 days</b>, the additional obligation will be subject to daily compounding penalties, as well as interest under the <i>Financial Administration Act</i> (FAA). We strongly encourage you to make your payment on time to avoid these additional charges. Please refer to the B.C. OBPS compliance module guidance document on our website for further information. </p><br/>
            <p><em>Please do not reply to this email. This email is auto-generated. If you have any questions, or need further assistance, please reach out to our support team at <a href="mailto:GHGRegulator@gov.bc.ca">GHGRegulator@gov.bc.ca</a></em></p>
            <br/>
            <p>Best Regards,</p>
            <p>Ministry of Energy and Climate Solutions</p>
            <p>Email: <a href="mailto:GHGRegulator@gov.bc.ca">GHGRegulator@gov.bc.ca</a></p>
            <p>Website: <a href="https://www2.gov.bc.ca/gov/content/environment/climate-change/industry/bc-output-based-pricing-system">BC
              Government Website Link</a>
            </p>
        ''',
    )


def reverse_supplementary_report_submitted_after_deadline_template(apps, schema_editor):
    EmailNotificationTemplate = apps.get_model('common', 'EmailNotificationTemplate')
    EmailNotificationTemplate.objects.filter(name='Supplementary Report Submitted after Deadline').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('common', '0095_notice_of_penalty_now_accruing_email_template'),
    ]

    operations = [
        migrations.RunPython(
            supplementary_report_submitted_after_deadline_template,
            reverse_supplementary_report_submitted_after_deadline_template,
            elidable=True,
        )
    ]
