# Generated by Django 5.1.14 on 2025-11-26 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0097_supplementary_report_submitted_after_deadline_template_template'),
    ]

    operations = []
