# Generated by Django 5.1.15 on 2025-12-03 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0099_update_dashboard_data'),
    ]

    operations = []
