# Generated by Django 5.1.15 on 2026-01-07 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0101_V4_6_1'),
    ]

    operations = []
