# Generated by Django 5.1.15 on 2026-02-04 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0105_V5_0_1'),
    ]

    operations = []
