# Generated by Django 5.1.15 on 2026-02-19 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0108_notice_of_penalty_after_compliance_met_email_template'),
    ]

    operations = []
