# Generated by Django 5.1.15 on 2026-03-04 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0112_notice_of_penalty_paid_email_template'),
    ]

    operations = []
