# Generated by Django 5.1.15 on 2026-03-04 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0113_V5_4_0'),
    ]

    operations = []
