# Generated by Django 5.1.15 on 2026-03-13 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0115_V5_4_2'),
    ]

    operations = []
