# Generated by Django 5.1.15 on 2026-03-31 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0118_V5_6_0'),
    ]

    operations = []
