# Generated by Django 5.1.15 on 2026-03-31 20:06

from django.db import migrations

OLD_URL = "https://www2.gov.bc.ca/assets/gov/environment/climate-change/ind/obps/guidance/bc_obps_guidance.pdf"
NEW_URL = "https://www2.gov.bc.ca/assets/gov/environment/climate-change/ind/obps/guidance/bc_obps_program_and_reporting_guidance.pdf"

TEMPLATE_NAMES = [
    'BORO ID Application Approved',
    'Opt-in And BORO ID Application Approved',
]


def update_guidance_document_link(apps, schema_editor):
    EmailNotificationTemplate = apps.get_model('common', 'EmailNotificationTemplate')
    for template in EmailNotificationTemplate.objects.filter(name__in=TEMPLATE_NAMES):
        template.body = template.body.replace(OLD_URL, NEW_URL)
        template.save()


def reverse_update_guidance_document_link(apps, schema_editor):
    EmailNotificationTemplate = apps.get_model('common', 'EmailNotificationTemplate')
    for template in EmailNotificationTemplate.objects.filter(name__in=TEMPLATE_NAMES):
        template.body = template.body.replace(NEW_URL, OLD_URL)
        template.save()


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0118_V5_6_0'),
    ]

    operations = [
        migrations.RunPython(
            update_guidance_document_link,
            reverse_update_guidance_document_link,
        ),
    ]
