# Generated by Django 5.1.15 on 2026-06-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0127_V5_13_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='message_id',
            field=models.UUIDField(
                db_comment="Message identifier for the email message in CHES (Common Hosted Email Service), BC government's shared email API",
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='transaction_id',
            field=models.UUIDField(
                db_comment="Transaction identifier for the email message in CHES (Common Hosted Email Service), BC government's shared email API",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
