# Generated by Django 5.1.15 on 2026-06-25 23:07

from django.db import migrations
from django.db import connection


class Migration(migrations.Migration):

    # Creates the erc_views schema for all views
    def create_views_schema(apps, schema_editor):
        cursor = connection.cursor()
        cursor.execute("CREATE SCHEMA IF NOT EXISTS erc_views")

    def drop_views_schema(apps, schema_editor):
        cursor = connection.cursor()
        cursor.execute("DROP SCHEMA erc_views")

    # EMISSION VIEW
    def create_emission_view(apps, schema_editor):
        cursor = connection.cursor()
        cursor.execute(
            """create or replace view erc_views.latest_submitted_emission_view as
            (
                select
                    r.reporting_year_id as reporting_year,
                    o.legal_name as operator_legal_name,
                    op.name as operation_name,
                    fr.facility_name,
                    fr.facility_type,
                    a.name as activity,
                    st.name as source_type,
                    (re.json_data ->> 'equivalentEmission')::numeric as tCO2e,
                    re.id as report_emission_id
                from erc.report_emission re
                join erc.report_source_type rst
                    on re.report_source_type_id = rst.id
                join erc.source_type st
                    on rst.source_type_id = st.id
                join erc.report_activity ra
                    on rst.report_activity_id = ra.id
                join erc.activity a
                    on ra.activity_id = a.id
                join erc.facility_report fr
                    on ra.facility_report_id = fr.id
                join erc.report_version rv
                    on fr.report_version_id = rv.id
                    and rv.is_latest_submitted = true
                join erc.report r
                    on rv.report_id = r.id
                join erc.operation op
                    on r.operation_id = op.id
                join erc.operator o
                    on r.operator_id = o.id
            );"""
        )

    def drop_emission_view(apps, schema_editor):
        cursor = connection.cursor()
        cursor.execute("DROP view erc_views.latest_submitted_emission_view")

    # FUEL VIEW
    def create_fuel_view(apps, schema_editor):
        cursor = connection.cursor()
        cursor.execute(
            """create or replace view erc_views.latest_submitted_fuel_view as
            (
                select
                    r.reporting_year_id as reporting_year,
                    o.legal_name as operator_legal_name,
                    op.name as operation_name,
                    fr.facility_name,
                    fr.facility_type,
                    a.name as activity,
                    st.name as source_type,
                    ft.name as fuel_type,
                    ft.unit as fuel_unit,
                    ft.classification as fuel_classification,
                    (rf.json_data ->> 'annualFuelAmount')::numeric as annual_fuel_amount,
                    rf.id as report_fuel_id
                from erc.report_fuel rf
                join erc.fuel_type ft
                    on rf.fuel_type_id = ft.id
                join erc.report_source_type rst
                    on rf.report_source_type_id = rst.id
                join erc.source_type st
                    on rst.source_type_id = st.id
                join erc.report_activity ra
                    on rst.report_activity_id = ra.id
                join erc.activity a
                    on ra.activity_id = a.id
                join erc.facility_report fr
                    on ra.facility_report_id = fr.id
                join erc.report_version rv
                    on fr.report_version_id = rv.id
                    and rv.is_latest_submitted = true
                join erc.report r
                    on rv.report_id = r.id
                join erc.operation op
                    on r.operation_id = op.id
                join erc.operator o
                    on r.operator_id = o.id
            );"""
        )

    def drop_fuel_view(apps, schema_editor):
        cursor = connection.cursor()
        cursor.execute("DROP view erc_views.latest_submitted_fuel_view")

    # PRODUCTION EMISSION ALLOCATION VIEW
    def create_production_emission_allocation_view(apps, schema_editor):
        cursor = connection.cursor()
        cursor.execute(
            """create or replace view erc_views.latest_submitted_production_allocation_view as
            (
                select
                    r.reporting_year_id as reporting_year,
                    o.legal_name as operator_legal_name,
                    op.name as operation_name,
                    p.name as product_name,
                    p.unit as product_unit,
                    p.is_regulated,
                    ec.category_name as emission_category,
                    rpea.allocated_quantity as tco2e_allocated_to_product,
                    rpea.id as report_product_emission_allocation_id
                from erc.report_product_emission_allocation rpea
                join erc.report_product rp
                    on rpea.report_product_id = rp.id
                join erc.regulated_product p
                    on rp.product_id = p.id
                join erc.emission_category ec
                    on rpea.emission_category_id = ec.id
                join erc.report_version rv
                    on rpea.report_version_id = rv.id
                    and rv.is_latest_submitted = true
                join erc.report r
                    on rv.report_id = r.id
                join erc.operation op
                    on r.operation_id = op.id
                join erc.operator o
                    on r.operator_id = o.id
            );"""
        )

    def drop_production_emission_allocation_view(apps, schema_editor):
        cursor = connection.cursor()
        cursor.execute("DROP view erc_views.latest_submitted_production_allocation_view")

    # COMPLIANCE OBLIGATION VIEW
    def create_compliance_obligation_view(apps, schema_editor):
        cursor = connection.cursor()
        cursor.execute(
            """create or replace view erc_views.compliance_obligation_view as
            (
                select
                    r.reporting_year_id as reporting_year,
                    o.legal_name as operator_legal_name,
                    op.name as operation_name,
                    co.obligation_id,
                    case
                        when crv.is_supplementary then crv.excess_emissions_delta_from_previous
                        else rcs.excess_emissions
                    end as obligation_tco2e,
                    co.fee_amount_dollars as obligation_dollars,
                    ei.invoice_fee_balance as unpaid_dollar_amount,
                    crv.status,
                    co.penalty_status,
                    co.id as compliance_obligation_id
                from erc.compliance_obligation co
                left join erc.elicensing_invoice ei
                    on co.elicensing_invoice_id = ei.id
                join erc.compliance_report_version crv
                    on co.compliance_report_version_id = crv.id
                join erc.report_compliance_summary rcs
                    on crv.report_compliance_summary_id = rcs.id
                join erc.report_version rv
                    on rcs.report_version_id = rv.id
                join erc.report r
                    on rv.report_id = r.id
                join erc.operation op
                    on r.operation_id = op.id
                join erc.operator o
                    on r.operator_id = o.id
            );"""
        )

    def drop_compliance_obligation_view(apps, schema_editor):
        cursor = connection.cursor()
        cursor.execute("DROP view erc_views.compliance_obligation_view")

    # COMPLIANCE EARNED CREDITS VIEW
    def create_compliance_earned_credits_view(apps, schema_editor):
        cursor = connection.cursor()
        cursor.execute(
            """create or replace view erc_views.compliance_earned_credit_view as (
                select
                    r.reporting_year_id as reporting_year,
                    o.legal_name as operator_legal_name,
                    op.name as operation_name,
                    crv.is_supplementary,
                    crv.credited_emissions_delta_from_previous,
                    rcs.credited_emissions,
                    cec.issuance_status,
                    cec.issued_date,
                    cec.earned_credits_amount,
                    cec.bccr_holding_account_id,
                    cec.id as compliance_earned_credit_id
                from erc.compliance_earned_credit cec
                join erc.compliance_report_version crv
                    on cec.compliance_report_version_id = crv.id
                join erc.report_compliance_summary rcs
                    on crv.report_compliance_summary_id = rcs.id
                join erc.report_version rv
                    on rcs.report_version_id = rv.id
                join erc.report r
                    on rv.report_id = r.id
                join erc.operation op
                    on r.operation_id = op.id
                join erc.operator o
                    on r.operator_id = o.id
            );"""
        )

    def drop_compliance_earned_credits_view(apps, schema_editor):
        cursor = connection.cursor()
        cursor.execute("DROP view erc_views.compliance_earned_credit_view")

    dependencies = [
        ('common', '0129_V5_14_0'),
        ('registration', '0184_update_registration_metadata'),
        ('reporting', '0199_alter_facilityreport_archived_at_and_more'),
        ('compliance', '0052_update_timestamp_metadata'),
    ]

    operations = [
        migrations.RunPython(
            create_views_schema,
            drop_views_schema,
        ),
        migrations.RunPython(
            create_emission_view,
            drop_emission_view,
        ),
        migrations.RunPython(
            create_fuel_view,
            drop_fuel_view,
        ),
        migrations.RunPython(
            create_production_emission_allocation_view,
            drop_production_emission_allocation_view,
        ),
        migrations.RunPython(
            create_compliance_obligation_view,
            drop_compliance_obligation_view,
        ),
        migrations.RunPython(
            create_compliance_earned_credits_view,
            drop_compliance_earned_credits_view,
        ),
    ]
