# Generated by Django 5.1.15 on 2026-07-15 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0132_update_dashboard_data'),
    ]

    operations = []
