name: Build Administration Docker container

on:
  workflow_call:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build administration container
        uses: ./.github/actions/nx-app-build
        with:
          project: administration
          image_url: ghcr.io/bcgov/cas-rep-frontend
          github_token: ${{ secrets.GITHUB_TOKEN }}
