name: Build Registration1 Docker container

on:
  workflow_call:

jobs:
  nx-docker-build-registration1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build registration1 container
        uses: ./.github/actions/nx-app-build
        with:
          project: registration1
          image_url: ghcr.io/bcgov/cas-reg1-frontend
          github_token: ${{ secrets.GITHUB_TOKEN }}
