name: Check immutable migrations
on:
  workflow_call:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: dev env setup
        uses: ./.github/actions/dev-env-setup
      - name: Run check
        run: ./.bin/check-immutable-migrations.sh
