name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  backend:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      # - name: asdf setup
      #   uses: asdf-vm/actions/setup@v1
      # - uses: actions/cache@v3
      #   id: asdf-cache
      #   with:
      #     path: |
      #       ~/.asdf
      #     key: ${{ runner.os }}-asdf-cache-${{ hashFiles('.tool-versions') }}
      # - uses: actions/checkout@v3
      # - name: Install dev tools
      #   run: make install_dev_tools
      #   working-directory: ./bc_obps
      # - name: Install poetry deps
      #   run: make install_poetry_deps
      #   working-directory: ./bc_obps
      # - name: Start postgres and create db
      #   run: make start_pg
      #   run: make create_db
      # - name: Run migrations
      #   run: make migrations
      #   run: make migrate
      #   working-directory: ./bc_obps
      # - name: Start backup
      #   run: make run
      #   working-directory: ./bc_obps
  e2e:
    # needs: backend
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn
        working-directory: ./client
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps
        working-directory: ./client
      # - name: Start the frontend
      #   run: yarn dev
        working-directory: ./client
      - name: Run Playwright tests
        run: yarn playwright test
        working-directory: ./client
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
