name: Release Docs

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-docs:
    name: Build documentation pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Enable Corepack and Yarn 4
        run: |
          corepack enable
          corepack prepare yarn@4.13.0 --activate

      - name: Install build and deploy with Astro
        uses: withastro/action@v6
        with:
          path: docs-site
          node-version: 24.16.0
          package-manager: yarn@4.13.0
          build-cmd: node sync-docs.js && yarn astro build

  deploy:
    name: Deploy documentation pages to GitHub Pages
    needs: build-docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Grab artifact
        uses: actions/download-artifact@v8
        with:
          name: docs-site
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: "docs-site"
          target-folder: docs
          single-commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
