name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  # client:
  #   runs-on: ubuntu-latest
  #   steps:
  install-client-dev-tools:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: dev env setup
        uses: ./.github/actions/dev-env-setup
      - run: yarn install --frozen-lockfile
        working-directory: ./client
  install-server-dev-tools:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: dev env setup
        uses: ./.github/actions/dev-env-setup
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.16"
      - name: Install Poetry
        uses: snok/install-poetry@v1
      # - name: Install Poetry dependencies
      #   uses: poetry install

  yarn-test:
    needs: install-client-dev-tools
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: dev env setup
        uses: ./.github/actions/dev-env-setup
      - run: yarn test
        working-directory: ./client
  e2e:
    needs: ["install-client-dev-tools", "install-server-dev-tools"]
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: dev env setup
        uses: ./.github/actions/dev-env-setup
      # - name: Install dependencies
      #   run: yarn
      #   working-directory: ./client
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps
        working-directory: ./client
      # - name: Start the frontend
      #   run: yarn dev
      # working-directory: ./client
      - name: Run Playwright tests
        run: yarn playwright test
        working-directory: ./client
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
