name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  # client:
  #   runs-on: ubuntu-latest
  #   steps:
  install-dev-tools:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: dev env setup
        uses: ./.github/actions/dev-env-setup
      # - run: make install_dev_tools
      # - run: make stop_pg # cleanly stop the database, otherwise it will complain in the subsequent jobs
      - run: yarn install --frozen-lockfile
        working-directory: ./client

  yarn-test:
    needs: install-dev-tools
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: dev env setup
        uses: ./.github/actions/dev-env-setup
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - run: yarn test
        working-directory: ./client

  # this runs
  # test-2:
  #   timeout-minutes: 60
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     # - uses: actions/setup-node@v3
  #     #   with:
  #     #     node-version: 18
  #     - name: Install dependencies
  #       run: yarn
  #       working-directory: ./client
  #     - name: jest
  #       run: yarn test
  #       working-directory: ./client
