name: trivy-image-scan
on:
  workflow_call:
    inputs:
      TAG:
        required: true
        type: string
      IMAGE:
        required: true
        type: string
jobs:
  trivy-image-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - name: Trivy Vulnerability Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ inputs.IMAGE }}:${{ inputs.TAG }}
        format: table
        exit-code: '0'
        ignore-unfixed: true
        vuln-type: os,library
        severity: CRITICAL