name: Trivy Scan Code

on:
  workflow_call:

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache Scan Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/trivy
          key: callee-trivy-${{ github.workflow }}-${{ github.run_id }}
          restore-keys: trivy-
      - name: Run Trivy vulnerability scanner in repo mode (debug)
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: fs
          scan-ref: "."
          format: table
          output: trivy-results.txt
          exit-code: "0"
          ignore-unfixed: false
          severity: CRITICAL,HIGH,MEDIUM
          timeout: 10m0s
      - name: Display Trivy results
        run: |
          echo "=== Trivy Vulnerability Scan Results ==="
          cat trivy-results.txt || echo "No results file found"
      - name: Run Trivy vulnerability scanner for SARIF output
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: fs
          scan-ref: "."
          format: sarif
          output: trivy-results.sarif
          exit-code: "0"
          ignore-unfixed: false
          severity: CRITICAL,HIGH,MEDIUM
          timeout: 10m0s
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif
      - name: Upload Trivy scan results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-results
          path: |
            trivy-results.sarif
            trivy-results.txt
