name: Trivy Scan Code

on:
  workflow_call:

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Cache Scan Dependencies
        uses: actions/cache@v5
        with:
          path: ~/.cache/trivy
          key: callee-trivy-${{ github.workflow }}-${{ github.run_id }}
          restore-keys: callee-trivy-${{ github.workflow }}-
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0
        with:
          scan-type: fs
          scan-ref: "."
          format: sarif
          output: trivy-results.sarif
          exit-code: "0"
          ignore-unfixed: false
          severity: CRITICAL,HIGH,MEDIUM
          timeout: 10m0s
          scanners: vuln,secret,config
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy-results.sarif
          category: trivy-code-scan
      - name: Upload Trivy scan results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-results
          path: trivy-results.sarif
