name: TruffleHog Simple Secret Detection

on:
  pull_request:
    types: [opened, edited, synchronize]
  issues:
    types: [opened, edited]

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run TruffleHog on repository
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          extra_args: --no-verification
        continue-on-error: true

      - name: Check PR/Issue content for obvious secrets
        if: always()
        run: |
          SECRETS_FOUND=false

          # Check PR description
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            PR_BODY="${{ github.event.pull_request.body }}"
            if echo "$PR_BODY" | grep -E "(API key|GitHub token|Database URL|password|secret|key):\s*[a-zA-Z0-9+/=@:.-]{10,}|ghp_[a-zA-Z0-9]{36}|postgresql://[^:]+:[^@]+@" > /dev/null; then
              echo "Secrets found in PR description"
              SECRETS_FOUND=true
            fi
          fi

          # Check issue description
          if [ "${{ github.event_name }}" = "issues" ]; then
            ISSUE_BODY="${{ github.event.issue.body }}"
            if echo "$ISSUE_BODY" | grep -E "(API key|GitHub token|Database URL|password|secret|key):\s*[a-zA-Z0-9+/=@:.-]{10,}|ghp_[a-zA-Z0-9]{36}|postgresql://[^:]+:[^@]+@" > /dev/null; then
              echo "Secrets found in issue description"
              SECRETS_FOUND=true
            fi
          fi

          if [ "$SECRETS_FOUND" = "true" ]; then
            echo "SECRETS_FOUND=true" >> $GITHUB_ENV
          else
            echo "SECRETS_FOUND=false" >> $GITHUB_ENV
          fi

      - name: Comment if secrets found
        if: failure() || env.SECRETS_FOUND == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const commentBody = `🐷 **TruffleHog Secret Detection Alert**

            ⚠️ **WARNING**: Potential secrets detected in this ${context.eventName.includes('pull_request') ? 'pull request' : 'issue'}!

            **Action Required**: Remove sensitive data before proceeding.

            ---
            *This is an automated security check by TruffleHog.*`;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue?.number || context.payload.pull_request?.number,
              body: commentBody
            });
